core/model/src/main/java/org/eclipse/rdf4j/model/util/GetStatementOptional.java
core/model/src/main/java/org/eclipse/rdf4j/model/util/ModelException.java
core/model/src/main/java/org/eclipse/rdf4j/model/util/Models.java
core/model/src/main/java/org/eclipse/rdf4j/model/util/RDFCollections.java
core/model/src/main/java/org/eclipse/rdf4j/model/util/Statements.java
core/model/src/main/java/org/eclipse/rdf4j/model/vocabulary/DCTERMS.java
core/model/src/test/java/org/eclipse/rdf4j/model/util/RDFCollectionsTest.java
core/model/src/test/java/org/eclipse/rdf4j/model/util/StatementsTest.java
core/repository/api/src/main/java/org/eclipse/rdf4j/repository/util/Connections.java
core/repository/api/src/main/java/org/eclipse/rdf4j/repository/util/Repositories.java

A first attempt at syncing updates on the old repository with the new eclipse repo, avoiding copying over the entire history. This updates includes a new feature and is authored only by me.

merge latest updates from master branch

---

core/http/server/src/test/java/org/eclipse/rdf4j/http/server/WebXmlValidationTest.java

Hudson instance seems to have trouble downloading the XML Schema,
causing the build to stall.

 #27 temporarily disabled web.xml schema validation

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md

This PR addresses GitHub issue: #16 
- moved github templates to hidden dir
- added Pull request template

 #16 moved github templates to hidden dir, added PR template

---

core/assembly/pom.xml
core/assembly/src/main/assembly/sdk.xml
core/assembly/src/main/dist/bin/console.bat
core/assembly/src/main/dist/bin/console.sh
core/console/pom.xml

This PR addresses GitHub issue: #50
- assembly descriptor updated
- sdk and onejar files now renamed
- console startup scripts fixed to use new package names. 

 #50 fixed assembly descriptors, poms, and scripts

---

compliance/store/src/test/java/org/eclipse/rdf4j/repository/sail/memory/SpinMemoryRepositoryConnectionTest.java
compliance/store/src/test/java/org/eclipse/rdf4j/repository/sail/memory/SpinRDFSMemoryRepositoryConnectionTest.java

This PR addresses GitHub issue: #
- disabled tests
Manually re-enable when working on fixes for SPIN functionality.

 #58 disabled SPIN compliance tests due to performance/stability

---

core/runtime-osgi/pom.xml

This PR addresses GitHub issue: #142
- fixes OSGi bundle instructions to use correct package names
- verified that the created bundle now includes the expected packages and classes

Fixed osgi bundle instructions.

---

core/runtime-osgi/build.xml

This PR addresses GitHub issue: #142
- fixed package names in build.xml 
- build.xml project name changed to 'rdf4j'
I've tested that all META-INF/services files now have correct names and content.

#142 fixed build.xml package names

---

compliance/sparql/src/test/java/org/eclipse/rdf4j/sail/federation/FederationSparqlTest.java
core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/optimizers/EvaluationStatistics.java

This PR addresses GitHub issue: #29. It replaces PR #148 which was accidentally created against the wrong branch. 
The evaluation of subqueries in FederationSail was not correct as
revealed by W3C test sq14. This is caused by an unsuitable join order,
where the sub select is processed using the results of a graph pattern
as intermediate result.
The simplest fix for this case is to set the cardinality hints for the
optimizer for SLICE algebra nodes to 1 such that they are executed as
left join argument with high probability.
The full fix (which will be done in another change) could to use a hash
based join strategy.

#29 fix subquery evaluation in FederationSail due to wrong join order

---

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/SimpleEvaluationStrategy.java
testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ComplexSPARQLQueryTest.java

This PR addresses GitHub issue: #161
- minor fix in evaluation of regular expression: do Unicode-based case matching when matching case-insensitively
- added compliance test that demonestrates expected behavior.

#161 case-insensitive regex matching should be based on unicode

---

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/HashJoinIteration.java
core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/evaluation/FederationStrategy.java

This PR addresses GitHub issue: #29 
In certain cases the nested loop join approach is not applicable (e.g.,
if the right argument is a sub-select with ORDER BY or LIMIT, see sq14).
This change now applies a HashJoin strategy in such cases.
Note that the HashJoinIteration has to be extended such that the left
intermediate result iteration can be passed to it.

#29 fix suqbquery evaluation in FederationSail (use hash join)

---

compliance/http/src/test/java/org/eclipse/rdf4j/http/server/ProtocolTest.java

This PR addresses GitHub issue: #167
Flawed test removed. Note that test failure was only intermittent and depends on runtime preference of server for RDF syntax formats. 
Test can never be guaranteed to succeed as server may send an RDF syntax
format that is simply not supported by the client - but this does not
mean a breach of protocol since the test's intent was to check what
happens when no Accept header is set. 

#167 removed fundamentally flawed test

---

core/model/src/main/java/org/eclipse/rdf4j/model/vocabulary/APF.java
core/model/src/main/java/org/eclipse/rdf4j/model/vocabulary/GEO.java
core/model/src/main/java/org/eclipse/rdf4j/model/vocabulary/GEOF.java
core/model/src/main/java/org/eclipse/rdf4j/model/vocabulary/LIST.java

This PR addresses GitHub issue: #171 
It uses IRI instead of URI in all classes in the org.eclipse.rdf4j.model.vocabulary package

Uses IRI class in all vocabularies

---

pom.xml

This PR addresses GitHub issue: #173
This ensures the failsafe plugin does not stop with an error when executing integration tests on a developer workstation (i.e. when running `mvn verify`). The empty value is overridden with the correct proxy when the eclipse-hudson-rdf4j profile is activated (which only happens on the Hudson CI server).
Ran `mvn verify` locally, verified this fixes the issue. Also double-checked that override on profile activation works as expected.

#173 set default empty value for hudson.rdf4j.proxy.opts

---

bom/pom.xml

This PR addresses GitHub issue: #189
- specifies version of rdf4j-rio-jsonld in bom pom.xml
- [yes] RDF4J code formatting has been applied
- [n/a] tests are included
- [n/a] all tests succeed

Add rdf4j-rio-jsonld to rdf4j-bom

---

core/http/workbench/src/main/webapp/transformations/create.xsl

This PR addresses GitHub issue: #196 
- Fixed create.xsl

Fixed xsl.

---

pom.xml

This PR addresses GitHub issue: #138
- included version of jsonld-java upgraded to 0.8.3.

upgrade to jsonld-java 0.8.3

---

core/http/server-spring/pom.xml
core/http/server-spring/src/test/java/org/eclipse/rdf4j/common/webapp/util/HttpServerUtilTest.java
core/http/workbench/pom.xml
pom.xml

This PR addresses GitHub issue: #206
- servlet api depency upgraded to 3.0.1 to enable future use of spring-test mock classes (which rely on servlet 3.0). 
- extended internal stub class in HttpServerUtilTest to conform to extended interface in new api

upgraded servlet-api (provided) dep to 3.0.1

---

core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/optimizers/FederationJoinOptimizer.java

This PR addresses GitHub issue: #180
- trivial fix in getUnionArgs method to retrieve args from _both_ sides of the union

#180 trivial fix in getUnionArgs

---

compliance/store/src/test/java/org/eclipse/rdf4j/repository/http/HTTPStoreConnectionTest.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/TransactionController.java

This PR addresses GitHub issue: #188 
- fixed TranactionController to read context param and preserveBNodeId param
- adapted code to make sure params are properly used 
- added test case, which greenlines

added processing of context and preserveBNodeId params in TxnController

---

compliance/http/pom.xml
compliance/http/src/test/java/org/eclipse/rdf4j/http/server/ProtocolTest.java
core/http/server-spring/pom.xml
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/ProtocolUtil.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/RepositoryController.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/statements/StatementsController.java
core/http/server-spring/src/test/java/org/eclipse/rdf4j/http/server/repository/statements/TestStatementsController.java
pom.xml

This PR addresses GitHub issue: #187 
- timeout parameter now read and used by StatementsController
- added protocol test that verifies form-encoded post for update with timeout param is accepted

update execution now takes timeout into account

---

core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/SPARQLConnection.java
core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/query/SPARQLOperation.java
core/spin/src/main/java/org/eclipse/rdf4j/spin/function/Concat.java

This PR addresses GitHub issue: #227
-    getLanguage() returns an Optional, if it has been verified to be non-empty, use getLanguage().get() (or getLanguage.orElse(null)) to retrieve the actual string value.
Make sure you've followed the Contributor Guidelines. In particular (please tick to indicate you've taken care of it):

#227 fixed use of getLanguage() return value

---

core/model/src/main/java/org/eclipse/rdf4j/model/BNode.java
core/model/src/main/java/org/eclipse/rdf4j/model/Literal.java
core/model/src/main/java/org/eclipse/rdf4j/model/ValueFactory.java

This PR addresses GitHub issue: #249
- Clarify the relationship to the RDF-1.1 specification. In particular, clarify the status of Literal.getDatatype that cannot be null or empty in RDF-1.1 as it could be in RDF-1.0.
No code or contract changes, just clarifications in javadoc of the contracts that the existing RDF4J code already follows.

Fixes issue #249 Clarify the conceptual relationship to RDF-1.1

---

core/http/client/src/main/java/org/eclipse/rdf4j/http/client/SparqlSession.java

This PR addresses GitHub issue: #228
- http query requests now send single, comma-separated Accept header 

create single Accept header with comma-separated values for formats

---

core/http/client/src/main/java/org/eclipse/rdf4j/http/client/SparqlSession.java
core/model/src/main/java/org/eclipse/rdf4j/RDF4JConfigException.java
core/repository/api/src/main/java/org/eclipse/rdf4j/repository/config/RepositoryConfigException.java
core/sail/api/src/main/java/org/eclipse/rdf4j/sail/config/SailConfigException.java

This PR addresses GitHub issue: #255
- default value of url length threshold set to 4083
- threshold now configurable via system property 'rdf4j.sparql.url.maxlength'

SPARQL endpoint url length threshold lowered and made configurable

---

.gitignore

This PR addresses GitHub issue: #258 
- added NetBeans files patterns to .gitignore
- [x ] RDF4J code formatting has been applied
- tests are included   :: **NA**
- all tests succeed   **NA**
ignore NetBeans IDE files
Signed-off-by:Jacek Grzebyta <grzebyta.dev@gmail.com>

fix issue #258

---

compliance/rio/src/test/java/org/eclipse/rdf4j/rio/trig/TriGParserCustomTest.java
core/rio/trig/src/main/java/org/eclipse/rdf4j/rio/trig/TriGParser.java
core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleParser.java

This PR addresses GitHub issue: #254 
- Add regression test for issue#254 to confirm bug
- Change the TriG parser to not assume that "GRAPH" is the SPARQL keyword if there is a colon immediately following it, as it could have been used as a pname in that case

issue#254 : Change TriG parser to not assume "GRAPH" is the SPARQL Keyword

---

core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/ActiveTransactionRegistry.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/TransactionController.java
core/http/server-spring/src/test/java/org/eclipse/rdf4j/http/server/repository/transaction/TestActiveTransactionRegistry.java
core/repository/sail/src/main/java/org/eclipse/rdf4j/repository/sail/SailRepositoryConnection.java

This PR addresses GitHub issue: #91
- primary cache in txn registry no longer has a timeout
- secondary cache with timeout verifies if entry is still actively used server-side. If not, entry is also removed from primary cache.
- added unit tests which verify expected behavior. 

#91 using secondary cache for maintenance

---

core/sail/fts/lucene/pom.xml
core/sail/fts/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneIndex.java
pom.xml

This PR addresses GitHub issue: #267 
Removed animal-sniffer-annotations dependency. This dependency is obsolete since RDF4J moved to Java 7/8.

removed animal-sniffer-annotations dependency

---

core/sail/fts/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneIndex.java
core/sail/fts/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneIndexNIOFS.java

This PR addresses GitHub issue: #267
Overlooked further usage (and import declarations), removed now. 
Compilation succeeds locally.

fixed compilation failures after sniffer-annotations removal

---

core/rio/rdfjson/src/main/java/org/eclipse/rdf4j/rio/rdfjson/RDFJSONWriter.java

This PR addresses GitHub issue: #273 
- Fix use of deprecated Jackson public API methods/variables including one that was removed in 2.7
- [n/a] tests are included
Lf2SpacesIndenter was removed in 2.7, so to be compatible with
2.7/2.8/etc. changing here to use the new name for it. There is no need to update to Jackson-2.7/2.8 at this point, other than to get bug fixes, but this will make it possible to interoperate with other libraries that do depend on features added there.
The previous pull request was targeted at master, but I would like this to be …

issue#273 : Use non-deprecated methods to be compatible with jackson2.7+

---

core/queryresultio/sparqlxml/src/main/java/org/eclipse/rdf4j/query/resultio/sparqlxml/AbstractSPARQLXMLParser.java
core/rio/rdfxml/src/main/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParser.java
core/rio/rdfxml/src/main/java/org/eclipse/rdf4j/rio/rdfxml/SAXFilter.java
core/rio/trix/pom.xml
core/rio/trix/src/main/java/org/eclipse/rdf4j/rio/trix/TriXParser.java
core/rio/trix/src/test/java/org/eclipse/rdf4j/rio/trix/TriXParserTest.java
core/rio/trix/src/test/resources/org/eclipse/rdf4j/rio/trix/not-a-trix-file.trix
core/util/src/main/java/org/eclipse/rdf4j/common/xml/SimpleSAXParser.java

This PR addresses GitHub issue: #281 
- Ensure that all XMLReader instances have ErrorHandler objects attached to them to prevent fatal errors being emitted to the Console 
- Adds Locator to SimpleSaxParser so that error messages and exceptions for parsers using it can have line and column numbers attached to them.
- Adds regression test for TriXParser to ensure it doesn't start emitting error messages to the System.err or System.out in future
Note that queryresultio doesn't have any formal infrastructure for reporting errors to users in a friendly …

issue#281 : Further use of ErrorHandler to prevent fatal errors emitted to console

---

core/rio/rdfxml/src/test/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParserTest.java
core/rio/trix/src/test/java/org/eclipse/rdf4j/rio/trix/TriXParserTest.java
core/sail/spin/src/test/java/org/eclipse/rdf4j/sail/spin/SpifSailTest.java

This PR addresses GitHub issue: #280
- SPIN unit tests now force English locale for test execution
- TriX and RDF/XML parser tests do not verify exact error message anymore.

workarounds in unit tests to account for different platform locales.

---

core/model/src/main/java/org/eclipse/rdf4j/model/vocabulary/DCAT.java

This PR addresses GitHub issue: #283 
- trivial change: added dcat:theme property / IRI in the vocab class
Signed-off-by:Bart Hanssens <bart.hanssens@fedict.be>

Added dcat:theme

---

core/queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqljson/AbstractSPARQLJSONWriter.java

This PR addresses GitHub issue: #308
- Fixes the use of deprecated Jackson methods in the SPARQL/JSON writer that have been or may be removed in future versions
This does not contain a bump to Jackson 2.8.2 (which we don't want to bump for 2.0.x), but I have locally tested that it still works upon upgrading from 2.6.2 to 2.8.2.

issue#308 : Fix use of deprecated/removed Jackson methods

---

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/CrossProductIteration.java

This PR addresses GitHub issue: #296 
- Closes the embedded iteration in handleClose().

Fixes #296 by closing the embedded iteration.

---

core/sail/spin/src/test/java/org/eclipse/rdf4j/sail/spin/SpifSailTest.java

This PR addresses GitHub issue: #239 
- Second try to fix issue #239 
- Replacement of PR eclipse/rdf4j#240
More information at eclipse/rdf4j/pull/240
Signed-off-by:Jacek Grzebyta <grzebyta.dev@gmail.com>

Fix #239, second try

---

core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractLuceneIndex.java
core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractReaderMonitor.java
core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSail.java
core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSailConnection.java
core/sail/fts/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneIndex.java

This PR addresses GitHub issue: #301 
- Adds more checks and sychronisation to avoid calling into Lucene API at unexpected times
Lock more Lucene methods. The internal Lucene API isn't stable for long term threaded access so external synchronisation is necessary.
Add checks on calls after closure
With these changes I have not been able to replicate the issue after several (30+) invocations of the testsuite. Previously I was getting the error about 1 in every 10 runs through LuceneSailTest.

issue#301 : Work on tightening the contract for lucene sail components

---

.github/CONTRIBUTING.md
README.md

GitHub issue: #266 
Added a short version of the guidelines to the readme. Guidelines updated to use simplified branching model, and added info on release cycle.
Please review for correctness. I'm not 100% sure about the organization of this either: if you have suggestions for changes to make it all easier to digest by all means go ahead.

Update to readme and contributor guidelines

---

.github/PULL_REQUEST_TEMPLATE.md

Got rid of the redundant link to the guidelines (GitHub shows it right at the top itself) and the tick boxes for formatting and tests, etc (nobody really uses them anyway it seems).

Issue #266: simplified Pull Request template

---

pom.xml

This PR addresses GitHub issue: #311 .
* Update Jackson to 2.8.2
* Add Jackson Dataformat CSV module to dependency management, but not to any dependencies sections. Usage of this module will be added in near future pull requests.

issue #311 : Update to Jackson-2.8.2

---

core/rio/api/src/main/java/org/eclipse/rdf4j/rio/RDFFormat.java

This PR addresses GitHub issue: #328 .
* added 'text/xml' as mime-type for RDF/XML and made necessary Javadoc changes 

Issue #328: Added 'text/xml' as accepted alternative mediatype

---

pom.xml

Use an HTTPS URL for Restlet, so code isn't fetched over an insecure connection. Switch to their current preferred TLD of .com rather than .org (they redirect .org to .com over HTTP, but not HTTPS).
Adjust the Eclipse link at the same time.

Use repositories over TLS.

---

core/http/workbench/src/main/java/org/eclipse/rdf4j/workbench/base/TransformationServlet.java

This PR addresses GitHub issue: #468 .
Signed-off-by: Joseph Walton <joe@kafsemo.org>

Issue #468: Don't wrap exceptions that can be thrown directly.

---

core/model/src/main/java/org/eclipse/rdf4j/model/datatypes/XMLDatatypeUtil.java
core/model/src/main/java/org/eclipse/rdf4j/model/util/Literals.java
core/model/src/test/java/org/eclipse/rdf4j/model/util/LiteralsTest.java

This PR addresses GitHub issue: #300 .
* added `Literals.getDurationValue` method to extract a java `Duration` object from a literal
* added `XMLDatatypeUtil.parseDuration` for parsing a lexical representation into a Duration object.
* added simple unit test

Issue #300: added Literals.getDurationValue and XMLDatatypeUtil.parseDuration

---

core/rio/api/src/main/java/org/eclipse/rdf4j/rio/RDFFormat.java

This PR addresses GitHub issue: #299  .
* q-value for RDF/XML is downgraded by 0.4 (so best-case scenario is it becomes 0.6)
* added failsafe to completely skip a format if the q-value goes below 0.1.

Issue #299 added downgrading of RDF/XML q-value for accept headers

---

core/model/src/main/java/org/eclipse/rdf4j/model/datatypes/XMLDatatypeUtil.java
core/model/src/main/java/org/eclipse/rdf4j/model/vocabulary/XMLSchema.java

This PR addresses (partially) GitHub issue: #300  .
* Adds XMLDatatypeUtil. isDurationDatatype
* Adds derived duration datatypes to XMLDatatypeUtil.isDerivedDatatype, XMLDatatypeUtil.qnameToURI and XMLDatatypeUtil.isValidValue
Signed-off-by: Thomas Pellissier Tanon <thomas@pellissier-tanon.fr>

Issue #300: added support of duration datatypes to XMLDatatypeUtil

---

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/GroupIterator.java
testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ComplexSPARQLQueryTest.java

This PR addresses GitHub issue: #573 .
* GroupIterator now only inserts empty BindingSet in solution if actual aggregate operators are present
* added test case to ComplexSPARQLQueryTest to verify expected behavior
* all SPARQL compliance tests (including test cases for aggregate/grouping behavior) greenline

Issue #573 fix for group by behaviour + unit test.

---

core/console/pom.xml
core/console/src/main/java/org/eclipse/rdf4j/console/SetParameters.java
core/console/src/test/java/org/eclipse/rdf4j/console/SetParametersTest.java
eclipse-settings/codetemplates.xml

This PR addresses GitHub issue: #544.
* Add tests for 'set log'
* Bring back the previous JDK logging implementation and adjust for Logback.

Issue #544: reimplement 'set log' for Logback

---

core/console/src/test/java/org/eclipse/rdf4j/console/SetParametersTest.java

This PR addresses the build break from merging #591.
Restore the same log level from the start of the test, rather
than assuming that it's DEBUG.
If I run the tests using a more recent Surefire and `-Dsurefire.runOrder=random`, the tests fail before this change, and pass afterwards.

Issue #544: Restore same log level.

---

core/http/protocol/src/main/java/org/eclipse/rdf4j/http/protocol/Protocol.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/ProtocolUtil.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/RepositoryController.java
core/query/src/main/java/org/eclipse/rdf4j/query/QueryResults.java

This PR addresses GitHub issue: #575 .
* added limit and offset params to REST protocol
* added util method `ProtocolUtil.parseLongParam`
* `RepositoryController` now applies optional limit and offset to query results (by wrapping iteration)

#575 added limit and offset as optional HTTP request params

---

core/console/src/main/java/org/eclipse/rdf4j/console/Federate.java
core/console/src/main/java/org/eclipse/rdf4j/console/SetParameters.java
core/console/src/test/java/org/eclipse/rdf4j/console/AbstractCommandTest.java
core/console/src/test/java/org/eclipse/rdf4j/console/DropTest.java
core/console/src/test/java/org/eclipse/rdf4j/console/FederateTest.java
core/console/src/test/java/org/eclipse/rdf4j/console/SetParametersTest.java
pom.xml

This PR addresses GitHub issue: #614 .
* The Console Federate command was using log level for control flow, resulting in federation failing to occur if the log level was debug or finer.
Debugging this involved updating Mockito to 2.2.0 and Logback to 1.1.7, but those changes don't seem to be related to the solution so they have been backed out due to the close release time.
Debugging also involved refactoring SetParametersTest to reuse AbstractCommandTest as designed, and included refactoring to use MockitoRule, @Mock and @InjectMocks to verify they were not related and can be maintained in future.
There is now a known baseline log level of debug setup for both FederateTest and SetParametersTest, based on their need to consistently verify …

issue #614 : Console Federate command broken by log level debug

---

core/model/src/main/java/org/eclipse/rdf4j/model/vocabulary/SKOSXL.java

This PR addresses GitHub issue: #609 
* Add a vocabulary class for the namespace SKOS-XL

issue #609: provide vocabulary constants for SKOS-XL

---

core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ast/SyntaxTreeBuilder.java
core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ast/sparql.jjt

This PR addresses GitHub issue: #617 .
The fix addresses the issue by setting the tab size to 1 when parsing updates (copied the same code that is applied to parsing queries). I also edited the generated SyntaxTreeBuilder.java instead of rerunning jjtree/javacc on sparql.jjt (although I verified that works).
Also updated package names in sparql.jjt to org.eclipse.rdf4j as they seem to have been forgotten.

Fixes #617: Tabs in update with federate query are not parsed correctly.

---

core/repository/sail/src/main/java/org/eclipse/rdf4j/repository/sail/helpers/SailUpdateExecutor.java
testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLUpdateTest.java

This PR addresses GitHub issue: #610 .
* SailUpdateExecutor silently skips invalid triples when executing the delete or insert part of an update
* added regression tests to confirm expected behavior

Issue #610: silently ignore invalid triples on DELETE-INSERT-WHERE

---

core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Service.java

This PR addresses GitHub issue: #620  .
Trivial fix by inserting a new line before the closing "}".

Fixes #620: Comments in federated queries lead to invalid SPARQL

---

compliance/store/src/test/java/org/eclipse/rdf4j/repository/sail/memory/MemoryEvaluationStrategyTest.java
compliance/store/src/test/java/org/eclipse/rdf4j/repository/sail/nativerdf/NativeEvaluationStrategyTest.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/EvaluationStrategyFactory.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/AbstractEvaluationStrategyFactory.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/ExtendedEvaluationStrategy.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/ExtendedEvaluationStrategyFactory.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StrictEvaluationStrategyFactory.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/TupleFunctionEvaluationStrategy.java
core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/MemoryStore.java
core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/MemoryStoreConnection.java
core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/NativeStore.java
core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/NativeStoreConnection.java
testsuites/store/src/main/java/org/eclipse/rdf4j/repository/EvaluationStrategyTest.java

This PR addresses GitHub issue: #164 .
* hotfix/workaround for issue with configuration of evaluation strategy in memory and native stores.
* both stores now use the provided Factory to create an EvaluationStrategy.
* EvaluationStrategy interface extended to allow passing through of `iterationCacheSyncThreshold` param.
We may want to revisit the design later, as it all is a bit tightly coupled. However, this is a hotfix and unless somehow has strong objections I'd like this merged in so we can proceed with release.
@pulquero, @ansell , your feedback in particular is appreciated.

#164 critical pre-release hotfix in native and memory store strategy selection

---

core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/MemoryStoreConnection.java

This PR addresses GitHub issue: #623 .
* trivial fix in internal commit: send change notification _before_ scheduling sync. 

Issue #623: notification before scheduling sync.

---

core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/MemoryOverflowModel.java

This PR addresses GitHub issue: #626 .
* trivial change in error logging: include datadir (if known) when error occurs in disk sync.

Issue #626: show dir being written to when error occurs in disk overflow

---

core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/QueryResultView.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/ActiveTransactionRegistry.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/Transaction.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/TransactionController.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/TransactionExportStatementsView.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/TransactionStartController.java
core/http/server-spring/src/test/java/org/eclipse/rdf4j/http/server/repository/transaction/TestActiveTransactionRegistry.java

This PR addresses GitHub issue: #630 .
* new class Transaction ensures single-threaded access to RepositoryConnection: it encapsulates both a RepositoryConnection and a dedicated Thread (provided by an ExecutorService)
* Drastically simplified concurrency handling: ActiveTransactionRegistry now keeps tracks of Transactions instead of RepositoryConnections - no longer any need for locking access to the RepositoryConnection
All integration/compliance tests succeed, and I have manually verified that this fix also fixes the IllegalMonitorStateException described in #630.

Issue: #630 TransactionController threading 

---

core/model/src/main/java/org/eclipse/rdf4j/model/util/ModelBuilder.java
core/model/src/test/java/org/eclipse/rdf4j/model/util/ModelBuilderTest.java

This PR addresses GitHub issue: #632 .
* ModelBuilder now can handle prefixed name strings in the object position
* deliberately does _not_ try to parse full IRI from string as this is too complex
* added unit test

Issue #632: modelbuilder object string

---

core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/DeleteData.java
core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/InsertData.java
core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/PrefixDeclProcessor.java
core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/UpdateExprBuilder.java
core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ast/ASTUnparsedQuadDataBlock.java
core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLParserTest.java
core/repository/sail/src/main/java/org/eclipse/rdf4j/repository/sail/helpers/SPARQLUpdateDataBlockParser.java
core/repository/sail/src/main/java/org/eclipse/rdf4j/repository/sail/helpers/SailUpdateExecutor.java

This PR addresses GitHub issue: #639 .
* InsertData and DeleteData have lineNumberOffset getter/setter 
* update data block parser overrides getLineNumber to process reported offset. 
* added unit tests.

Fix #639: line number error reporting in INSERT/DELETE DATA updates

---

core/model/src/main/java/org/eclipse/rdf4j/model/impl/SimpleLiteral.java
core/model/src/test/java/org/eclipse/rdf4j/model/impl/SimpleLiteralTest.java
core/query/src/main/java/org/eclipse/rdf4j/query/AbstractBindingSet.java

This PR addresses GitHub issue: #649 .
* hashCode implementation for SimpleLiteral and AbstractBindingSet re-fixed (see SES-2188)
* added unit tests to avoid future regression

Fix #649: fixed hashCode impl regression

---

bom/pom.xml

This PR addresses GitHub issue: #652.
* specify <type>war</type> were needed (thus the `<dependencies>` could also be used outside `<dependencyManagement>`
* remove now missing rdf4j-sail-lucene4 etc.
* Reordered some dependencies to be closer to file system alhabetical
This avoids problems with maven site plugin when using the BOM, which would otherwise log various errors from the dependency plugin.
Signed-off-by: Stian Soiland-Reyes <stain@apache.org>

Fix #652: Keep BOM updated so they are valid dependencies

---

compliance/store/src/test/java/org/eclipse/rdf4j/repository/sail/memory/MemoryEvaluationStrategyTest.java
compliance/store/src/test/java/org/eclipse/rdf4j/repository/sail/nativerdf/NativeEvaluationStrategyTest.java
core/console/src/test/java/org/eclipse/rdf4j/console/SetParametersTest.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/ActiveTransactionRegistry.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/Transaction.java
core/model/src/main/java/org/eclipse/rdf4j/model/util/ModelBuilder.java
core/model/src/main/java/org/eclipse/rdf4j/model/vocabulary/SKOSXL.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/EvaluationStrategyFactory.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/function/xsd/CastFunction.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/AbstractEvaluationStrategyFactory.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/ExtendedEvaluationStrategy.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/SimpleEvaluationStrategy.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/TupleFunctionEvaluationStatistics.java
core/repository/api/src/main/java/org/eclipse/rdf4j/repository/filters/AccurateRepositoryBloomFilter.java
core/repository/api/src/main/java/org/eclipse/rdf4j/repository/filters/InaccurateRepositoryBloomFilter.java
core/repository/api/src/main/java/org/eclipse/rdf4j/repository/filters/RepositoryBloomFilter.java
core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/SimpleParseLocationListener.java
core/sail/federation/src/test/java/org/eclipse/rdf4j/sail/federation/BloomFilterFederationQueryTest.java
core/sail/spin/src/test/java/org/eclipse/rdf4j/sail/spin/EvaluationModeTest.java
eclipse-settings/codetemplates.xml
testsuites/store/src/main/java/org/eclipse/rdf4j/repository/EvaluationStrategyTest.java

This PR addresses GitHub issue: #662 .
* fixed eclipse copyright header template 
* global search-and-replace to make existing files use the corrected header
Please all update your eclipse settings with the correct header template ASAP.

Fix #662: eclipse copyright header code template

---

core/sail/api/src/main/java/org/eclipse/rdf4j/sail/helpers/AbstractSailConnection.java

This PR addresses GitHub issue: #648 .
* Adds logging when rollback fails because transaction is not active

Fix #648 : Log failure to rollback to help with debugging

---

core/rio/api/src/main/java/org/eclipse/rdf4j/rio/LanguageHandler.java
core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/BasicParserSettings.java
core/rio/languages/src/main/java/org/eclipse/rdf4j/rio/languages/BCP47LanguageHandler.java
core/rio/languages/src/main/java/org/eclipse/rdf4j/rio/languages/RFC3066LanguageHandler.java
core/rio/languages/src/main/resources/META-INF/services/org.eclipse.rdf4j.rio.LanguageHandler
testsuites/rio/src/main/java/org/eclipse/rdf4j/rio/AbstractParserHandlingTest.java

This PR addresses GitHub issue: #449 to support BCP47.
* Adds implementation of BCP47 based on Java-7+ Locale
* Switches BasicParserSettings to use BCP47 by default, per our reliance on RDF-1.1
RFC3066 is now only used if it is specifically setup in parser settings, or referenced directly.
The use of BCP47 is required for RDF-1.1, where RFC3066 was required for RDF-1.0. Since we have changed to RDF-1.1, we need to change the default language tag handler to match.
I still want to add some regression tests related to issue #665 and other language tag case-sensitivity issues to verify and preserve the new BCP47 behaviour unless we change the regression test, but the core implementation of BCP47 ```new …
```

issue #449 : Add support for BCP47, and use by default

---

compliance/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLServiceEvaluationTest.java
core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Service.java

This PR addresses GitHub issue: #646 .
* vars introduced by BIND or VALUES now included in service vars
* added unit test to check for regression
@damyan-ognyanov

Fix #646: included vars from VALUES clauses and BIND clause in service vars

---

core/model/src/main/java/org/eclipse/rdf4j/model/impl/SimpleLiteral.java
core/model/src/test/java/org/eclipse/rdf4j/model/impl/SimpleLiteralTest.java

This PR addresses GitHub issue: #668 .
* SimpleLiteral.hashCode now uses label only again (cf. Literal API spec)
* updated unit tests to remove incorrect assertions and add test on different-case language tags

Fix #668: reverted hashCode implementation to conform to API spec

---

core/model/src/main/java/org/eclipse/rdf4j/model/util/Literals.java
core/model/src/main/java/org/eclipse/rdf4j/model/util/language/IanaLanguageTag.java
core/model/src/main/java/org/eclipse/rdf4j/model/util/language/Iso3166.java
core/model/src/main/java/org/eclipse/rdf4j/model/util/language/Iso639.java
core/model/src/main/java/org/eclipse/rdf4j/model/util/language/LanguageTag.java
core/model/src/main/java/org/eclipse/rdf4j/model/util/language/LanguageTagCodes.java
core/model/src/main/java/org/eclipse/rdf4j/model/util/language/LanguageTagSyntaxException.java
core/model/src/test/java/org/eclipse/rdf4j/model/util/LiteralsTest.java
core/rio/languages/src/main/java/org/eclipse/rdf4j/rio/languages/BCP47LanguageHandler.java

This PR addresses GitHub issue: #673 .
* Adds a utility function for the steps required for BCP47 language tag normalisation
* Converts BCP47LanguageHandler to use the utility function

Fix #673 : Add utility for BCP47 normalisation

---

core/query/src/main/java/org/eclipse/rdf4j/query/AbstractBindingSet.java
core/query/src/test/java/org/eclipse/rdf4j/query/BindingSetTest.java
core/query/src/test/java/org/eclipse/rdf4j/query/impl/ListBindingSetTest.java
core/query/src/test/java/org/eclipse/rdf4j/query/impl/MapBindingSetTest.java
core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/QueryBindingSetTest.java
core/repository/sparql/pom.xml
core/repository/sparql/src/test/java/org/eclipse/rdf4j/repository/sparql/query/SPARQLQueryBindingSetTest.java

This PR addresses GitHub issue: #676 .
* reverted changed hashcode impl back to be API-conformant 
* add regression tests for all BindingSet implementations

Fix #676: revert changes to hashcode of AbstractBindingSet

---

core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/QueryResultView.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/RepositoryController.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/RepositoryInterceptor.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/contexts/ContextsController.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/graph/GraphController.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/namespaces/NamespaceController.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/namespaces/NamespacesController.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/size/SizeController.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/statements/ExportStatementsView.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/statements/StatementsController.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/Transaction.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/TransactionController.java
core/http/server-spring/src/test/java/org/eclipse/rdf4j/http/server/repository/statements/TestStatementsController.java
core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/NativeSailStore.java
testsuites/store/src/main/java/org/eclipse/rdf4j/sail/RDFStoreTest.java

This PR addresses GitHub issue: #680 .
* RepositoryInterceptor in RDF4J Server no longer keeps a shared RepositoryConnection, instead it creates a new, pre-configured connection whenever needed. Callers are responsible for closing the connection when done.
* Native store internal locking simplified 
These fixes have been tested in combination with the test case provided in #680, and it seems to resolve the issue. In addition all existing tests greenline.
I will look into adding the provided test case to our suite as a regression test.

Fix #680: concurrent requests over http IllegalMonitorException

---

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/EvaluationStatistics.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/ZeroLengthPathIteration.java
core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/ZeroLengthPathIterationTest.java

This PR addresses GitHub issue: #689 .
* QueryJoinOptimizer incorrectly reorganized joins involving ArbitraryLengthPaths due to too-low estimate of cost.
* cost estimate now based on store estimate of single statement pattern involving the ALP's subject and object, and an unknown predicate, times 2 (we estimate an ALP's path length will be at least 2). 
* Tested manually that the bug is specifically caused by the optimizer, not by the execution engine: if the optimizer is completely disabled, the engine does compute the correct query result.

Fix #689: bug in ZeroLengthPathIteration + cost estimate improvement in planner

---

core/sail/inferencer/src/main/java/org/eclipse/rdf4j/sail/inferencer/fc/AbstractForwardChainingInferencerConnection.java

This PR addresses GitHub issue: #697 .
* only report info-level log if actual statements inferred

Fix #697: only report if actual statements inferred

---

core/sail/fts/elasticsearch/src/main/java/org/eclipse/rdf4j/sail/elasticsearch/ElasticsearchIndex.java
core/sail/fts/elasticsearch/src/test/java/org/eclipse/rdf4j/sail/elasticsearch/ElasticsearchIndexTest.java
core/sail/fts/elasticsearch/src/test/java/org/eclipse/rdf4j/sail/elasticsearch/ElasticsearchSailGeoSPARQLTest.java
core/sail/fts/elasticsearch/src/test/java/org/eclipse/rdf4j/sail/elasticsearch/ElasticsearchSailIndexedPropertiesTest.java
core/sail/fts/elasticsearch/src/test/java/org/eclipse/rdf4j/sail/elasticsearch/ElasticsearchSailSpinTest.java
core/sail/fts/elasticsearch/src/test/java/org/eclipse/rdf4j/sail/elasticsearch/ElasticsearchSailTest.java
core/sail/fts/elasticsearch/src/test/java/org/eclipse/rdf4j/sail/elasticsearch/ElasticsearchSailTupleFunctionTest.java
core/sail/fts/elasticsearch/src/test/java/org/eclipse/rdf4j/sail/elasticsearch/ElasticsearchTestUtils.java
testsuites/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractLuceneSailGeoSPARQLTest.java
testsuites/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractLuceneSailIndexedPropertiesTest.java
testsuites/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractLuceneSailSpinTest.java
testsuites/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractLuceneSailTest.java
testsuites/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractLuceneSailTupleFunctionTest.java

This PR addresses GitHub issue: #698 .
* Fix the use of shared directories across all elastic search tests
* Add a global semaphore to ensure that JUnit never runs multiple tests through at once, given the use of global JVM state by the ElasticSearch libraries
* Use try-finally to reliably attempt to clean up resources

issue #698 : Remove shared test directory for elastic search tests

---

compliance/http/src/test/java/org/eclipse/rdf4j/http/server/ProtocolTest.java
compliance/store/src/test/java/org/eclipse/rdf4j/repository/http/HTTPTupleQueryResultTest.java
core/http/client/src/main/java/org/eclipse/rdf4j/http/client/BackgroundGraphResult.java
core/http/client/src/main/java/org/eclipse/rdf4j/http/client/BackgroundTupleResult.java
core/http/client/src/main/java/org/eclipse/rdf4j/http/client/QueueCursor.java
core/http/client/src/main/java/org/eclipse/rdf4j/http/client/SesameClientImpl.java
core/http/client/src/main/java/org/eclipse/rdf4j/http/client/SesameSession.java
core/http/client/src/main/java/org/eclipse/rdf4j/http/client/SparqlSession.java
core/http/client/src/test/java/org/eclipse/rdf4j/http/client/BackgroundGraphResultHangTest.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/Transaction.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/TransactionStartController.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/federation/FederatedServiceResolverImpl.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/federation/JoinExecutorBase.java
core/repository/api/src/main/java/org/eclipse/rdf4j/repository/base/AbstractRepository.java
core/repository/http/src/main/java/org/eclipse/rdf4j/repository/http/HTTPRepository.java
core/repository/manager/src/main/java/org/eclipse/rdf4j/repository/manager/LocalRepositoryManager.java
core/repository/manager/src/main/java/org/eclipse/rdf4j/repository/manager/RemoteRepositoryManager.java
core/repository/manager/src/main/java/org/eclipse/rdf4j/repository/manager/RepositoryManager.java
core/repository/sail/src/main/java/org/eclipse/rdf4j/repository/sail/ProxyRepository.java
core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/SPARQLRepository.java
core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/Federation.java
core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/evaluation/ParallelJoinCursor.java
core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/evaluation/ParallelLeftJoinCursor.java
core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/evaluation/QueueCursor.java
core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/MemorySailStore.java
core/util/src/main/java/org/eclipse/rdf4j/common/iteration/AbstractCloseableIteration.java
core/util/src/main/java/org/eclipse/rdf4j/common/iteration/LookAheadIteration.java
testsuites/store/src/main/java/org/eclipse/rdf4j/repository/GraphQueryResultTest.java
testsuites/store/src/main/java/org/eclipse/rdf4j/repository/TupleQueryResultTest.java

This PR addresses GitHub issue: #684 .
* Cleans up more reliably in BackgroundTupleResult when InterruptedException occurs
* Removes internal synchronisation in QueueCursor for exceptions so it now uses ConcurrentLinkedQueue instead of LinkedList.
All tests pass for me after the changes.

issue #684 : More reliably clean up for InterruptedException in BackgroundTupleResult

---

compliance/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLServiceEvaluationTest.java
core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Service.java

This PR addresses GitHub issue: #703 .
* `Service.computeServiceVars` now also visits all descendents of `Extension` objects.
* added unit test, greenlines after fix.
* update test case javadoc

Fix #703: service clause bind clause varname fix + unit test

---

core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLParser.java
core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/UpdateExprBuilder.java
core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/WildcardProjectionProcessor.java
core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ast/ASTModify.java
core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ast/ASTOperation.java
core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ast/ASTQuery.java
core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ast/ASTUnparsedQuadDataBlock.java
core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ast/SyntaxTreeBuilder.java
core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ast/sparql.jjt
core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLParserTest.java

This PR addresses GitHub issue: #686 .
* SPARQLParser now applies WildcardProjectionProcessor to update as well as queries
* SPARQL Grammar adapted so an ASTWhereClause is generated for modify updates
* added regression test

Fix #686: parser now processes subselect wildcards in update operations

---

.travis.yml
pom.xml

This PR addresses GitHub issue: #719 .
* maven failsafe and surefire plugins both use increased heap space for forked jvms 
* obsolete MaxPermSize parameter removed
* bumped versions of various core build / test plugins (compiler, jar, clean, failsafe, surefire). 
* travis environment tweaked to set default maven heap size to 1G

Fix #719: build configuration tweaks

---

core/console/src/main/java/org/eclipse/rdf4j/console/Console.java

This PR addresses GitHub issue: #539 .
* trivial fix to make automatic inclusion of namespace prefixes known in the repository the default.

Fix #539: made automated use of known ns prefixes in queries the default.

---

core/repository/sail/src/main/java/org/eclipse/rdf4j/repository/sail/helpers/SailUpdateExecutor.java
testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLUpdateTest.java

This PR addresses GitHub issue: #729 .
* SailUpdateExecutor now checks presence of `sesame:nil` value as graph name for DELETE clause, and replaces with `null` value.
* added test cases for `DELETE { GRAPH sesame:nil {....` and `WITH sesame:nil DELETE {....` variants.

Fix #729: processing of sesame:nil virtual graph name for DELETE WHERE operations

---

compliance/store/pom.xml
core/http/client/pom.xml
core/model/pom.xml
core/query/pom.xml
core/queryalgebra/evaluation/pom.xml
core/queryalgebra/model/pom.xml
core/queryparser/api/pom.xml
core/queryresultio/api/pom.xml
core/repository/api/pom.xml
core/repository/http/pom.xml
core/repository/manager/pom.xml
core/repository/sail/pom.xml
core/repository/sparql/pom.xml
core/rio/api/pom.xml
core/sail/api/pom.xml
core/sail/base/pom.xml
core/sail/inferencer/pom.xml
core/sail/memory/pom.xml
core/sail/model/pom.xml
core/sail/nativerdf/pom.xml
core/util/pom.xml
pom.xml

This PR addresses GitHub issue: #732 .
* Add japicmp maven plugin to core modules to start gathering knowledge about the scope of our likely public API for #619
* Reenables animal sniffer with the java-8 signatures. This will be useful with Java-9 betas being used more regularly for experimentation.
* Removes some unused managed dependencies
The japicmp inclusions may not be all of the eventual public API modules, but it forms a likely base. The japicmp plugin does not yet have aggregation support, so each of the individual modules that will make up the public API need to have the plugin added to them manually.
Notably, none of the rio or queryresultio modules need to be in the public API IMO, as they are all accessible as services by all …

issue #732 : Add support for japicmp to core modules

---

core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/TransactionController.java

This PR addresses GitHub issue: #725 .

Fix #725: Don't always deregister the connection on commit

---

compliance/sparql/src/test/java/org/eclipse/rdf4j/sail/federation/FederationSPARQL10QueryTest.java
compliance/sparql/src/test/java/org/eclipse/rdf4j/sail/federation/FederationSPARQL11QueryTest.java
compliance/sparql/src/test/java/org/eclipse/rdf4j/sail/federation/FederationSparqlTest.java
core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/algebra/OwnedTupleExpr.java
core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/evaluation/FederationStrategy.java

This PR addresses GitHub issue: #181  .
* Better naming to Federation compliance tests.
* Test case for #181.
* Fix for #181.

Fix #181: federation scoping of joins from different graphs

---

compliance/queryresultio/src/test/java/org/eclipse/rdf4j/query/resultio/binary/SPARQLBinaryTupleBackgroundTest.java
compliance/queryresultio/src/test/java/org/eclipse/rdf4j/query/resultio/sparqljson/SPARQLJSONTupleBackgroundTest.java
compliance/queryresultio/src/test/java/org/eclipse/rdf4j/query/resultio/sparqlxml/SPARQLXMLTupleBackgroundTest.java
compliance/queryresultio/src/test/java/org/eclipse/rdf4j/query/resultio/text/csv/SPARQLCSVTupleBackgroundTest.java
compliance/queryresultio/src/test/java/org/eclipse/rdf4j/query/resultio/text/tsv/SPARQLTSVTupleBackgroundTest.java
compliance/rio/src/test/java/org/eclipse/rdf4j/rio/binary/BinaryRDFWriterBackgroundTest.java
compliance/rio/src/test/java/org/eclipse/rdf4j/rio/jsonld/JSONLDWriterBackgroundTest.java
compliance/rio/src/test/java/org/eclipse/rdf4j/rio/nquads/NQuadsWriterBackgroundTest.java
compliance/rio/src/test/java/org/eclipse/rdf4j/rio/ntriples/NTriplesWriterBackgroundTest.java
compliance/rio/src/test/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLPrettyWriterBackgroundTest.java
compliance/rio/src/test/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLWriterBackgroundTest.java
compliance/rio/src/test/java/org/eclipse/rdf4j/rio/trig/TriGPrettyWriterBackgroundTest.java
compliance/rio/src/test/java/org/eclipse/rdf4j/rio/trig/TriGWriterBackgroundTest.java
core/http/client/src/main/java/org/eclipse/rdf4j/http/client/BackgroundGraphResult.java
core/http/client/src/main/java/org/eclipse/rdf4j/http/client/BackgroundTupleResult.java
core/query/src/main/java/org/eclipse/rdf4j/query/QueryResults.java
core/query/src/main/java/org/eclipse/rdf4j/query/impl/BackgroundGraphResult.java
core/query/src/main/java/org/eclipse/rdf4j/query/impl/QueueCursor.java
core/queryresultio/api/src/main/java/org/eclipse/rdf4j/query/resultio/QueryResultIO.java
core/queryresultio/api/src/main/java/org/eclipse/rdf4j/query/resultio/helpers/BackgroundTupleResult.java
core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/query/QueueCursor.java
core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/evaluation/QueueCursor.java
core/util/src/main/java/org/eclipse/rdf4j/common/iteration/QueueIteration.java
testsuites/queryresultio/src/main/java/org/eclipse/rdf4j/query/resultio/AbstractQueryResultIOTest.java

This PR addresses GitHub issue: #740 .
* Move BackgroundGraphResult and BackgroundTupleResult (and QueueCursor) to more accessible locations
* Add new API calls that will use the background methods (QueryResults.parseGraphBackground and QueryResultIO.parseTupleBackground) with a small fixed length BlockingQueue to simulate a pull based parser. Parser will now block (ie, wait) on their respective handle methods until the queue has the capacity to allow it to go further.
This pull request addresses part of #738, in that the internal push-based parsing now has an easy to use push-back mechanism to rate-limit and (almost) short-circuit the parsing based on the consumer. In reality, the capacity of the BlockingQueue used imposes a limit on the …

Fix #740: New background results API

---

core/rio/rdfxml/src/test/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParserTest.java
core/rio/trix/src/test/java/org/eclipse/rdf4j/rio/trix/TriXParserTest.java

This PR addresses GitHub issue: #759 .
* Use fixed Locale.ENGLISH for XML error verification in tests. If this turns out not to work, the message verification can be easily removed, but prefer if the tests were specific to the error they are attempting to test

issue #759 : Use fixed Locale.ENGLISH for XML error verification

---

benchmark/pom.xml
benchmark/src/main/java/org/eclipse/rdf4j/benchmark/ForwardChainingSchemaCachingRDFSInferencerBenchmark.java
benchmark/src/main/java/org/eclipse/rdf4j/benchmark/ReasoningBenchmark.java
pom.xml

This PR addresses GitHub issue: #751 .
* Fixed version number in the benchmark pom
* Applied the renaming of ForwardChainingSchemaCachingRDFSInferencer to the benchmarking classes

#751 updated benchmark pom and applied renaming

---

compliance/rio/src/test/java/org/eclipse/rdf4j/rio/turtle/CustomTurtleParserTest.java
core/model/src/test/java/org/eclipse/rdf4j/model/AbstractModelTest.java
core/util/src/test/java/org/eclipse/rdf4j/common/net/ParsedURITest.java
testsuites/rio/src/main/java/org/eclipse/rdf4j/rio/ntriples/AbstractNTriplesParserUnitTest.java

This PR addresses GitHub issue: #748.
Ahead of removing deprecated methods from Model, fix the tests that still use those methods.

Clean up tests using deprecated methods

---

compliance/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/ArbitraryLengthPathTest.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/PathIteration.java

Use hashCode of PathIteration to identify intermediate variables
This PR addresses GitHub issue: #781 .

issue #781: Use hashCode of PathIteration

---

compliance/queryresultio/src/test/java/org/eclipse/rdf4j/query/resultio/text/tsv/SPARQLTSVTupleBackgroundTest.java
compliance/queryresultio/src/test/java/org/eclipse/rdf4j/query/resultio/text/tsv/SPARQLTSVTupleTest.java
core/queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/text/tsv/SPARQLResultsTSVWriter.java

This PR addresses GitHub issue: #747 .

Fix #747: Don't encode TSV literals in quotes unless needed

---

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryJoinOptimizer.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StrictEvaluationStrategy.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/limited/LimitedSizeEvaluationStrategy.java
core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Join.java
core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Projection.java
core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/helpers/TupleExprs.java
core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java
core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/evaluation/FederationStrategy.java

This PR uses LH join bindings to eval zero or one path modifiers and greatly improves the performance. Previously zero or one path modifiers were treated like a subqueries and used a hash join operation. Note that zero or more path modifiers were already improved with #689
This PR addresses GitHub issue: #695 .

Fix #695: Don't treat path modifiers as subqueries

---

core/http/workbench/src/main/java/org/eclipse/rdf4j/workbench/proxy/CookieHandler.java
core/http/workbench/src/main/java/org/eclipse/rdf4j/workbench/util/CookieHandler.java

This PR addresses GitHub issue: #787` .
* as per documented in the Java Servlet API, getContextPath return an empty string rather than null if the context path is the root. 
As part of this I discovered that we have two separate CookieHandler classes, for some reason. Something worth investigating in a followup.

Fix #787: CookieHandlers now check for empty context path string instead of null

---

core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/AbstractRDFParser.java
core/rio/binary/src/main/java/org/eclipse/rdf4j/rio/binary/BinaryRDFParser.java
core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDInternalTripleCallback.java
core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDParser.java
core/rio/jsonld/src/test/java/org/eclipse/rdf4j/rio/jsonld/JSONLDInternalTripleCallbackTest.java
core/rio/nquads/src/main/java/org/eclipse/rdf4j/rio/nquads/NQuadsParser.java
core/rio/ntriples/src/main/java/org/eclipse/rdf4j/rio/ntriples/NTriplesParser.java
core/rio/rdfjson/src/main/java/org/eclipse/rdf4j/rio/rdfjson/RDFJSONParser.java
core/rio/rdfxml/src/main/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParser.java
core/rio/trix/src/main/java/org/eclipse/rdf4j/rio/trix/TriXParser.java
core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleParser.java
testsuites/rio/src/main/java/org/eclipse/rdf4j/rio/RDFWriterTest.java

This PR addresses GitHub issue: #745 .
* Consistently call AbstractRDFParser.clear before and after parsing to ensure state is consistent with the API goals of safely (not concurrently, just in serial) reusing RDFParser instances within the RDF-1.1 Abstract Model expectations
* Adds a test to ensure that the same blank node is parsed as two distinct objects by the same RDFParser across successive calls to RDFParser.parse

issue #745 : Clear parser state before/after parsing

---

core/model/src/main/java/org/eclipse/rdf4j/model/vocabulary/SHACL.java

This PR addresses GitHub issue: #800  .
* Vocabulary class with constants for W3C Shapes Constraint Language (SHACL)
SHACL should be fairly stable now, the EC has just started a work package on using OWL and SHACL for DCAT-AP validation.
Class was generated using [VocGen](https://github.com/Fedict/lod-vocgen)
This commit does not provide any code for running / checking SHACL rules (i.e. does not contain a SHACL engine)

Initial commit SHACL vocab

---

core/http/client/src/main/java/org/eclipse/rdf4j/http/client/SharedHttpClientSessionManager.java

This PR addresses GitHub issue: #647 
It is generally not a good idea to retry HTTP requests against a database service. This change forces the original HTTP error to be returned and doesn't try anything more.

issue #647: Disable automatic retries in client

---

core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/config/SPARQLRepositoryConfig.java
core/repository/sparql/src/test/java/org/eclipse/rdf4j/repository/sparql/config/SPARQLRepositoryConfigTest.java

Constructors that take SPARQL query and/or update endpoints did not set the type field properly. Repository managers could not retrieve the config information from the system repository without the type statement later, causing getRepository to fail with an exception:
org.eclipse.rdf4j.repository.config.RepositoryConfigException: Repository implementation for repository missing
Signed-off-by: Xiaofeng Li <luke.the.coder@gmail.com>
This PR addresses GitHub issue: #819  .
Call default constructor in constructors that take endpoint parameters.

issue #819: Missing type for SPARQL repo config

---

core/model/src/main/java/org/eclipse/rdf4j/model/datatypes/XMLDatatypeUtil.java
core/model/src/main/java/org/eclipse/rdf4j/model/impl/ValidatingValueFactory.java
core/model/src/main/java/org/eclipse/rdf4j/model/util/Literals.java
core/model/src/main/java/org/eclipse/rdf4j/model/util/URIUtil.java
core/model/src/test/java/org/eclipse/rdf4j/model/util/URIUtilTest.java

This PR addresses GitHub issue: #712 .
* Validates literals with known datatypes, literal languages, blank node IDs, and IRIs before passing the values to the underlying ValueFactory

Fix #712: Add ValidatingValueFactory wrapper

---

core/model/src/main/java/org/eclipse/rdf4j/model/vocabulary/DCAT.java
core/model/src/main/java/org/eclipse/rdf4j/model/vocabulary/DOAP.java

added reccommended prefix for doap, as in [http://prefix.cc/doap](http://prefix.cc/doap)
This PR addresses GitHub issue: #866 .
* added PREFIX / NS constants for the vocabulary DOAP, to make it compliant with the others provided, which usually expose `NS(PREFIX,NAMESPACE)` constants

update DOAP.java with default prefix

---

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/QueryBindingSet.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StrictEvaluationStrategy.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/ExtensionIterator.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/PathIteration.java
core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/query/SPARQLQueryBindingSet.java
testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ComplexSPARQLQueryTest.java

This PR addresses GitHub issue: #79 .
* Uses a binding with value null for unbound solutions that must remain so
* hasBinding will return true, but getValue will return null
* Query strategies need to check if binding already has a solution AND
* if the solution for the variable is to remain unbound

Fix #79: Use null binding for unbound variable solutions

---

core/console/src/main/java/org/eclipse/rdf4j/console/Create.java
core/console/src/test/java/org/eclipse/rdf4j/console/AbstractCommandTest.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/RepositoryListController.java
core/http/workbench/src/main/java/org/eclipse/rdf4j/workbench/commands/CreateServlet.java
core/repository/manager/src/main/java/org/eclipse/rdf4j/repository/manager/LocalRepositoryManager.java
core/repository/manager/src/main/java/org/eclipse/rdf4j/repository/manager/RemoteRepositoryManager.java
core/repository/manager/src/main/java/org/eclipse/rdf4j/repository/manager/RepositoryManager.java
core/runtime/src/main/java/org/eclipse/rdf4j/runtime/RepositoryManagerFederator.java

This PR addresses GitHub issue: #860 .
* Avoid the use of RepositoryManager#getSystemRepository()
* First step to allow alternative RepositoryManager implementations that don't use a SYSTEM repository

Fix #860: Deprecate RepositoryManager#getSystemRepository

---

core/model/src/main/java/org/eclipse/rdf4j/model/Model.java
core/model/src/main/java/org/eclipse/rdf4j/model/NamespaceAware.java
core/rio/api/src/main/java/org/eclipse/rdf4j/rio/Rio.java
core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/ContextStatementCollector.java
core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDInternalRDFParser.java

This PR addresses GitHub issue: #834 .
* Adds a new NamespaceAware interface to abstract out the Model.getNamespace and Model.getNamespaces methods so code can check for NamespaceAware rather than Model
This allows users of Rio.write, in particular, to submit their own collections without having to override Model, and have namespaces preserved in the output.

Fix #834 : Add NamespaceAware interface

---

core/rio/nquads/src/main/java/org/eclipse/rdf4j/rio/nquads/NQuadsWriter.java
core/rio/ntriples/src/main/java/org/eclipse/rdf4j/rio/ntriples/NTriplesWriter.java

This PR addresses GitHub issue: #850 .
* ESCAPE_UNICODE setting was already applied to literals in NTriples/NQuads
* With this PR it is also applied to IRIs in NTriples/NQuads
* If the ESCAPE_UNICODE is set to false IRIs with unicode chars will be written using the writer's character set and not escaped

Fix #850: Apply ESCAPE_UNICODE setting to IRI in NTriples

---

core/sail/spin/src/main/java/org/eclipse/rdf4j/sail/spin/SpinSailConnection.java

This PR addresses GitHub issue: #364 .
* Changed handleConstraintViolation from private to protected, so it can be overridden (e.g. to create a fancier report)

Fix #364: Changed handleConstraintViolation to protected

---

core/console/src/main/java/org/eclipse/rdf4j/console/Create.java
core/console/src/test/java/org/eclipse/rdf4j/console/AbstractCommandTest.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/RepositoryConfigRepository.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/RepositoryInterceptor.java
core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/RepositoryListController.java
core/http/workbench/src/main/java/org/eclipse/rdf4j/workbench/commands/CreateServlet.java
core/repository/api/src/main/java/org/eclipse/rdf4j/repository/config/RepositoryConfig.java
core/repository/api/src/main/java/org/eclipse/rdf4j/repository/config/RepositoryConfigUtil.java
core/repository/http/src/main/java/org/eclipse/rdf4j/repository/http/config/HTTPRepositoryConfig.java
core/repository/manager/src/main/java/org/eclipse/rdf4j/repository/manager/LocalRepositoryManager.java
core/repository/manager/src/main/java/org/eclipse/rdf4j/repository/manager/RemoteRepositoryManager.java
core/repository/manager/src/main/java/org/eclipse/rdf4j/repository/manager/RepositoryManager.java
core/repository/manager/src/main/java/org/eclipse/rdf4j/repository/manager/SystemRepository.java
core/repository/manager/src/main/java/org/eclipse/rdf4j/repository/manager/SystemRepositoryFactory.java
core/repository/manager/src/main/resources/META-INF/services/org.eclipse.rdf4j.repository.config.RepositoryFactory
core/repository/manager/src/test/java/org/eclipse/rdf4j/repository/manager/LocalRepositoryManagerTest.java
core/repository/sail/src/main/java/org/eclipse/rdf4j/repository/sail/config/ProxyRepositoryConfig.java
core/repository/sail/src/main/java/org/eclipse/rdf4j/repository/sail/config/SailRepositoryConfig.java
core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/config/SPARQLRepositoryConfig.java
core/runtime/src/main/java/org/eclipse/rdf4j/runtime/RepositoryManagerFederator.java
core/sail/api/src/main/java/org/eclipse/rdf4j/sail/config/AbstractSailImplConfig.java
core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/config/BaseSailConfig.java
core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/config/FederationConfig.java
core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/config/AbstractLuceneSailConfig.java
core/sail/inferencer/src/main/java/org/eclipse/rdf4j/sail/inferencer/fc/config/CustomGraphQueryInferencerConfig.java
core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/config/MemoryStoreConfig.java
core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/config/NativeStoreConfig.java

This PR addresses GitHub issue: #859 .
* RepositoryConifg is stored in config.ttl files (SYSTEM repository is updated if it already exists)
* RepositoryManager does not lock configs and can be used by multiple processes
* http-server uses a pseudo SYSTEM repository that does not support queries and limited isolation levels

Fix #859: Use config.ttl files instead of SYSTEM repository

---

core/http/client/src/main/java/org/eclipse/rdf4j/http/client/SPARQLProtocolSession.java
core/http/client/src/main/java/org/eclipse/rdf4j/http/client/SharedHttpClientSessionManager.java
core/sail/model/pom.xml
core/sail/model/src/main/java/org/eclipse/rdf4j/sail/model/NonSerializables.java
core/sail/model/src/main/java/org/eclipse/rdf4j/sail/model/SailModel.java
core/util/pom.xml

This PR addresses GitHub issue: #872 .
* Use java7 String.join
* Create custom ThreadFactory
* Move NonSerializables to sail-model

Fix #872: Move guava dependency from util to sail-model

---

core/rio/api/src/main/java/org/eclipse/rdf4j/rio/RDFWriterFactory.java
core/rio/api/src/main/java/org/eclipse/rdf4j/rio/Rio.java
core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/BasicWriterSettings.java
core/rio/binary/src/main/java/org/eclipse/rdf4j/rio/binary/BinaryRDFWriterFactory.java
core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDWriter.java
core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDWriterFactory.java
core/rio/n3/src/main/java/org/eclipse/rdf4j/rio/n3/N3Writer.java
core/rio/n3/src/main/java/org/eclipse/rdf4j/rio/n3/N3WriterFactory.java
core/rio/nquads/src/main/java/org/eclipse/rdf4j/rio/nquads/NQuadsWriterFactory.java
core/rio/ntriples/src/main/java/org/eclipse/rdf4j/rio/ntriples/NTriplesWriterFactory.java
core/rio/rdfjson/src/main/java/org/eclipse/rdf4j/rio/rdfjson/RDFJSONWriterFactory.java
core/rio/rdfxml/src/main/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLWriter.java
core/rio/rdfxml/src/main/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLWriterFactory.java
core/rio/rdfxml/src/main/java/org/eclipse/rdf4j/rio/rdfxml/util/RDFXMLPrettyWriter.java
core/rio/rdfxml/src/main/java/org/eclipse/rdf4j/rio/rdfxml/util/RDFXMLPrettyWriterFactory.java
core/rio/trig/src/main/java/org/eclipse/rdf4j/rio/trig/TriGWriter.java
core/rio/trig/src/main/java/org/eclipse/rdf4j/rio/trig/TriGWriterFactory.java
core/rio/trix/src/main/java/org/eclipse/rdf4j/rio/trix/TriXWriterFactory.java
core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleWriter.java
core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleWriterFactory.java

This PR addresses GitHub issue: #876 .
* Add baseURI parameter to WriterFactory methods
* Add BasicWriterSettings.java.BASE_DIRECTIVE setting to omit directive
* Use ParsedIRI#relativize() in output when baseURI is provided

Fix #876: Add BASE_DIRECTIVE writer config and baseURI parameter to writer interface

---

core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/query/QueryStringUtil.java
core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/query/SPARQLBooleanQuery.java
core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/query/SPARQLGraphQuery.java
core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/query/SPARQLTupleQuery.java
core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/query/SPARQLUpdate.java

This PR addresses GitHub issue: #888 .
* Skip SELECT clause replacement for non-tuple queries

Fix #888: Inline variable bindings for non-tuple SPARQL operations

---

core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryJoinOptimizerTest.java
core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/BinaryTupleOperator.java
core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/UnaryTupleOperator.java
core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java
core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/algebra/AbstractNaryOperator.java

This PR addresses GitHub issue: #87  .
* Include multiple aggregate operations into the same Extension

Fix #87: Handle multiple aggregates in ORDER BY clause

---

core/repository/api/src/main/java/org/eclipse/rdf4j/repository/util/Repositories.java

This PR addresses GitHub issue: #93 .
* Adds non-transactional versions of methods in Repositories helper utility class
Some Repository implementations do not silently succeed if transactions are attempted to be committed on read-only endpoints when there were no changes queued up for the transaction.
Hence, it is necessary to add versions of all of the Repositories methods that do not attempt to begin, commit, or rollback transactions.

Fix #93 : Add non-transactional versions of Repositories methods

---

core/repository/sail/src/main/java/org/eclipse/rdf4j/repository/sail/SailUpdate.java

Fix #25: Execute each sequence of update operations in a single transaction
This PR addresses GitHub issue: #25 .
* If an error is detected it ignores subsequent operations
* If an error is detected all operations are rolledback

Fix #25: Execute each sequence of update operations in a single transaction

---

compliance/rio/src/test/java/org/eclipse/rdf4j/rio/turtle/TurtlePrettyWriterTest.java
core/repository/manager/src/main/java/org/eclipse/rdf4j/repository/manager/LocalRepositoryManager.java
core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/BasicWriterSettings.java
core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/ArrangedWriter.java
core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleWriter.java
core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleWriterFactory.java
core/util/src/main/java/org/eclipse/rdf4j/common/io/IndentingWriter.java
testsuites/rio/src/main/java/org/eclipse/rdf4j/rio/RDFWriterTest.java

Omits all blank node labels and inlines their values as a nested objects or lists
This PR addresses GitHub issues: #889 #316 and #317
* PRETTY_PRINT enabled by default
* INLINE_BLANK_NODES disabled by default, but
* When enabled blank nodes are written as [] or () and repeated every time they are used, and
* Throws an exception when a blank node cycle is detected

Fix #889: Add INLINE_BLANK_NODE setting for TurtleWriter

---

compliance/rio/src/test/java/org/eclipse/rdf4j/rio/trig/TriGParserTest.java
compliance/rio/src/test/java/org/eclipse/rdf4j/rio/turtle/TurtleParserTest.java
core/rio/trig/src/main/java/org/eclipse/rdf4j/rio/trig/TriGParser.java
testsuites/rio/src/main/java/org/eclipse/rdf4j/rio/trig/TriGParserTestCase.java
testsuites/rio/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleParserTestCase.java

This PR addresses GitHub issue: #473  .
* Enable VERIFY_DATATYPE_VALUES in tests
* Change tests to fail on parse errors
* Require a graph name when using the GRAPH clause in TriG

Fix #473: Fail on parser errors when VERIFY_DATATYPE_VALUES is true

---

core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleParser.java

This PR addresses GitHub issue: #537 .
* Report object statement in parseCollection and parseImplicitBlank methods before returning

Fix #537: Report blank node object before subject statements

---

core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java
core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLParserTest.java

This PR addresses GitHub issue: #77 .
* Normalize literal labels when datatype present in SPARQL parser

Fix #77: Normalize typed literals in SPARQL parser

---

core/rio/jsonld/pom.xml

This PR addresses GitHub issue: #898  .
* Exclude jsonld-java httpcomponent dependencies
* Add httpcomponent dependencies to rdf4j-rio-jsonld

Fix #898: Exclude json-ld hc deps and add common rdf4j hc deps

---

core/query/src/main/java/org/eclipse/rdf4j/query/impl/BackgroundGraphResult.java
core/queryresultio/api/src/main/java/org/eclipse/rdf4j/query/resultio/helpers/BackgroundTupleResult.java
core/util/src/main/java/org/eclipse/rdf4j/common/iteration/IterationWrapper.java
core/util/src/main/java/org/eclipse/rdf4j/common/iteration/QueueIteration.java

This PR addresses GitHub issue: #896 and #853   .
* When result is closed, resume parsing until complete, and then close underlying

Fix #896: Finish parsing background results on close

---

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/federation/RepositoryFederatedService.java
core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/query/QueryStringUtil.java
core/repository/sparql/src/test/java/org/eclipse/rdf4j/repository/sparql/query/QueryStringUtilTest.java

This PR addresses GitHub issue: #911.
* Expand simple literals without xsd:string, include the datatype if it isn't xsd:string
* Compatible with both RDF 1.0 and RDF 1.1

Fix #911: Federation not compatible with RDF 1.0 endpoints

---

http/client/src/main/java/org/eclipse/rdf4j/http/client/BackgroundResultExecutor.java
http/client/src/main/java/org/eclipse/rdf4j/http/client/SPARQLProtocolSession.java
http/client/src/main/java/org/eclipse/rdf4j/http/client/SharedHttpClientSessionManager.java
repository/http/src/main/java/org/eclipse/rdf4j/repository/http/HTTPRepository.java
repository/http/src/main/java/org/eclipse/rdf4j/repository/http/HTTPRepositoryConnection.java
repository/manager/src/main/java/org/eclipse/rdf4j/repository/manager/RemoteRepositoryManager.java
repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/SPARQLConnection.java

This PR addresses GitHub issue: #920 .
* Add AutoClose to SPARQLProtocolSession
* Force close open results when session is closed
* Close session when HTTPRepositoryConnection is closed
* Force close open sessions when session manager is closed

Fix #920: Closing http repoCon forces open results to close

---

http/client/src/main/java/org/eclipse/rdf4j/http/client/RDF4JProtocolSession.java
http/client/src/main/java/org/eclipse/rdf4j/http/client/SesameClientImpl.java
http/client/src/main/java/org/eclipse/rdf4j/http/client/SesameSession.java
http/client/src/main/java/org/eclipse/rdf4j/http/client/SharedHttpClientSessionManager.java
http/protocol/src/main/java/org/eclipse/rdf4j/http/protocol/Protocol.java

This PR addresses GitHub issue: #880 #852 #851 .
* The client sends a PING request to the server every 30s to keep the transaction from timing out
* Even if the server doesn't understand the request, it should at least reset the timeout

Fix #880: Periodically ping server to keep transaction alive

---

pom.xml

This PR addresses GitHub issue: #799 .
* Reuse the recently introduced jackson-bom to make versioning of jackson family libraries consistent
Deviates from the Jackson BoM in the case of jackson-annotations which for 2.8.x is still being released for each patch (although it isn't intended to have changes on patch versions). This is to avoid having users misunderstand the situation regarding jackson-annotations versioning. From 2.9.0 the situation for jackson-annotations is planned to be changed so that 2.9.0 is a fixed version for it. When the occurs the exception for jackson-annotations can be removed and only jackson-bom included.
More details on the jackson-annotations issue available at https://github.com/FasterXML/jackson-bom/issues/4 …

issue #799 : Use Jackson BoM

---

core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleWriter.java
testsuites/rio/src/main/java/org/eclipse/rdf4j/rio/RDFWriterTest.java

This PR addresses GitHub issue: #921 .
* Check for +INF, -INF, and NaN before using short numeric turtle syntax

Fix #921: Check for special double values in turtle writer

---

core/model/src/main/java/org/eclipse/rdf4j/model/datatypes/XMLDatatypeUtil.java
core/model/src/test/java/org/eclipse/rdf4j/model/datatypes/XMLDatatypeUtilTest.java

This PR addresses GitHub issue: #934 .
* XMLGregorianCalendar supports years >9999
* Change regex to pass these through

Fix #934: Allow years >9999 in xsd validation

---

core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLParser.java
testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLUpdateTest.java

This PR addresses GitHub issue: #924  .
* Pass baseURI along (as with PREFIX) while parsing update operations

Fix #924: Inherit BASE clause in subsequent update operations

---

core/http/workbench/src/main/webapp/transformations/update.xsl

This PR addresses GitHub issue: #908 #373  .
* Add text in textarea tag to force xslt to include and end tag

Fix #908: Add text in textarea tag for MS Edge browser rendering

---

repository/http/src/main/java/org/eclipse/rdf4j/repository/http/HTTPRepositoryConnection.java
repository/http/src/main/java/org/eclipse/rdf4j/repository/http/helpers/HTTPRepositorySettings.java

This PR addresses GitHub issue: #728.
* Add default value of the buffer size as `RioSetting`
* Add support of the setting in `HTTPRepositoryConnection`

Fix #728 : Buffer size configurable using instance of RioSettings

---

core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/btree/BTree.java

This PR addresses GitHub issue: #940 .
* Add synchronized flag to close() method in the event that it is called from an interrupt handler

Fix #940: synchronize RangeIterator#close

---

compliance/rio/pom.xml
http/protocol/pom.xml

This PR addresses GitHub issue: #919 .
* Add JVM arg --add-modules=java.xml.bind if jdk9

Issue #919: Add jdk9 profiles to add-modules java.xml.bind for tests

---

queryparser/api/src/main/java/org/eclipse/rdf4j/query/parser/QueryPrologLexer.java
queryparser/api/src/test/java/org/eclipse/rdf4j/query/parser/QueryPrologLexerTest.java

This PR addresses GitHub issue: #951 .
* Regex was update to handle multiline comments, but matcher group wasn't

Fix #951: Handle multiline comments in QueryPrologLexer

---

model/src/main/java/org/eclipse/rdf4j/model/impl/SimpleLiteral.java

This PR addresses GitHub issue: #948 .
* Creates a StringBuilder of the exact length needed for SimpleLiteral#toString()

Fix #948: Use exact string buffer size for SimpleLiteral#toString()

---

queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/text/tsv/SPARQLResultsTSVWriter.java

This PR addresses GitHub issue: #962 .
* Check for empty label in TSV writer

Fix #962: Check for empty labels

---

rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/BasicParserSettings.java

This PR addresses GitHub issue: #967  .
* Added missing default namespaces from https://www.w3.org/2011/rdfa-context/rdfa-1.1
* Ordered the namespaces according to this list
* Minor comments

Added and ordered default namespaces

---

model/src/main/java/org/eclipse/rdf4j/model/vocabulary/OWL.java

This PR addresses GitHub issue: #766  .
* Added constants for OWL2 (same namespaces as OWL), following the earlier naming convention used in this file (all uppercase, no underscore or other separator between words)
* Removed some blank lines
* Deprecated owl:Individual (AFAIK, it never was an actual class in OWL anyway, only a concept)

Added constants for OWL2

---

model/src/main/java/org/eclipse/rdf4j/model/util/Models.java
rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/AbstractRDFParser.java
rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/BasicParserSettings.java
rio/binary/src/main/java/org/eclipse/rdf4j/rio/binary/BinaryRDFParser.java
rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDInternalTripleCallback.java
rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDParser.java
rio/nquads/src/main/java/org/eclipse/rdf4j/rio/nquads/NQuadsParser.java
rio/ntriples/src/main/java/org/eclipse/rdf4j/rio/ntriples/NTriplesParser.java
rio/rdfjson/src/main/java/org/eclipse/rdf4j/rio/rdfjson/RDFJSONParser.java
rio/rdfxml/src/main/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParser.java
rio/trig/src/main/java/org/eclipse/rdf4j/rio/trig/TriGParser.java
rio/trix/src/main/java/org/eclipse/rdf4j/rio/trix/TriXParser.java
rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleParser.java

This PR addresses GitHub issue: #438 .
* Add BasicParserSettings.SKOLEMIZE_ORIGIN to store scheme and authority
* Add AbstractRDFParser#createNode() method to user SKOLEMIZE_ORIGIN setting

Fix #438: Add SKOLEMIZE_ORIGIN parser setting

---

rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleParser.java

Signed-off-by: Yasen Marinov <yasen.marinov@ontotext.com>
This PR addresses GitHub issue: #984 .
Skip whitespaces when parsing a blank node as an object.

Fix #984: Skip whitespaces when parsing object blank node

---

rio/ntriples/src/main/java/org/eclipse/rdf4j/rio/ntriples/NTriplesParser.java
rio/ntriples/src/main/java/org/eclipse/rdf4j/rio/ntriples/NTriplesUtil.java
rio/ntriples/src/main/java/org/eclipse/rdf4j/rio/ntriples/NTriplesWriter.java
rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleUtil.java

This PR addresses GitHub issue: #986 .
* Encode illegal IRI characters that could trip up parsing, such as <>

Fix #986: Encode illegal IRI characters as codepoints in Turtle

---

rio/api/src/main/resources/META-INF/services/java.nio.file.spi.FileTypeDetector

This PR addresses GitHub issue: #978 .
* Change package name in services

Fix #978: Fix package name of RioFileTypeDetector

---

rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/ArrangedWriter.java

This PR addresses GitHub issue: #1000!
* Use a stable comparison with literals that have the same label

Fix #1000: Check for literal datatype/language when comparing literals

---

rio/api/pom.xml
rio/api/src/test/java/org/eclipse/rdf4j/rio/helpers/RioFileTypeDetectorTest.java

- Test that the ServiceLoader knows about RioFileTypeDetector
- Update to point at the current package
Signed-off-by: Joseph Walton <joe@kafsemo.org>

Fixes #978 by updating META-INF/services and including test.

---

compliance/rio/src/test/java/org/eclipse/rdf4j/rio/trig/TriGParserCustomTest.java
compliance/rio/src/test/java/org/eclipse/rdf4j/rio/turtle/CustomTurtleParserTest.java
rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleParser.java
rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleWriter.java

This PR addresses GitHub issue: #1006 .
* Remove trailing dots in prefix as they are not part of the prefix or boolean value
PR #889 stopped printing a space before period, which exposed this parsing issue

Fix #1006: Unread trailing dot from prefix/boolean term

---

util/src/main/java/org/eclipse/rdf4j/common/io/FileUtil.java

This PR addresses GitHub issue: #1009 .
* File#mkdir() is return false on ci.eclipse.org build server
* Use Files#createDirectory, which gives more detailed error messages

Fix #1009: Use Files#createDirectory, which gives more details about failures

---

compliance/queryresultio/src/test/java/org/eclipse/rdf4j/query/resultio/sparqljson/SPARQLJSONTupleTest.java
compliance/queryresultio/src/test/resources/sparqljson/other-keys.srj
queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqljson/AbstractSPARQLJSONParser.java

This PR addresses GitHub issue: #994 .
* Spec allows other json keys in result
* Ignore unknown json keys when parsing

Fix #994: Ignore other json keys in sparql-json

---

util/src/main/java/org/eclipse/rdf4j/common/net/ParsedIRI.java
util/src/test/java/org/eclipse/rdf4j/common/net/ParsedIRITest.java

This PR addresses GitHub issue: #1014  .
* Fixed parsing of IP-address as host
* Added two tests (ip address with and without port)

Fixed parsing IP addr with port

---

rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/BasicParserSettings.java

Removes a javadoc reference to sesame versions that isn't relevant now.

Remove javadoc reference to sesame versions

---

util/src/main/java/org/eclipse/rdf4j/common/net/ParsedIRI.java
util/src/test/java/org/eclipse/rdf4j/common/net/ParsedIRITest.java

Issues/#1017 Fix an issue with ParsedIRI and IRIs with host starting with a digit
Currently in the parseHost() method if the host starts with a digit then we consider that the host
is IPv4 address. However, there are no restrictions on using digits in host names so the parseHost() method
throws exceptions on perfetcly fine host names which start with a digit.
The suggested approach is: deltect a leading digit in the host name -> try to parse as IPv4
If the parsing fails -> parse the host as a regular host name (ireg-name according RFC-3987).
Once the host is parsed check if it is valid (it is considered invalid if its TLD is not made of letters only).
If the host is invalid we consider that indeed IPv4 address was intended and we throw.

#1017 Fix an issue with ParsedIRI and IRIs with host starting with digit

---

pom.xml

This PR addresses GitHub issue: #1035  .
Update jackson to 2.9.5, http client and http core
jackson: 2.8.8 -> 2.9.5
http client: 4.5.2 -> 4.5.5
http core: 4.4.4 -> 4.4.9

#1035: Update jackson to 2.9.5, http client and http core

---

queryrender/src/main/java/org/eclipse/rdf4j/queryrender/BaseTupleExprRenderer.java
queryrender/src/main/java/org/eclipse/rdf4j/queryrender/QueryRenderer.java
queryrender/src/main/java/org/eclipse/rdf4j/queryrender/RenderUtils.java
queryrender/src/main/java/org/eclipse/rdf4j/queryrender/builder/AbstractQueryBuilder.java
queryrender/src/main/java/org/eclipse/rdf4j/queryrender/builder/BasicGroup.java
queryrender/src/main/java/org/eclipse/rdf4j/queryrender/builder/FilterBuilder.java
queryrender/src/main/java/org/eclipse/rdf4j/queryrender/builder/GroupBuilder.java
queryrender/src/main/java/org/eclipse/rdf4j/queryrender/builder/QueryBuilder.java
queryrender/src/main/java/org/eclipse/rdf4j/queryrender/builder/QueryBuilderFactory.java
queryrender/src/main/java/org/eclipse/rdf4j/queryrender/builder/SupportsExpr.java
queryrender/src/main/java/org/eclipse/rdf4j/queryrender/builder/SupportsGroups.java
queryrender/src/main/java/org/eclipse/rdf4j/queryrender/builder/UnionBuilder.java
queryrender/src/main/java/org/eclipse/rdf4j/queryrender/builder/ValueExprFactory.java
queryrender/src/main/java/org/eclipse/rdf4j/queryrender/builder/package-info.java
queryrender/src/main/java/org/eclipse/rdf4j/queryrender/package-info.java
queryrender/src/main/java/org/eclipse/rdf4j/queryrender/serql/SerqlTupleExprRenderer.java
queryrender/src/main/java/org/eclipse/rdf4j/queryrender/serql/SerqlValueExprRenderer.java
queryrender/src/main/java/org/eclipse/rdf4j/queryrender/sparql/ContextCollector.java
queryrender/src/main/java/org/eclipse/rdf4j/queryrender/sparql/SparqlValueExprRenderer.java

This PR addresses GitHub issue: #1029 .
* all classes in `org.eclipse.rdf4j.queryrender.builder` package marked deprecated in favor of new `sparqlbuilder` module.

GH-1029 marked org.eclipse.rdf4j.queryrender.builder classes deprecated

---

compliance/manager/pom.xml
compliance/manager/src/test/java/org/eclipse/rdf4j/repository/manager/LocalRepositoryManagerTest.java
pom.xml
rio/api/pom.xml
rio/api/src/test/java/org/eclipse/rdf4j/rio/helpers/RioFileTypeDetectorTest.java
rio/rdfxml/pom.xml
rio/rdfxml/src/test/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParserTest.java
rio/trix/pom.xml
rio/turtle/pom.xml
rio/turtle/src/test/java/org/eclipse/rdf4j/rio/turtle/TestTurtleParser.java

Java Hamcrest development has [largely stalled](https://github.com/hamcrest/JavaHamcrest/issues/131). Although it's only lightly used in rdf4j's tests, I believe it's worth tracking a currently maintained framework.
This PR switches all use of `org.hamcrest` over to [AssertJ](http://joel-costigliola.github.io/assertj/). As a side benefit, some assertions are substantially more concise.
(Partly addresses #1030.)

Use AssertJ

---

pom.xml

This PR addresses GitHub issue: #1035  
Updates jackson to 2.9.6 to address a security vulnerability in jackson 2.9.5

#1035: Update jackson to 2.9.6

---

client/pom.xml
compliance/pom.xml
http/pom.xml
model/pom.xml
pom.xml
query/pom.xml
queryalgebra-model/pom.xml
queryparser/pom.xml
queryrender/pom.xml
queryresultio/pom.xml
repository/pom.xml
rio/pom.xml
sparqlbuilder/pom.xml
util/pom.xml

This PR addresses GitHub issue: #461 .
* bump jsp and jstl jar versions
* `rdf4j-client-parent` renamed to `rdf4j-parent` 
* fixes to streamline reuse of `rdf4j-parent` as cross-repo project root pom. Saves us having to duplicate dependency versions, plugin configurations etc across repos.

GH-461 servlet jsp version bump and project pom cleanup

---

pom.xml

This PR addresses GitHub issue: #1047 .
* solr compliance tests fail when using commons-io 2.4 
* possibly a last-minute regression due to change in maven dependency resolution (change of root pom setup)
* fix to bump to commons-io 2.5

GH-1047 commons-io 2.5

---

queryalgebra-model/src/main/java/org/eclipse/rdf4j/query/algebra/Filter.java

This PR addresses GitHub issue: #1026 .
* Filter includes binding names from subqueries in the condition
* Fixes testcase eclipse/rdf4j-testsuite#28

GH-1026 filter binding names should include names from subquery 

---

compliance/queryresultio/src/test/resources/sparqljson/other-keys.srj
queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqljson/AbstractSPARQLJSONParser.java

Signed-off-by: Andriy Nikolov <an@metaphacts.com>
This PR addresses GitHub issue: #1051 .
* Objects with non-standard keys in SPARQL JSON results get consumed.
* Extended the test file `other-keys.srj`

Fix #1051: non-standard keys with arrays in JSON SPARQL results

---

rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/AbstractRDFParser.java
rio/turtle/src/test/java/org/eclipse/rdf4j/rio/turtle/TestTurtleParser.java

This PR addresses GitHub issue: #1054 .
* Rio parsers handle unparsable IRIs by passing them to the valuefactory as-is, unless VERIFY_URI_SYNTAX is enabled.

GH-1054 test + fix for unparsable IRI when syntax verify is off

---

repository/manager/src/main/java/org/eclipse/rdf4j/repository/manager/LocalRepositoryManager.java
rio/jsonld/src/test/java/org/eclipse/rdf4j/rio/jsonld/JSONLDHierarchicalWriterTest.java

This PR addresses GitHub issue: #1057 .
* Add `\r` to ignored characters in jsonld test, thus fixing those tests on Windows.
* Use `Files.move` with `REPLACE_EXISTING` to replace the local repository configuration. Failure of this operation cause exception to be thrown. This change might require a consideration as until now failure of this operation was silently ignored.

Fix tests on windows

---

util/src/main/java/org/eclipse/rdf4j/common/net/ParsedIRI.java
util/src/test/java/org/eclipse/rdf4j/common/net/ParsedIRITest.java.orig

This PR addresses GitHub issue: #1066  .
* IRI with ip address followed by no path or port are still valid 
* fix in error reporting to avoid index out of bounds exception

Fix GH-1066 host ip address with no following port or path is still valid

---

rio/ntriples/src/main/java/org/eclipse/rdf4j/rio/ntriples/NTriplesParser.java

This PR addresses GitHub issue: #1069  .
* parsing of subcomponents of triple simply throws an exception when it encounters a problem
* `parseTriple` catches exception and handles it based on parser configuration

GH-1069 fix in handling of (fatal) errors when FAIL option is not set

---

model/src/main/java/org/eclipse/rdf4j/model/vocabulary/VANN.java

Signed-off-by: Pat McBennett <pat.mcbennett@gmail.com>
This PR addresses GitHub issue: #1074 .
* Added the VANN vocab to the collection of vocabularies already defined within RDF4J.

#1074 Adding VANN vocab class (again - see PR number 1075!).

---

compliance/manager/src/test/java/org/eclipse/rdf4j/repository/manager/LocalRepositoryManagerTest.java
repository/manager/src/main/java/org/eclipse/rdf4j/repository/manager/LocalRepositoryManager.java

This PR addresses GitHub issue: #1077 .
* Changed order of updateSystem / move config file in LocalRepositoryManager.addRepositoryConfig
* Added basic unit test

Fixed adding repo when legacy SYSTEM repo still exists + test

---

util/src/main/java/org/eclipse/rdf4j/common/io/FileUtil.java

This PR addresses GitHub issue: eclipse/rdf4j-storage#107 .
* avoid race conditions on temp dir names by synchronizing the method

eclipse/rdf4j-storage#107 handle concurrent access to createTempDir

---

util/src/main/java/org/eclipse/rdf4j/common/io/FileUtil.java

This PR addresses GitHub issue: eclipse/rdf4j-storage#107 .
* reuse core Java `Files.createTempDirectory` method
* deprecate home-grown `FileUtil.createTempDir` as it's just redundant.

GH-107 reuse Files.createTempDirectory, deprecate FilUtil method

---

compliance/rio/src/test/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParserCustomTest.java
queryresultio/sparqlxml/src/main/java/org/eclipse/rdf4j/query/resultio/sparqlxml/AbstractSPARQLXMLParser.java
rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/XMLParserSettings.java
rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/XMLReaderBasedParser.java
rio/rdfxml/src/main/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParser.java
rio/rdfxml/src/test/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParserTest.java
rio/rdfxml/src/test/resources/org/eclipse/rdf4j/rio/rdfxml/rdfxml-external-general-entity.rdf
rio/rdfxml/src/test/resources/org/eclipse/rdf4j/rio/rdfxml/rdfxml-external-param-entity.rdf
rio/trix/pom.xml
rio/trix/src/main/java/org/eclipse/rdf4j/rio/trix/TriXParser.java
rio/trix/src/test/java/org/eclipse/rdf4j/rio/trix/TriXParserTest.java
rio/trix/src/test/resources/org/eclipse/rdf4j/rio/trix/trix-xxe-external-entity.trix
rio/trix/src/test/resources/org/eclipse/rdf4j/rio/trix/trix-xxe-external-param-entity.trix
util/src/main/java/org/eclipse/rdf4j/common/xml/SimpleSAXParser.java

This PR addresses GitHub issue: #1056  .
* RdfXmlParser and TriXParser have a shared superclass that takes care of XML reader config
* doctype declaration disallowed by default, external text/param entities disabled
* SPARQLResultsXMLParser enforces the same settings
* added testcases
PS I consistently used the wrong issue number in my commit message. Some day soon I may get this right, but today's not that day...

Fix #1056 xxe vulnerability

---

pom.xml

This PR addresses GitHub issue: #1175  .
* Remove unused spatial4j 0.6 dependency

Remove obsolete spatial4j

---

util/src/main/java/org/eclipse/rdf4j/common/io/ZipUtil.java
util/src/test/java/org/eclipse/rdf4j/common/io/ZipUtilTest.java

This PR addresses GitHub issue: #1210 .
* Check if zip file entries try to 'escape' / 'break out' of the directory  (i.e. tricks like `../../../etc/`)
* Added test to check if a file 
* Minor code formatting

Verify that zip file entries don't try to escape the parent dir + test

---

pom.xml

This PR addresses GitHub issue: #1214 .
* Upgraded to Mockito 2
* Ignore JDK 9 module-info in pom.xml

Upgrade to latest Mockito 2

---

rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleParser.java
rio/turtle/src/test/java/org/eclipse/rdf4j/rio/turtle/TestTurtleParser.java

This PR addresses GitHub issue: #1205  .
* Check for new line inside object literal
* Added test for new line inside quoted (not allowed) and triple quoted (allowed) literal
* Minor code formatting in tests
(FYI, the `writeLiteral` method in the TurtleWriter checks for CR / NL and uses triple quotes when the literal contains a CR / NL, so writing should already be covered)

Check for CR or NL in single quoted object + test case

---

rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/XMLParserSettings.java
rio/rdfxml/src/test/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParserTest.java
rio/trix/src/test/java/org/eclipse/rdf4j/rio/trix/TriXParserTest.java

This PR addresses GitHub issue: #1202 .
* re-allow doctype declarations in XML parsing by default - a lot of well-known sources of RDF data include a doctype, current default makes these documents unparsable. 
* external entities and DTDs still disallowed/ignored to protected against XXE.

GH-1202 allow doctype declarations by default

---

compliance/pom.xml
compliance/repository/pom.xml
compliance/repository/src/test/java/org/eclipse/rdf4j/repository/http/HTTPMemServer.java
compliance/repository/src/test/java/org/eclipse/rdf4j/repository/http/HTTPRepositoryTest.java
compliance/repository/src/test/java/org/eclipse/rdf4j/repository/http/HTTPRepositoryTransactionTest.java
compliance/repository/src/test/java/org/eclipse/rdf4j/repository/http/HTTPSparqlDatasetTest.java
compliance/repository/src/test/java/org/eclipse/rdf4j/repository/http/HTTPSparqlSetBindingTest.java
compliance/repository/src/test/java/org/eclipse/rdf4j/repository/http/HTTPSparqlUpdateTest.java
compliance/repository/src/test/java/org/eclipse/rdf4j/repository/http/HTTPStoreConnectionTest.java
compliance/repository/src/test/java/org/eclipse/rdf4j/repository/http/HTTPTupleQueryResultTest.java
compliance/repository/src/test/java/org/eclipse/rdf4j/repository/http/RDFSchemaHTTPRepositoryConnectionTest.java
compliance/repository/src/test/java/org/eclipse/rdf4j/repository/sparql/SPARQLGraphQueryResultTest.java
compliance/repository/src/test/java/org/eclipse/rdf4j/repository/sparql/SPARQLRepositorySparqlUpdateTest.java
compliance/repository/src/test/java/org/eclipse/rdf4j/repository/sparql/SPARQLRepositoryTest.java
compliance/repository/src/test/java/org/eclipse/rdf4j/repository/sparql/SPARQLServiceEvaluationTest.java
compliance/repository/src/test/java/org/eclipse/rdf4j/repository/sparql/SPARQLStoreConnectionTest.java
compliance/repository/src/test/resources/log4j.properties
compliance/repository/src/test/resources/logback-test.xml

This PR addresses GitHub issue: #1230 .
* migrated compliance tests for SPARQLRepository and HTTPRepository
* removed reference to obsolete module

migrate httprepository/sparqlrepository compliance tests

---

util/src/main/java/org/eclipse/rdf4j/common/io/ZipUtil.java
util/src/test/java/org/eclipse/rdf4j/common/io/ZipUtilTest.java

This PR addresses GitHub issue: #1210  .
* Backport security fix for zip traversal already merged in develop (2.5.0)

Backport fix for zip traversal from develop

---

rio/api/src/main/java/org/eclipse/rdf4j/rio/RioConfig.java
rio/api/src/main/java/org/eclipse/rdf4j/rio/RioSetting.java
rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/AbstractRioSetting.java
rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/BasicParserSettings.java
rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/BasicWriterSettings.java
rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/BooleanRioSetting.java
rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/JSONLDSettings.java
rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/JSONSettings.java
rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/LongRioSetting.java
rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/NTriplesParserSettings.java
rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/NTriplesWriterSettings.java
rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/RDFJSONParserSettings.java
rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/RDFaParserSettings.java
rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/RioConfigurationException.java
rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/RioSettingImpl.java
rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/StringRioSetting.java
rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/TriXParserSettings.java
rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/TurtleParserSettings.java
rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/XMLParserSettings.java
rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/XMLWriterSettings.java
rio/api/src/test/java/org/eclipse/rdf4j/rio/RioConfigTest.java
rio/api/src/test/java/org/eclipse/rdf4j/rio/helpers/BooleanRioSettingTest.java
rio/api/src/test/java/org/eclipse/rdf4j/rio/helpers/LongRioSettingTest.java
rio/api/src/test/java/org/eclipse/rdf4j/rio/helpers/RioSettingTest.java
rio/api/src/test/java/org/eclipse/rdf4j/rio/helpers/StringRioSettingTest.java
rio/ntriples/src/main/java/org/eclipse/rdf4j/rio/ntriples/NTriplesParser.java
rio/trix/src/main/java/org/eclipse/rdf4j/rio/trix/TriXParser.java

This PR addresses GitHub issue: #1200 .
* added new BooleanRioSetting, StringRioSetting, LongRioSetting that support conversion from string to expected type
* added new abstract impl that adds override by means of system properties (e.g. via a `-D` flag)
* added basic unit tests
Up for discussion: should we clean up the key names for some of these settings? Some use a `org.eclipse.rio.somesetting` convention, others `org.eclipse.rio.some_setting`, and yet others have names like `http://javax.xml.XMLConstants/feature/secure-processing`. As far as I know there's no restrictions on what can be used as a command-line flag, but it's just a bit confusing I think. I am not sure though if changing existing key names for these setting will break …

GH-1200 RioSetting with string, boolean or long values can now be set with system properties

---

rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleParser.java
rio/turtle/src/test/java/org/eclipse/rdf4j/rio/turtle/TurtleParserTest.java

This PR addresses GitHub issue: #1237 .
* if VERIFY_URI_SYNTAX is set but non-fatal, an illegal datatype URI should result in a skipped line, not a fatal error
* distinguish between unparsable datatype IRIs and datatypes that are something else (e.g. literals)
* regression tests added to cover cases (renamed test class for consistency)

GH-1237 invalid datatype IRI only fatal is VERIFY_URI_SYNTAX is enabled and fatal

---

repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/memory-rdfs-dt.ttl
repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/memory-rdfs-legacy.ttl
repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/memory-rdfs-new.ttl
repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/memory-rdfs.ttl
repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/memory-spin-rdfs-lucene.ttl
repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/memory-spin-rdfs.ttl
repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/native-rdfs-dt.ttl
repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/native-rdfs.ttl
repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/native-spin-rdfs-lucene.ttl
repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/native-spin-rdfs.ttl

This PR addresses GitHub issue: #1226 .
* all config templates use the SchemaCachingInferencer as the default RDFS reasoner

Use SchemaCachingInferencer as default in config templates

---

model/src/main/java/org/eclipse/rdf4j/model/vocabulary/RDF4J.java

This PR addresses GitHub issue: #1113 .
* constant vocabulary class RDF4J added as future successor for SESAME vocab.
* added RDF4J.SHACL_SHAPE_GRAPH as constant for the context identifier used in the ShaclSail.
This is trivial enough that I'll do an immediate merge (I need it to get the refactor PR stable) but please do not let that stop you from reviewing and commenting.

GH-1113 added shared constant vocabulary for SHACL shape graph

---

model/src/main/java/org/eclipse/rdf4j/model/vocabulary/LDP.java

This PR addresses GitHub issue: #1285  .
* Deprecate correct term

Deprecate PreferEmptyContainer, not MinimalContainer

---

util/src/main/java/org/eclipse/rdf4j/common/io/NioFile.java

This PR addresses GitHub issue: #1294
The temporary txncache.dat file cannot be deleted on Windows as the file
is still locked while attempting the deletion.
Closing the resource handle properly makes sure that deletion works.

#1294: Fix resource leak in txncache file deletion

---

repository/manager/pom.xml

This PR addresses GitHub issue: #1302.
* temporary workaround for testing circular dependency: test dependencies use a fixed older version of rdf4j. 
* documented necessity to stub out these dependencies in unit tests as per #1263
* documented need to allow injection of a `ModelFactory` for test stubbing/mocking purposes as per #1263.

GH-1263 temporary workaround for test dependency issue

---

rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDHierarchicalProcessor.java
rio/jsonld/src/test/java/org/eclipse/rdf4j/rio/jsonld/JSONLDHierarchicalWriterTest.java
rio/jsonld/src/test/resources/serialized/testOrder.json
rio/jsonld/src/test/resources/serialized/testOrderDuplicatedChild.json
rio/jsonld/src/test/resources/serialized/testRootIsNotTheParentNode.json
rio/jsonld/src/test/resources/serialized/testRootIsNotTheParentNodeInContext.json

This PR addresses GitHub issue: #1283  .
* Adds a filter to the `expanded` list in `JSONLDHierarchicalProcessor` that removes all root nodes that are also children within the hierarchy.
* Adds two tests for ordering in the hierarchy to `JSONLDHierarchicalWriterTest` that ensures children nodes are not duplicated at the root level.
* Updates `testRootIsNotTheParentNode` and `testRootIsNotTheParentNodeInContext` in `JSONLDHierarchicalWriterTest` to remove children nodes from the root level.

Fix eclipse/rdf4j#1283: remove duplicated root nodes jsonld hierarchy

---

sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/core/QueryElementCollection.java

This PR addresses GitHub issue: #1299.
Replace default HashSet with a LinkedHashSet - same set behavior but elements remain in the general order in which the user code adds them. This permits the user code to optimize queries by placing fast patterns before slow patterns.

#1299 - Random order of conditions in where clause prevents query optimization

---

repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/memory-rdfs-lucene.ttl
repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/native-rdfs-lucene.ttl

This PR addresses GitHub issue: #1311  .
* added config templates for native store and memory store with lucene and rdfs entailment

GH-1311 config templates for native/memory + rdfs and lucene

---

eclipse-rdf4j-conventions.xml

This PR addresses GitHub issue: #822 .
* minor modification in code conventions: don't re-join split lines - gives greater developer discretion in formatting.

formatter no longer joins lines back up if deliberately split

---

http/client/pom.xml
http/client/src/main/java/org/eclipse/rdf4j/http/client/SPARQLProtocolSession.java
testsuites/rio/src/main/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParserTestCase.java

This PR addresses GitHub issue: #1236 .
* ensure httpclient includes sparqlxml and binary result formats (necessary for minimal compliance)
* fix sparqlrepo to prefer SPARQL/XML over rdf4j's binary format

GH-1236 include minimally-conforming query result formats for compliance

---

repository/api/src/main/java/org/eclipse/rdf4j/repository/Repository.java
repository/api/src/test/java/org/eclipse/rdf4j/repository/RepositoryTest.java
repository/http/src/main/java/org/eclipse/rdf4j/repository/http/HTTPRepository.java
repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/SPARQLRepository.java

This PR addresses GitHub issue: #1223 .
* Repository API no longer requires user to explicitly call `init()`
* added testcase, and fixes for HTTPRepository and SPARQLRepository
* related fix for SailRepository (and Sail) to follow

GH-1223 init is now optional

---

queryparser/sparql/pom.xml
queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/WildcardProjectionProcessor.java
queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/WildcardProjectionProcessorTest.java

This PR addresses GitHub issue: #1403 .
* WildcardProjectionProcessor skips filter constraints and BIND expressions when collecting variables for projection
* added regression tests

GH-1403 wildcard processor skips binds and filter constraints

---

compliance/rio/src/test/java/org/eclipse/rdf4j/rio/turtle/CustomTurtleParserTest.java
rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/AbstractRDFParser.java

This PR addresses GitHub issue: #1409
Also fixes an issue in AbstractRDFParser.createURI() where non-fatal validation of IRIs didn't return null (this was masked by old code in resolveURI()).

GH-1409: Unnecessary parsing of IRIs every time an RDF parser is used

---

queryalgebra-model/src/main/java/org/eclipse/rdf4j/query/algebra/AbstractQueryModelNode.java
queryalgebra-model/src/main/java/org/eclipse/rdf4j/query/algebra/GraphPatternGroupable.java
queryalgebra-model/src/main/java/org/eclipse/rdf4j/query/algebra/TupleExpr.java
queryalgebra-model/src/main/java/org/eclipse/rdf4j/query/algebra/UnaryTupleOperator.java
queryalgebra-model/src/main/java/org/eclipse/rdf4j/query/algebra/helpers/TupleExprs.java
queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/GraphPattern.java
queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java

This PR addresses GitHub issue: #1405  .
* Introduced `GraphPatternGroupable` behavioral interface
* TupleExprBuilder marks TupleExprs that from a group graph pattern
* EvaluationStrategy bases join evaluation strategy on this.

GH-1405 query planner uses hashjoin when scoped group pattern

---

rio/ntriples/pom.xml
rio/ntriples/src/main/java/org/eclipse/rdf4j/rio/ntriples/NTriplesUtil.java
rio/ntriples/src/main/java/org/eclipse/rdf4j/rio/ntriples/NTriplesWriter.java
rio/ntriples/src/test/java/org/eclipse/rdf4j/rio/ntriples/NTriplesUtilTest.java

This PR addresses GitHub issue: #1317 .
* NTriplesWriter now uses NTriplesUtil for serializing literals
* `escapeUnicode` param now correctly passed down through overloaded methods. 
* added regression tests.

GH-1317 escapeUnicode param passed through correctly

---

query/src/main/java/org/eclipse/rdf4j/query/dawg/DAWGTestResultSetParser.java

This PR addresses GitHub issue: #389  .
* bugfix in the DAWG result processor which caused 144 W3C compliance tests to fail.

GH-389 bug fix in W3C DAWG test parsing

---

queryresultio/text/pom.xml
queryresultio/text/src/test/java/org/eclipse/rdf4j/query/resultio/text/csv/CSVQueryResultsComparisons.java
queryresultio/text/src/test/java/org/eclipse/rdf4j/query/resultio/text/csv/SPARQLCSVTupleBackgroundTest.java
queryresultio/text/src/test/java/org/eclipse/rdf4j/query/resultio/text/csv/SPARQLCSVTupleTest.java

* removed dependency on queryalgebra-evaluation (circular because it lives in a different repo and is built and deployed _after_ these tests are executed)
* created a private util class that copies the relevant parts of QueryEvaluationUtil to properly execute CSV query result comparison in tests.

removed circular dependency

---

compliance/repository/pom.xml
compliance/repository/src/test/java/org/eclipse/rdf4j/repository/http/HTTPMemServer.java

This PR addresses GitHub issue: #1124  .
* bumped version of jetty used by compliance tests to 9.4.
Reason this is necessary is that Rdf4j Server now uses servlet api 3.1, and is no longer compatible with our ancient version of Jetty (which still used servlet api 2.5).

GH-1124 update to jetty 9.4 / servlet api 3.1

---

model/pom.xml
model/src/main/java/org/eclipse/rdf4j/model/util/RDFCollections.java
model/src/test/java/org/eclipse/rdf4j/model/util/RDFCollectionsTest.java

This PR addresses GitHub issue: #1348 .
* overload `asRDF()` and `consumeCollection` to accept optional `ValueFactory`.
* added regression test

allow optional injection of ValueFactory in RDFCollections

---

pom.xml
query/src/main/java/org/eclipse/rdf4j/query/GraphQueryResult.java
query/src/main/java/org/eclipse/rdf4j/query/Operation.java
query/src/main/java/org/eclipse/rdf4j/query/QueryResults.java
util/src/main/java/org/eclipse/rdf4j/common/lang/FileFormat.java
util/src/main/java/org/eclipse/rdf4j/common/lang/service/FileFormatServiceRegistry.java

This PR addresses GitHub issue: #1148 .
* Fixed javadoc issues preventing mvn -Passembly install with jdk11 (errors), adding source parameter as suggested in https://bugs.openjdk.java.net/browse/JDK-8212233
* Fixed unescaped LT/GT:  some jdk9+ javadoc versions seem to be more sensitive/crash-prone an can NPE on things like unescaped &lt;...&gt; (generics, see https://bugs.openjdk.java.net/browse/JDK-8181854), e.g. JDK 11.0.4 on Debian ARMv8

Fixed javadoc errors/NPE in maven profile

---

core/queryparser/api/src/main/java/org/eclipse/rdf4j/query/parser/QueryPrologLexer.java
core/queryparser/api/src/test/java/org/eclipse/rdf4j/query/parser/QueryPrologLexerTest.java

This PR addresses GitHub issue: #1511 .
* Make sure the QueryPrologLexer.getRestOfQueryToken does not throw NPE (e.g. when just entering "PREFIX" in the console, without anything else).
Workaround is to just use an empty string (which should be OK because the method  - with any input - does not guarantee that the returned string is syntactically correct).

Fix for NPE with malformed PREFIX query

---

tools/console/src/main/java/org/eclipse/rdf4j/console/Console.java
tools/console/src/main/java/org/eclipse/rdf4j/console/ConsoleIO.java
tools/console/src/main/java/org/eclipse/rdf4j/console/command/Close.java
tools/console/src/main/java/org/eclipse/rdf4j/console/command/Convert.java
tools/console/src/main/java/org/eclipse/rdf4j/console/command/QueryEvaluator.java
tools/console/src/main/java/org/eclipse/rdf4j/console/command/Serql.java
tools/console/src/main/java/org/eclipse/rdf4j/console/command/Sparql.java
tools/console/src/main/java/org/eclipse/rdf4j/console/command/TupleAndGraphQueryEvaluator.java
tools/console/src/main/java/org/eclipse/rdf4j/console/setting/SaveHistory.java
tools/console/src/test/java/org/eclipse/rdf4j/console/ConsoleIOTest.java
tools/console/src/test/java/org/eclipse/rdf4j/console/command/AbstractCommandTest.java
tools/console/src/test/java/org/eclipse/rdf4j/console/command/SparqlTest.java
tools/console/src/test/java/org/eclipse/rdf4j/console/command/VerifyTest.java
tools/console/src/test/java/org/eclipse/rdf4j/console/setting/AbstractSettingTest.java
tools/console/src/test/java/org/eclipse/rdf4j/console/setting/LogLevelTest.java

This PR addresses GitHub issue: #1517 .
* Added JLine default command history file, to be saved in Console app config directory
* Added setting to enable/disable command history while console is running (e.g. to when entering a command with user credentials or other sensitive info)

Added history feature and settings

---

core/sail/shacl/pom.xml

This PR addresses GitHub issue: #1529  .
* configured surefire plugin set `jmh.ignoreLock` to `true` to avoid benchmark execution failing
* ran local parallel test, seems to solve the issue (but proof is in Jenkins obviously)

JMH runner ignores lock to avoid parallel builds failing

---

testsuites/benchmark/pom.xml

This PR addresses GitHub issue: #1148 .
* Added a jdk9+ profile with jakarta/javax.annotation dependency for benchmark
CQ not required, since the jakarta version of javax is part of Jakarta Eclipse EE 8

Added jakarta dependency javax.annotation

---

pom.xml
tools/pom.xml
tools/runtime/pom.xml

This PR addresses GitHub issue: #1148 .
* Added additional dependencies to unbreak the JDK11 javadoc /  maven plugin

Added dependencies for javadoc plugin

---

core/sparqlbuilder/pom.xml
core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/util/SparqlBuilderUtils.java
core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/rdf/RdfLiteralTest.java
core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/util/SparqlBuilderUtilsTest.java

This PR addresses GitHub issue: #1518 .
* do not pad empty string literals
* added regression tests and basic setup for more unit testing in sparqlbuilder

GH-1518: sparqlbuilder padding of empty string

---

core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/NativeSailStore.java
core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/NativeSailStoreTest.java

This PR addresses GitHub issue: #1548 .
Isn't a problem with invalid/not found, S/P/O, because removeStatements immediately returns when
a search for an S/P/O yields UNKNOWN_ID
But for contexts, zero or more contexts can be given + the UNKNOW_ID (-1) is used when zero contexts are selected, effectively removing statements from all contexts + zero is used for empty context.
* use MIN-INT number for context not in the store
* added a test
Another way to solve this would be using a List  + converting it back to int array, or  use System.arraycopy to return only the array of found contexts, but that seems less clear IMHO.

make invalid context different from unknown/all context + added test

---

.github/PULL_REQUEST_TEMPLATE.md

See https://help.github.com/en/articles/closing-issues-using-keywords. This phrasing will ensure the corresponding issue is automatically closed when the PR is merged.

Fix to allow auto-closing of linked issue

---

core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/ContextStore.java

GitHub issue resolved: #1578  
* Made a distinction between a "context file not found" and another IO error
* Less alarming log entry, at the expense of some minor code duplication in catch block

Produce less alarming log entry when context file does not yet exist

---

core/http/client/src/main/java/org/eclipse/rdf4j/http/client/RDF4JProtocolSession.java
core/http/client/src/main/java/org/eclipse/rdf4j/http/client/SPARQLProtocolSession.java
core/http/client/src/test/java/org/eclipse/rdf4j/http/client/RDF4JProtocolSessionTest.java
core/http/client/src/test/resources/fixtures/repository-config.nt
core/http/protocol/pom.xml
core/http/protocol/src/main/java/org/eclipse/rdf4j/http/protocol/Protocol.java
core/http/protocol/src/main/java/org/eclipse/rdf4j/http/protocol/error/ErrorType.java
core/http/protocol/src/test/java/org/eclipse/rdf4j/http/protocol/ProtocolTest.java
core/repository/manager/src/main/java/org/eclipse/rdf4j/repository/manager/RemoteRepositoryManager.java
core/repository/manager/src/test/java/org/eclipse/rdf4j/repository/manager/RemoteRepositoryManagerTest.java
tools/server-spring/pom.xml
tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/RepositoryController.java
tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/config/ConfigController.java
tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/config/ConfigView.java
tools/server-spring/src/test/java/org/eclipse/rdf4j/http/server/repository/RepositoryControllerTest.java
tools/server-spring/src/test/java/org/eclipse/rdf4j/http/server/repository/config/ConfigControllerTest.java
tools/server-spring/src/test/java/org/eclipse/rdf4j/http/server/repository/config/ConfigViewTest.java
tools/server/src/main/webapp/WEB-INF/rdf4j-http-server-servlet.xml

This PR addresses GitHub issue: #1541 .
* new endpoint for retrieval of repository config
* new endpoint for changing existing repo config
* modified `PUT /repo/<ID>` endpoint to only accept if repository does not yet exist.

new endpoint for repo config retrieval

---

tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXFactory.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/endpoint/EndpointFactory.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/repository/FedXRepositoryConfig.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/repository/FedXRepositoryConfigTest.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/repository/FedXRepositoryFactory.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/util/Vocabulary.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/FedXInRDF4JWorkbenchTest.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/repository/FedXRepositoryConfigTest.java
tools/federation/src/test/resources/tests/dataconfig/endpointfactoryTest.ttl
tools/federation/src/test/resources/tests/dataconfig/resolvableRepositories.ttl
tools/federation/src/test/resources/tests/rdf4jserver/config-withDataConfig.ttl
tools/federation/src/test/resources/tests/rdf4jserver/config.ttl
tools/federation/src/test/resources/tests/rdf4jserver/dataConfig.ttl

GitHub issue resolved: #1585 
As of this change tbe federation members can be specified inline in the
repository config turtle file, i.e. no separate dataConfig.ttl file is
required.

#1585: support inline definition of federation members

---

core/http/client/pom.xml
core/queryresultio/text/pom.xml

GitHub issue resolved: #1617   
* jcl-over-slf4j now a runtime dependency for rdf4j-http-client and queryresultio-text
* explicitly exclude commons-logging from the transitive deps in queryresultio-text

GH-1617 fix commons-logging/jcl-over-slf4j dependencies

---

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/JoinIterator.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/package-info.java
core/queryalgebra/model/pom.xml
core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/UnaryTupleOperator.java
core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/helpers/TupleExprs.java
core/queryalgebra/model/src/test/java/org/eclipse/rdf4j/query/algebra/helpers/TupleExprsTest.java
core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/optimizers/PrepareOwnedTupleExpr.java
testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ComplexSPARQLQueryTest.java

GitHub issue resolved: #1405   
* use merge-join for group patterns to handle scope, with special case
exception for FILTER (NOT) EXISTS

GH-1405 fixed scope handling in join iterator

---

tools/federation/build/test/rdf4j-server/WEB-INF/rdf4j-http-server-servlet.xml
tools/federation/pom.xml
tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXFactory.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/repository/FedXRepositoryFactory.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/repository/FedXRepositoryWrapper.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/FedXWithLocalRepositoryManagerTest.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/server/FedXRepositoryResolverBean.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/server/SPARQLEmbeddedServer.java

GitHub issue resolved: #1621
As of this change the RepositoryResolver (e.g. the reference to the
repository manager) is automatically injected to the FedXRepository, if
FedX is managed from a RepositoryManager.
This is for instance the case when FedX is used in the RDF4J workbench.

#1621: inject RepositoryResolver into FedX repository

---

core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/ContextStore.java

GitHub issue resolved: #1578  
* Produce less alarming log entry when context file does not yet exist
* 
*

GH-1578 backport fix for context store logging to master

---

pom.xml
tools/pom.xml

GitHub issue resolved: #1640  
* Spring version property now part of main pom.xml
* Use version Spring Framework 5.2.1

Moved spring version property to main pom.xml + upgrade to 5.2

---

bom/pom.xml

GitHub issue resolved: #1677   
* rdf4j-runtime is now a pom-type dependency
* removed obsolete rdf4j-store-testsuite dependency
* cleaned up pom organization a bit.

GH-1677 rdf4j-runtime now a pom-type dep, cleaned up BOM a bit

---

core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/Expressions.java
core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/Function.java
core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/constraint/ExpressionsTest.java

Signed-off-by: Roman Kishchenko <rkishchenko@gmail.com>
GitHub issue resolved: #1687

GH-1687 Fix NPE when calling Expressions.bnode().getQueryString()

---

core/sail/lucene-spin/src/main/java/org/eclipse/rdf4j/lucene/spin/LuceneSpinSail.java
core/sail/lucene-spin/src/main/java/org/eclipse/rdf4j/lucene/spin/LuceneSpinSailConnection.java
core/sail/lucene-spin/src/main/java/org/eclipse/rdf4j/lucene/spin/config/package-info.java
core/sail/lucene-spin/src/main/java/org/eclipse/rdf4j/lucene/spin/package-info.java
core/sail/lucene-spin/src/main/java/org/eclipse/rdf4j/sail/lucene/fn/DistanceTupleFunction.java
core/sail/lucene-spin/src/main/java/org/eclipse/rdf4j/sail/lucene/fn/QueryTupleFunction.java

GitHub issue resolved: #1692  
* marked LuceneSpinSail and related classes deprecated. Stated intent to remove in next major release.

GH-1692 mark LuceneSpinSail as deprecated

---

core/model/pom.xml
pom.xml
tools/pom.xml
tools/server-spring/pom.xml

GitHub issue resolved: #1097  
* Use 23.5-jre instead of 18.0

Updated guava dependency

---

.github/workflows/merge_master_to_develop.yml

this job failed for me just now. See https://github.com/eclipse/rdf4j/commit/f8ead84c7f5c93c8518b0e7ff9f221ea77ea4e86/checks?check_suite_id=347622360 
Not sure if this typo was the cause but it looks incorrect to me.

fix typo in source branch of github action

---

core/http/client/src/main/java/org/eclipse/rdf4j/http/client/SharedHttpClientSessionManager.java

GitHub issue resolved: #1718 
It turns out that the default configuration of the HttpClient has a
configuration for cookie parsing which does not follow todays standards,
thus yielding to warnings in the log for certain cookies.
According to the HttpClient documentation users are advised to
explicitly use RFC 6265 compliant policies.
This is done as of this change by adjusting the CookieSpec in the
default HttpClientBuilder used in the RDF4J SPARQLRepository.
Signed-off-by: Andreas Schwarte <aschwarte10@gmail.com>

#1718: fix invalid cookie warnings in HttpClient from SPARQLRepository

---

core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/SailDatasetImpl.java
core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/LimitedSizeNativeStoreConnectionTest.java

GitHub issue resolved: #1665  
* Only get statements from remaining contexts (current one minus deprecated) instead of full array of contexts

Only get statements from remaining (current - deprecated) contexts

---

core/sail/elasticsearch-store/src/main/java/org/eclipse/rdf4j/sail/elasticsearchstore/ElasticsearchStore.java
core/sail/elasticsearch-store/src/main/java/org/eclipse/rdf4j/sail/elasticsearchstore/UserProvidedClientProvider.java
core/sail/elasticsearch-store/src/test/java/org/eclipse/rdf4j/sail/elasticsearchstore/benchmark/AddBenchmark.java
core/sail/elasticsearch-store/src/test/java/org/eclipse/rdf4j/sail/elasticsearchstore/benchmark/DeleteBenchmark.java
core/sail/elasticsearch-store/src/test/java/org/eclipse/rdf4j/sail/elasticsearchstore/benchmark/InitBenchmark.java
core/sail/elasticsearch-store/src/test/java/org/eclipse/rdf4j/sail/elasticsearchstore/benchmark/QueryBenchmark.java
core/sail/elasticsearch-store/src/test/java/org/eclipse/rdf4j/sail/elasticsearchstore/benchmark/ReadCacheBenchmark.java
core/sail/elasticsearch-store/src/test/java/org/eclipse/rdf4j/sail/elasticsearchstore/benchmark/TransactionBenchmark.java
core/sail/elasticsearch-store/src/test/resources/benchmarkFiles/query5.qr
core/sail/elasticsearch-store/src/test/resources/benchmarkFiles/query6.qr
core/sail/elasticsearch-store/src/test/resources/logback.xml
core/sail/extensible-store/pom.xml
core/sail/extensible-store/src/main/java/org/eclipse/rdf4j/sail/extensiblestore/ExtensibleStore.java
core/sail/extensible-store/src/main/java/org/eclipse/rdf4j/sail/extensiblestore/PartialStatement.java
core/sail/extensible-store/src/main/java/org/eclipse/rdf4j/sail/extensiblestore/ReadCache.java
core/sail/extensible-store/src/test/java/org/eclipse/rdf4j/sail/extensiblestoreimpl/ExtensibleStoreConnectionImplForTests.java
core/sail/extensible-store/src/test/java/org/eclipse/rdf4j/sail/extensiblestoreimpl/ExtensibleStoreImplForTests.java
core/sail/extensible-store/src/test/java/org/eclipse/rdf4j/sail/extensiblestoreimpl/NaiveHashSetDataStructure.java
core/sail/extensible-store/src/test/java/org/eclipse/rdf4j/sail/extensiblestoreimpl/TransactionIsolationAndWalTests.java
pom.xml

GitHub issue resolved: #1731  
* a read cache that wraps a DataStructureInterface and provides caching of all read operations and write through for write operations
* automatic cache clearing
* lazy caching (getStatement iterations are still lazy)
* memory sensitive cache that will be garbage collected if the JVM runs low on memory

ExtensibleStore read cache

---

core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/SearchQueryEvaluator.java

GitHub issue resolved: #1667 
A simple change to the JavaDoc of SearchQueryEvaluator#replaceQueryPatternsWithResults to improve its clarity (following the [suggestion](https://groups.google.com/d/msg/rdf4j-users/S8knUuL_Fsw/--_ypZmnBAAJ) by @barthanssens on the mailing list).

Fix typo in the JavaDoc of SearchQueryEvaluator#replaceQueryPatternsWithResults

---

pom.xml

GitHub issue resolved: #1526  
* Generate HTML5 when using JDK9 or newer

Generate html5 javadoc when using JDK9 or newer

---

core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/SPARQLRepository.java

GitHub issue resolved: 
* Fix typo `SPARQLREpository` in javadoc

Fix typo "SPARQLREpository" in javadoc

---

core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/FileIO.java

GitHub issue resolved: #1790  
* Use Files methods to bypass finalize issue with FileInputStream/FileOutputStream

Use Files static method to bypass finalize issue with FileInputStream

---

core/http/protocol/src/main/java/org/eclipse/rdf4j/http/protocol/transaction/TransactionWriter.java

GitHub issue resolved: #1805  
* Use StandardCharsets constant instead of string value
* Minor javadoc changes

Use StandardCharsets.UTF_8

---

core/query/src/main/java/org/eclipse/rdf4j/query/QueryResult.java
core/repository/api/src/main/java/org/eclipse/rdf4j/repository/RepositoryConnection.java
core/repository/api/src/main/java/org/eclipse/rdf4j/repository/RepositoryResult.java
testsuites/repository/src/main/java/org/eclipse/rdf4j/repository/RepositoryConnectionTest.java

GitHub issue resolved: #1747   
* RepositoryResult and QueryResult extend java.lang.Iterable
* added method overloads to avoid ambiguous calls in RepositoryConnection

#1747 repositoryresult and queryresult iterable

---

compliance/repository/pom.xml
compliance/repository/src/test/java/org/eclipse/rdf4j/repository/sparql/federation/RepositoryFederatedServiceIntegrationTest.java
core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/federation/RepositoryFederatedService.java
core/repository/sparql/src/test/java/org/eclipse/rdf4j/repository/sparql/federation/RepositoryFederatedServiceTest.java

GitHub issue resolved: #1802 
This change adjusts the optimized evaluation of SERVICE queries using
the VALUES clause.
In order to address performance and correctness issues, the VALUES
clause is now inserted in the beginning of the WHERE block (instead of
appending it to the generated query).
This change also does some cleanup to the RepositoryFederatedService
implementation (e.g. replacing deprecated code)
Change is covered by numerous integration unit tests
See #1802 for full details

GH-1802 Fix vectored evaluation using VALUES in RepositoryFederatedService

---

tools/federation/pom.xml
tools/federation/src/main/java/org/eclipse/rdf4j/federated/repository/FedXRepositoryConfigBuilder.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/FedXWithLocalRepositoryManagerTest.java
tools/server/pom.xml
tools/workbench/pom.xml
tools/workbench/src/main/java/org/eclipse/rdf4j/workbench/commands/CreateServlet.java
tools/workbench/src/main/webapp/transformations/create-federate.xsl
tools/workbench/src/main/webapp/transformations/create.xsl

GitHub issue resolved: #1787
This change integrates the 'rdf4j-tools-federation' module into
'rdf4j-server.war' and thus makes it available in the RDF4J workbench.
For convenience we reuse the existing UI facilities to create a
federation: instead of creating a federation sail, we now create a FedX
based Federation repository.
Note that dependencies on rdfj4-tools-federated have been explicitly
added to rdf4j-server and rdf4j-workbench. Ideally the dependency could
be added to rdf4j-storage, however this currently has cyclic dependency
issues.
Signed-off-by: Andreas Schwarte <aschwarte10@gmail.com>

GH-1787: integrate FedX federation support into the RDF4J workbench

---

core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/federation/RepositoryFederatedService.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXConfig.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/FederationEvalStrategy.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/concurrent/ParallelServiceExecutor.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/join/ParallelServiceJoinTask.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/ServiceTests.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/evaluation/FederationEvalStrategyTest.java

GitHub issue resolved: #1816  
This change improves and fixes the evaluation of (external) SERVICE
clauses in FedX.
Before this change there have been issues with blocking behavior and and
hanging queries, when SERVICE queries were evaluated as bound joins. As
this was not the default, it was not yet discovered. The reason was that
HTTP slots in the background tuple results were not processed in a
suitable order.
As of this change we slightly adopted the evaluation logics: now we
basically consume the background tuple result and keep it in memory for
upcoming operators, thus process it in order.
Also the Bound Join evaluation is now activated by default.
Moreover, a slight follow up of #1802 is added: the boundJoinBlockSize
is no longer hard-coded in the RepositoryFederatedService, but …

GH-1816: improve (external) SERVICE evaluation in FedX engine

---

compliance/pom.xml

GitHub issue resolved: #1831  
* tweaked nexus-staging plugin to skip deployment for compliance modules
* removed obsolete reference to old maven-deploy-plugin (which we don't use as the nexus plugin replaces it)

GH-1831 configure nexus staging plugin to skip deployment for compliance modules

---

tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXConfig.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXConnection.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/QueryManager.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/CheckStatementPattern.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/ExclusiveStatement.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/StatementSourcePattern.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/cache/CacheUtils.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/FederationEvalStrategy.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/SailFederationEvalStrategy.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/SailTripleSource.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/SparqlFederationEvalStrategy.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/SparqlTripleSource.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/TripleSource.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/TripleSourceBase.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/union/ParallelGetStatementsTask.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/union/ParallelPreparedAlgebraUnionTask.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/union/ParallelPreparedUnionTask.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/union/ParallelUnionTask.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/optimizer/SourceSelection.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/repository/FedXRepositoryConnection.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/structures/QueryInfo.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/FedXWithInferenceTest.java

GitHub issue resolved: #1814 
As of this change it is possible to configure inference on federation
queries using Query#setIncludeInferred. By default the value is set to
'true', similar to the SailQuery.
The corresponding value is now passed to the TripleSource and is thus
considered for all sub-queries sent to the relevant endpoints.
Functionality for the query types is validated in a unit test.

GH-1814: support to configure inference on federation queries

---

compliance/repository/src/test/java/org/eclipse/rdf4j/repository/sparql/federation/RepositoryFederatedServiceIntegrationTest.java
core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/federation/RepositoryFederatedService.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/FedXWithLocalRepositoryManagerTest.java

GitHub issue resolved: #1820 
This change introduces a mode in RepositoryFederatedService which allows
to always use a fresh RepositoryConnection for the actual query
invocation. In order to properly close the connection, the result
iteration is wrapped in a "CloseConnectionIteration"
The new mode is active by default, i.e. as of this change a fresh
connection is used for each SERVICE invocation.
For the re-use of the managed connection we now made sure to support
synchronized access, i.e. avoid to loose the references to created
connections.
The unit tests show that connections are properly closed. If it wasn't
the case, we would observe hanging tests for > 30s (i.e. until the
automatic timeout occurs)

GH-1820: fix connection handling in RepositoryFederatedService

---

testsuites/benchmark/pom.xml

Jakarata annotations has been problematic for a few weeks now, essentially problems downloading it from the repo. Switching to the good old javax implementation.

Jakarata annotations fix

---

compliance/repository/src/test/java/org/eclipse/rdf4j/repository/http/HTTPRepositoryOptimisticIsolationTest.java
core/http/client/src/main/java/org/eclipse/rdf4j/http/client/RDF4JProtocolSession.java
testsuites/repository/src/main/java/org/eclipse/rdf4j/repository/OptimisticIsolationTest.java
testsuites/repository/src/main/java/org/eclipse/rdf4j/repository/optimistic/DeleteInsertTest.java
testsuites/repository/src/main/java/org/eclipse/rdf4j/repository/optimistic/IsolationLevelTest.java
testsuites/repository/src/main/java/org/eclipse/rdf4j/repository/optimistic/LinearTest.java
testsuites/repository/src/main/java/org/eclipse/rdf4j/repository/optimistic/RemoveIsolationTest.java
testsuites/repository/src/main/java/org/eclipse/rdf4j/repository/optimistic/SerializableTest.java
tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/Transaction.java

GitHub issue resolved: #1844 and #1847  
- re-enable previously disabled tests in the suite
- add compliance test for the HTTPRepository
- fixes issue #1847: a bug in transactional handling of SPARQL updates over the REST API.

GH-1844 GH-1847 optimistic repository isolation tests and bugfix

---

tools/pom.xml
tools/server-spring/pom.xml

* added guava dep version to dependencyManagement section in tools pom
Btw reason I did this is that I suddenly started getting errors on commandline maven builds.

guava dependency declared in tools pom

---

core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/TxnStatusFile.java
core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/NativeStoreTxnTest.java
core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/benchmark/QueryBenchmark.java
core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/benchmark/TransactionsPerSecondBenchmark.java

GitHub issue resolved: #1108  
* use single bytes for transaction status for higher TPS
* 
*

#1108 transaction status now uses single byte for higher TPS

---

tools/federation/src/main/java/org/eclipse/rdf4j/federated/optimizer/JoinOrderOptimizer.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/BasicTests.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/BindTests.java
tools/federation/src/test/resources/tests/basic/query_bind.rq
tools/federation/src/test/resources/tests/basic/query_bind.srx
tools/federation/src/test/resources/tests/data/data1.ttl

GitHub issue resolved: #1856  
BIND clauses (i.e. Extensions) were not yet supported in the join order
optimizer (particularly in the cost model). In this change we add a
simple heuristic to support BIND clauses.
Evaluation is validated in a few selected unit tests.

GH-1856: support BIND clauses in FedX federation

---

core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/federation/RepositoryFederatedService.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/ServiceTests.java
tools/federation/src/test/resources/tests/service/query11_error_a.rq
tools/federation/src/test/resources/tests/service/query11_error_b.rq

GitHub issue resolved: #1820 
This change makes sure to always fresh connections in any kind of
RuntimeExceptions. Before we missed the case where the service
repository could have thrown a QueryEvaluationException.
Also we add some unit test in the federation repository which partially
cover this issue.

GH-1820: fix RepositoryFederatedService to always close connection

---

tools/federation/src/main/java/org/eclipse/rdf4j/federated/write/ReadOnlyWriteStrategy.java
tools/federation/src/test/java/demos/GettingStartedDemoMinimal.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/BasicTests.java

GitHub issue resolved: #1852 
This change adjusts the implementations of #begin(), #commit() and
#rollback() to not throw an Exception, but rather do nothing.
Thus we now can use the Repositories#tupleQuery convenience function

GH-1852: support Repositories#tupleQuery in FedX repository

---

pom.xml

As documented in https://wiki.eclipse.org/Jenkins#How_can_artifacts_be_deployed_to_OSSRH_.2F_Maven_Central.3F
I'm focusing on getting the new Jenkins environment in working order for running deployments. I'm vaguely hoping that the new infrastructure will help with the many failures in deployment as well.
I'll run some test deployments from this branch, for which I will (temporarily) disable the autorelease feature of the staging plugin.

tweak gpg sign plugin for running on new Jenkins CI

---

compliance/repository/pom.xml
compliance/repository/src/test/java/org/eclipse/rdf4j/repository/manager/LocalRepositoryManagerIntegrationTest.java
compliance/repository/src/test/java/org/eclipse/rdf4j/repository/manager/RepositoryManagerIntegrationTest.java
core/repository/manager/pom.xml
core/repository/manager/src/test/java/org/eclipse/rdf4j/repository/manager/LocalRepositoryManagerTest.java

Distinguish between compliance/integration tests, and unit tests.
GitHub issue resolved: #1871  
* removed fixed test dependencies from repositorymanager unit tests
* moved tests that require a functioning sail to the repository-compliance module

GH-1871 moved most tests to compliance module

---

core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/SPARQLConnection.java
core/repository/sparql/src/test/java/org/eclipse/rdf4j/repository/sparql/SPARQLConnectionTest.java

GitHub issue resolved: #1867  
* SPARQLConnection passes its parser config on to client so it can be used for tweaking strictness of result processing.
* added simple unit test

GH-1867 pass parserconfig to protocol session

---

tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/NJoin.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/NTuple.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/FederationEvalStrategy.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/join/HashJoin.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/optimizer/DefaultFedXCostModel.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/optimizer/FedXCostModel.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/optimizer/StatementGroupAndJoinOptimizer.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/FedXBaseTest.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/optimizer/JoinOptimizerTest.java
tools/federation/src/test/resources/tests/optimizer/queryPlan_Join_1.txt
tools/federation/src/test/resources/tests/optimizer/queryPlan_Join_2.txt

GitHub issue resolved: #1876 
Before we first release FedX I would like to use the chance to do refactoring and cleanup of code, which will help fus for future maintenance.
**The main goal of this refactoring is to**
a) have a clean definition of the cost model
b) have the grouping and optimizing done in an optimizer and avoid
static method invocations
c) provide extension points for the federation evaluation strategy to
customize the cost model
**Performed Changes:**
* StatementGroupOptimizer has been renamed to
StatementGroupAndJoinOptimizer as it was taking care for grouping and
optimizing the join order
* The large methods in the StatementGroupAndJoinOptimizer are split up
into smaller parts
* the JoinOrderOptimizer has been removed: all cost estimation functions
have been moved …

GH-1876: refactor join order optimizer and federation cost model

---

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/PathIteration.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/optimizer/DefaultFedXCostModel.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/optimizer/StatementGroupAndJoinOptimizer.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/PropertyPathTests.java
tools/federation/src/test/resources/tests/propertypath/data1.ttl
tools/federation/src/test/resources/tests/propertypath/data2.ttl

GitHub issue resolved: #1882
This change adds basic support for property paths in the federation
engine.
Example patterns:
* `?subClass rdfs:subClassOf/rdfs:label ?label`
* `?class rdfs:subClassOf+ ?class`
* `?concept rdfs:label|skos:altLabel ?label`
Note that some adjustments to queryalgebra PathIteration were required:
* as in FedX we generate SPARQL query strings, variables must not
contain the "-" character (which is invalid for SPARQL queries). This
character is replaced with _
* in the FedX engine we are not seeing "QueryBindingSet" instances, but
"MapBindingSet" instances. The addBinding method is made robust to
support both instance types
* in remote settings we even see ListBindingSet. In the check we make
sure to convert the BindingSet instance if required
Note also that the …

GH-1882: basic support for property path in FedX engine

---

core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/ArrangedWriter.java
core/rio/turtle/src/test/java/org/eclipse/rdf4j/rio/turtle/ArrangedWriterTest.java

GitHub issue resolved: #1883
This change amends the pretty-printer of the TurtleWriter to take the namespaces of subjects of statements into account.

GH-1883 unhandled namespaces of statement subjects for TurtleWriter

---

tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/ExclusiveArbitraryLengthPath.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/ExclusiveGroup.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/ExclusiveStatement.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/ExclusiveTupleExpr.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/ExclusiveTupleExprRenderer.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/FederationEvalStrategy.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/SparqlTripleSource.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/TripleSource.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/TripleSourceBase.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/optimizer/DefaultFedXCostModel.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/optimizer/ExclusiveTupleExprOptimizer.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/optimizer/StatementGroupAndJoinOptimizer.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/util/QueryAlgebraUtil.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/util/QueryStringUtil.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/PropertyPathTests.java
tools/federation/src/test/resources/tests/propertypath/data1.ttl
tools/federation/src/test/resources/tests/propertypath/data2.ttl
tools/federation/src/test/resources/tests/propertypath/query_path_exclusiveGroup.qp
tools/federation/src/test/resources/tests/propertypath/query_path_exclusivePath.qp

This change provides an optimization for property path expressions that
yield results at a single endpoint. Similarly to the concept of
ExclusiveStatement we now use a marker for them.
We introduce the interface ExclusiveTuplExpr which can now be used to
declare any exclusive TupleExpr. Note that the existing
ExclusiveStatement and ExclusiveGroup nodes have also become instances
of ExclusiveTupleExpr.
For rendering such nodes in sub-queries the ExclusiveTupleExprRenderer
interface is defined. Additionally, some rendering logic is introduced
in the Query utility classes.
Note that ExclusiveGroups are now generalized such that they can contain
any ExclusiveTupleExpr (and not only ExclusiveStatements).
Notes:
* the if/else branches in StatementGroupAndJoinOptimizer were shuffled
around such …

GH-1882: optimization for property paths with an exclusive endpoint

---

tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/NJoin.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/join/HashJoin.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/optimizer/DefaultFedXCostModel.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/optimizer/StatementGroupAndJoinOptimizer.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/util/QueryAlgebraUtil.java

GitHub issue resolved: #1538
This change moves the general method that inspects TupleExpr for free
variables to QueryAlgebraUtils. Background is to have it in a more
convenient place.
In addition the computation of free variables for LeftJoin is improved.

GH-1538: Move getFreeVars method to QueryAlgebraUtil

---

tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/FedXTupleExpr.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/StatementTupleExpr.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/VariableExpr.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/optimizer/DefaultFedXCostModel.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/util/QueryAlgebraUtil.java

This change restructures the FedX algebra interface hierarchy to share
common methods of all nodes.
The most top-level interface for any FedX specific algebra node is now a
FedXTupleExpr.
In addition, we have the new interface VariableExpr which can be used to
determine the free variables (e.g. during cost estimation).
Note that the logging severity for unknown nodes is reduced to DEBUG as
the fallback values are sufficient for most cases.

ID-1538: restructure the FedX algebra interface hierarchy

---

tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/concurrent/ControlledWorkerScheduler.java

GitHub issue resolved: #1904 
In FedX we use configurable threadpools for executing join and union sub
queries, as well as other remote requests. Also the pool size is meant
to be configurable via FedXConfig setters.
However, due to a bug in the construction of the ThreadPoolExecutor the
size is always set to a most 10 threads. This is because we have an
unbound queue and set the minimumCoreSize to 10. In such setting new
threads are only created if the core size of the pool is not reached.
We now explicitly set the core pool size to the configured number of
workers, and in addition configure the pool in such a way that idle
threads can get destroyed. The idle timeout is set to 60s.

GH-1904: fix ThredPool initialization in FedX

---

tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXFactory.java

At construction time of the FedX factory we actually do not require the
existence of the base directory.
Actually the base directory is only required to exist in rare federation
setups (e.g. with a managed NativeStore). This is because FedX currently
does not persist files to disk. Note that this was recently changed by
switching to an in-memory cache.
To make the federation factory work with different implementations of a
RepositoryManager and to not require the existence of potentially empty
directories we no longer throw an Exception.
GitHub issue resolved: #1538

GH-1538: do not require existence of base directory at FedX construction

---

core/http/protocol/src/main/java/org/eclipse/rdf4j/http/protocol/Protocol.java
core/http/protocol/src/test/java/org/eclipse/rdf4j/http/protocol/ProtocolTest.java
core/rio/binary/src/main/java/org/eclipse/rdf4j/rio/binary/BinaryRDFConstants.java
core/rio/binary/src/main/java/org/eclipse/rdf4j/rio/binary/BinaryRDFParser.java
core/rio/binary/src/main/java/org/eclipse/rdf4j/rio/binary/BinaryRDFWriter.java
core/rio/binary/src/test/java/org/eclipse/rdf4j/rio/binary/BinaryRDFWriterBackgroundTest.java
core/rio/binary/src/test/java/org/eclipse/rdf4j/rio/binary/BinaryRDFWriterTest.java
core/rio/ntriples/src/main/java/org/eclipse/rdf4j/rio/ntriples/NTriplesUtil.java
core/rio/ntriples/src/test/java/org/eclipse/rdf4j/rio/ntriples/NTriplesUtilTest.java

Adds support for RDF* to the HTTP protocol (e.g. passing triples to subj, pred, obj parameters on /statements GET). This also changes how an old workaround for SES-2129 is handled.
Adds support for RDF* to the binary RDF result format. The version stays the same and triples are handled as a new value type. This should offer the most compatibility for users who mix client and server versions.

Protocol and binary RDF result for RDF*

---

compliance/model/pom.xml
compliance/model/src/test/java/org/eclipse/rdf4j/model/SimpleUpgradeableModelTest.java
compliance/model/src/test/java/org/eclipse/rdf4j/model/util/IsomorphicBenchmark.java
compliance/model/src/test/java/org/eclipse/rdf4j/model/util/IsomorphicTest.java
compliance/model/src/test/java/org/eclipse/rdf4j/model/util/Main.java
compliance/repository/src/test/java/org/eclipse/rdf4j/repository/sparql/federation/RepositoryFederatedServiceIntegrationTest.java
core/model/src/main/java/org/eclipse/rdf4j/model/impl/LinkedHashModelFactory.java
core/model/src/main/java/org/eclipse/rdf4j/model/impl/SimpleUpgradeableModel.java
core/model/src/main/java/org/eclipse/rdf4j/model/impl/SimpleUpgradeableModelFactory.java
core/model/src/test/java/org/eclipse/rdf4j/model/ModelCollectionTest.java
core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLParseBenchmark.java
core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/Changeset.java
core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/SimpleUpgradeableModel.java
core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/MemorySailStore.java

GitHub issue resolved: #1929  
* Use SimpleUpgradeableModel in Changeset which will upgrade from a HashSet to a Model if it encounters queries that it can't answer.
* Adding 1000 statements in SNAPSHOT takes ~6 ms instead of ~9ms

#1929 introduce a SimpleUpgradeableModel

---

tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/ExclusiveGroup.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/FedXStatementPattern.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/FilterTuple.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/SparqlFederationEvalStrategy.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/optimizer/FilterOptimizer.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/FilterTests.java

The previous implementation did not correctly handle the optimization of
filter expressions in presence of ExclusiveGroups: if it was attempted,
an UnsupportedOperationException was thrown.
Now the appropriate methods are handled in the ExclusiveGroup and
filters as well as bound bindings are properly handled
GitHub issue resolved: #1944

GH-1944: fix filter evaluation for exclusive groups in FedX

---

tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXConnection.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/FederationEvalStrategy.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/repository/FedXRepositoryConnection.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/write/WriteTest.java

* do not throw UnsupportedOperationException for internal namespace
handling methods
* pass information on the original update string to the engine
* UPDATE queries are always handled inside the federation engine to
adhere to the configured write strategy
* cover this by unit tests
GitHub issue resolved: #1949

GH-1949: fix INSERT DATA query handling for writable FedX federation

---

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/SilentIteration.java
core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/federation/RepositoryFederatedService.java
core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/federation/SilentIteration.java
core/util/src/main/java/org/eclipse/rdf4j/common/iteration/SilentIteration.java
core/util/src/test/java/org/eclipse/rdf4j/common/iteration/SilentIterationTest.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/ServiceTests.java

The SilenetIteration failed to close the inner iteration, thus resulting
in resource leaks (e.g. pending connections).
Without this fix the attached unit tests takes 20s before forcefully
closing the connection. Now it correctly terminates immediately after
test execution.
Note that additionally a TRACE logger has been introduced to give users
the chance to observe errors.
GitHub issue resolved: #1958

GH-1958: fix resource closing in federated service SilentIteration

---

core/rio/hdt/pom.xml
core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTParser.java
core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTPart.java
core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTTriplesSectionBitmap.java
core/rio/hdt/src/test/java/org/eclipse/rdf4j/rio/hdt/HDTParserTest.java

GitHub issue resolved: #1963  
* Improved test
* Fix issues with language and datatypes not being decoded
* Fix incorrect generation of incorrect triples

GH-1963-rio-hdt-lang-fix

---

core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTArrayLog64.java
core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTDictionarySection.java
core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTDictionarySectionFactory.java
core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTDictionarySectionPFC.java
core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTParser.java
core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTPart.java
core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/VByte.java
core/rio/hdt/src/test/java/org/eclipse/rdf4j/rio/hdt/HDTParserTest.java

GitHub issue resolved: #1962  
* Removed bufferedinputstream (so buffering happens outside, like other parsers)
* Added a caching mechanism for PFC: first store the PFC-encoded dictionaries into memory, and only start decoding them after the inputstream is fully processed. Then the decoding happens one block at the time, when a string in that block is requested (with a cached of the 100 most recently accessed blocks)
* Fixed another datetype parsing issue
* Fixed issue for logarray64 incorrectly decoding large(r) values across 5 bytes: add 'L' for long mask instead of int
* Some minor improvements for debugging

GH-1962-hdt-improvements

---

core/http/client/src/main/java/org/eclipse/rdf4j/http/client/SPARQLProtocolSession.java

The SparqlProtocolSession uses this.getClass() as a name for the logger.
When having an extension of the class, this leads to misleading log
output. Particularly the logging levels are also harder to control
(w.r.t namespacing and packaging).
The general recommendation for logger names should be to use the class
name, at least it should adhere to the rdf4j package structure.
GitHub issue resolved: #1970

GH-1970: fix logger name in SPARQLProtocolSession

---

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/AST/TargetNode.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/AbstractShaclTest.java
core/sail/shacl/src/test/resources/test-cases/datatype/targetNodeLang/shacl.ttl
core/sail/shacl/src/test/resources/test-cases/datatype/targetNodeLang/valid/case1/query1.rq

GitHub issue resolved: #1968   
* generate sparql query correctly when target is a literal with language
* 
*

#1968 support language in shacl target node, eg. "string"@en

---

tools/federation/src/main/java/org/eclipse/rdf4j/federated/repository/FedXRepository.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/FedXInRDF4JWorkbenchTest.java

Due to a wrong initialization order in an environment where the
federation is initialized through a RepositoryManager, references to the
evaluation strategy instance are not available in the Endpoint.
This in turn caused an NPE in the filter evaluation.
This change fixes the issue by first initializing the manager, and only
after that the federation members.
GitHub issue resolved: #1990

GH-1990: fix FedX initialization order for RepositoryManager environment

---

compliance/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/manifest/SPARQL12QueryTest.java
compliance/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/manifest/W3CApprovedSPARQL11UpdateTest.java
compliance/sparql/src/test/java/org/eclipse/rdf4j/sail/federation/FederationSPARQL11QueryTest.java
compliance/sparql/src/test/java/org/eclipse/rdf4j/sail/nativerdf/NativeSPARQLQueryTest.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/GroupIterator.java
core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/GroupIteratorTest.java
testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ComplexSPARQLQueryTest.java
testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/manifest/SPARQL11ManifestTest.java
testsuites/sparql/src/main/resources/testcases-sparql-1.1-w3c/aggregates/manifest.ttl
testsuites/sparql/src/main/resources/testcases-sparql-1.2/aggregates/agg-empty-group-1.rq
testsuites/sparql/src/main/resources/testcases-sparql-1.2/aggregates/agg-empty-group-1.srx
testsuites/sparql/src/main/resources/testcases-sparql-1.2/aggregates/agg-empty-group-2.rq
testsuites/sparql/src/main/resources/testcases-sparql-1.2/aggregates/agg-empty-group-2.srx
testsuites/sparql/src/main/resources/testcases-sparql-1.2/aggregates/empty.ttl
testsuites/sparql/src/main/resources/testcases-sparql-1.2/aggregates/manifest.ttl
testsuites/sparql/src/main/resources/testcases-sparql-1.2/manifest-all.ttl

- modified behavior of groupIterator based on whether it's an explicit grouping or not
- modified and extended unit tests
- disabled incorrect W3C conformance test per discussion on GH-1978
GitHub issue resolved: #1978

GH-1978 fix handling of empty results in grouping/aggregate

---

release.sh

- push release branch to avoid direct commits on master
- use hub command to create PR for release branch to master
- use hub command to create PR for updating develop branch
GitHub issue resolved: #1995

GH-1995 push release branch and automate PR creation

---

core/rio/turtle/src/test/java/org/eclipse/rdf4j/rio/turtle/ArrangedWriterTest.java

GitHub issue resolved: #1986  
* (backport) use line separator when comparing output

GH-1986 use line separator

---

testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/manifest/SPARQLQueryTest.java
testsuites/sparql/src/main/resources/testcases-sparql-1.2/aggregates/agg-empty-group-count-01.rq
testsuites/sparql/src/main/resources/testcases-sparql-1.2/aggregates/agg-empty-group-count-01.srj
testsuites/sparql/src/main/resources/testcases-sparql-1.2/aggregates/agg-empty-group-count-02.rq
testsuites/sparql/src/main/resources/testcases-sparql-1.2/aggregates/agg-empty-group-count-02.srj
testsuites/sparql/src/main/resources/testcases-sparql-1.2/aggregates/manifest.ttl

- this adds two additional test cases to the SPARQL 1.2 aggregate testsuite. 
- took the opportunity to slightly update the testsuite code, it was
still using SeRQL and ignore tests involving SPARQL/JSON results
GitHub issue resolved: #1978

GH-1978 additional test cases from the SPARQL WG

---

core/http/client/src/main/java/org/eclipse/rdf4j/http/client/SPARQLProtocolSession.java
core/queryresultio/api/src/main/java/org/eclipse/rdf4j/query/resultio/AbstractQueryResultWriter.java
core/queryresultio/api/src/main/java/org/eclipse/rdf4j/query/resultio/QueryResultWriter.java
core/queryresultio/binary/src/main/java/org/eclipse/rdf4j/query/resultio/binary/BinaryQueryResultWriter.java
core/queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqljson/AbstractSPARQLJSONWriter.java
core/queryresultio/sparqlxml/src/main/java/org/eclipse/rdf4j/query/resultio/sparqlxml/AbstractSPARQLXMLWriter.java
core/queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/text/csv/SPARQLResultsCSVWriter.java
core/queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/text/tsv/SPARQLResultsTSVWriter.java
core/rio/api/src/main/java/org/eclipse/rdf4j/rio/RDFWriter.java
core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/AbstractRDFWriter.java
core/rio/binary/src/main/java/org/eclipse/rdf4j/rio/binary/BinaryRDFWriter.java
core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDWriter.java
core/rio/n3/src/main/java/org/eclipse/rdf4j/rio/n3/N3Writer.java
core/rio/ntriples/src/main/java/org/eclipse/rdf4j/rio/ntriples/NTriplesWriter.java
core/rio/rdfjson/src/main/java/org/eclipse/rdf4j/rio/rdfjson/RDFJSONWriter.java
core/rio/rdfxml/src/main/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLWriter.java
core/rio/trix/src/main/java/org/eclipse/rdf4j/rio/trix/TriXWriter.java
core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/ArrangedWriter.java
core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleWriter.java
tools/console/src/main/java/org/eclipse/rdf4j/console/util/ConsoleRDFWriter.java

GitHub issue resolved: #400  
* Allow ProtocolSession to bypass handler and stream response data directly to Outputstream if applicable
* added getOutputStream method to make wrapped outputstream accessible to protocol session.

GH-400 passthrough result

---

core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ast/ASTServiceGraphPattern.java
core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/TestServiceUpdateExprBuilder.java

Fixes GH-2013 by traversing parents until sourceString is found
GitHub issue resolved: #2013  
* added a simplified test case reproducing the issue
* fix in `ASTServiceGraphPattern` that traverse the node parents untl a `sourceString` is found

Fixes GH-2013 by traversing parents until sourceString is found

---

compliance/model/pom.xml

GitHub issue resolved: #2031  
* remove test dependency that pulls in a fixed version of the RDF4J sail
* no further changes are necessary as nothing actually uses this dependency

GH-2031 remove test dependency

---

core/model/src/main/java/org/eclipse/rdf4j/model/Model.java
testsuites/model/pom.xml
testsuites/model/src/main/java/org/eclipse/rdf4j/model/AbstractModelTest.java

- allows optimized retrieval of statements in model implementations
- default implementation just reuses filter internally
- added some basic regression tests
GitHub issue resolved: #2030

GH-2030 add getStatements method to Model

---

tools/runtime-osgi/pom.xml

GitHub issue resolved: #2043 
Changed BND instructions to also make following imports optional:
* org.locationtech
* org.elasticsearch
* ch.qos.logback

GH-2043 make more imports optional of runtime-osgi

---

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryJoinOptimizer.java

GitHub issue resolved: #2048  
* code was commented out ever since it was written, so assume we can safely remove it now
* 
*

GH-2048 remove code that has been commented out

---

core/model/src/main/java/org/eclipse/rdf4j/model/impl/SimpleTriple.java
core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemTriple.java
core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemValueFactory.java
core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/MemoryRDFStarSupportTest.java
core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/model/MemTripleTest.java
testsuites/repository/src/main/java/org/eclipse/rdf4j/repository/RDFStarSupportTest.java

GitHub issue resolved: #2024  
* adding and retrieving of Triple objects in the memory store added
* modified SimpleTriple.equals method to allow equality with other implementations of the Triple interface (cf. other simple model object implementations, e.g. SimpleIRI.equals)
* added basic unit and integration tests

GH-2024 rdfstar support in memorystore

---

.github/PULL_REQUEST_TEMPLATE.md

GitHub issue resolved: #2011  
* added PR author checklist (not required for people to check things off, more a reminder)
* added a note about our default merge strategy being squash and merge
* added a link to the developer documentation that goes into more detail about our merge strategy.

GH-2011 merge strategy and checklist added to PR template

---

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryJoinOptimizer.java
core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/AbstractQueryModelNode.java
core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/QueryModelNode.java
core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/StatementPattern.java
core/queryalgebra/model/src/test/java/org/eclipse/rdf4j/query/algebra/AbstractQueryModelNodeTest.java
core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/optimizers/QueryMultiJoinOptimizer.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/CheckStatementPattern.java
tools/federation/src/test/resources/tests/basic/query_limit01.qp
tools/federation/src/test/resources/tests/filter/query01.qp
tools/federation/src/test/resources/tests/filter/query01a.qp
tools/federation/src/test/resources/tests/medium/query03.qp
tools/federation/src/test/resources/tests/optimizer/queryPlan_Join_1.txt
tools/federation/src/test/resources/tests/optimizer/queryPlan_Join_2.txt
tools/federation/src/test/resources/tests/optimizer/queryPlan_Optional1
tools/federation/src/test/resources/tests/optimizer/queryPlan_Optional2
tools/federation/src/test/resources/tests/optimizer/queryPlan_query01
tools/federation/src/test/resources/tests/propertypath/query_path_exclusiveGroup.qp
tools/federation/src/test/resources/tests/propertypath/query_path_exclusivePath.qp
tools/federation/src/test/resources/tests/service/query01.qp
tools/federation/src/test/resources/tests/service/query02.qp
tools/federation/src/test/resources/tests/service/query02a.qp
tools/federation/src/test/resources/tests/service/query04.qp
tools/federation/src/test/resources/tests/service/query08.qp

Related GitHub issue: #2044  
* introduce getter and setter for cardinality in QueryModelNode
* default implementation in AbstractQueryModelNode
* include cardinality in signature for StatementPattern
* prints `StatementPattern (resultSizeEstimate=1)` instead of just `StatementPattern`
Eg:
```
Projection
ProjectionElemList
ProjectionElem "name"
ProjectionElem "mbox"
Filter
Regex
Str
Var (name=mbox)
Var (name=pattern)
Var (name=flags)
Join
StatementPattern (resultSizeEstimate=1)
Var (name=y)
Var (name=_const_2c03e873_uri, value=http://example.org/ns#pattern, anonymous)
Var (name=pattern)
Join
StatementPattern (resultSizeEstimate=1)
Var (name=y)
Var (name=_const_144ac82a_uri, value=http://example.org/ns#flags, anonymous)
Var (name=flags) …
```

GH-2044 store cardinality in query model node

---

.github/workflows/merge_master_to_develop.yml

GitHub issue resolved: #2011 
Tweaked the github action that creates the master->develop branch sync to output a warning to use merge commit, and made the link to the action script clickable.
---- 

GH-2011 added warning to use merge commit to merge the branch sync

---

core/query/src/main/java/org/eclipse/rdf4j/query/Query.java
core/repository/api/src/main/java/org/eclipse/rdf4j/repository/RepositoryConnection.java
core/repository/sail/src/main/java/org/eclipse/rdf4j/repository/sail/SailRepositoryConnection.java
core/repository/sail/src/test/java/org/eclipse/rdf4j/repository/sail/SailRepositoryConnectionTest.java
core/sail/api/src/main/java/org/eclipse/rdf4j/sail/SailConnection.java
core/sail/api/src/main/java/org/eclipse/rdf4j/sail/helpers/SailConnectionWrapper.java

GitHub issue resolved: #99  
- adds new method 'prepareQuery' to SailConnection that gets the raw
query string
- SailConnection can optionally pass back a custom implementation of
TupleExpr. If this happens the SailRepository skips parsing the query
and will just pass back in the custom TuplExpr when
SailConnection.evaluate is called.
- by default the method does nothing (returns empty optional)

GH-99 allow SailConnection to bypass Query Parser

---

tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/FederationEvalStrategy.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/TripleSource.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/TripleSourceBase.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/BasicTests.java

This change correctly set externally passed binding to single source
queries, i.e. where the query is relevant at a single owner (and thus
the original query string is passed as-is)
GitHub issue resolved: #2006

GH-2006: fix handling of external bindings in FedX SingleSourceQuery

---

core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java
core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLParserTest.java
testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ComplexSPARQLQueryTest.java
testsuites/sparql/src/main/resources/testcases-sparql-1.1/property-paths/manifest.ttl

GitHub issue resolved: #2078 
---- 

GH-2078 property path negation and inversion

---

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/RDFStarTripleSource.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StrictEvaluationStrategy.java
core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/EvaluationStrategyWithRDFStarTest.java

GitHub issue resolved: #2028 
- Introduced a new interface `RDFStarTripleSource` that  extends `TripleSource` interface with `getRdfStarTriples(s, p, o)`.
- added implementation of `evaluate(TripleRef)` that uses the new interface, if possible or checks the nodes from standard reification for solutions
- added a synthetic test cases to evaluate a `TripleRef` node through both types of sources
---- 

GH-2028 TripleRef evaluation in StrictEvaluationStrategy

---

compliance/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/SHACLComplianceTest.java
testsuites/shacl/src/main/java/org/eclipse/rdf4j/shacl/manifest/AbstractSHACLTest.java

GitHub issue resolved: #2091 
---- 

GH-2091 deprecate old shacl compliance tests

---

core/http/client/src/main/java/org/eclipse/rdf4j/http/client/SPARQLProtocolSession.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/EvaluationStatistics.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StrictEvaluationStrategy.java
core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/EvaluationStrategyWithRDFStarTest.java
core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/DelegatingSailDataset.java
core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/SailDataset.java
core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/SailDatasetImpl.java
core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/SailDatasetTripleSource.java
core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/UnionSailDataset.java
core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/MemTripleIterator.java
core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/MemorySailStore.java
core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemTripleIterator.java
testsuites/repository/src/main/java/org/eclipse/rdf4j/repository/RDFStarSupportTest.java

GitHub issue resolved: #2085 
This enables SPARQL* querying on in-memory stores.
- added `getTriples` to SailDataset and related classes
- added implementation to SailDatasetTripleSource (which is used by memory store and native store)
- added memory store specific triple iterator
---- 

GH-2085 naive implementation of RDFStarTripleSource for memory store

---

core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/datastore/DataFile.java
core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/benchmark/QueryBenchmark.java
core/sail/nativerdf/src/test/resources/benchmarkFiles/query4.qr
core/sail/nativerdf/src/test/resources/benchmarkFiles/query5.qr

GitHub issue resolved: #2107 
In DataFile try to predict the size of the data that needs to be read so that we can get away with a single read. This improves performance because even though the operating system might be smart, it's still cheaper to get 50 bytes in one read than to get 4+20 in two reads.
---- 

GH-2107 predict the size of the data that needs to be read in DataFile

---

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/planNodes/Tuple.java

GitHub issue resolved: #2113 
Reduce memory use by removing String.replace call.
---- 

Gh 2113 reduce memory use in shacl

---

tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXConnection.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXFactory.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/endpoint/EndpointBase.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/endpoint/EndpointFactory.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/endpoint/provider/NativeRepositoryInformation.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/endpoint/provider/RepositoryInformation.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/util/Vocabulary.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/write/ReadOnlyWriteStrategy.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/write/RepositoryWriteStrategy.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/write/WriteStrategy.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/FedXFactoryTest.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/endpoint/EndpointFactoryTest.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/repository/FedXRepositoryConfigTest.java
tools/federation/src/test/resources/tests/dataconfig/endpointfactoryTest_writable.ttl
tools/federation/src/test/resources/tests/rdf4jserver/config.ttl
tools/federation/src/test/resources/tests/rdf4jserver/dataConfig.ttl

GitHub issue resolved: #2101  
Added `fedx:writable` property which can optionally be set to true for a member endpoint service (or a member repository when using "classic config").
Added simple unit tests to verify property is communicated. 
---- 

GH-2101 set fedx:writable property for explicit writable member endpoint

---

core/sail/nativerdf/pom.xml
core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/datastore/DataStore.java
core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/datastore/IDFile.java
core/sail/nativerdf/src/test/resources/benchmarkFiles/query4.qr

GitHub issue resolved: #2111 
Cache and read ahead in the IDFile to reduce number of IO opertions.
---- 

GH-2111 cache IDFile

---

core/model/src/main/java/org/eclipse/rdf4j/model/vocabulary/WGS84.java

GitHub issue resolved: #2122
- Add constants for Basic Geo (WGS84 lat/long) vocabulary
---- 
- [ x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
- [x ] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change
- [x ] every commit has been [signed off](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)
Note: we merge all feature pull requests using [squash and merge](https://help.github.com/en/github/administering-a-repository/about-merge-methods-on-github#squashing-your-merge-commits). See [RDF4J git merge …

GH-2122 Add WGS84 vocabulary

---

pom.xml
tools/pom.xml
tools/workbench/pom.xml
tools/workbench/src/main/java/org/eclipse/rdf4j/workbench/commands/DeleteServlet.java
tools/workbench/src/main/java/org/eclipse/rdf4j/workbench/commands/QueryServlet.java

GitHub issue resolved: #1098 
Removed all references to org.json package. Replaced its use in the workbench with equivalent Jackson functionality. 
I've not written unit tests because the servlet code is rather tangled, and writing tests for it is a chore I just can't face at the moment. However, I compiled and ran the modified workbench, and verified that executing queries, saving queries, and deleting data still all work as expected.
---- 
Note: we merge all feature pull requests using [squash and merge](https://help.github.com/en/github/administering-a-repository/about-merge-methods-on-github#squashing-your-merge-commits). See [RDF4J git merge strategy](https://rdf4j.org/documentation/developer/merge-strategy/) for …

GH-1098 removed org.json dep, replaced usage with Jackson

---

core/rio/api/src/main/java/org/eclipse/rdf4j/rio/RDFFormat.java

GitHub issue resolved: #2120 
- old constructors (without rdf* boolean) reinserted for backward compatibility. Defaulting to no RDF* support
- marked older constructors deprecated
---- 

GH-2120 added old-signature constructors for backward compatibility

---

compliance/repository/src/test/java/org/eclipse/rdf4j/repository/sparql/SPARQLStoreConnectionTest.java
core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/SPARQLConnection.java
core/repository/sparql/src/test/java/org/eclipse/rdf4j/repository/sparql/SPARQLConnectionTest.java
testsuites/repository/src/main/java/org/eclipse/rdf4j/repository/RepositoryConnectionTest.java

GitHub issue resolved: #2121 
- SPARQLConnection internally keeps tracks of pending adds / removals. When either commit is called or an add is interleaved with remove (vice versa) the pendings adds/removals get flushed into a single INSERT/DELETE DATA operation
- added one or two unit tests to check content and sequence of update operations in the produced SPARQL string.
---- 

GH-2121 group adds/removes together in sparql update sequence

---

core/model/src/main/java/org/eclipse/rdf4j/model/ValueFactory.java
core/model/src/main/java/org/eclipse/rdf4j/model/util/Models.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryJoinOptimizer.java
core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/QueryModelVisitor.java
core/queryresultio/api/src/main/java/org/eclipse/rdf4j/query/resultio/AbstractQueryResultWriter.java
core/queryresultio/api/src/main/java/org/eclipse/rdf4j/query/resultio/QueryResultWriter.java
core/queryresultio/api/src/main/java/org/eclipse/rdf4j/query/resultio/TupleQueryResultFormat.java
core/rio/api/src/main/java/org/eclipse/rdf4j/rio/RDFWriter.java
pom.xml

GitHub issue resolved: #2143  
- modified several RDF* related changes to ensure reasonable defaults are in place
- modified several recent public and protected method changes to ensure binary compatibility
- configured [japicmp](https://siom79.github.io/japicmp/MavenPlugin.html) to check (and fail!) build on both source and binary compatibility with previous minor release. It ignore items annotated with InternalUseOnly or Experimental.  
---- 
Note: we merge all feature pull requests using [squash and merge](https://help.github.com/en/github/administering-a-repository/about-merge-methods-on-github#squashing-your-merge-commits). See [RDF4J git merge strategy](https://rdf4j.org/documentation/developer/merge-strategy/) …

GH-2143 ensure project is binary compatible with 3.1 releases

---

compliance/sparql/src/test/java/org/eclipse/rdf4j/sail/federation/FederationSPARQL10QueryTest.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryModelNormalizer.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StrictEvaluationStrategy.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/JoinIterator.java
core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/AbstractQueryModelNode.java
core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/GraphPatternGroupable.java
core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java
testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ComplexSPARQLQueryTest.java

GitHub issue resolved: #2140 
- moved decision on join strategy to single place
- hope/expectation is that using HashJoinIteration will be more efficient than the previous loop join strategy.
This is a work in progress as there are likely corner cases that will fail. We'll also need to run some performance tests to see if it actually makes a difference (although I'm in favor of this change regardless as it's a cleaner approach).
---- 
Note: we merge all feature pull requests using [squash and merge](https://help.github.com/en/github/administering-a-repository/about-merge-methods-on-github#squashing-your-merge-commits). See [RDF4J git merge strategy](https://rdf4j.org/documentation/developer/merge-strategy/) for more …

GH-2140 use HashJoinIteration instead of doing loop join

---

core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/NativeStore.java
core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/TxnStatusFile.java
core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/datastore/HashFile.java
core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/benchmark/TransactionsPerSecondBenchmark.java
core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/benchmark/TransactionsPerSecondForceSyncBenchmark.java

GitHub issue resolved: #2125 
- Benchmarks for NativeStore fsync feature.
- Small changes to improve transaction throughput for small transactions.
- cache "isWritable()" in NativeStore
- transaction status NONE is represented by the empty file (truncating is about as slow as overwriting, but truncating means that one txn status write can be done with append instead of overwrite making it faster)
---- 

Gh 2125 native store force sync benchmarks and transaction status improvements

---

core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/datastore/DataFile.java
core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/datastore/HashFile.java
core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/datastore/IDFile.java
core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/benchmark/DataFileBenchmark.java
core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/benchmark/HashFileBenchmark.java
core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/benchmark/IDFileBenchmark.java
core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/benchmark/Main.java
core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/benchmark/TransactionsPerSecondBenchmark.java
core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/benchmark/TransactionsPerSecondForceSyncBenchmark.java

GitHub issue resolved: #2151 
Some benchmarks for the lower level file operations in NativeStore and a couple of tweaks to control caching and syncing better as well as support for specifying the initial size of the HashFile.
---- 

Gh 2151 nativestore datastore benchmarks

---

tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/FederationEvalStrategy.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/optimizer/GenericInfoOptimizer.java

This change supports extensibility of the evaluation strategy to
potentially propagate SERVICE clauses as part of SingleSourceQueries.
Existing functionality is remaining as-is.
Note that existing functionality is already covered with unit tests.
GitHub issue resolved: #2169 
---- 

GH-2169: support to propagate SERVICE clauses to SingleSourceQuery

---

tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedX.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXConfig.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/write/DefaultWriteStrategyFactory.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/write/WriteStrategyFactory.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/write/WriteTest.java

This change makes the FedX WriteStrategy configurable (e.g. for
application developers who want to define a different implementation).
Default behavior remains as before.
Functionality is covered with a unit test.
GitHub issue resolved: #2167 
---- 

GH-2167: make FedX WriteStrategy configurable

---

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryModelNormalizer.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StrictEvaluationStrategy.java
core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/AbstractQueryModelNode.java
core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Projection.java
core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/VariableScopeChange.java
core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/helpers/TupleExprs.java
core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java
core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ast/ASTGraphPatternGroup.java
core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ast/SimpleNode.java
core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/optimizers/PrepareOwnedTupleExpr.java
testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ComplexSPARQLQueryTest.java

GitHub issue resolved: #2171 
- TupleExprBuilder uses this to build algebra tree with correct settings
- GraphPatternGroupable renamed to VariableScopeChange
- easier to distinguish corner cases at correct abstraction level
- added regression test for handling of values clause and named graphs
---- 

GH-2171 AST nodes now determine if node is scope change

---

core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java
core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ast/ASTGraphPatternGroup.java
core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/QueryPlanRetrievalTest.java

GitHub issue resolved: #2171 
This covers the case where the group graph pattern has the where clause as its direct parent - in this case we shouldn't count it as a scope change.
There are still several failing tests in QueryPlanRetrievalTest but I'm not immediately sure if these are problems in the new approach or simply a consequence of slight brittleness. 
---- 

GH-2171 group pattern as direct child of where clause is not a scope change

---

core/query/src/main/java/org/eclipse/rdf4j/query/explanation/GenericPlanNode.java
core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryCostEstimatesTest.java
core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/AbstractQueryModelNode.java
core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/BinaryTupleOperator.java
core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/helpers/QueryModelTreePrinter.java
core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/helpers/QueryModelTreeToGenericPlanNode.java
core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/QueryPlanRetrievalTest.java
tools/federation/src/test/resources/tests/optimizer/queryPlan_Join_1.txt

GitHub issue resolved: #2119 
- newScope variable in the generic plan node
- algorithm variable in the generic plan node (should have been there all along)
- modifications to the old query plan printer
---- 

GH-2119 nodes that introduce a new scope get a "new scope" label in the query plan

---

tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/ExclusiveStatement.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/StatementSourcePattern.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/SailTripleSource.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/SparqlTripleSource.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/TripleSource.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/TripleSourceBase.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/util/QueryStringUtil.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/NamedGraphTests.java
tools/federation/src/test/resources/tests/named-graphs/data2.trig

GitHub issue resolved: #2186 #2185 
GH-2186, GH-2185: variable named graphs + fixed graph handling for SAIL
* add unit tests covering variable named graphs
* fix handling of graphs (especially FROM NAMED) in Sail Strategy
Note that we now always use prepared SELECT queries if the query is
targeted against a variable graph or against a FROM NAMED graph.
GH-2186: move getStatements for prepared query to TripleSourceBase
There was actually no real difference in the implementation provided by
SparqlTripleSource and SailTripleSource. Thus we move the implementation
of SparqlTripleSource unmodified (except for adding brackets) to the
abstract base class to avoid code duplication.
---- 
Note: we merge all feature pull requests using [squash and …

GH-2186, GH-2185: variable named graphs + fixed graph handling for SAIL

---

core/util/src/main/java/org/eclipse/rdf4j/common/net/ParsedIRI.java
core/util/src/test/java/org/eclipse/rdf4j/common/net/ParsedIRITest.java

GitHub issue resolved: #2179 
- on non-standard uri schemes, do not validate that the host describes a valid TLD
- added tests
---- 

GH-2179 relax host validation on non-standard IRI schemes

---

core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java
core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLParserTest.java

GitHub issue resolved: #2142 
- regression test for complex nested property path parsing involving inversions
- simple fix for the immediate case which avoids creating reflexive paths (subject and object same var), which can happen in nested expressions.
- added FIXME header to indicate a more robust refactoring of the path expression processing is long overdue. 
---- 

GH-2142 property path intermediate vars

---

compliance/repository/pom.xml
compliance/sparql/pom.xml
pom.xml
tools/federation/pom.xml
tools/server/pom.xml

GitHub issue resolved: #1974  
* Upgrade to latest (9.4.27) Eclipse Jetty server

GH-1974 sync jetty version

---

core/query/src/main/java/org/eclipse/rdf4j/query/explanation/GenericPlanNode.java
core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/QueryPlanRetrievalTest.java

GitHub issue closing #2206 
Use box-drawing characters (https://en.wikipedia.org/wiki/Box-drawing_character) for making query plans easier to read.
---- 

GH-2206 prettier plans by using box-drawing characters to group joins

---

.github/workflows/develop-status.yml
.github/workflows/master-status.yml
.github/workflows/pr-verify.yml
compliance/repository/src/test/java/org/eclipse/rdf4j/repository/sparql/SPARQLStoreConnectionTest.java
core/sail/elasticsearch-store/src/test/java/org/eclipse/rdf4j/sail/elasticsearchstore/TestHelpers.java

GitHub issue resolved: #2009  
* bumps build on Java 11 to Java 13
* bumps version of elasticsearch (see also #2016 )
* fixes issue in SPARQLStoreConnectionTest with use of reflection

GH-2009 Update to java 13 for Github Actions

---

core/model/src/main/java/org/eclipse/rdf4j/model/impl/DynamicModel.java
core/model/src/test/java/org/eclipse/rdf4j/model/DynamicModelConcurrentModificationAndUpgradeTest.java

GitHub issue resolved: #221 
- LinkedHashMap is not removed while upgrading, allowing current users to keep using it
- Upgrading during a write will now wait for the write to complete, thanks to synchronized writes
---- 

GH-2211 more thread safe upgrading of the DynamicModel

---

core/model/src/main/java/org/eclipse/rdf4j/model/impl/DynamicModel.java
core/model/src/test/java/org/eclipse/rdf4j/model/DynamicModelConcurrentModificationAndUpgradeTest.java

GitHub issue resolved: #2211 
This is a draft branch to address test failure in `org.eclipse.rdf4j.model.DynamicModelConcurrentModificationAndUpgradeTest`  on Github CI. The test succeeds when ran on my local machine so it's flaky (which is not unusual with multithreaded stuff). 
I am not immediately spotting a problem with either the test or the implementation, so opening this draft PR to see the problem (hoping the CI build at least consistently fails) and cooperate on a fix. 
---- 
Note: we merge all feature pull requests using [squash and merge](https://help.github.com/en/github/administering-a-repository/about-merge-methods-on-github#squashing-your-merge-commits). See [RDF4J git merge strategy](https://rdf4j.org/documentation/developer/merge-strategy/) for more …

GH-2211 Fix DynamicModel upgrade flaky test failure

---

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StrictEvaluationStrategy.java
core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StrictEvaluationStrategyTest.java

GitHub issue resolved: #2224 
- recognize 'q' as a legal flag on a regex pattern, conform spec, and handle by setting `Pattern.LITERAL`.
- added regression tests.
---- 

GH-2224 handle q flag in SPARQL REGEX filters

---

tools/federation/src/main/java/org/eclipse/rdf4j/federated/util/QueryAlgebraUtil.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/QueryPlanTest.java
tools/federation/src/test/resources/tests/optimizer/queryPlan_bind.qp
tools/federation/src/test/resources/tests/optimizer/queryPlan_bind.rq

We now explicitly consider the binding names of the BIND clause (i.e. an
Extension) as variable for the join. In this way, statements where such
bindings occur obtain a lower cost.
Toy example for illustration:
```
SELECT ?project ?label WHERE {
BIND(:SomeThing AS ?type)
?project rdfs:label ?label .
?project rdf:type ?type .
}
```
With this change the type BGP gets evaluated before the label BGP.
Change is covered with a unit test.
---- 
Note: we merge all feature pull requests using [squash and merge](https://help.github.com/en/github/administering-a-repository/about-merge-methods-on-github#squashing-your-merge-commits). See [RDF4J git merge …

GH-2238: fix join order optimization for bound variables through BIND

---

core/repository/sail/src/main/java/org/eclipse/rdf4j/repository/sail/helpers/RDFSailRemover.java
testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLUpdateTest.java

GitHub issue resolved: #387 
* a suitable sized - but empty - array of contexts was created based on the size of a set
---- 

GH-387 really uses contexts instead of only creating an empty array

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/pr-verify.yml
pom.xml

GitHub issue resolved: #2259 
- xml formatting check part of automatic validation by CI
- xml formatting format part of automatic formatting as part of local build
- updated PR template to add links to guidelines and point out formatting conventions
- made it a bit clearer which maven goals you can run to make this easier
---- 

GH-2259 changes to PR template, guidelines, and activation of formatting plugins

---

core/model/src/main/java/org/eclipse/rdf4j/model/util/Literals.java
core/model/src/test/java/org/eclipse/rdf4j/model/util/LiteralsTest.java

Signed-off-by: SakshiSaini17092 <sakshi17092@iiitd.ac.in>
GitHub issue resolved: #688 
Added getLabel function for Optional.
---- 

GH-688: Added getLabel OptionalMethod for Optional

---

core/query/pom.xml
core/rio/api/pom.xml

GitHub issue resolved: #2199 
* exclude jackson dependencies from rio-api
(I added the json-ld java to support user-specified DocumenLoader a few releases ago, but forgot to exclude the unused dependencies)
---- 

GH-2199 exclude jackson dependencies from POM

---

core/spin/src/main/java/org/eclipse/rdf4j/spin/function/EvalFunction.java

GitHub issue resolved: #1135 
Replaced deprecated URI with IRI
---- 

GH-1135 replaced deprecated URI with IRI

---

core/query/src/main/java/org/eclipse/rdf4j/query/QueryResults.java
core/query/src/test/java/org/eclipse/rdf4j/query/QueryResultsTest.java

Signed-off-by: shubhi0108 <shubhi16267@iiitd.ac.in>
GH-2158: Formatted getAllValues function
Signed-off-by: navdhaagarwal <navdha16250@iiitd.ac.in>
GH-2158: Added a test
Signed-off-by: navdhaagarwal <navdha16250@iiitd.ac.in>
GH-2158: changed function name
Signed-off-by: navdhaagarwal <navdha16250@iiitd.ac.in>
GH2158: Final check with one more test
Signed-off-by: navdhaagarwal <navdha16250@iiitd.ac.in>
GitHub issue resolved: #2158 
Added a new utility function `getAllValues()` to QueryResults for fetching all the values of a binding variable from the `TupleQueryResult`
---- 
Note: we merge all feature pull requests using [squash and …

GH-2158: Added getAllValues function to QueryResults

---

core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/ArrangedWriter.java
core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleWriter.java
core/rio/turtle/src/test/java/org/eclipse/rdf4j/rio/turtle/ArrangedWriterTest.java

Signed-off-by: Mirr99 <mihir17166@iiitd.ac.in>
GitHub issue resolved: #1079
- Added a function call to `queueBlankStatements(SubjectInContext key)` to ensure that the statements related to a repeated BNode are also written.
Please let me know if a test case is required.

GH-1079 INLINE_BLANK_NODES-lose-bnode

---

core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/SPARQLConnection.java
core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/SPARQLRepository.java
core/repository/sparql/src/test/java/org/eclipse/rdf4j/repository/sparql/SPARQLConnectionTest.java

Signed-off-by: SakshiSaini17092 <sakshi17092@iiitd.ac.in>
GitHub issue resolved: #956  
I added a boolean indicator for silentMode just like quadMode. Which can be enabled/disabled through SparqlConnection.
---- 

GH-956-SilentModeSparqlEndpoint : added silentMode in sparql connection

---

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/ValueExprEvaluationException.java

GitHub issue resolved: #2304
Disable stack trace collection for ValueExprEvaluationException.
---- 

GH-2304: Disables stack trace collection for ValueExprEvaluationException

---

core/repository/sail/src/main/java/org/eclipse/rdf4j/repository/sail/helpers/SailUpdateExecutor.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXConnection.java

GitHub issue resolved: #2306  
- in FedXConnection, when checking if supplied bindings contain anything other than the "special" FedX bindings, do not assume we know the exact number of supplied FedX bindings, as it can vary.
- in SailUpdateExecutor, when merging result bindings with preset bindings, ensure a binding is not null before merging.
---- 
Note: we merge all feature pull requests using [squash and merge](https://help.github.com/en/github/administering-a-repository/about-merge-methods-on-github#squashing-your-merge-commits). See [RDF4J git merge …

GH-2306 more robust check for external bindings in FedXConnection

---

core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleParser.java
core/rio/turtle/src/test/java/org/eclipse/rdf4j/rio/turtle/TurtleParserTest.java

e.g. this character:
https://www.compart.com/en/unicode/U+1109D
the following string fail to unread:
```
"<r:\uD804\uDC9D>"
```
since same position is loaded more than once into reader's buf.
GitHub issue resolved: #2315
unread index is decremented properly to ensure proper unread
---- 

GH-2315 bugfix: some complex unicode characters fail to unread properly

---

core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/NativeStore.java

GitHub issue resolved: #2327  
Trivial fix to rename an internal variable. 
---- 

GH-2327 renamed reference to 'mainStore'

---

core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleParser.java
core/rio/turtle/src/test/java/org/eclipse/rdf4j/rio/turtle/TurtleParserTest.java

Signed-off-by: Elad Shaked <elad.shaked@sparkbeyond.com>
GitHub issue resolved: #2338
TurtleParser pops chars until the StringBuilder has 8 or more chars. It may be the case that Unicode surrogates cause 9 chars to be read (say 7 normal chars followed by a surrogate pair). When trying to pushback those chars into buffer of size 8 causes an overflow.
Increase PushbackReader buffer size to 10 (could have done with 9)
---- 
Note: we merge all feature pull requests using [squash and merge](https://help.github.com/en/github/administering-a-repository/about-merge-methods-on-github#squashing-your-merge-comm …

GH-2338 Increased TurtleParser pushback reader buffer to 10

---

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSailValidationException.java
core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/SourceConstraintComponent.java
core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/results/ValidationResult.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/ValidationReportTest.java

GitHub issue resolved: #2018  
Support for `sh:value` for all constraints except for cardinality constraints and logical constraints. 
---- 

Gh-2018 support for sh:value

---

compliance/elasticsearch/pom.xml
core/rio/jsonld/src/test/java/org/eclipse/rdf4j/rio/jsonld/JSONLDParserCustomTest.java
pom.xml

GitHub issue resolved: #2192 
* updated jackson dependencies
* updated json-ld java
* small change in test
* include newer snake YAML dependency for ES compliance test
---- 

GH-2192 upgrade jsonld-java and jackson + fix for test

---

core/rio/ntriples/src/main/java/org/eclipse/rdf4j/rio/ntriples/NTriplesParser.java
core/rio/ntriples/src/test/java/org/eclipse/rdf4j/rio/ntriples/AbstractNTriplesParserUnitTest.java

Signed-off-by: Elad Shaked <elad.shaked@sparkbeyond.com>
GitHub issue resolved: #2357
In NTriplesParser, lines starting with a hash tag ('#') are send to rdfHander.handleComment rather than being ignored
---- 

GH-2357 Add NTripletsParser comment lines handling

---

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/AST/ClassPropertyShape.java

Signed-off-by: henry-lp <tailp@kth.se>
GitHub issue resolved: #2363
This PR fixes the violations for the following SonarQube rules:
https://rules.sonarsource.com/java/RSPEC-1656
If you do no want to receive automated PRs for SonarQube warnings, reply to this PR with 'STOP'

GH-2363 Proposal for patching SonarQube rule 1656

---

core/model/src/main/java/org/eclipse/rdf4j/model/vocabulary/RSX.java
core/model/src/main/java/org/eclipse/rdf4j/model/vocabulary/SHACL.java
core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/AST/NodeShape.java
core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/AST/ShaclProperties.java
core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/AST/TargetShape.java
core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSail.java
core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/config/ShaclSailConfig.java
core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/config/ShaclSailFactory.java
core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/config/ShaclSailSchema.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/AbstractShaclTest.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/ExtendedFeaturesetTest.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/ShaclSailSupportedPredicatesDocumentationTest.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/ComplexTargetBenchmark.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/TargetBenchmarkInitialData.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/config/ShaclSailConfigTest.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/config/ShaclSailFactoryTest.java
core/sail/shacl/src/test/resources/shaclDatatypeTargetFilter.ttl
core/sail/shacl/src/test/resources/shaclDatatypeTargetFilterWithUnion.ttl
core/sail/shacl/src/test/resources/test-cases/class/complexTargetShape/shacl.ttl
core/sail/shacl/src/test/resources/test-cases/class/complexTargetShape2/shacl.ttl
core/sail/shacl/src/test/resources/test-cases/class/simpleTargetShape/shacl.ttl
core/sail/shacl/src/test/resources/test-cases/datatype/notNodeShapeTargetShape/shacl.ttl
core/sail/shacl/src/test/resources/test-cases/datatype/notTargetShape/shacl.ttl

GitHub issue resolved: #2371 
- switch from sh:targetShape to rsx:targetShape
---- 

GH-2371 switch to rsx namespace for targetShape

---

compliance/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/function/CustomFunctionEvaluationTest.java
compliance/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/function/TestTripleSourceCustomFunction.java
compliance/sparql/src/test/resources/META-INF/services/org.eclipse.rdf4j.query.algebra.evaluation.function.Function
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/function/Function.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/function/FunctionRegistry.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StrictEvaluationStrategy.java

GitHub issue resolved: #2362  
Allow access to database during function evaluation.
---- 

GH-2362 pass TripleSource through to function evaluation

---

compliance/lucene/src/test/java/org/eclipse/rdf4j/sail/lucene/LuceneSailTest.java
core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSail.java
testsuites/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractLuceneSailTest.java

GitHub issue resolved: #2377  
With the current algorithm the document for the last resource was never
persisted. This is now change to explicitly persist the last document
after loop completion.
Behavior is covered with a unit test
---- 
- [ x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
- [x ] I've added tests for the changes I made
- [ x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
- [x ] every commit …

GH-2377: fix LuceneSail#reindex() to create document for last resource

---

pom.xml

GitHub issue resolved: #2396  
Remove enforcer plugin from maven build process
- java 8 compatibility is covered by Github action build job
- speeds up build process
- avoids unnecessary downloads of rdf4j snapshot builds once a day
---- 

GH-2396 remove enforcer plugin

---

core/http/client/src/main/java/org/eclipse/rdf4j/http/client/RDF4JProtocolSession.java
core/http/client/src/main/java/org/eclipse/rdf4j/http/client/SPARQLProtocolSession.java
core/http/client/src/main/java/org/eclipse/rdf4j/http/client/SharedHttpClientSessionManager.java

GitHub issue resolved: #2419 
- SharedHttpClientSessionManager's internal ScheduledExecutorService made accessible (protected) for subclasses
- SPARQLProtocolSession's internal HttpContext made accessible (protected) for subclasses
- some minor updates to javadoc, comments and code organization. 
This allows custom extensions that want to things like hooking into external credential providers, custom handling of authentication over HTTP, etc. This was already possible by providing a fully separate HttpClientSessionManager implementation, but often these customizations are minor adjustments of the basics provided in the SharedHttpClientSessionManager, so it makes sense to subclass and tweak, instead of writing a full implementation from …

GH-2419 make executor and httpcontext accessible for subclasses

---

release.sh

GitHub issue resolved: #1917 
- release script now uses `gh` instead of `hub`
- tweaked list of things to do for comms and documentation a little to reflect single repo structure.
---- 

GH-1917 switch to official github cli, updated todo list for comms/doco

---

assembly-descriptors/pom.xml
assembly-descriptors/src/main/resources/assemblies/benchmark.xml
core/pom.xml
core/queryparser/sparql/pom.xml
core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLParseBenchmark.java
core/sail/extensible-store/pom.xml
core/sail/extensible-store/src/test/java/org/eclipse/rdf4j/sail/extensiblestore/benchmark/ExtensibleDynamicEvaluationStatisticsBenchmark.java
core/sail/extensible-store/src/test/java/org/eclipse/rdf4j/sail/extensiblestore/benchmark/ExtensibleDynamicEvaluationStatisticsLowMemBenchmark.java
core/sail/memory/pom.xml
core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/MemoryBenchmark.java
core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/QueryBenchmark.java
core/sail/nativerdf/pom.xml
core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/benchmark/DataFileBenchmark.java
core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/benchmark/HashFileBenchmark.java
core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/benchmark/IDFileBenchmark.java
core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/benchmark/QueryBenchmark.java
core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/benchmark/TransactionsPerSecondBenchmark.java
core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/benchmark/TransactionsPerSecondForceSyncBenchmark.java
core/sail/sail-spin/pom.xml
core/sail/sail-spin/src/test/java/org/eclipse/rdf4j/sail/spin/benchmarks/BasicBenchmarks.java
core/sail/shacl/pom.xml
core/util/pom.xml
core/util/src/test/java/org/eclipse/rdf4j/common/iteration/benchmark/IterationBenchmarks.java
pom.xml

GitHub issue resolved: #2431 
- main method makes direct execution from IDE possible
- fat jar (target/jmh-benchmark.jar) makes command line execution
possible
to run benchmarks from command line (example: memory store benchmarks):
1. `cd core/sail/memory`
2. `mvn package -Pquick` 
3. `java -jar target/jmh-benchmarks.jar MemoryBenchmark.load` (to run the specific load benchmark test). 
To run from Eclipse, you can right-click on the benchmark and select "Run as Java application". Occassionally you may need to run a `mvn clean install` beforehand to make this work. Adapt the OptionBuilder in the benchmark's main class to control which exact benchmark tests get run.
---- 
PR Author Checklist (see the [contributor …

GH-2431 all benchmarks now have a main, and a fat jar

---

assembly-descriptors/pom.xml

GitHub issue resolved: #2431  
Fix parent pom version in new module after merge to develop branch. 
---- 

GH-2431 correct parent pom version on develop branch

---

core/queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqljson/SPARQLResultsJSONParser.java
core/queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqljson/SPARQLStarResultsJSONConstants.java
core/queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqljson/SPARQLStarResultsJSONParser.java
core/queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqljson/SPARQLStarResultsJSONParserFactory.java
core/queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqljson/SPARQLStarResultsJSONWriter.java
core/queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqljson/SPARQLStarResultsJSONWriterFactory.java
core/queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqlstarjson/SPARQLStarResultsJSONParser.java
core/queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqlstarjson/SPARQLStarResultsJSONParserFactory.java
core/queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqlstarjson/SPARQLStarResultsJSONWriter.java
core/queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqlstarjson/SPARQLStarResultsJSONWriterFactory.java
core/queryresultio/sparqljson/src/main/resources/META-INF/services/org.eclipse.rdf4j.query.resultio.TupleQueryResultParserFactory
core/queryresultio/sparqljson/src/main/resources/META-INF/services/org.eclipse.rdf4j.query.resultio.TupleQueryResultWriterFactory
core/queryresultio/sparqljson/src/test/java/org/eclipse/rdf4j/query/resultio/sparqljson/SPARQLJSONTupleTest.java
core/queryresultio/sparqljson/src/test/java/org/eclipse/rdf4j/query/resultio/sparqljson/SPARQLStarJSONTupleBackgroundTest.java
core/queryresultio/sparqljson/src/test/java/org/eclipse/rdf4j/query/resultio/sparqljson/SPARQLStarJSONTupleTest.java
core/queryresultio/sparqljson/src/test/resources/sparqljson/rdfstar-extendedformat-jena.srj
core/queryresultio/sparqljson/src/test/resources/sparqljson/rdfstar-extendedformat-rdf4j.srj
core/queryresultio/sparqljson/src/test/resources/sparqljson/rdfstar-extendedformat-stardog.srj
testsuites/queryresultio/src/main/java/org/eclipse/rdf4j/query/resultio/AbstractQueryResultIOTupleTest.java

GitHub issue resolved: #2415 
- allow parsing of RDF* extended syntax when receiving "normal" sparql json results mime type
- support Stardog syntax variant
- support Jena syntax variant
Note that RDF4J still uses the base-64 encoding approach when writing / sending RDF* triples in `application/sparql-results+json` format, a client would have to explicitly ask for `application/x-sparqlstar-results+json` to receive the extended format from an RDF4J-based endpoint. Depending on which way community opinions go with respect to this, we may change that behavior in a followup.
---- 
Note: we merge all …

GH-2415 allow parsing RDF* using standard sparql json result parser

---

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StrictEvaluationStrategy.java
testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ComplexSPARQLQueryTest.java

GitHub issue resolved: #2443 
- added regression test and fix for handling of sesame:nil in a GRAPH clause in SPARQL queries
---- 

GH-2443 fix processing of sesame:nil in GRAPH clause

---

core/queryresultio/binary/src/test/java/org/eclipse/rdf4j/query/resultio/binary/BinaryTupleQueryResultWriterTest.java
core/queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqljson/AbstractSPARQLJSONWriter.java
core/queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqljson/SPARQLResultsJSONWriter.java
core/queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqljson/SPARQLStarResultsJSONWriter.java
core/queryresultio/sparqljson/src/test/java/org/eclipse/rdf4j/query/resultio/sparqljson/SPARQLResultsJSONWriterTest.java
core/queryresultio/sparqljson/src/test/java/org/eclipse/rdf4j/query/resultio/sparqljson/SPARQLStarResultsJSONWriterTest.java
core/queryresultio/sparqlxml/src/test/java/org/eclipse/rdf4j/query/resultio/sparqlxml/SPARQLXMLTupleQueryResultWriterTest.java
core/queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/text/tsv/SPARQLResultsTSVMappingStrategy.java
core/queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/text/tsv/SPARQLResultsTSVWriter.java
core/queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/text/tsv/SPARQLStarResultsTSVParser.java
core/queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/text/tsv/SPARQLStarResultsTSVParserFactory.java
core/queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/text/tsv/SPARQLStarResultsTSVWriter.java
core/queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/text/tsv/SPARQLStarResultsTSVWriterFactory.java
core/queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/textstar/tsv/SPARQLStarResultsTSVMappingStrategy.java
core/queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/textstar/tsv/SPARQLStarResultsTSVParser.java
core/queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/textstar/tsv/SPARQLStarResultsTSVParserFactory.java
core/queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/textstar/tsv/SPARQLStarResultsTSVWriter.java
core/queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/textstar/tsv/SPARQLStarResultsTSVWriterFactory.java
core/queryresultio/text/src/main/resources/META-INF/services/org.eclipse.rdf4j.query.resultio.TupleQueryResultParserFactory
core/queryresultio/text/src/main/resources/META-INF/services/org.eclipse.rdf4j.query.resultio.TupleQueryResultWriterFactory
core/queryresultio/text/src/test/java/org/eclipse/rdf4j/query/resultio/text/csv/SPARQLCSVTupleQueryResultWriterTest.java
core/queryresultio/text/src/test/java/org/eclipse/rdf4j/query/resultio/text/tsv/SPARQLStarTSVTupleBackgroundTest.java
core/queryresultio/text/src/test/java/org/eclipse/rdf4j/query/resultio/text/tsv/SPARQLStarTSVTupleQueryResultWriterTest.java
core/queryresultio/text/src/test/java/org/eclipse/rdf4j/query/resultio/text/tsv/SPARQLStarTSVTupleTest.java
core/queryresultio/text/src/test/java/org/eclipse/rdf4j/query/resultio/text/tsv/SPARQLTSVTupleQueryResultWriterTest.java
testsuites/queryresultio/pom.xml
testsuites/queryresultio/src/main/java/org/eclipse/rdf4j/query/resultio/AbstractTupleQueryResultWriterTest.java

GitHub issue resolved: #2437 
- SPARQL results JSON writer functionality for RDF* extended  format merged into default parser
- SPARQL results TSV writer functionality for RDF* extended  format merged into default parser
- moved extended TSV parser/writer to package `org.eclipse.rdf4j.query.resultio.text.tsv`and adapted serviceloader entries
- added generic test suite for tuple query results writers to check behavior under different configuration settings
---- 
Note: we merge all feature pull requests using [squash and merge](https://help.github.com/en/github/administering-a-repository/about-merge-me …

GH-2437 merge writers for rdf* extended formats with writer for standard form

---

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/SourceConstraintComponent.java
core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/results/ValidationResult.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/UnknownShapesTest.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/ValidationReportTest.java

GitHub issue resolved: #2439 
We now produce sh:value correctly for all constraint components with an exception for logical components where we need to wait for the new AST to support sh:value correctly.
---- 

GH-2439 sh:value produced correctly for all constraint components

---

core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/UpdateExprBuilder.java
core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/TestSparqlStarParser.java
testsuites/repository/src/main/java/org/eclipse/rdf4j/repository/RDFStarSupportTest.java

Fix in UpdateExprBuilder to process TripleRefs in WHERE clause
- added simple test cases
GitHub issue resolved: #2441 
---- 

GH-2441 fix UpdateExprBuilder to support SPARQLStar expressions in WHERE

---

core/queryresultio/api/src/main/java/org/eclipse/rdf4j/query/resultio/TupleQueryResultFormat.java
core/queryresultio/sparqlxml/src/main/java/org/eclipse/rdf4j/query/resultio/sparqlxml/AbstractSPARQLXMLWriter.java
core/queryresultio/sparqlxml/src/main/java/org/eclipse/rdf4j/query/resultio/sparqlxml/SPARQLResultsSAXParser.java
core/queryresultio/sparqlxml/src/main/java/org/eclipse/rdf4j/query/resultio/sparqlxml/SPARQLResultsXMLConstants.java
core/queryresultio/sparqlxml/src/main/java/org/eclipse/rdf4j/query/resultio/sparqlxml/SPARQLStarResultsXMLParser.java
core/queryresultio/sparqlxml/src/main/java/org/eclipse/rdf4j/query/resultio/sparqlxml/SPARQLStarResultsXMLParserFactory.java
core/queryresultio/sparqlxml/src/main/java/org/eclipse/rdf4j/query/resultio/sparqlxml/SPARQLStarResultsXMLWriter.java
core/queryresultio/sparqlxml/src/main/java/org/eclipse/rdf4j/query/resultio/sparqlxml/SPARQLStarResultsXMLWriterFactory.java
core/queryresultio/sparqlxml/src/main/resources/META-INF/services/org.eclipse.rdf4j.query.resultio.TupleQueryResultParserFactory
core/queryresultio/sparqlxml/src/main/resources/META-INF/services/org.eclipse.rdf4j.query.resultio.TupleQueryResultWriterFactory
core/queryresultio/sparqlxml/src/test/java/org/eclipse/rdf4j/query/resultio/sparqlxml/SPARQLStarXMLTupleBackgroundTest.java
core/queryresultio/sparqlxml/src/test/java/org/eclipse/rdf4j/query/resultio/sparqlxml/SPARQLStarXMLTupleQueryResultWriterTest.java
core/queryresultio/sparqlxml/src/test/java/org/eclipse/rdf4j/query/resultio/sparqlxml/SPARQLStarXMLTupleTest.java
core/queryresultio/text/src/test/java/org/eclipse/rdf4j/query/resultio/text/csv/SPARQLCSVTupleQueryResultWriterTest.java
site/content/documentation/programming/rdfstar.md
site/content/documentation/reference/rdf4j-binary.md
testsuites/queryresultio/src/main/java/org/eclipse/rdf4j/query/resultio/AbstractTupleQueryResultWriterTest.java

GitHub issue resolved: #2054  
- extended SPARQL/XML results format to deal with RDF*
- updated documentation
- added additional test for handling of nested RDF* triples
---- 

GH-2054 extended SPARQL/XML results format to deal with RDF*

---

core/model/src/main/java/org/eclipse/rdf4j/model/vocabulary/RDF4J.java
core/model/src/main/java/org/eclipse/rdf4j/model/vocabulary/SESAME.java
core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StrictEvaluationStrategy.java
core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/DatasetDeclProcessor.java
core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/PrefixDeclProcessor.java
core/repository/sail/src/main/java/org/eclipse/rdf4j/repository/sail/helpers/SailUpdateExecutor.java
core/spin/src/main/java/org/eclipse/rdf4j/spin/SpinParser.java
core/spin/src/test/java/org/eclipse/rdf4j/spin/SpinParserTest.java
testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ComplexSPARQLQueryTest.java
testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLUpdateTest.java
tools/workbench/src/test/java/org/eclipse/rdf4j/workbench/commands/TestInfoServlet.java

GitHub issue resolved: #2401  
- introduce new constant `RDF4J.NIL` and marked `SESAME.NIL` deprecated
- updated relevant usage and tests
---- 

GH-2401 introduce rdf4j:nil and deprecate sesame:nil

---

assembly/pom.xml
release.sh

GitHub issue resolved: #2469 
- fixes assembly plugin config to handle long file names 
- minor typo in release script
---- 

GH-2469 fix assembly plugin config and minor typo in release script

---

compliance/solr/pom.xml
pom.xml

GitHub issue resolved: #1097 
- update to guava version 29.0
- override managed dependency to allow for solr testing rig
---- 

GH-1097 bump guava to version 29.0

---

core/repository/http/src/main/java/org/eclipse/rdf4j/repository/http/HTTPRepository.java
core/repository/http/src/main/java/org/eclipse/rdf4j/repository/http/package-info.java
core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/SPARQLRepository.java
core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/package-info.java
core/repository/sparql/src/test/java/org/eclipse/rdf4j/repository/sparql/SPARQLRepositoryTest.java

GitHub issue resolved: #2267 
- fix hardcoded TupleQueryResultFormat in SPARQLRepository
- did some javadoc cleanup while I was at it
---- 

GH-2267 fix hardcoded TupleQueryResultFormat in SPARQLRepository

---

core/queryresultio/sparqlxml/src/main/java/org/eclipse/rdf4j/query/resultio/sparqlxml/SPARQLResultsSAXParser.java
core/queryresultio/sparqlxml/src/main/java/org/eclipse/rdf4j/query/resultio/sparqlxml/SPARQLResultsXMLConstants.java
core/queryresultio/sparqlxml/src/test/java/org/eclipse/rdf4j/query/resultio/sparqlxml/SPARQLXMLTupleTest.java
core/queryresultio/sparqlxml/src/test/resources/sparqlxml/rdfstar-extendedformat-rdf4j.srx
core/queryresultio/sparqlxml/src/test/resources/sparqlxml/rdfstar-extendedformat-stardog.srx

GitHub issue resolved: #2495 
- SPARQL results xml parser can now deal with Stardog variant of extended format
- added test cases
---- 

GH-2495 add Stardog dialect of SPARQL*/XML results

---

core/queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqljson/AbstractSPARQLJSONParser.java
core/queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqljson/SPARQLResultsJSONParser.java
core/queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqljson/SPARQLStarResultsJSONConstants.java
core/queryresultio/sparqljson/src/test/java/org/eclipse/rdf4j/query/resultio/sparqljson/SPARQLJSONTupleTest.java
core/queryresultio/sparqljson/src/test/resources/sparqljson/rdfstar-extendedformat-rdf4j-doublesubject.srj
core/queryresultio/sparqljson/src/test/resources/sparqljson/rdfstar-extendedformat-rdf4j-incompletetriple.srj

GitHub issue resolved: #2502  
- stardog dialect departs from common pattern by not wrapping subject,  predicate and object of an RDF* triple into a "value" json object.
- parser treats stardog as a separate case.
- added updated test data; all tests now greenline.
---- 

GH-2502 modified SPARQL/JSON parser to deal with Stardog dialect

---

core/repository/api/src/main/java/org/eclipse/rdf4j/repository/RepositoryConnection.java
site/content/documentation/programming/repository.md

GitHub issue resolved: #2504 
Documentation changes only: made it somewhat more explicit that using transactions can improve performance
---- 

GH-2504 added info on performance impact when using transactions

---

.github/workflows/develop-status.yml
.github/workflows/master-status.yml

This is an attempt to fix current master-to-develop being stuck by the expedient of just renaming the status check jobs, so that they're aligned with the name of the required check as configured in the branch protection. 
---- 

Fix protection branch action hook by using 'build' as job name

---

.github/workflows/develop-status.yml
.github/workflows/master-status.yml
.github/workflows/pr-verify.yml

GitHub issue resolved: #2510 
- bump to new version of cache action
- add config to all build jobs, not just pr verify
This may need some tweaking / testing. 
---- 

GH-2510 bump version of cache action and use in status CI jobs as well

---

core/sail/elasticsearch/src/main/java/org/eclipse/rdf4j/sail/elasticsearch/ElasticsearchIndex.java
core/sail/lucene-api/pom.xml
core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractSearchIndex.java
core/sail/lucene/pom.xml
core/sail/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneDocument.java
core/sail/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneIndex.java
core/sail/lucene/src/test/java/org/eclipse/rdf4j/sail/lucene/examples/LuceneSailExample.java
core/sail/solr/src/main/java/org/eclipse/rdf4j/sail/solr/SolrIndex.java
pom.xml

GitHub issue resolved: #2489 
With the current implementation in rdf4j, the lucene index have had some troubles in indexing and searching over geospatial data. After trying some modifications as presented in the issue #2489, no good results came out. So in this pull request the new way to index data introduced by Lucene is integrated and has been tested on very huge geo-shapes, the indexing works much much faster and it doesn't fail at all, adding to that the very fast search capability over such data is attained.
---- 
Note: we merge all feature pull requests using [squash and merge](https://help.github.com/en/github/administering-a-repository/abou …

GH-2489 Indexing and searching over geospatial data using lucene

---

core/queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqljson/AbstractSPARQLJSONParser.java
core/queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqljson/SPARQLResultsJSONParser.java
core/queryresultio/sparqljson/src/test/java/org/eclipse/rdf4j/query/resultio/sparqljson/SPARQLJSONTupleTest.java
core/queryresultio/sparqljson/src/test/resources/sparqljson/rdfstar-extendedformat-stardog-namedgraph.srj

GitHub issue resolved: #2526   
- silently read away optional graph element of embedded triple.
- treating Stardog as a completely separate case for easy of debugging
- hopefully we can just remove this code completely once the format has
had some standardization
---- 

GH-2526 handle stardog RDF* optional graph element

---

core/model/src/main/java/org/eclipse/rdf4j/model/package-info.java
core/repository/api/src/main/java/org/eclipse/rdf4j/repository/package-info.java
core/rio/api/src/main/java/org/eclipse/rdf4j/rio/package-info.java
core/rio/binary/src/main/java/org/eclipse/rdf4j/rio/binary/package-info.java
core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/core/package-info.java
pom.xml

GitHub issue resolved: #2520 
- obsolete rdf4j.eclipse.org project url replaced with rdf4j.org
---- 

GH-2520 replace all usage of old domain name

---

core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/TurtleParserSettings.java
core/rio/trig/pom.xml
core/rio/trig/src/test/java/org/eclipse/rdf4j/rio/trig/TriGParserCustomTest.java
core/rio/turtle/pom.xml
core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleParser.java
core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtlestar/TurtleStarParser.java
core/rio/turtle/src/test/java/org/eclipse/rdf4j/rio/turtle/CustomTurtleParserTest.java
core/rio/turtle/src/test/java/org/eclipse/rdf4j/rio/turtle/TurtleParserTest.java
core/rio/turtle/src/test/java/org/eclipse/rdf4j/rio/turtlestar/TurtleStarParserTest.java

GitHub issue resolved: #2511 
- regular turtle parser accepts Turtle* (to handle cases where endpoints send it on the normal Turtle MIME-type)
- can be configured to _not_ accept RDF* data when needed (e.g. for validation)
---- 

GH-2511 allow regular Turtle parser to process RDF*

---

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/planNodes/Tuple.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/OrderingTest.java

GitHub issue resolved: #2561 
Short tuples are smaller than longer tuples if otherwise equal.
---- 

GH-2561 fix ordering of tuples that have different lengths

---

pom.xml
tools/pom.xml

GitHub issue resolved: #2552  
Excluded most of the dependencies that were included when upgrading Guava. 
Keeping (perhaps a bit too cautious) failureaccess (which seems to be sometimes required at runtime) and the almost empty listenablefuture (only used to signal that listenablefutures are present)
---- 
Note: we merge all feature pull requests using [squash and merge](https://help.github.com/en/github/administering-a-repository/about-merge-methods-on-github#squashing-your-merge-commits). See [RDF4J git merge …

GH-2552 exclude guava dependencies

---

core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/AddRemoveBenchmarkEmpty.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/ClassBenchmarkEmpty.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/DatatypeBenchmarkEmpty.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/DatatypeBenchmarkLinear.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/DatatypeBenchmarkPrefilled.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/DatatypeBenchmarkSerializableEmpty.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/HasValueBenchmarkEmpty.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/LanguageInBenchmarkEmpty.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/MaxCountBenchmarkEmpty.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/MinCountBenchmarkEmpty.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/MinCountBenchmarkPrefilled.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/MinCountPrefilledVsEmptyBenchmark.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/NotClassBenchmarkEmpty.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/NotMaxCountBenchmarkEmpty.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/NotUniqueLangBenchmarkEmpty.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/ParallelBenchmark.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/ShaclLoadingBenchmark.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/UniqueLangBenchmarkEmpty.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/ValueInBenchmarkEmpty.java

This doesn't resolve an issue per say, but just adjusts many of the shacl benchmarks to use less memory so be more sensitive to time spent doing GC.
---- 

GH-1396 lower memory usage for benchmarks to take GC into consideration

---

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/RdfsSubClassOfReasoner.java
core/sail/shacl/src/test/resources/test-cases/class/subclass/invalid/case6/query1.rq
core/sail/shacl/src/test/resources/test-cases/class/subclass/shacl.ttl
core/sail/shacl/src/test/resources/test-cases/class/subclass/valid/case6/query1.rq
core/sail/shacl/src/test/resources/test-cases/class/subclass/valid/case6/query2.rq
core/sail/shacl/src/test/resources/test-cases/class/subclass/valid/case6/query3.rq

GitHub issue resolved: #2577 
Retrieve `rdfs:subClassOf` statements fro the shapes graph too.
---- 

GH-2577 shacl subclassof in shapes graph

---

core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ast/SyntaxTreeBuilderTokenManager.java

GitHub issue resolved: #2574 
Split a big method.
---- 

GH-2574 make SPARQL parsing faster

---

.github/PULL_REQUEST_TEMPLATE.md
site/content/documentation/developer/merge-strategy.md
site/content/documentation/developer/squashing.md
site/content/documentation/developer/workflow.md

GitHub issue resolved: #2011   
- back to specifying 'merge-commit' as our PR merge strategy
---- 

GH-2011 back to merge-commits as our preferred strategy

---

pom.xml
tools/pom.xml

GitHub issue resolved: #2595   
- upgrade junit dependency to 4.13.1
----

GH-2595 bump junit version to 4.13.1

---

bom/pom.xml

GitHub issue resolved: #2610 
- this makes it possible to use the slf4j-simple library in RDF4J-based projects without having to set the version explicitly
----

GH-2610 set version of slf4j-simple in bom

---

core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/BinaryOperator.java
core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/ConnectiveOperation.java
core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/ConnectiveOperator.java
core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/Expressions.java
core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/In.java
core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/Operation.java
core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/SparqlAggregate.java
core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/SparqlFunction.java
core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/UnaryOperator.java
core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/examples/sparql11spec/Section17Test.java

GitHub issue resolved: GH-2317
add support for sparql [NOT]IN operators
----

GH-2317 (not)in function

---

core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/UpdateExprBuilder.java
core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/TestSparqlStarParser.java

GitHub issue resolved: #2618 
Allow anonymous vars introduced by TripleRef to be reffered in head of the DELETE update when DELETE/WHERE update is processed
----

Fixes GH-2618 by allowing TripleRef anonymous vars in DELETE/WHERE

---

tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXConnection.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/PassThroughTupleExpr.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/TripleSourceBase.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/structures/FedXTupleQuery.java
tools/federation/src/main/java/org/eclipse/rdf4j/federated/structures/QueryInfo.java
tools/federation/src/test/java/org/eclipse/rdf4j/federated/BasicTests.java

GitHub issue resolved: #2624 
This change provides an optimization to the FedX federation engine to
allow pass-through of query results for single source queries, if a
TupleQueryResultHandler was supplied (i.e. if the query was executed
through TupleQuery#evaluate(handler).
The implementation is done through a helper tuple expression (to
propagate information into the federation evaluation strategy. Also we
use a number of marker interfaces.
The implementation is covered by unit tests whose assertions are very
strict and will ensure to find errors if other parts of the framework
change.
Note that if no pass-through is possible, the same logic as before is
applied.
----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md …

GH-2624: support pass through of single source federated queries

---

core/http/client/pom.xml
core/http/client/src/main/java/org/eclipse/rdf4j/http/client/SPARQLProtocolSession.java
core/http/client/src/test/java/org/eclipse/rdf4j/http/client/RDF4JProtocolSessionTest.java
core/http/client/src/test/java/org/eclipse/rdf4j/http/client/SPARQLProtocolSessionTest.java
core/queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqljson/SPARQLStarResultsJSONWriter.java
core/queryresultio/sparqlxml/src/main/java/org/eclipse/rdf4j/query/resultio/sparqlxml/SPARQLStarResultsXMLWriter.java
core/rio/trig/src/main/java/org/eclipse/rdf4j/rio/trigstar/TriGStarWriter.java
core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtlestar/TurtleStarWriter.java
core/util/src/main/java/org/eclipse/rdf4j/common/io/Sink.java

GitHub issue resolved: #2627  
- Added `Sink.acceptFileFormat` to let a sink optionally indicate it can accept formats other than its own
- discovered (and fixed) minor bug in pass-through handling: we should flush after copying
- Added tests for pass-through handling
----

GH-2627 allow result writers to accept other formats for passthrough

---

site/layouts/_default/index.html
site/layouts/_default/summary.html

- ensures images do not overflow to next news items when shown in a list
(my bad for not actually logging an issue for this first, but it's a really minor thing in the site content rather than the code)
----

minor fix to alignment of images in news items

---

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/AST/AndPropertyShape.java
core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/AST/OrPropertyShape.java
core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/AST/TargetShape.java
core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/AbstractShaclTest.java
core/sail/shacl/src/test/resources/test-cases/hasValue/targetShapeAnd/invalid/case4/query1.rq
core/sail/shacl/src/test/resources/test-cases/hasValueIn/targetShapeOr/invalid/case4/query1.rq
core/sail/shacl/src/test/resources/test-cases/hasValueIn/targetShapeOr/invalid/case5/query1.rq

GitHub issue resolved: #2632  
Fixes a bug in rsx:targetShape when suing `sh:or` or `sh:and`.
----

GH-2632 rsx:targetShape bug when using sh:or or sh:and

---

.github/CODEOWNERS

GitHub issue resolved: #2650  
- simple CODEOWNERS file with only one rule
- we can refine later if we want to assign specific parts of the code base to specific people 
- the intent is not to make people the sole guardian of (a piece of) the code base, merely as an aid to assign reviewers to a PR more easily.

GH-2650 simple codeowners file assigning all core committers

---

.github/workflows/update-epics.yml

GitHub issue resolved: #2456  
Automatically updates task lists on epics, marking resolved issues as checked off. See https://github.com/marketplace/actions/epic-issues-for-github
----

GH-2456 add epic update workflow

---

core/model/src/main/java/org/eclipse/rdf4j/model/impl/SimpleValueFactory.java

GitHub issue resolved: #2655  
- avoids deprecation notices in client code
- subsequent removal of old AbstractValueFactory (see GH-2663) made easier
----

GH-2655 override old AbstractValueFactory completely

---

core/rio/ntriples/src/main/java/org/eclipse/rdf4j/rio/ntriples/NTriplesParser.java

GitHub issue resolved: #2667 
Much of the N-Triples parser code is copy/paste of the Turtle parser code, however baseURI is never called / used (which makes sense, because N-Triples does not support relative IRIs)
* changed javadoc to mention that baseURI is ignored
* remove the not null check for baseURI, because it is not used anyway
----

GH-2667 n-triples baseuri doc

---

core/model-api/src/main/java/org/eclipse/rdf4j/model/Literal.java
core/model-api/src/main/java/org/eclipse/rdf4j/model/ValueFactory.java
core/model-api/src/main/java/org/eclipse/rdf4j/model/base/AbstractLiteral.java
core/model-api/src/main/java/org/eclipse/rdf4j/model/base/AbstractValueFactory.java
core/model-api/src/main/java/org/eclipse/rdf4j/model/base/ComponentTemporalAmount.java
core/model-api/src/test/java/org/eclipse/rdf4j/model/LiteralTest.java
core/model-api/src/test/java/org/eclipse/rdf4j/model/ValueFactoryTest.java
core/model/src/main/java/org/eclipse/rdf4j/model/impl/AbstractValueFactory.java
core/model/src/main/java/org/eclipse/rdf4j/model/impl/ValidatingValueFactory.java
core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/RDFStarDecodingValueFactory.java

GitHub issue resolved: #2658
- add Literal.temporalAccessor/AmountValue() methods
- add ValueFactory.createLiteral(TemporalAccessor/Amount) methods
- implement new methods in AbstractLiteral and AbstractValueFactory
----

GH-2658 Literal/ValueFactory java.time support

---

core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleWriter.java
core/util/src/main/java/org/eclipse/rdf4j/common/io/IndentingWriter.java

…to avoid needing
to encode latin1 strings
GitHub issue resolved: #2676
This buffers the outputwriter in the turtle writer which avoids a lot of Charset encoder overhead.
It also adds one method to the IndentingWriter that postpones when a String is converted into char[].
That might be useful if the String is an latin1 string and coversion to UTF-8 is a nop in that case.
In my testing it roughly doubles the speed at which a turtle file is writen.
----

GH-2676 add BufferedWriter to avoid charset encoding overhead in OutputStreamWriter
