- core/http/server/src/main/webapp/WEB-INF/classes/logback.xml
This PR addresses GitHub issue: #151
>  #151 fixed package name in logback.xml

- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/helpers/TupleExprs.java
This PR addresses GitHub issue: #210 
- Faster containsProjection()
> issues/#210 improved containsProjection() performance.

- edl-v1.0.txt
This PR addresses GitHub issue: #
- ...
- ...
- ...
> #245 fixed linebreaks

- core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/SPARQLConnection.java
- core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/query/SPARQLOperation.java
- core/spin/src/main/java/org/eclipse/rdf4j/spin/function/Concat.java
Fixes in compilation errors introduced by sync with 2.0 branch.
> fixed java 7 compilation errors

- core/spin/src/main/java/org/eclipse/rdf4j/spin/SpinParser.java
- core/spin/src/test/resources/testcases/test31.ttl
This PR addresses GitHub issue: #298
- ...
- ...
- ...
> issues/#298 fix + test.

- core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractReaderMonitor.java
This PR addresses GitHub issue: #301
- Tests pass for multiple repeated executions.
> Concurrency fix.

- core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractLuceneIndex.java
- core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractReaderMonitor.java
- core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSail.java
- core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSailConnection.java
- core/sail/fts/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneIndex.java
Putting up this PR to see how GitHub deals with cherrypicking. Somewhat surprisingly it shows @ansell's fixes in the diff, despite the fact that both branch have these fixes already.
> Sync of Releases/2.0.x to master

- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/EvaluationStatistics.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/TupleFunctionEvaluationStatistics.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/TupleFunctionEvaluationStrategy.java
- core/sail/spin/src/main/java/org/eclipse/rdf4j/sail/spin/SpinSailConnection.java
- core/sail/spin/src/main/java/org/eclipse/rdf4j/spin/function/spif/CanInvoke.java
- core/sail/spin/src/test/java/org/eclipse/rdf4j/sail/spin/EvaluationModeTest.java
- core/sail/spin/src/test/resources/testcases/testEvaluationMode.ttl
This PR addresses GitHub issue: #565  .
* Fixes problems in TupleFunctionEvaluationStrategy.
* 
* 
> Issues #565 Bug fixes for TupleFunctionEvaluationStrategy.

- core/model/src/main/java/org/eclipse/rdf4j/model/util/ModelBuilder.java
- core/model/src/main/java/org/eclipse/rdf4j/model/vocabulary/FOAF.java
- core/model/src/test/java/org/eclipse/rdf4j/model/util/ModelBuilderTest.java
This PR addresses GitHub issue: #97 .
* Introduced a new ModelBuilder class that allows fluent creation of RDF Models.
Early draft for feedback purposes. Tests to follow.
> Issue #97: fluent ModelBuilder

- core/repository/api/src/main/java/org/eclipse/rdf4j/repository/base/AbstractRepository.java
- core/repository/sail/src/main/java/org/eclipse/rdf4j/repository/sail/SailRepository.java
- core/sail/api/src/main/java/org/eclipse/rdf4j/sail/helpers/AbstractSail.java
- core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSail.java
- core/sail/fts/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneIndex.java
This PR addresses GitHub issue: #607 .
* After doing shutdown() user is not able to start new connection - it will throw exception
* Added more loggers
Signed-off-by:Jacek Grzebyta <grzebyta.dev@gmail.com>
> Issue #607: shutDown propagation in LuceneSail

- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/memory-customrule.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/memory-rdfs-dt.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/memory-rdfs.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/memory-spin-rdfs.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/memory-spin.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/memory.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/native-customrule.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/native-rdfs-dt.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/native-rdfs.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/native-spin-rdfs.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/native-spin.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/native.ttl
This PR addresses GitHub issue: #625 .
* fixed default value (StrictEvaluationStrategyFactory instead of Simple... )
* added config parameters to other relevant templates
* manually tested variants
> Issue #625: console strategy choice in repo creation

- core/sail/inferencer/src/main/java/org/eclipse/rdf4j/sail/inferencer/fc/AbstractForwardChainingInferencerConnection.java
- core/sail/spin/pom.xml
- core/sail/spin/src/main/java/org/eclipse/rdf4j/sail/spin/SpinSailConnection.java
- core/sail/spin/src/test/resources/logback-test.xml
This PR addresses GitHub issue: #601 .
* replaced slf4j-simple with logback in test setup
* added more debug- and trace-level logging to inferencer
> Fix #601: SPIN added more logging and made logback the test log implementation

- core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractSearchIndex.java
- core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/DistanceQuerySpec.java
- core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/DistanceQuerySpecBuilder.java
- core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/DistanceTupleFunction.java
- core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSail.java
- core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSailConnection.java
- core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSailSchema.java
- core/sail/fts/lucene-api/src/main/resources/META-INF/services/org.eclipse.rdf4j.query.algebra.evaluation.function.TupleFunction
- core/sail/spin/src/main/java/org/eclipse/rdf4j/sail/spin/SpinSailConnection.java
- testsuites/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractLuceneSailSpinTest.java
- testsuites/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractLuceneSailTupleFunctionTest.java
- testsuites/lucene/src/main/resources/org/eclipse/rdf4j/sail/220-example.ttl
This PR addresses GitHub issue: #713  .
This is a PR for work that was started as part of #220.
> Fix #713: Support for late evaluation of geo distance search

- core/model/src/main/java/org/eclipse/rdf4j/model/util/Models.java
- core/model/src/test/java/org/eclipse/rdf4j/model/util/ModelsTest.java
This PR addresses GitHub issue: #706 .
* added several additional convenience methods to `Models` utility (see #706 for rationale)
Putting this up for early review - I still need to add unit tests for the new methods but wanted to get some early feedback (if any).
> Fix #706: added several convenience methods to Models utility

- core/model/src/main/java/org/eclipse/rdf4j/model/vocabulary/VCARD4.java
This PR addresses GitHub issue: #765  .
* 
* 
*
> Fix #765: Added generated VCARD4 vocabulary

- core/queryrender/src/main/java/org/eclipse/rdf4j/queryrender/RenderUtils.java
- core/queryrender/src/test/java/org/eclipse/rdf4j/queryrender/RenderUtilsTest.java
Signed-off-by: Joseph Walton <joe@kafsemo.org>
This PR addresses GitHub issue: #754.
* Append the value in the `Optional` rather than stringifying it.
* 
*
> Fix #754: Fix serialisation of language tag in toSPARQL.

- core/rio/rdfjson/src/main/java/org/eclipse/rdf4j/rio/rdfjson/RDFJSONParser.java
This PR addresses GitHub issue: #773  .
* One-character-fix: test if rdfHandler is not null instead of null (fix for possible NPE)
> Fix #773: Check for handler not null instead of null

- core/sail/api/src/main/java/org/eclipse/rdf4j/sail/config/AbstractSailImplConfig.java
- core/sail/api/src/main/java/org/eclipse/rdf4j/sail/config/SailConfigSchema.java
- core/sail/api/src/main/java/org/eclipse/rdf4j/sail/helpers/AbstractSail.java
This PR addresses GitHub issue: #535  .
* added setter, so one can change the timeout instead of always using the default
* used the variable in wait() instead of default
> Fix #535: Made timeout configurable

- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/function/hash/HashFunction.java
- core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/function/hash/HashLeadingZeroTest.java
This PR addresses GitHub issue: #775  .
* fixed bug (missing leading zeros)
* convert bytes to hexstring without BigInteger
* added javadoc and override
> Convert bytes to hex string with leading zeros

- core/repository/api/src/main/java/org/eclipse/rdf4j/repository/config/ConfigTemplate.java
- core/repository/api/src/test/java/org/eclipse/rdf4j/repository/config/TestConfigTemplate.java
This PR addresses GitHub issue: #792  .
> Fix #792: Encode dollar sign in repository template replacement

- core/http/client/src/main/java/org/eclipse/rdf4j/http/client/RDF4JProtocolSession.java
This PR addresses GitHub issue: #764
> Fix #764: Include additional headers in sesame session requests

- core/http/workbench/src/main/java/org/eclipse/rdf4j/workbench/proxy/ServerValidator.java
This PR addresses GitHub issue: #786
> Fix #786: Catch NumberFormatException when checking server protocol

- core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/MemoryStore.java
Signed-off-by: belks <stefan.belk@semantic-web.com>
This PR addresses GitHub issue: #804  .
> issue #803

- core/rio/rdfxml/src/main/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLWriter.java
This PR addresses GitHub issue: #772
> Fix #772: Don't print xsd:string datatypes

- core/http/client/src/main/java/org/eclipse/rdf4j/http/client/SPARQLProtocolSession.java
This PR addresses GitHub issue: #362
> Fix #362: Don't use HttpParams unless timeout override

- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryJoinOptimizer.java
- core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryJoinOptimizerTest.java
This PR addresses GitHub issue: #380
> Fix #380: Always evaluate Extension/BIND before join

- .travis.yml
This PR addresses GitHub issue: #831 .
* Adds develop branch to .travis.yml
Once this is merged, merging master into develop again will synchronize the changes there so it can take effect.
> Fix #831 : Add develop branch to .travis.yml

- core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/BaseDeclProcessor.java
- core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/query/SPARQLOperation.java
- core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/AbstractRDFParser.java
- core/rio/rdfxml/src/main/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParser.java
- core/rio/rdfxml/src/main/java/org/eclipse/rdf4j/rio/rdfxml/SAXFilter.java
- core/util/src/main/java/org/eclipse/rdf4j/common/net/ParsedIRI.java
- core/util/src/main/java/org/eclipse/rdf4j/common/net/ParsedURI.java
- core/util/src/test/java/org/eclipse/rdf4j/common/net/ParsedIRITest.java
- testsuites/rio/src/main/java/org/eclipse/rdf4j/rio/n3/N3ParserTestCase.java
- testsuites/rio/src/main/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParserTestCase.java
- testsuites/serql/src/main/java/org/eclipse/rdf4j/query/parser/serql/SeRQLParserTestCase.java
- testsuites/serql/src/main/java/org/eclipse/rdf4j/query/parser/serql/SeRQLQueryTestCase.java
This PR addresses GitHub issue: #69 .
* Creats ParsedIRI for RFC 3987 IRI syntax validation
* Deprecates ParsedURI in favor of ParsedIRI
> Fix #69: IRI Parser for validation and resolution

- core/model/src/main/java/org/eclipse/rdf4j/model/datatypes/XMLDatatypeUtil.java
- core/model/src/test/java/org/eclipse/rdf4j/model/datatypes/XMLDatatypeUtilTest.java
- core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/BaseDeclProcessor.java
- core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/query/SPARQLOperation.java
- core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/AbstractRDFParser.java
- core/rio/rdfxml/src/main/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParser.java
- core/rio/rdfxml/src/main/java/org/eclipse/rdf4j/rio/rdfxml/SAXFilter.java
- core/util/src/main/java/org/eclipse/rdf4j/common/net/ParsedIRI.java
- core/util/src/main/java/org/eclipse/rdf4j/common/net/ParsedURI.java
- core/util/src/test/java/org/eclipse/rdf4j/common/net/ParsedIRITest.java
- testsuites/rio/src/main/java/org/eclipse/rdf4j/rio/n3/N3ParserTestCase.java
- testsuites/rio/src/main/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParserTestCase.java
- testsuites/serql/src/main/java/org/eclipse/rdf4j/query/parser/serql/SeRQLParserTestCase.java
- testsuites/serql/src/main/java/org/eclipse/rdf4j/query/parser/serql/SeRQLQueryTestCase.java
This PR addresses GitHub issue: #74 .
* Uses ParsedIRI to validate xsd:anyURI
> Issues/#74 Validate xsd:anyURI values

- core/util/src/main/java/org/eclipse/rdf4j/common/net/ParsedIRI.java
This PR addresses GitHub issue: #846  .
With this change performance of ParsedIRI is the same as ParsedURI.
* Uses int[] instead of String to use direct code point comparison and avoid surrogates
* Use binary search for character sets
> Fix #846: Use int[] instead of String for IRI parsing

- core/console/src/main/java/org/eclipse/rdf4j/console/ConsoleIO.java
This PR addresses GitHub issue: #864 .
> Fix #864: Check for null input on console

- core/spin/src/test/resources/testcases/test16.ttl
This PR addresses GitHub issue: #77 .
> Issue #77: Update SPIN test

- core/spin/src/test/resources/testcases/test16.ttl
> Revert "Issue #77: Update SPIN test"

- core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java
- core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLParserTest.java
> Revert "Fix #77: Normalize typed literals in SPARQL parser"

- pom.xml
This PR addresses GitHub issue: #906 .
> Fix #906: Remove hudson.rdf4j.proxy.opts

- core/repository/http/src/main/java/org/eclipse/rdf4j/repository/http/HTTPRepository.java
This PR addresses GitHub issue: #928  .
> Fix #928: Fix broken doc link

- core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/RepositoryListController.java
This PR addresses GitHub issue: #945 .
> Fix #945: Check for null repo config description

- pom.xml
> Upgrade to newer JSONLD

- core/model/src/main/java/org/eclipse/rdf4j/model/vocabulary/LDP.java
This PR addresses GitHub issue: #326  .
* Added LDP vocabulary
> Added LDP vocabulary

- queryparser/api/src/test/java/org/eclipse/rdf4j/query/parser/QueryPrologLexerTest.java
This PR addresses GitHub issue: #975 and #951  .
* Include @aschwarte10 contributed test case
> Fix #975: Add test case for multiline comment

- client/pom.xml
This PR addresses GitHub issue: #995 .
* Nexus Staging Rules require javadoc jar for rdf4j-client
> Fx #995: Add aggregate javadoc for rdf4j-client jar

- queryresultio/text/pom.xml
- queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/text/csv/SPARQLResultsCSVMappingStrategy.java
- queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/text/csv/SPARQLResultsCSVParser.java
- queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/text/csv/SPARQLResultsCSVWriter.java
- queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/text/tsv/SPARQLResultsTSVParser.java
Signed-off-by: Andrew Rucker Jones <arjones@t-online.de>
This PR addresses GitHub issue: #1060 .
* Update to opencsv 4.2.
* Refactor CSV parsing to take advantage of parallel processing of CSV input.
* Refactor to eliminate recompiling of unchanging regular expressions in CSV and TSV parsing.
> Issue #1060: More efficient parsing of CSV and TSV input.

- repository/http/src/main/java/org/eclipse/rdf4j/repository/http/HTTPRepository.java
This PR addresses GitHub issue: #1085 .
* added `setAdditionalHttpHeaders` and `getAdditionalHttpHeaders` to `HTTPRepository`
* ensured custom headers are configured on the underlying `RDF4JProtocolSession`
> Fix GH-1085 added functionality to configure custom headers on HTTPRepository

- README.md
* adds fix for GH-1085 to develop branch
* add fix for eclipse/rdf4j-storage#107 to develop branch
> sync master to develop

- compliance/manager/src/test/java/org/eclipse/rdf4j/repository/manager/LocalRepositoryManagerTest.java
- query/src/test/java/org/eclipse/rdf4j/common/iteration/UnionIterationTest.java
- repository/api/src/main/java/org/eclipse/rdf4j/repository/base/RepositoryConnectionWrapper.java
- repository/api/src/main/java/org/eclipse/rdf4j/repository/config/RepositoryConfigUtil.java
- repository/api/src/main/java/org/eclipse/rdf4j/repository/util/RepositoryUtil.java
- repository/http/src/main/java/org/eclipse/rdf4j/repository/http/HTTPRepository.java
- repository/http/src/main/java/org/eclipse/rdf4j/repository/http/HTTPRepositoryConnection.java
- repository/manager/src/main/java/org/eclipse/rdf4j/repository/manager/LocalRepositoryManager.java
- repository/manager/src/main/java/org/eclipse/rdf4j/repository/manager/SystemRepository.java
- repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/SPARQLConnection.java
- rio/turtle/src/test/java/org/eclipse/rdf4j/rio/turtle/TestTurtleParser.java
- util/src/main/java/org/eclipse/rdf4j/common/io/FileUtil.java
- util/src/main/java/org/eclipse/rdf4j/common/io/IOUtil.java
- util/src/main/java/org/eclipse/rdf4j/common/io/ResourceUtil.java
- util/src/main/java/org/eclipse/rdf4j/common/io/ZipUtil.java
- util/src/main/java/org/eclipse/rdf4j/common/xml/DocumentUtil.java
This PR addresses GitHub issue: #1092  .
* Use try-with-resources instead of try-finally
> Use try-with-resources

- rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/XMLReaderBasedParser.java
This PR addresses GitHub issue: #1056  .
* minor code cleanup based off previous PR review
> GH-1056 minor code cleanup

- rio/rdfxml/src/main/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParser.java
This PR addresses GitHub issue: #81  .
* Added javadoc
> Added documentation on JAXP

- rio/rdfxml/src/main/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParser.java
This PR addresses GitHub issue: eclipse/rdf4j#81 .
* Added jdk.xml prefix
> Update property name

- util/src/main/java/org/eclipse/rdf4j/common/io/UncloseableOutputStream.java
This PR addresses GitHub issue: #1191  .
* Added uncloseable output stream (see also #1172)
* Code formatting on input stream
> Added uncloseableoutputstream + code formatting

- model/src/main/java/org/eclipse/rdf4j/model/vocabulary/LOCN.java
This PR addresses GitHub issue: #1203  .
* Added constants for LOCN vocabulary
> Added LOCN vocabulary

- sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/SparqlFunction.java
This PR addresses GitHub issue: #1308.
- Added STR function
> #1308 - STR function missing from SparqlFunctions

- pom.xml
This PR addresses GitHub issue: #1173 .
* Remove unused commons lang dependency
> Remove unused commons-lang dependency

- pom.xml
This PR addresses GitHub issue: #1433  .
* Updated dependency
> Updated JSON-LD

- query/src/main/java/org/eclipse/rdf4j/query/impl/FallbackDataset.java
- query/src/main/java/org/eclipse/rdf4j/query/impl/SimpleDataset.java
This PR addresses GitHub issue: #439  .
* Use "FROM" and "FROM NAMED" instead of "USING"
I assume this is the only changed that is needed, since the (old) ticket mentions it is a "good first issue", so I guess this is the only trivial change that was required ?
> Changed USING to FROM

- model/src/main/java/org/eclipse/rdf4j/model/impl/AbstractModel.java
- model/src/main/java/org/eclipse/rdf4j/model/impl/LinkedHashModel.java
- model/src/main/java/org/eclipse/rdf4j/model/impl/TreeModel.java
This PR addresses GitHub issue: #1473 .
* check if model is empty before continuing with remove() method, for performance
* 
*
> issues/1473 check if model is empty before continuing with remove()

- queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java
- queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilderTest.java
This PR addresses GitHub issue: #1490 .
* sparql parser now maps a valueconstant to a var when creating statementpattern 
* added regression test
> GH-1490 ensure valueconstant is mapped to var

- queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/BaseDeclProcessor.java
- rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/AbstractRDFParser.java
- rio/rdfxml/src/main/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParser.java
This PR addresses GitHub issue: #1072  .
* remove references / use of depecrated class ParsedURI
> remove references to ParsedURI

- core/sail/federation/src/test/java/org/eclipse/rdf4j/sail/federation/SPARQLBuilderTest.java
This PR addresses GitHub issue: #1536  .
* Code formatting
* Made connection static (seems like an issue with parameterized junit + threads on multicore ARMv8)
> Made connection static

- assembly/pom.xml
- tools/runtime/pom.xml
GitHub issue resolved: #1564 
* Typos, nested tag should be dependencySourceInclude instead of dependencySourceInclude**s** (wrapper tag)
> Fixed typos

- pom.xml
- tools/pom.xml
GitHub issue resolved: #1567  
* Removed duplicate properties in pom.xml and properties from tools/pom.xml
> Remove duplicate version properties

- pom.xml
GitHub issue resolved: #1569   
* Updated apache httpcore and httpclient
> Updated apache httpcore and httpclient

- core/rio/jsonld/src/test/java/org/eclipse/rdf4j/rio/jsonld/JSONLDWriterTest.java
GitHub issue resolved: #1486  
* Code formatting
> Code formatting

- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/AST/PathPropertyShape.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/AST/PropertyShape.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/AST/ShaclProperties.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/UnknownShapesTest.java
- core/sail/shacl/src/test/resources/complexPath.ttl
GitHub issue resolved: #1561   
* detect use of complex shacl paths
* log a warning
* deactivate the shape so that we don't crash down the line
> #1561 log a warning when using complex paths and deactivate the shape 

- core/http/client/src/test/java/org/eclipse/rdf4j/http/client/RDF4JProtocolSessionTest.java
- core/repository/manager/src/test/java/org/eclipse/rdf4j/repository/manager/RemoteRepositoryManagerTest.java
GitHub issue resolved: #1604  
* random port in wiremock
* 
*
> #1604 wiremock random port

- core/sail/sail-spin/src/main/java/org/eclipse/rdf4j/sail/spin/SpinSail.java
- core/sail/sail-spin/src/main/java/org/eclipse/rdf4j/sail/spin/SpinSailConnection.java
- core/sail/sail-spin/src/main/java/org/eclipse/rdf4j/sail/spin/config/SpinSailConfig.java
- core/sail/sail-spin/src/main/java/org/eclipse/rdf4j/sail/spin/config/SpinSailFactory.java
- core/sail/sail-spin/src/main/java/org/eclipse/rdf4j/sail/spin/config/SpinSailSchema.java
- core/sail/sail-spin/src/test/java/org/eclipse/rdf4j/sail/spin/benchmarks/BasicBenchmarks.java
> Revert "Issues/1596 configurable spin"

- core/sail/sail-spin/src/main/java/org/eclipse/rdf4j/sail/spin/SpinSail.java
- core/sail/sail-spin/src/main/java/org/eclipse/rdf4j/sail/spin/SpinSailConnection.java
- core/sail/sail-spin/src/main/java/org/eclipse/rdf4j/sail/spin/config/SpinSailConfig.java
- core/sail/sail-spin/src/main/java/org/eclipse/rdf4j/sail/spin/config/SpinSailFactory.java
- core/sail/sail-spin/src/main/java/org/eclipse/rdf4j/sail/spin/config/SpinSailSchema.java
- core/sail/sail-spin/src/test/java/org/eclipse/rdf4j/sail/spin/benchmarks/BasicBenchmarks.java
GitHub issue resolved: #1596   
* configurable SPIN constraint validation
* very useful to disable to improve performance if SPIN constraint validation is not needed
*
> #1596 configurable SPIN constraint validation

- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/BindingSetAssignment.java
- core/spin/src/main/java/org/eclipse/rdf4j/spin/SpinParser.java
Signed-off-by: Udit Sharma <usharma898@gmail.com>
GitHub issue resolved: #1623 
* Fixed equals and hashcode in BindingSetAssignment
* 
*
> #1623 Fixed equals() and hashcode()

- core/sail/sail-spin/src/main/java/org/eclipse/rdf4j/sail/spin/SpinSail.java
- core/sail/sail-spin/src/main/java/org/eclipse/rdf4j/sail/spin/package-info.java
- core/sail/sail-spin/src/main/java/org/eclipse/rdf4j/spin/function/spif/package-info.java
- core/sail/sail-spin/src/test/java/org/eclipse/rdf4j/sail/spin/SpinSailTest.java
- core/sail/sail-spin/src/test/resources/testcases/testDeepConstructRule-expected.ttl
- core/sail/sail-spin/src/test/resources/testcases/testDeepConstructRule.ttl
- core/sail/sail-spin/src/test/resources/testcases/testNegationConstructRule.ttl
- core/spin/src/main/java/org/eclipse/rdf4j/spin/package-info.java
GitHub issue resolved: #1262  
* Deprecated the SpinSail and added comments that explain why and recommend alternative solutions
* 
*
> #1262 deprecate the SpinSail

- release.sh
Signed-off-by: Håvard Ottestad <hmottestad@gmail.com>
GitHub issue resolved: #1598   
* 
* 
*
> #1598 adjustments for the script

- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSail.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/ShutdownTest.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/ClassBenchmarkEmpty.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/ComplexLargeBenchmark.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/DatatypeBenchmarkEmpty.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/DatatypeBenchmarkLinear.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/DatatypeBenchmarkPrefilled.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/DatatypeBenchmarkSerializableEmpty.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/MaxCountBenchmarkEmpty.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/MinCountBenchmarkEmpty.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/MinCountBenchmarkPrefilled.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/MinCountPrefilledVsEmptyBenchmark.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/NotClassBenchmarkEmpty.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/NotMaxCountBenchmarkEmpty.java
GitHub issue resolved: #1638  
* fixes benchmark
* add test and shutdown thread pool correctly
* also changed a method from public to package private, it should not have been public to begin with!
> #1638 fixed bechmark, added test, use shutdownNow

- tools/workbench/src/main/java/org/eclipse/rdf4j/workbench/commands/UpdateServlet.java
GitHub issue resolved: #1643  
*  Fix  for incorrect conflict resolution
> Fix for incorrect conflict resolution

- testsuites/rio/pom.xml
> GH-1515 fix missing runtime dependency

- testsuites/rio/pom.xml
stabilizing the build for develop
> sync master -> develop

- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/UnknownShapesTest.java
GitHub issue resolved: #1649  
* Make the test work on Windows by also replacing CR/LF
> Fix for OS using CR/LF (MS-Windows) and CR

- core/repository/api/src/test/java/org/eclipse/rdf4j/repository/RDFSchemaRepositoryConnectionTest.java
- core/sail/inferencer/src/main/java/org/eclipse/rdf4j/sail/inferencer/fc/SchemaCachingRDFSInferencerConnection.java
- testsuites/benchmark/pom.xml
- testsuites/benchmark/src/main/java/org/eclipse/rdf4j/benchmark/Main.java
GitHub issue resolved: #1685  
* added regression test that demonstrates the problem
> GH-1685 subclassof inferencer bug

- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/MultithreadedTest.java
GitHub issue resolved: #1702  
* modify test to use executor service instead of parallel streams
* 
*
> #1702 modify test to use executor service instead of parallel streams

- core/sail/elasticsearch-store/src/main/java/org/eclipse/rdf4j/sail/elasticsearchstore/ElasticsearchDataStructure.java
- core/sail/extensible-store/src/main/java/org/eclipse/rdf4j/sail/extensiblestore/ReadCommittedWrapper.java
GitHub issue resolved: #  
* some minor optimisations
* 
*
> #1711 various optimisations for ElasticsearchStore

- pom.xml
GitHub issue resolved: #1433  
* Upgrade to JsonLD-java 0.12.5
> Upgrade to JsonLD-Java 0.12.5

- .github/workflows/develop-status.yml
- .github/workflows/master-status.yml
- .github/workflows/pr-verify.yml
- README.md
- added badges on README for master and develop status (had to split master and develop compliance into separate jobs for this)
- modified pull request testing to do full compliance testing (safer, and only marginally slower)
> Streamline action workflow

- core/model/src/main/java/org/eclipse/rdf4j/model/datatypes/XMLDatatypeUtil.java
- core/model/src/main/java/org/eclipse/rdf4j/model/vocabulary/XMLSchema.java
- core/model/src/test/java/org/eclipse/rdf4j/model/datatypes/XMLDatatypeUtilTest.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/function/xsd/StringCast.java
- core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemValueFactory.java
GitHub issue resolved: #1729  
* Added constant to XMLSchema vocabulary
* Added checks in XmlDateUtil
* Added tests
> Added xsd:dateTimeStamp, initial patch provided by Toni Cebrián

- compliance/model/pom.xml
- core/queryparser/sparql/pom.xml
- core/sail/elasticsearch-store/pom.xml
- core/sail/memory/pom.xml
- core/sail/nativerdf/pom.xml
- core/sail/sail-spin/pom.xml
- core/sail/shacl/pom.xml
- core/util/pom.xml
- pom.xml
- testsuites/benchmark/pom.xml
GitHub issue resolved: #1690  
* upgrade jmh
* 
*
> #1690 upgrade jmh

- core/model/src/main/java/org/eclipse/rdf4j/model/datatypes/XMLDatatypeUtil.java
GitHub issue resolved: #1735   
* Added javadoc
* Use precompiled patterns
> XMLDateutil performance

- core/model/src/main/java/org/eclipse/rdf4j/model/datatypes/XMLDatatypeUtil.java
- core/model/src/test/java/org/eclipse/rdf4j/model/datatypes/XMLDatatypeUtilTest.java
GitHub issue resolved: #1744  
* Use isNaN vs ==
> Fix for comparing with NaN and test

- core/query/src/main/java/org/eclipse/rdf4j/query/QueryResults.java
GitHub issue resolved: #1750  
* Create new parseBackground method with RDFParser as argument
* Let current parseBackground (with RDFFormat as argument) also use this method
* Minor javadoc changes / code formatting
> Added method with RDFParser argument + minor javadoc changes

- core/sail/elasticsearch-store/src/main/java/org/eclipse/rdf4j/sail/elasticsearchstore/ElasticsearchStore.java
GitHub issue resolved: #1760  
* 
* 
*
> #1760 allow users to provide client directly

- tools/workbench/src/main/java/org/eclipse/rdf4j/workbench/base/TransformationServlet.java
GitHub issue resolved: #1664   
* Moved check config for null
> Make sure to check for null first

- core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/core/query/Queries.java
GitHub issue resolved: #1381  
* Added convenience methods for INSERT and DELETE
> Added convenience methods

- .github/workflows/pr-verify.yml
GitHub issue resolved: #  
* 
* 
*
> add caching to github CI

- assembly/pom.xml
> include rdf4j-tools-federation in SDK and onejar

- core/model/src/main/java/org/eclipse/rdf4j/model/impl/FilteredModel.java
GitHub issue resolved: #1767  
* Tests always evaluate to true, so just return true
> Simplified return statements

- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/GroupIterator.java
- core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/GroupIteratorTest.java
GitHub issue resolved: #1774  
* Return integer 0 instead of double 0.0
* Added test cases for avg, count, sum
> Correction for zero average + added test cases

- core/model/src/main/java/org/eclipse/rdf4j/model/impl/FilteredModel.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/GroupIterator.java
- core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/GroupIteratorTest.java
Merge changes from master into develop
> Sync dev with master

- core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/evaluation/ParallelJoinCursor.java
- core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/evaluation/ParallelLeftJoinCursor.java
- core/sail/federation/src/test/java/org/eclipse/rdf4j/sail/federation/SPARQLBuilderTest.java
GitHub issue resolved: #1736   
* reproduce bug consistently
* fix race condition with synchronization
> #1736 race condition in the federated sail

- tools/federation/src/test/java/demos/MonitorRequestsDemo.java
- tools/federation/src/test/java/demos/QueryPlanLogDemo.java
GitHub issue resolved: #1555  
Improve the examples and demo snippets
> GH-1555 Improve FedX Demo code and examples

- release.sh
GitHub issue resolved: #  
* 
* 
*
> merge master into develop

- pom.xml
* set longer timeout 2 hours instead of 10 min (default)
* polling every 10 sec instead of every 3 (default)
*
> deploy fix: upgrade dependency and add some timeout and reduce polling

- .github/CONTRIBUTING.md
- README.md
> Added link to squashing and cleaned up a bit

- core/model/src/main/java/org/eclipse/rdf4j/model/util/ModelCollector.java
- core/model/src/test/java/org/eclipse/rdf4j/model/util/ModelCollectorTest.java
GitHub issue resolved: #1809   
* Added ModelCollector class
* Added tests for serial and parallel stream
> GH-1809: Added collector for Model + test

- core/model/src/main/java/org/eclipse/rdf4j/model/util/Models.java
- core/model/src/main/java/org/eclipse/rdf4j/model/util/Statements.java
- core/model/src/test/java/org/eclipse/rdf4j/model/util/ModelsTest.java
- core/model/src/test/java/org/eclipse/rdf4j/model/util/StatementsTest.java
GitHub issue resolved: #1739  
* added `Statements.stripContext`
* added `Models.stripContexts` 
* adedd unit tests
> GH-1739 strip context

- core/util/src/main/java/org/eclipse/rdf4j/common/net/ParsedIRI.java
- core/util/src/main/java/org/eclipse/rdf4j/common/xml/XMLWriter.java
GitHub issue resolved: #1812   
* minor code cleanup
* 
*
> #1812 minor code cleanup

- compliance/solr/pom.xml
- core/sail/solr/pom.xml
GitHub issue resolved: #1836  
* updated repo url
> GH-1836 updated restlet repo reference

- core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/SailSourceBranch.java
GitHub issue resolved: #1031  
* 
* 
*
> #1031 allow flushing for SERIALIZABLE transactions

- core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleUtil.java
GitHub issue resolved: #1842  
* Send errors to logger.debug instead of using system.err.println
> GH-1842 use logger.debug instead of System.err.println

- tools/federation/src/test/java/demos/FedXWithRemoteRepositoryManager.java
GitHub issue resolved: #1555 
Just another demo snippet
> GH-1555: add example on how to use FedX with RemoteRepositoryManager

- core/sail/federation/src/main/java/org/eclipse/rdf4j/runtime/RepositoryManagerFederator.java
- core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/Federation.java
- core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/algebra/package-info.java
- core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/config/FederationConfig.java
- core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/config/FederationFactory.java
- core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/config/package-info.java
- core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/evaluation/package-info.java
- core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/optimizers/FederationJoinOptimizer.java
- core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/optimizers/package-info.java
GitHub issue resolved: #1554  
* marked old federation sail and related packages as deprecated
> Gh 1554 deprecate federationsail

- printTestResults.sh
Script for printing test results.
> print test results

- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSailConnection.java
GitHub issue resolved: #1927   
* use SailConnection instead of NotifyingSailConnection where possible
* use Sail instead of MemoryStore where possible
*
> #1927 use SailConnection where possible in ShaclSail

- core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/SailSourceConnection.java
GitHub issue resolved: #1932  
* enum for: all, inferredOnly, explicitOnly
* use inferredOnly branch when getting statements to delete
*
> #1932 faster clearInferred(...)

- core/rio/jsonld/pom.xml
- core/rio/pom.xml
- pom.xml
GitHub issue resolved: #1936  
* moved httpcomponents exclusions to root pom
* removed unused test-jar dependency
* some cleanup
> GH-1936 clean up json-java deps and exclusions

- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSail.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/planNodes/UnBufferedPlanNode.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/results/ModelInterface.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/AbstractShaclTest.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/Utils.java
GitHub issue resolved: #1954  
* list all files/dirs instead of testing if a file/dir exists
* removed an assert that stops inlining
* skip inference on empty shacl sail
> #1954 make ShaclSail tests faster

- pom.xml
GitHub issue resolved: #1972  
* Upgrade to spring 5.2.4
> GH-1972-spring

- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/GroupIterator.java
- core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/GroupIteratorTest.java
- testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ComplexSPARQLQueryTest.java
- original behavior was correct: GH-1978 is not a bug
- used opportunity to clean up implementation flow
- added additional unit and compliance tests
GitHub issue resolved: #1978
> GH-1978 cleaned up aggregate processing

- core/rio/turtle/src/test/java/org/eclipse/rdf4j/rio/turtle/ArrangedWriterTest.java
GitHub issue resolved: #1986  
* Use line separator when comparing output
> Gh 1986 arrangedwritertest crlf

- core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/SPARQLConnection.java
- core/repository/sparql/src/test/java/org/eclipse/rdf4j/repository/sparql/SPARQLConnectionTest.java
GitHub issue resolved: #1960  
* check if transaction string is not empty before sending update
* added regression test
> GH-1960 treat commit as no-op if no updates in the txn

- release.sh
> GH-1995 make sure pull request targets develop branch

- core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/optimizers/EvaluationStatistics.java
- core/sail/federation/src/test/java/org/eclipse/rdf4j/sail/federation/optimizers/CardinalityTest.java
GitHub issue resolved: #1873 
* reassigned the `vars` list (list -> set -> list) so that it contains only distinct elements
* added a new package `optimizers` under `core/sail/federation/src/test/java/org/eclipse/rdf4j/sail/federation` as suggested by @hmottestad 
* added tests in a new file, `CardinalityTest.java` in the package `optimizers`, also added the header comment in the new file
> GH-1873 fixing incorrect cardinality calculation

- compliance/model/pom.xml
- core/rio/hdt/pom.xml
- core/rio/pom.xml
- core/sail/elasticsearch-store/pom.xml
- core/sail/elasticsearch-store/src/main/java/org/eclipse/rdf4j/sail/elasticsearchstore/ElasticsearchStore.java
- core/sail/extensible-store/pom.xml
- core/sail/extensible-store/src/main/java/org/eclipse/rdf4j/sail/extensiblestore/ExtensibleSailStore.java
- core/sail/extensible-store/src/main/java/org/eclipse/rdf4j/sail/extensiblestore/ExtensibleStore.java
- pom.xml
GitHub issue resolved: #1784  
* make druid-hll "provided" because I didn't do a CQ for transitive dependencies
* 
*
> GH-1784 make druid-hll "provided" because I didn't do a CQ for transitive dependencies

- pom.xml
GitHub issue resolved: #1975  
* Use OpenCSV 4.6 instead of 4.3.2
* Apache Commons Text and Lang3 upgrade
---- 
> GH-1975 upgraded apache commons and opencsv

- README.md
Some editorial changes to the README to give clearer build/test instructions. 
---- 
> Extended instructions on how to build the project

- compliance/repository/pom.xml
- core/model/src/main/java/org/eclipse/rdf4j/model/util/Models.java
- core/model/src/test/java/org/eclipse/rdf4j/model/util/ModelsTest.java
- pom.xml
GitHub issue resolved: #1982  
Briefly describe the changes proposed in this PR: 
Various small fixes to maven and the build.
---- 
> GH-1982 fix duplicate dependency and several IntelliJ-specific build issues

- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/AST/PropertyShape.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/MinCountBenchmarkEmpty.java
- core/sail/shacl/src/test/resources/shaclMinCountZero.ttl
GitHub issue resolved: #2123 
---- 
> Gh 2123 min count zero

- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/QueryModelNode.java
> GH-2069 forgot to add default methods to inferface

- core/sail/extensible-store/pom.xml
- core/sail/extensible-store/src/main/java/org/eclipse/rdf4j/sail/extensiblestore/ExtensibleStore.java
- core/sail/extensible-store/src/main/java/org/eclipse/rdf4j/sail/extensiblestore/evaluationstatistics/DynamicStatistics.java
- core/sail/extensible-store/src/main/java/org/eclipse/rdf4j/sail/extensiblestore/evaluationstatistics/ExtensibleDynamicEvaluationStatistics.java
- tools/runtime-osgi/pom.xml
GitHub issue resolved: #2137  
Changed which HyperLogLog implementation we use and also modified how the staleness is calculated.
---- 
> GH-2137 Use cnet.agkn.hll instead of druid-hll

- core/queryresultio/api/src/main/java/org/eclipse/rdf4j/query/resultio/QueryResultWriter.java
- core/rio/api/src/main/java/org/eclipse/rdf4j/rio/RDFWriter.java
This gives us leeway to modify the design later, also with discussion on
issue GH-1942 in mind.
GitHub issue resolved: #400 
---- 
> GH-400 marked new method in RDFWriter as experimental/internal

- core/repository/api/src/main/java/org/eclipse/rdf4j/repository/RepositoryConnection.java
GitHub issue resolved: #1762 
---- 
> GH-1762 added note about namespaces to javadoc for export methods

- compliance/elasticsearch/pom.xml
- compliance/solr/pom.xml
- compliance/solr/solr/cores/embedded/conf/solrconfig.xml
- core/sail/elasticsearch-store/src/test/java/org/eclipse/rdf4j/sail/elasticsearchstore/ClientWithStats.java
- core/sail/elasticsearch-store/src/test/java/org/eclipse/rdf4j/sail/elasticsearchstore/TestHelpers.java
- core/sail/lucene/pom.xml
- pom.xml
GitHub issue resolved: #2015 
* bump versions for Solr, Lucene and Elasticsearch
* implement new method (abstract class has changed in ES)
---- 
> GH-2015 solr elastic upgrade

- pom.xml
GitHub issue resolved: #2203 
* upgrade slf4j dependency
---- 
> GH-2203 use slf4j 1.7.30

- core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLParserTest.java
GitHub issue resolved: #2189 
* Re-added import that was used after all
---- 
> GH 2189 fix import

- core/model/src/main/java/org/eclipse/rdf4j/model/impl/DynamicModel.java
- core/model/src/test/java/org/eclipse/rdf4j/model/DynamicModelConcurrentModificationAndUpgradeTest.java
GitHub issue resolved: #2211 
---- 
> GH-2211 add more latches and loop to reduce chance of flaky failure

- pom.xml
> GH-2259 don't validate on standard run

- core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/core/query/ModifyQueryTest.java
- core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/examples/updatespec/Section3Test.java
GitHub issue resolved: #1481 
We added a test that shows how the query described in #1481 can be run using SPARQLBuilder
---- 
> GH-1481 accept graph patterns in DELETE WHERE updates

- core/rio/rdfxml/src/main/java/org/eclipse/rdf4j/rio/rdfxml/SAXFilter.java
- core/rio/rdfxml/src/test/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParserTest.java
- core/rio/rdfxml/src/test/resources/org/eclipse/rdf4j/rio/rdfxml/rdfxml-namespace-addition.rdf
GitHub issue resolved: #543  
According to the suggestions on our PR #2280 we have cherry-picked the commits related to this issue and made the required changes.
---- 
> GH-543 rdfxml rdf parse type literal

- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/GroupIterator.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/util/ValueComparator.java
- core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/GroupIteratorTest.java
- core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/util/ValueComparatorTest.java
Signed-off-by: SakshiSaini17092 <sakshi17092@iiitd.ac.in>
GitHub issue resolved: #1033 
I changed the Compare method of the Aggregrate Method min/max
---- 
> GH-1033: Changed the Compare Method of Aggregrate

- .github/workflows/develop-status.yml
- .github/workflows/master-status.yml
- .github/workflows/pr-verify.yml
GitHub issue resolved: #2331 
---- 
> GH-2331 Github CI Java 14

- compliance/rio/src/test/java/org/eclipse/rdf4j/rio/n3/N3ParserTest.java
- core/rio/n3/src/main/java/org/eclipse/rdf4j/rio/n3/N3Parser.java
- core/rio/n3/src/main/java/org/eclipse/rdf4j/rio/n3/N3ParserFactory.java
- core/rio/n3/src/test/java/org/eclipse/rdf4j/rio/n3/N3ParserTest.java
GitHub issue resolved: #1913 
- replacing PR #2278 with a minor change to the unit test
---- 
> GH-1913 N3 owl:sameAs shorthand support

- core/model/src/main/java/org/eclipse/rdf4j/model/vocabulary/DOAP.java
GitHub issue resolved: #2360 
* added new classes / properties
* ordered java constants by name
* used a create-method (see also XSD) instead of static init block
---- 
> GH-2360 added missing DOAP classes/properties + small refactoring

- site/README.md
GitHub issue resolved: #2333   
A readme file in the `site/` directory with some pointers about Hugo.
> GH-2333 readme file specifically for website editing

- examples/pom.xml
- examples/src/main/java/org/eclipse/rdf4j/examples/function/ExistingPalindromeFunction.java
- pom.xml
- site/content/documentation/tutorials/custom-sparql-functions.md
- site/layouts/shortcodes/example.html
GitHub issue resolved: #2373 
- added code example of a function that uses `TripleSource` to inspect the database.
- added a paragraph + link in the custom function Howto
- updated pom in examples section to use RDF4J 3.3.0 (about time too, it was still on 2.ancient)
---- 
> GH-2373 update function howto and example code to show use of TripleSource

- site/content/about.md
GitHub issue resolved: #2398 
* Added link to the linkedpipes website
---- 
> GH-2398 added link to linkedpipes

- core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/ArrangedWriter.java
- core/rio/turtle/src/test/java/org/eclipse/rdf4j/rio/turtle/ArrangedWriterTest.java
GitHub issue resolved: #2324 
---- 
> GH-2324 inlining blank nodes

- site/content/documentation/programming/repository.md
- site/static/css/rdf4j.css
> hot fix missing commits from rdf4j-docs

- site/content/download.md
- site/content/news/rdf4j-331.md
- site/content/release-notes/3.3.0.md
- site/content/release-notes/3.3.1.md
GitHub issue resolved: #2424 
- news item, release notes, and download links for the 3.3.1 release
---- 
> GH-2424 release notes, download, and news item for 3.3.1

- core/model/src/main/java/org/eclipse/rdf4j/model/Statement.java
- core/model/src/main/java/org/eclipse/rdf4j/model/Triple.java
- core/model/src/main/java/org/eclipse/rdf4j/model/util/Statements.java
- core/model/src/test/java/org/eclipse/rdf4j/model/util/StatementsTest.java
- site/content/documentation/programming/rdfstar.md
- site/layouts/shortcodes/javadoc.html
GitHub issue resolved: #2430 
- simple conversion utility functions as a lightweight solution
- added necessary tests and fixed some javadocs
---- 
> GH-2430 added utility method for conversion between Statements and Triples

- core/sail/extensible-store/pom.xml
- core/sail/extensible-store/src/main/java/org/eclipse/rdf4j/sail/extensiblestore/ReadCache.java
- core/sail/nativerdf/pom.xml
- core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/datastore/IDFile.java
- pom.xml
GitHub issue resolved: #2475  
- replaced internal use of commons-collections with guava
- removed dependencies on commons-collections
---- 
> GH-2475 replace commons collections

- pom.xml
GitHub issue resolved: #2490 
---- 
> GH 2490 JTS upgrade

- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSail.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/Utils.java
GitHub issue resolved: #2492 
- faster shacl tests
---- 
> GH-2492 improve shacl test performance

- release.sh
- site/content/download.md
- site/content/news/rdf4j-341.md
- site/content/release-notes/3.4.1.md
GitHub issue resolved: #2506  
- release notes + news
- fixed minor typo in release script
---- 
> GH-2506 release notes and announcement for 3.4.1

- pom.xml
GitHub issue resolved: #2528  
Briefly describe the changes proposed in this PR: bump version to 0.13.2
---- 
> GH-2528 upgrade jsonld-java dependency

- site/content/download.md
- site/content/news/performance-in-3.2.md
- site/content/news/rdf4j-342.md
- site/content/release-notes/3.4.2.md
- site/layouts/_default/index.html
- site/layouts/release-notes/list.html
- site/static/css/rdf4j.css
GitHub issue resolved: #2522 
release notes, download links, and news item for RDF4J 3.4.2.
---- 
> GH-2522 release notes 3.4.2

- site/content/news/hacktoberfest.md
GitHub issue resolved: #2540 
Brief news item about Hacktoberfest with links to signup and to relevant points for getting started with RDF4J contributions.
---- 
> GH-2540 Hacktoberfest news item

- pom.xml
GitHub issue resolved: #2548 
patch release updates of Apache HTTP Components and Core
---- 
> GH-2548 upgraded HTTP client and components

- pom.xml
GitHub issue resolved: #2550 
Upgrade to spring 5.2.9 (patch upgrade)
---- 
> GH-2550 update spring dependency

- pom.xml
GitHub issue resolved: #2553  
Upgrade to 2.10.5, since it may fix a JSON  issue in rare circumstances (https://github.com/FasterXML/jackson-core/issues/616)
---- 
> GH-2553 upgrade jackson dependency

- .github/workflows/develop-status.yml
- .github/workflows/master-status.yml
- .github/workflows/pr-verify.yml
- core/sail/sail-spin/src/test/java/org/eclipse/rdf4j/sail/spin/SpinSailTest.java
- core/sail/sail-spin/src/test/java/org/eclipse/rdf4j/sail/spin/SpinSailWithoutRDFSInferencerTest.java
- core/spin/src/main/java/org/eclipse/rdf4j/spin/function/SpinxFunction.java
- core/spin/src/main/java/org/eclipse/rdf4j/spin/function/SpinxFunctionParser.java
- pom.xml
Signed-off-by: hmottestad <hmottestad@gmail.com>
GitHub issue resolved: #2544  
Support Java 15.
---- 
> GH-2544 Java 15

- pom.xml
GitHub issue resolved: #2555  
- Several (minor) updates of apache commons dependencies
---- 
> Upgraded apache commons dependencies

- site/content/documentation/programming/shacl.md
GitHub issue resolved: #2567 
Update docs.
---- 
> GH-2567 update documentation on how to update or clear the shacl shapes

- core/model/src/main/java/org/eclipse/rdf4j/model/Triple.java
Signed-off-by: Alessandro Bollini <22@metreeca.com>
GitHub issue resolved: #2564 
- added interface-level contracts for `Triple.equals()/.hashCode()` methods
- added interface-level interoperability warning related to `Triple.equals()/.hashCode()` contracts
---- 
> Specify Triple.equals()/.hashCode() implementation

- site/content/news/rdf4j-343.md
News item for the 3.4.3 release (not linked to an issue because we forgot to create one)
> news item for 3.4.3 release

- site/content/documentation/developer/squashing.md
- site/content/documentation/programming/spin.md
- site/layouts/shortcodes/info.html
- site/layouts/shortcodes/warning.html
GitHub issue resolved: #2593  
- added step-by-step example of squashing
- added some tips on how to keep things clean to make your life easier
- added a section on using rebase instead of merge to keep your branch up to date
----
> GH-2593 more explanation about squashing, rebasing, and clean commits

- site/content/documentation/tools/server-workbench.md
GitHub issue resolved: #1121 
----
> GH-1121 Add list of repository types

- site/content/documentation/programming/repository.md
Signed-off-by: Jonathan Bisson <bjonnh-eclipse@bjonnh.net>
GitHub issue resolved: #2602 
Corrected an error in a link of the documentation.
----
- [NA] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change
> GH-2602 Correcting wrong link in documentation.

- site/content/documentation/tools/server-workbench.md
GitHub issue resolved: #2620  
----
> GH-2620 added paragraph on systemd and tomcat

- core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/Changeset.java
- core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/SailDatasetImpl.java
- core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/SailDatasetTripleSource.java
- core/sail/elasticsearch-store/src/test/java/org/eclipse/rdf4j/sail/elasticsearchstore/compliance/ElasticsearchStoreConnectionTest.java
- core/sail/federation/src/test/java/org/eclipse/rdf4j/sail/federation/FederationConnectionTest.java
- core/sail/inferencer/src/test/java/org/eclipse/rdf4j/sail/inferencer/fc/CustomGraphQueryInferencerRepositoryConnectionTest.java
- core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/MemorySailStore.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/MemoryStoreConnectionTest.java
- core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/NativeStoreConnectionTest.java
- core/sail/sail-spin/src/test/java/org/eclipse/rdf4j/sail/spin/SpinRDFSMemoryRepositoryConnectionTest.java
- testsuites/repository/src/main/java/org/eclipse/rdf4j/repository/RDFStarSupportTest.java
- testsuites/repository/src/main/java/org/eclipse/rdf4j/repository/RepositoryConnectionTest.java
GitHub issue resolved: #2604  
- fixed transactional handling of RDF* triple retrieval in Memory Store
----
> GH-2604 rdfstar transaction bug

- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/AST/AndPropertyShape.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/AST/OrPropertyShape.java
GitHub issue resolved: GH-2632 
----
> GH-2632 performance fix

- site/content/download.md
- site/content/news/rdf4j-344.md
- site/content/release-notes/3.4.4.md
> release notes 3.4.4

- core/client/pom.xml
GitHub issue resolved: #2648  
See title
----
> GH-2648 add model-api and model-vocabulary

- tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXConnection.java
- tools/federation/src/main/java/org/eclipse/rdf4j/federated/write/ReadOnlyWriteStrategy.java
- tools/federation/src/main/java/org/eclipse/rdf4j/federated/write/RepositoryWriteStrategy.java
- tools/federation/src/main/java/org/eclipse/rdf4j/federated/write/WriteStrategy.java
- tools/federation/src/test/java/org/eclipse/rdf4j/federated/write/RepositoryWriteStrategyTest.java
> Merge master develop

- site/content/download.md
- site/content/news/rdf4j-350.md
- site/content/release-notes/3.5.0.md
GitHub issue resolved: #2547 
First draft, incomplete 
----
> GH-2547 release notes for 3.5.0

- pom.xml
> fix for ossrh deployment of maven artifacts

- core/model/pom.xml
> removed japicmp from rdf4j-model - temporarily to fix build issue

- core/model/pom.xml
> Revert "removed japicmp from rdf4j-model - temporarily to fix build issue"

- pom.xml
- updated (patch releases) Apache HTTP Core, Jetty and Spring Framework related to potential connection issues
----
> GH 2720 apache jetty spring

- core/model/src/test/java/org/eclipse/rdf4j/model/benchmark/ValueHashBenchmark.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/QueryBindingSet.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Var.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/SortBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/SparqlOverheadBenchmark.java
- core/sail/memory/src/test/resources/benchmarkFiles/query4.qr
- core/sail/memory/src/test/resources/benchmarkFiles/query5.qr
- core/sail/memory/src/test/resources/benchmarkFiles/query6.qr
- core/util/src/main/java/org/eclipse/rdf4j/common/iteration/AbstractCloseableIteration.java
GitHub issue resolved: #2714 
Benchmarks to show overhead of BindingSet.
----
> GH-2714 benchmarks to show overhead of BindingSet

- pom.xml
GitHub issue resolved: #2726 
- bump spatial4j version 
----
> GH-2726 upgrade spatial4j

- site/content/download.md
- site/content/news/rdf4j-360m1.md
> news item and download links for 3.6.0-M1

- site/content/news/rdf4j-360m1.md
> fixed date for 3.6.0-M1 news item

- site/content/download.md
- site/content/news/rdf4j-360m2.md
> News item for 3.6.0-M2 build

- release.sh
- site/content/download.md
- site/content/news/rdf4j-351.md
- site/content/release-notes/3.5.1.md
> release notes for 3.5.1

- tools/server/src/main/webapp/styles/default/screen.css
- tools/workbench/src/main/webapp/styles/default/screen.css
Signed-off-by: Linn Aung <linnyehtutaung@gmail.com>
GH-1371 change of font-family and font-size
Signed-off-by: Linn Aung <linnyehtutaung@gmail.com>
----
> GH-1371 change of font in web gui

- compliance/model/src/test/java/org/eclipse/rdf4j/model/util/IsomorphicBenchmark.java
- compliance/model/src/test/resources/benchmark/blankNodesLarge.ttl
- Created a larger synthetic blank nodes file to show that the new algorithm is still > 100x slower
----
> Isomorphic benchmark file

- pom.xml
> GH-2806 increase amount of memory for tests as a temporary measure to fix tests failing due to running out of heap space

- core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/Changeset.java
- core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/SailSourceBranch.java
- pom.xml
GitHub issue resolved: #2829  
- new POJO class for keeping observations
- conversion to old StatementPattern for legacy code
----
> GH-2829 Optimized observations in Changeset

- scripts/release.sh
- scripts/templates/patch-release-notes.md
- site/content/download.md
- site/content/news/rdf4j-361.md
- site/content/release-notes/3.6.1.md
Javadocs, release-notes and news item for 3.6.1
> 3.6.1-release-notes

- pom.xml
GitHub issue resolved: #2899
Upgrade the version of animal:sniffer so that multi-release dependencies don't fail the check.
----
> GH-2899 Update animal:sniffer to V1.20

- pom.xml
GitHub issue resolved: #2909 
- bump spring framework version 
----
> GH-2909 bump spring framework version

- pom.xml
GitHub issue resolved: #2927 
- bump apache commons-io and commons-lang3 versions
----
> GH-2927 bump commons versions

- core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleWriter.java
- core/rio/turtle/src/test/java/org/eclipse/rdf4j/rio/turtle/TurtleWriterTest.java
GitHub issue resolved: #2932 
----
> GH-2932 blank node inlining with circular references

- core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleWriter.java
- core/rio/turtle/src/test/java/org/eclipse/rdf4j/rio/turtle/TurtleWriterTest.java
> Merge main develop

- pom.xml
GitHub issue resolved: #2943 
- upgraded guava 
(suggest to do this on main instead of develop, since it solves a potential security issue)
----
> GH-2943 upgrade guava

- site/content/download.md
- site/content/news/rdf4j-362.md
- site/content/release-notes/3.6.2.md
Javadocs, release-notes and news item for 3.6.2
> 3.6.2-release-notes

- pom.xml
GitHub issue resolved: #2981 
- re-generated javadoc for 3.6.2 release using JDK 8 to fix layout issues
- added option to pom to make sure generation with JDK9+ generates correct search links 
Note that it is necessary to actually use JDK 8 to generate this correctly - I have sofar failed to configure things so that newer javadoc tools use the old layout (even though that should apparently be possible with the `--frames` config option).
----
> GH-2981 javadoc generation

- pom.xml
GitHub issue resolved: #2930 
- upgrade jackson
----
> GH-2930 bump jackson version

- core/rio/nquads/src/main/java/org/eclipse/rdf4j/rio/nquads/NQuadsParser.java
- core/rio/nquads/src/test/java/org/eclipse/rdf4j/rio/nquads/AbstractNQuadsParserUnitTest.java
- core/rio/ntriples/src/main/java/org/eclipse/rdf4j/rio/ntriples/NTriplesParser.java
Signed-off-by: Tomas Kovachev <t.kovachev1996@gmail.com>
GitHub issue resolved: #2993 
Refactored NTriples/NQuads Parser to use a buffered reader for processing input to improve performance.
> GH-2993 Refactored NTriples/NQuads Parser to use buffering

- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSailConnection.java
GitHub issue resolved: #3002 
- start measuring time before we initialise the iterator
----
> GH-3002 Fix performance logging in the ShaclSail

- pom.xml
GitHub issue resolved: #3005 
----
> GH-3005 comment out snapshot repo clause in pom.xml

- pom.xml
GitHub issue resolved: #2707 
- bump jsonld-java dependency, which fixes a few minor issues (see https://github.com/jsonld-java/jsonld-java/blob/master/README.md#2021-03-06)
----
> GH-2707: upgrade jsonld-java dependency

- site/content/download.md
- site/content/news/rdf4j-363.md
- site/content/release-notes/3.6.3.md
Javadocs, release-notes and news item for 3.6.3
> 3.6.3-release-notes

- tools/server/pom.xml
GitHub issue resolved: #1209 
- upgrade ziplet dependency
----
> GH-1209: upgrade ziplet dependency

- site/content/about.md
- site/layouts/partials/jumbotron.html
- site/layouts/partials/nav.html
- site/layouts/partials/navbar.html
- site/layouts/partials/sidebar.html
As per feedback received at https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/26 
- add TM to logo on website
- add TM to first official occurrence of full project name
----
> add TM to logo and first official name occurrence (review feedback)

- site/config.toml
- site/content/_index.md
Minor editorial changes for the project website 
----
> adapted browser titlebar and SEO keywords

- site/content/documentation/programming/repository.md
GitHub issue resolved: #3030 
- correction for typo in title
----
> GH-3030: correction for ES title

- core/queryresultio/api/src/main/java/org/eclipse/rdf4j/query/resultio/QueryResultIO.java
GitHub issue resolved: #3044 
* correction in javadoc, no code changes
----
> GH-3044: fixed references to supported formats

- SECURITY.md
GitHub issue resolved: #3045  
- added security policy with overview of supported versions
- added reporting instructions
----
> GH-3045 add security policy

- .github/workflows/pr-verify.yml
- pom.xml
GitHub issue resolved: #3060  
- fix PR verification workflow to use caching
- force creation of new cache entry by changing the pom
----
> GH-3060 fixes github action build problems

- SECURITY.md
- site/content/download.md
- site/content/news/rdf4j-370.md
- site/content/release-notes/3.7.0.md
Javadocs, release-notes and news item for 3.7.0
> 3.7.0-release-notes

- testsuites/rio/pom.xml
> GH-2046 remove xalan dep, necessary packages are part of JDK

- site/content/release-notes/3.7.0.md
minor addition to the 3.7.0 release notes (thanks for the heads up @aschwarte10 ! )
> added upgrade note about renamed protected method

- site/content/release-notes/3.7.0.md
> Sync main develop

- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/BindingSetAssignmentInliner.java
- core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/BindingSetAssignmentInlinerTest.java
GitHub issue resolved: #3090  
- handle edge case of empty values clause
----
> GH-3090 fix NoSuchElementException on empty VALUES clause

- site/content/download.md
- site/content/news/rdf4j-371.md
- site/content/release-notes/3.7.1.md
Javadocs, release-notes and news item for 3.7.1
> 3.7.1-release-notes

- pom.xml
GitHub issue resolved: #3125
----
> GH-3125: upgrade commons io and codec

- pom.xml
GitHub issue resolved: #3138 
- bump Jetty version to fix CVEs
----
> GH-3138: bump jetty version

- pom.xml
GitHub issue resolved: #3136 
- bump version to 1.7.31
----
> GH-3136: bump slf4j version

- site/content/release-notes/4.0.0.md
I've opened a branch with a draft release notes document. I suggest we all add upgrade points to this as we go, preferable as soon as we merge our fixes. It's easier to update this when the change you've made is still fresh than it is if we have to scramble to get the release done in a few months from now :)
> Release notes 4.0.0

- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/ClassConstraintComponent.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/targets/TargetClass.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/AbstractShaclTest.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/ShaclTestWithoutRdfsReasoner.java
- core/util/src/main/java/org/eclipse/rdf4j/common/iteration/UnionIteration.java
- pom.xml
resolving merge conflict on jetty version
> Merge main into develop (conflict)

- pom.xml
GitHub issue resolved: #3173  
- bump JTS version
----
> GH-3173: upgraded JTS library

- compliance/repository/src/test/java/org/eclipse/rdf4j/repository/manager/LocalRepositoryManagerIntegrationTest.java
- compliance/repository/src/test/resources/fixtures/memory-invalid.ttl
- core/repository/manager/src/main/java/org/eclipse/rdf4j/repository/manager/LocalRepositoryManager.java
- core/repository/manager/src/test/java/org/eclipse/rdf4j/repository/manager/LocalRepositoryManagerTest.java
GitHub issue resolved: #3169  
- validate supplied Repository Config before adding into manager
----
> GH-3169 validate repository config before adding to manager

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
GitHub issue resolved: #3199 
fix mistakes in templates (unfortunately the only way I've found of debugging them is by just applying them and see if they work or not...)
----
> GH-3199 fix minor template config issues

- bom/pom.xml
GitHub issue resolved: #2992 
----
> GH-2992 remove reference to deleted serql testsuite

- pom.xml
GitHub issue resolved: #3253 
- bump japicmp version
----
> GH-3253: update japicmp dependency

- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/StatementMatcher.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/targets/TargetClass.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/StableQueryGenerationTest.java
GitHub issue resolved: #3234 
- sort the classes before generating queries
- some code cleanup and prettier queries
----
> GH-3234 stable SPARQL queries from targetClass

- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSail.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSailConnection.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/Stats.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/SimpleAbstractConstraintComponent.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/UniqueLangConstraintComponent.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/NoShapesTest.java
GitHub issue resolved: #3231 
- skip validation early if validation is disabled or we there are no shapes
----
> GH-3231 skip validation early

- site/content/download.md
- site/content/news/rdf4j-372.md
- site/content/release-notes/3.7.2.md
Javadocs, release-notes and news item for 3.7.2
> 3.7.2-release-notes

- tools/console/src/main/java/org/eclipse/rdf4j/console/command/Verify.java
GitHub issue resolved: #3259 
- use bulk validation in console
----
> GH-3259 use bulk validation in console

- pom.xml
GitHub issue resolved: #3301 
- upgrade elasticsearch library version to latest 6.8.x and lucene to latest 7.7.x  
----
> GH-3302: upgrade elasticsearch and lucene dependencies

- pom.xml
GitHub issue resolved: #3310 
- upgrade jetty dependency 
----
> GH-3310: upgraded jetty dependency

- site/content/download.md
- site/content/news/rdf4j-373.md
- site/content/release-notes/3.7.3.md
Signed-off-by: Jeen Broekstra <jeen@fastmail.com>
----
> javadocs and release notes for 3.7.3

- testsuites/sail/src/main/java/org/eclipse/rdf4j/sail/SailConcurrencyTest.java
> scale down size of large txn to avoid test failures in Github Actions

- .github/workflows/pr-verify.yml
- assembly/src/main/dist/docker/Dockerfile
- assembly/src/main/dist/docker/Dockerfile.amd64
- assembly/src/main/dist/docker/Dockerfile.arm64v8
- pom.xml
GitHub issue resolved: #2046 
GitHub issue related: #3350 
- updated some build plugins that don't work on jdk17 (versions already covered by CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20318 )
- updated base docker image to jre11 which we need because we are targeting 11 with our compiler (using the docker image is the only way I know to test that I didn't break the war file)
----
> GH-3350 update pom and docker to support jdk17

- site/content/documentation/tutorials/getting-started.md
I didn't create a GitHub issue as this change is so minute. If I still need to create an issue as part of your process, please let me know and I can create one.
> Fix typo in Getting Started guide

- pom.xml
- spring-components/pom.xml
- spring-components/rdf4j-spring/pom.xml
GitHub issue resolved: #3392 
- update spring framework and spring boot version
- use same spring and guava versions for rdf4j server and new spring components
----
> GH-3392: updated spring boot/framework etc versions in poms

- scripts/release-notes.sh
- site/content/download.md
- site/content/news/rdf4j-374.md
- site/content/release-notes/3.7.4.md
Javadocs, release-notes and news item for 3.7.4
> 3.7.4-release-notes

- spring-components/spring-boot-sparql-web/src/main/java/org/eclipse/rdf4j/http/server/readonly/QueryResponder.java
- spring-components/spring-boot-sparql-web/src/test/java/org/eclipse/rdf4j/http/server/readonly/MemoryBackedOnlySparqlApplicationTest.java
- spring-components/spring-boot-sparql-web/src/test/java/org/eclipse/rdf4j/http/server/readonly/TestSPARQLRepository.java
GitHub issue resolved: #3418
This PR fixes issue number #3418 and adds a test demonstrating the fix.
----
> GH-3418 Added custom repository test to show that issue #3418 is fixed.

- .github/workflows/develop-status.yml
GitHub issue resolved: # GH-3350
Also test develop branch with java 17.
Not yet the main branch
----
> test the develop branch with java 17 in the github action

- examples/pom.xml
- pom.xml
GitHub issue resolved: #3452 
- use latest slf4j version
- make sure example project uses same version
----
> GH-3452: upgrade slf4j dependency + align version

- spring-components/rdf4j-spring-demo/src/main/resources/logback.xml
- spring-components/rdf4j-spring-demo/src/test/java/org/eclipse/rdf4j/spring/demo/TestConfig.java
- spring-components/rdf4j-spring-demo/src/test/java/org/eclipse/rdf4j/spring/demo/dao/ArtistDaoTests.java
- spring-components/rdf4j-spring-demo/src/test/resources/logback.xml
GitHub issue resolved: #3455 
* test sources moved
* logback.xml file added so tests are silent
----
> GH-3455: Fix RDF4J Spring Demo tests

- core/common/io/src/test/java/org/eclipse/rdf4j/common/io/IOUtilTest.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/function/numeric/Rand.java
- core/sail/api/src/test/java/org/eclipse/rdf4j/sail/helpers/AbstractSailTest.java
- core/sail/lucene/src/test/java/org/eclipse/rdf4j/sail/lucene/AbstractGenericLuceneTest.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/LoadingBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/NotifyingSailBenchmark.java
- core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/LongMultithreadedTransactions.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/MultithreadedTest.java
- pom.xml
- spring-components/pom.xml
- spring-components/spring-boot-sparql-web/pom.xml
- testsuites/benchmark/src/main/java/org/eclipse/rdf4j/benchmark/QueryOrderBenchmark.java
- testsuites/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractLuceneSailTest.java
- testsuites/queryresultio/src/main/java/org/eclipse/rdf4j/query/resultio/AbstractQueryResultIOTest.java
- testsuites/repository/src/main/java/org/eclipse/rdf4j/repository/TupleQueryResultTest.java
- tools/federation/src/test/java/org/eclipse/rdf4j/federated/MediumConcurrencyTest.java
- tools/federation/src/test/java/org/eclipse/rdf4j/federated/generator/DataGenerator.java
- tools/federation/src/test/java/org/eclipse/rdf4j/federated/performance/SparqlRepositoryTest.java
- tools/pom.xml
- tools/server/src/test/java/org/eclipse/rdf4j/http/server/ProtocolIT.java
GitHub issue resolved: #3463  
----
> GH-3463 upgrade junit to 5.8.1

- site/content/documentation/programming/spring.md
- site/content/documentation/reference/_index.md
- site/content/download.md
- site/content/news/rdf4j-400-M1.md
- site/content/release-notes/4.0.0-M1.md
- site/layouts/shortcodes/javadoc-4m1.html
Javadocs and news item for 4.0.0-M1
> 4.0.0-M1 news item and docs

- site/content/news/rdf4j-400-M1.md
> fix release notes link

- compliance/elasticsearch/pom.xml
- core/sail/solr/pom.xml
GitHub issue resolved: #3504 
- upgrade dependency to 2.15 to fix vulnerability 
----
> GH-3504: security upgrade of log4j-core

- compliance/elasticsearch/pom.xml
- core/rio/ntriples/src/main/java/org/eclipse/rdf4j/rio/ntriples/NTriplesParser.java
- core/rio/ntriples/src/test/java/org/eclipse/rdf4j/rio/ntriples/AbstractNTriplesParserUnitTest.java
- core/sail/solr/pom.xml
- site/content/documentation/programming/spring.md
- site/content/documentation/reference/_index.md
- site/content/download.md
- site/content/news/rdf4j-400-M1.md
- site/content/release-notes/4.0.0-M1.md
- site/layouts/shortcodes/javadoc-4m1.html
> Merge main develop (conflict resolved)

- pom.xml
GitHub issue resolved: #3516
- upgrade logback core/classic dependency
- 
----
> GH-3516: upgrade logback dependency

- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/QueryBenchmark.java
- core/sail/memory/src/test/resources/benchmarkFiles/common-themes.qr
- core/sail/memory/src/test/resources/benchmarkFiles/different-datasets-with-similar-distributions.qr
- core/sail/memory/src/test/resources/benchmarkFiles/long-chain.qr
- core/sail/memory/src/test/resources/benchmarkFiles/lots-of-optional.qr
- core/sail/memory/src/test/resources/benchmarkFiles/minus.qr
- core/sail/memory/src/test/resources/benchmarkFiles/nested-optionals.qr
- core/sail/memory/src/test/resources/benchmarkFiles/particularly-large-join-surface.qr
- core/sail/memory/src/test/resources/benchmarkFiles/query-distinct-predicates.qr
- core/sail/memory/src/test/resources/benchmarkFiles/simple-filter-not.qr
- core/sail/memory/src/test/resources/benchmarkFiles/wild-card-chain-with-common-ends.qr
GitHub issue resolved:  GH-3521
- more query benchmarks
- some have been commented out because they are too slow
----
> GH-3521 more query benchmarks

- compliance/elasticsearch/pom.xml
GitHub issue resolved: #3504 
- upgrade to log4j 2.17.0
- 
----
> GH-3504: upgrade to log4j 2.17.0

- compliance/sparql/pom.xml
- core/sail/lmdb/pom.xml
- core/sail/shacl/pom.xml
- spring-components/spring-boot-sparql-web/pom.xml
GitHub issue resolved: #2710 
----
> GH-2710 remove references to old missing util modules

- site/content/about.md
GitHub issue resolved: #3549 
- add link in documentation to Oracle v21 Graph Adapter (no code changes)
- 
----
> GH-3549: added link to Oracle Graph adapter for RDF4J

- compliance/elasticsearch/pom.xml
GitHub issue resolved: #3504 
- upgrade to 2.17.1 to 
----
> GH-3504: upgrade log4j dependency to 2.17.1

- core/common/io/src/main/java/org/eclipse/rdf4j/common/io/ResourceUtil.java
- site/content/release-notes/4.0.0.md
GitHub issue resolved: #3144 
- remove unused methods
----
> GH-3144: remove unused methods

- pom.xml
GitHub issue resolved: #3535 
Version bump.
> GH-3535 Upgrade JMH to 1.33

- pom.xml
GitHub issue resolved: #3603  
----
- [] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
> GH-3603: upgrade spring version

- pom.xml
GitHub issue resolved: #3617 
- upgrade to 2.11.0 
----
- [] I've added tests for the changes I made
> GH-3617: update apache commons IO

- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/SortBenchmark.java
Signed-off-by: Håvard Ottestad <hmottestad@gmail.com>
----
> fix benchmark after merge

- bom/pom.xml
- core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbStore.java
- core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/package-info.java
- core/storage/pom.xml
- site/content/documentation/programming/lmdb-store.md
GitHub issue resolved: #3416 
- added basic setup documentation for the LMDB Store
- added native extensions to BOM for easier inclusion
@kenwenzel I'd appreciate your input on this as well, if you have time.
----
> GH-3416 LMDB documentation and pom adjustments

- site/content/documentation/programming/lmdb-store.md
- site/content/documentation/reference/_index.md
- site/content/download.md
- site/content/news/rdf4j-400-M2.md
- site/content/release-notes/4.0.0-M2.md
> news and upgrade notes for 4.0.0-M2

- site/content/news/rdf4j-400-M2.md
> fix typo in link for release notes

- core/sail/api/src/main/java/org/eclipse/rdf4j/common/concurrent/locks/AbstractReadWriteLockManager.java
- core/sail/api/src/main/java/org/eclipse/rdf4j/common/concurrent/locks/ExclusiveLockManager.java
- core/sail/api/src/main/java/org/eclipse/rdf4j/common/concurrent/locks/ReadPrefReadWriteLockManager.java
- core/sail/api/src/main/java/org/eclipse/rdf4j/common/concurrent/locks/WritePrefReadWriteLockManager.java
- core/sail/api/src/test/java/org/eclipse/rdf4j/common/concurrent/locks/ExclusiveLockManagerTest.java
- core/sail/api/src/test/java/org/eclipse/rdf4j/common/concurrent/locks/LockManagerTest.java
- core/sail/api/src/test/java/org/eclipse/rdf4j/common/concurrent/locks/LockTrackingLoggingTest.java
- core/sail/api/src/test/java/org/eclipse/rdf4j/common/concurrent/locks/MemoryAppender.java
- core/sail/api/src/test/java/org/eclipse/rdf4j/common/concurrent/locks/ReadPrefReadWriteLockManagerTest.java
- core/sail/api/src/test/java/org/eclipse/rdf4j/common/concurrent/locks/WritePrefReadWriteLockManagerTest.java
- core/sail/api/src/test/resources/logback-test.xml
GitHub issue resolved: #3636 
Added tests for all the lock managers.
----
> GH-3636 lock manger tests

- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSail.java
GitHub issue resolved: #3638 
- update example in javadoc in ShaclSail to reflect current best practice
----
> GH-3638 update example in javadoc in ShaclSail to reflect current best practice

- core/model-api/src/main/java/org/eclipse/rdf4j/model/ValueFactory.java
- core/model/src/main/java/org/eclipse/rdf4j/model/util/Values.java
- core/model/src/test/java/org/eclipse/rdf4j/model/util/ValuesTest.java
- tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/ActiveTransactionRegistry.java
- tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/Transaction.java
- tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/TransactionController.java
- fix conflicts in PR #3679
----
> Merge main into develop 

- .gitignore
- pom.xml
Signed-off-by: Håvard Ottestad <hmottestad@gmail.com>
----
> Skip sorting of XML files in hidden folders

- pom.xml
Merge main into develop with fix for merge conflict
> Merge main into develop with fix for merge conflict

- pom.xml
Related to GH-3350.
- copied updated dev-level dependencies from develop branch
----
> GH-3350 Support building on JDK 17 on the main branch

- core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbRecordIterator.java
- core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbSailStore.java
- core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbStore.java
- core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbStoreConnection.java
- core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbUtil.java
- core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/TripleStore.java
- core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/TxnRef.java
- core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/ValueStore.java
- core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/LmdbStoreErrorHandlingTest.java
GitHub issue resolved: #3644 
Adds error handling to value and triple store.
----
> GH-3644 Correctly handle internal errors in LMDB value and triple store.

- compliance/model/src/test/java/org/eclipse/rdf4j/model/util/IsomorphicTest.java
- compliance/model/src/test/resources/benchmarkFiles/GH-3671-case.ttl
- core/model/src/main/java/org/eclipse/rdf4j/model/util/GraphComparisons.java
GitHub issue resolved: #3671 
- added regression test that demonstrates problem
- increasing sha length to 256 bits fixes the issue
----
> GH-3671 isomorphism bug

- pom.xml
- scripts/release-notes.sh
- fix javadoc on jdk 12+
- fix sorting of milestones
----
> Fix release scripts

- site/content/download.md
- site/content/news/rdf4j-375.md
- site/content/release-notes/3.7.5.md
Javadocs, release-notes and news item for 3.7.5
> 3.7.5-release-notes

- core/model/src/main/java/org/eclipse/rdf4j/model/impl/SimpleValueFactory.java
- core/query/src/main/java/org/eclipse/rdf4j/query/explanation/GenericPlanNode.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/EvaluationStatistics.java
- core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java
- core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ast/JavaCharStream.java
- core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ast/SyntaxTreeBuilder.java
- core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/AbstractRDFParser.java
- core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/ValueStore.java
GitHub issue resolved: #3740 
----
> GH-3740 reduce use of UUID

- site/content/download.md
- site/content/news/rdf4j-376.md
- site/content/release-notes/3.7.6.md
Javadocs, release-notes and news item for 3.7.6
> 3.7.6-release-notes

- core/sail/api/src/main/java/org/eclipse/rdf4j/common/concurrent/locks/AbstractReadWriteLockManager.java
- core/sail/api/src/main/java/org/eclipse/rdf4j/common/concurrent/locks/Lock.java
- core/sail/api/src/main/java/org/eclipse/rdf4j/common/concurrent/locks/StampedLockManager.java
- core/sail/api/src/main/java/org/eclipse/rdf4j/common/concurrent/locks/WritePrefReadWriteLockManager.java
- core/sail/api/src/main/java/org/eclipse/rdf4j/common/concurrent/locks/diagnostics/LockCleaner.java
- core/sail/api/src/main/java/org/eclipse/rdf4j/common/concurrent/locks/diagnostics/LockMonitoring.java
- core/sail/api/src/main/java/org/eclipse/rdf4j/common/concurrent/locks/diagnostics/LockTracking.java
GitHub issue resolved: #3757 
----
> GH-3757 a LockManager based on StampedLock with an integrated cache framework

- core/model-api/src/main/java/org/eclipse/rdf4j/model/base/AbstractStatement.java
- core/query/src/main/java/org/eclipse/rdf4j/query/impl/SimpleDataset.java
- core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/Changeset.java
- core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/SailSourceBranch.java
- core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemStatementIterator.java
GitHub issue resolved: #3753 #3754 
----
> GH-3754 clear changeset on close

- core/sail/api/src/main/java/org/eclipse/rdf4j/common/concurrent/locks/StampedLockManager.java
- core/sail/api/src/main/java/org/eclipse/rdf4j/common/concurrent/locks/diagnostics/ConcurrentCleaner.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSail.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSailConnection.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/AbstractShaclTest.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/SerializableTest.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/ShapesGraphTest.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/config/ShaclSailFactoryTest.java
GitHub issue resolved: #3759 
----
> GH-3760 ShaclSail concurrent transactions deadlock

- pom.xml
GitHub issue resolved: #3759 
----
> GH-3759 maven compiler properties

- pom.xml
> Upgrade surefire / failsafe to m6

- tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/AbstractRepositoryController.java
- tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/RepositoryController.java
- tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/contexts/ContextsController.java
- tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/handler/AbstractQueryRequestHandler.java
- tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/handler/DefaultQueryRequestHandler.java
- tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/handler/DefaultRepositoryRequestHandler.java
- tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/handler/QueryRequestHandler.java
- tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/handler/RepositoryRequestHandler.java
- tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/resolver/DefaultRepositoryResolver.java
- tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/resolver/RepositoryResolver.java
GitHub issue resolved: #3769  
----
> GH-3769 make RepositoryController extensible

- core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/FileIO.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/MemoryRDFStarSupportTest.java
- testsuites/repository/src/main/java/org/eclipse/rdf4j/testsuite/repository/RDFStarSupportTest.java
Merge main into develop. Resolved conflicts.
> Merge main into develop

- scripts/milestone-release.sh
> fix milestone script

- site/content/download.md
- site/content/news/rdf4j-377.md
- site/content/release-notes/3.7.7.md
Javadocs, release-notes and news item for 3.7.7
> 3.7.7-release-notes

- site/content/download.md
- site/content/news/rdf4j-400-M3.md
- site/content/release-notes/4.0.0-M3.md
Javadocs, release-notes and news item for 4.0.0-M3
> 4.0.0-M3-release-notes

- pom.xml
GitHub issue resolved: #3802 
----
> GH-3802 upgrade logback

- core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/SailSourceConnection.java
- core/sail/inferencer/src/main/java/org/eclipse/rdf4j/sail/inferencer/fc/SchemaCachingRDFSInferencer.java
- core/sail/inferencer/src/main/java/org/eclipse/rdf4j/sail/inferencer/fc/SchemaCachingRDFSInferencerConnection.java
- core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/MemorySailStore.java
- core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/NativeStoreConnection.java
- testsuites/benchmark/src/main/java/org/eclipse/rdf4j/benchmark/ReasoningBenchmark.java
GitHub issue resolved: #3789  
- logging
- support isolation level NONE
- improve performance
- fix flushing of inferred statements in the NativeStore
- concurrent forward chaining
----
> GH-3789 RDFS Reasoner Challenge fixes

- site/content/documentation/programming/lmdb-store.md
GitHub issue resolved: #3630 
Improve the documentation for the LMDB store by describing the configuration parameters and by showing some code examples.
----
> Improve LMDB store documentation.

- .github/workflows/merge_main_to_develop.yml
GitHub issue resolved: #3851 
----
> GH-3851 update pull-request action

- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSail.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/ValidationQuery.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/Select.java
GitHub issue resolved: #3846 
- use FixedThreadPool
- mark relevant method and class as protected (also make the method non-static) so that they can be extended/overridden 
- annotate with experimental because we may want to change stuff before the next major release
----
> GH-3846 use FixedThreadPool in the ShaclSail

- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/BaseConcurrentBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/ConcurrentQueryBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/LoadingBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/MemValueFactoryConcurrentBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/NotifyingSailBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/ParallelMixedReadWriteBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/ParallelQueryBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/QueryBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/QueryWriteBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/SortBenchmark.java
> GH-3857 cleanup benchmarks

- core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/MemorySailStore.java
GitHub issue resolved: #3860 
- detect when there is less than 64MB of free RAM (with Xmx>=256MG) and stop releasing the write lock while running the snapshot cleanup in the MemoryStore
- the snapshot cleanup process already tracks what it has already cleaned to improve performance, but the HashSets used for tracking are now clearer if we have little memory
----
> GH-3860 handle high churn of memory store

- core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/TripleStore.java
(cherry picked from commit 554adee3801af9cce1fde04da5e5d56e38ba6551) 
See: https://github.com/eclipse/rdf4j/pull/3841
GitHub issue resolved: #3840 
----
> GH-3840 Fix cardinality computation of LMDB store.

- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/BenchmarkIT.java
> GH-3890 disable slow test

- site/content/download.md
- site/content/news/rdf4j-401.md
- site/content/release-notes/4.0.1.md
Javadocs, release-notes and news item for 4.0.1
> 4.0.1-release-notes

- pom.xml
GitHub issue resolved: #3905 
----
> GH-3905 adjust japicmp

- core/sail/api/src/main/java/org/eclipse/rdf4j/common/concurrent/locks/diagnostics/LockTracking.java
GitHub issue resolved: #3921 
----
> GH-3921 synchronize on map when iterating

- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/StatementMatcher.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/targets/RSXTargetShape.java
GitHub issue resolved: #3904 
- Remove assertions and add a "max" variable to keep track of the highest counter used by any StableRandomVariableProvider
----
> GH-3904 fix main by improving StableRandomVariableProvider.normalize(...)

- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/BaseConcurrentBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/ConcurrentQueryBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/LoadingBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/MemValueFactoryConcurrentBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/NotifyingSailBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/ParallelMixedReadWriteBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/QueryBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/QueryWriteBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/SortBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/SparqlOverheadBenchmark.java
Related to #3857 
- copy benchmarks from develop branch to allow us to compare performance accurately
----
> GH-3857 copy benchmarks from develop branch to allow us to compare performance accurately

- site/content/download.md
- site/content/news/rdf4j-402.md
- site/content/release-notes/4.0.2.md
Javadocs, release-notes and news item for 4.0.2
> 4.0.2-release-notes

- core/sail/api/src/main/java/org/eclipse/rdf4j/common/concurrent/locks/AbstractReadWriteLockManager.java
- core/sail/api/src/main/java/org/eclipse/rdf4j/common/concurrent/locks/WritePrefReadWriteLockManager.java
- core/sail/api/src/test/java/org/eclipse/rdf4j/common/concurrent/locks/AbstractReadWriteLockManagerTest.java
- core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/Changeset.java
- core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/SailSink.java
- core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/SailSourceBranch.java
- core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/MemorySailStore.java
- core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemStatementIteratorCache.java
- core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemValueFactory.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/BaseConcurrentBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/ParallelMixedReadWriteBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/ParallelQueryBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/QueryBenchmark.java
- core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/MemoryOverflowModel.java
- core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/NativeSailStore.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/ParallelBenchmark.java
GitHub issue resolved: #3855 
----
> GH-3855 changeset performance

- about.md
- core/sail/lmdb/pom.xml
- pom.xml
GitHub issue resolved: #3931 
- include LWJGL LMDB native extensions 
- add license blurb to about.md
----
> GH-3931 include lmdb native extensions for distribution

- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/targets/EffectiveTarget.java
GitHub issue resolved: #4001 
- check if there actually are any removed statements before we decide to use the more complex target retrieval that considers removed statements
----
> GH-4001 Optimize EffectiveTarget

- spring-components/spring-boot-sparql-web/README.md
GitHub issue resolved: #GH-4005
Fix two small issues in the spring boot web component documentation,
----
> Gh 4005 spring boot documentation fixes

- core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemIRI.java
GitHub issue resolved: #4012 
----
> GH-4012 use toStringCache in MemIRI .equals(...) 

- core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/UnionSailDataset.java
- core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/UnionSailSource.java
- core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/MemorySailStore.java
- core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemStatementList.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/SnapshotMonitorTest.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/ParallelMixedReadWriteBenchmark.java
- testsuites/repository/src/main/java/org/eclipse/rdf4j/testsuite/repository/TupleQueryResultTest.java
GitHub issue resolved: #3998 
----
> GH-3998 snapshot monitoring performance

- core/sail/api/src/main/java/org/eclipse/rdf4j/sail/helpers/AbstractSailConnection.java
- core/sail/extensible-store/src/main/java/org/eclipse/rdf4j/sail/extensiblestore/ExtensibleStoreConnection.java
- core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbStoreConnection.java
- core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/MemoryStoreConnection.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/MemTripleSourceTest.java
- core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/NativeStoreConnection.java
GitHub issue resolved: #3996 
----
> GH-3996 Reduce locking in AbstractSailConnection

- core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java
- core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLParserTest.java
GitHub issue resolved: #4014 
----
> GH-4014 handle function over var declared in group by

- scripts/release.sh
- site/content/download.md
- site/content/news/rdf4j-403.md
- site/content/release-notes/4.0.3.md
> 4.0.3 release notes

- core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/SailSourceBranch.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/MultithreadedTest.java
GitHub issue resolved: #4030 
- make `pending` synchronized so we can check if we need to remove the current `Changeset` when closing it.
----
> GH-4030 fix for potential deadlock

- spring-components/spring-boot-sparql-web/src/main/java/org/eclipse/rdf4j/http/server/readonly/EvaluateResultHttpResponse.java
- spring-components/spring-boot-sparql-web/src/main/java/org/eclipse/rdf4j/http/server/readonly/QueryResponder.java
- spring-components/spring-boot-sparql-web/src/main/java/org/eclipse/rdf4j/http/server/readonly/sparql/EvaluateResult.java
- spring-components/spring-boot-sparql-web/src/main/java/org/eclipse/rdf4j/http/server/readonly/sparql/QueryTypes.java
- spring-components/spring-boot-sparql-web/src/main/java/org/eclipse/rdf4j/http/server/readonly/sparql/SparqlQueryEvaluator.java
- spring-components/spring-boot-sparql-web/src/main/java/org/eclipse/rdf4j/http/server/readonly/sparql/SparqlQueryEvaluatorDefault.java
GitHub issue resolved: #4004 
Briefly describe the changes proposed in this PR: See https://github.com/eclipse/rdf4j/pull/4009
----
> GH-4004 provide reusable querytypes

- site/content/download.md
- site/content/news/rdf4j-410-M1.md
Javadocs, release-notes and news item for 4.1.0-M1
> 4.1.0-M1-release-notes

- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryJoinOptimizer.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/evaluationsteps/LeftJoinQueryEvaluationStep.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/BottomUpJoinIterator.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/HashJoinIteration.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/LeftJoinIterator.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/QueryJoinOptimizer.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/QueryModelNormalizerOptimizer.java
- tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/FederationEvalStrategy.java
GitHub issue resolved: #4037 
- optimized the code
- create a new HashSet if we need to modify the set produced by the VarNameCollector
----
> GH-4037 fix for removing from VarNameCollector

- compliance/elasticsearch/pom.xml
- pom.xml
GitHub issue resolved: #4056 
----
> GH-4056 bump patch versions of dependencies

- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/util/OrderComparator.java
- testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/RepositorySPARQLComplianceTestSuite.java
- testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/tests/OrderByTest.java
GitHub issue resolved: #4020 
GitHub issue resolved: #4041 
- use try-catch to handle exception thrown by missing binding
----
> Fix for order by bug with ArrayBindingSet

- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/util/OrderComparator.java
- testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/RepositorySPARQLComplianceTestSuite.java
- testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/tests/OrderByTest.java
> Merge main into develop with fix

- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/ArrayBindingSet.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/ArrayBindingBasedQueryEvaluationContext.java
GitHub issue resolved: #4050 
----
> GH-4050 use == more in the ArrayBindingSet and also clean up some unneeded code

- scripts/release.sh
- site/content/download.md
- site/content/news/rdf4j-410.md
- site/content/release-notes/4.1.0.md
Javadocs, release-notes and news item for 4.1.0
> 4.1.0-release-notes

- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/ConjunctiveConstraintSplitterOptimizer.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/FilterOptimizer.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/ParentReferenceCleaner.java
- core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/FilterOptimizerTest.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/AbstractQueryModelNode.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Add.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/ArbitraryLengthPath.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Clear.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Copy.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Create.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Group.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/LeftJoin.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Load.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Modify.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Move.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Projection.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/ProjectionElemList.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Regex.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Service.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/StatementPattern.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/ZeroLengthPath.java
- core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilderTest.java
- testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/query/parser/sparql/manifest/SPARQLQueryComplianceTest.java
GitHub issue resolved: #4102 
----
> GH-4102 fix parent reference after optimization

- compliance/repository/src/test/java/org/eclipse/rdf4j/repository/sparql/SPARQLStoreConnectionTest.java
- core/repository/http/src/main/java/org/eclipse/rdf4j/repository/http/HTTPRepositoryConnection.java
- core/repository/sail/src/main/java/org/eclipse/rdf4j/repository/sail/SailRepositoryConnection.java
- core/sail/api/src/main/java/org/eclipse/rdf4j/sail/helpers/AbstractSailConnection.java
- core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/Changeset.java
- testsuites/repository/src/main/java/org/eclipse/rdf4j/testsuite/repository/RepositoryConnectionTest.java
- tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/Transaction.java
- tools/server/src/test/java/org/eclipse/rdf4j/http/server/RemoteRepositoryTestIT.java
GitHub issue resolved: #4126 
----
> GH-4126 clear default graph remote repo bug

- pom.xml
GitHub issue resolved: #3385 
- bump jackson version (fixing a jackson CVE issue)
----
> GH-3385-jackson-upgrade

- site/content/download.md
- site/content/news/rdf4j-411.md
- site/content/release-notes/4.0.5.md
- site/content/release-notes/4.1.1.md
Javadocs, release-notes and news item for 4.1.1
> 4.1.1-release-notes

- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/PathIteration.java
- core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java
- testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/tests/AggregateTest.java
- tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/CheckStatementPattern.java
GitHub issue resolved: #4157 
- added a test case and fixed the bug
- also some minor code cleanup
----
> GH-4157 Fix for assertion error due to Var not being cloned

- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/GroupIterator.java
- testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/tests/AggregateTest.java
GitHub issue resolved: #4175 
----
> GH-4175 backport fix from GH-4132 for aggregate SUM

- scripts/release.sh
- site/content/download.md
- site/content/news/rdf4j-412.md
- site/content/release-notes/4.1.2.md
Javadocs, release-notes and news item for 4.1.2
> 4.1.2-release-notes

- site/content/download.md
- site/content/news/rdf4j-413.md
- site/content/release-notes/4.1.3.md
Javadocs, release-notes and news item for 4.1.3
> 4.1.3-release-notes

- testsuites/sparql/src/main/resources/testcases-sparql-1.1/aggregates/sparql11-sum-02.srx
- testsuites/sparql/src/main/resources/testcases-sparql-1.1/builtin/sparql11-not-in-02.srx
- testsuites/sparql/src/main/resources/testcases-sparql-1.1/property-paths/sparql11-wildcard-cycles-04.srx
Results of some tests were incorrect and always failing when compared to actual from SPARQLQueryComplianceTests.  This PR is to patch those results.
> GH-4167 - Fixing datafiles for SPARQLQueryComplianceTest

- site/content/download.md
- site/content/news/rdf4j-420.md
- site/content/release-notes/4.2.0.md
Javadocs, release-notes and news item for 4.2.0
> 4.2.0-release-notes

- pom.xml
GitHub issue resolved: #4233 
- use latest Apache Commons Text dependency
----
> GH-4233: upgrade apache commons text dependency

- pom.xml
GitHub issue resolved: #4263 
- update jackson and jackson-databind dependency
----
> GH-4263: upgrade jackson databind dependency

- pom.xml
- spring-components/pom.xml
GitHub issue resolved: #4265 
- updated spring framework version
- updated spring boot version, to align versions of spring framework
----
> GH-4265: update spring and springboot

- scripts/milestone-release.sh
- scripts/release.sh
- site/content/download.md
- site/content/news/rdf4j-421.md
- site/content/release-notes/4.2.1.md
Javadocs, release-notes and news item for 4.2.1
> 4.2.1-release-notes

- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/GroupIterator.java
GitHub issue resolved: #Gh-4212
Change the hashcode from ^= to use the standard java of using a prime multiplied with addition for hash code generation.
----
> GH-4212 standard hashcode for groupby key

- tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/TripleSourceBase.java
- tools/federation/src/test/java/org/eclipse/rdf4j/federated/BasicTests.java
- tools/federation/src/test/resources/tests/data/data1.trig
GitHub issue resolved: #4295
Pass the set dataset into the queries created/evaluated in TripleSourceBase.
----
> GH-4295 fed x not applied dataset

- compliance/elasticsearch/src/test/java/org/eclipse/rdf4j/sail/elasticsearch/examples/ElasticsearchSailExample.java
- compliance/solr/src/test/java/org/eclipse/rdf4j/sail/solr/examples/SolrSailExample.java
- core/common/transaction/src/main/java/org/eclipse/rdf4j/common/transaction/IsolationLevels.java
- core/queryparser/api/src/main/java/org/eclipse/rdf4j/query/parser/QueryParserUtil.java
- core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/UpdateExprBuilder.java
- core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDParser.java
- core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDWriter.java
- core/rio/rdfjson/src/main/java/org/eclipse/rdf4j/rio/rdfjson/RDFJSONUtility.java
- core/rio/rdfjson/src/main/java/org/eclipse/rdf4j/rio/rdfjson/RDFJSONWriter.java
- testsuites/rio/src/main/java/org/eclipse/rdf4j/testsuite/rio/trig/TriGParserTestCase.java
- testsuites/rio/src/main/java/org/eclipse/rdf4j/testsuite/rio/turtle/TurtleParserTestCase.java
- testsuites/shacl/src/main/java/org/eclipse/rdf4j/testsuite/shacl/manifest/SHACLManifestTestSuiteFactory.java
- tools/config/src/main/java/org/eclipse/rdf4j/common/app/AppConfiguration.java
- tools/federation/src/main/java/org/eclipse/rdf4j/federated/EndpointManager.java
- tools/federation/src/main/java/org/eclipse/rdf4j/federated/QueryManager.java
- tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/SailFederationEvalStrategy.java
- tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/iterator/QueryResultIteration.java
- tools/federation/src/main/java/org/eclipse/rdf4j/federated/optimizer/ServiceOptimizer.java
- tools/federation/src/main/java/org/eclipse/rdf4j/federated/util/FilterUtils.java
- tools/workbench/src/main/java/org/eclipse/rdf4j/workbench/proxy/WorkbenchServlet.java
- tools/workbench/src/main/webapp/transformations/create-remote.xsl
- tools/workbench/src/main/webapp/transformations/template.xsl
GitHub issue resolved: #3043 
- no changes in Sesame settings / ontology etc
- fix references to Sesame in javadoc and XSLT files
----
> GH-3043 replace sesame refs

- .github/workflows/develop-status.yml
- .github/workflows/main-status.yml
- .github/workflows/pr-verify.yml
GitHub issue resolved: #4312 
- update Github Actions CI to Java 19
----
> GH-4312 update Github Actions CI to Java 19

- compliance/pom.xml
- examples/pom.xml
- pom.xml
GitHub issue resolved: #4340 
- update all plugins
- add inherited plugins to plugins management
- enforce a minimum maven version of 3.6.0
----
> GH-4340 update all plugins and enforce a minimum Maven version of 3.6.0

- core/common/iterator/src/main/java/org/eclipse/rdf4j/common/iteration/QueueIteration.java
- core/repository/http/src/main/java/org/eclipse/rdf4j/repository/http/HTTPGraphQuery.java
- core/repository/http/src/main/java/org/eclipse/rdf4j/repository/http/HTTPTupleQuery.java
- core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/query/SPARQLGraphQuery.java
- core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/query/SPARQLTupleQuery.java
- tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXConnection.java
- tools/federation/src/main/java/org/eclipse/rdf4j/federated/QueryManager.java
- tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/FederationEvalStrategy.java
- tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/SailTripleSource.java
- tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/SparqlTripleSource.java
- tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/TripleSourceBase.java
- tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/concurrent/ParallelExecutorBase.java
- tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/concurrent/ParallelTaskBase.java
- tools/federation/src/main/java/org/eclipse/rdf4j/federated/structures/FedXTupleQuery.java
- tools/federation/src/test/java/org/eclipse/rdf4j/federated/MediumConcurrencyTest.java
GitHub issue resolved: #4328 
- Resolves part of #4328
----
> GH-4328 fedx unclosed iteration (part 1)

- .github/workflows/new-issue.yml
GitHub issue resolved: #4337  
----
> GH-4337 set correct action version

- .github/workflows/new-issue.yml
See https://github.com/marketplace/actions/add-to-github-projects
GitHub issue resolved: #4337  
----
> GH-4337 correct version label for action

- .github/workflows/new-issue.yml
GitHub issue resolved: #4337  
----
> GH-4337 fix board url

- pom.xml
- spring-components/pom.xml
GitHub issue resolved: #4356 
- update Jetty, Spring and Apache HttpClient / HttpCore dependencies
----
> GH-4356 web dependencies

- tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/concurrent/ControlledWorkerScheduler.java
GitHub issue resolved: #4328 
----
> GH-4328 FedX unclosed iteration

- core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSail.java
GitHub issue resolved: #4357 
- no code changes
- remove SERQL example
- remove 'initialize()' from repository code example
- split FIXMEs
----
> GH-4357 javadoc lucenesail

- scripts/release.sh
- site/content/download.md
- site/content/news/rdf4j-423.md
- site/content/release-notes/4.2.3.md
Javadocs, release-notes and news item for 4.2.3
> 4.2.3-release-notes

- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/UnknownShapesTest.java
GitHub issue resolved: #4457 
----
> GH-4457 fix flaky UnknownShapesTest

- compliance/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/ArbitraryLengthPathTest.java
- core/model/pom.xml
- core/model/src/test/java/org/eclipse/rdf4j/model/datatypes/DateTimeTest.java
- core/model/src/test/java/org/eclipse/rdf4j/model/impl/ModelCollectionTest.java
- core/sail/extensible-store/src/test/java/org/eclipse/rdf4j/sail/extensiblestore/evaluationstatistics/EvaluationStatisticsTest.java
- core/sail/inferencer/src/test/java/org/eclipse/rdf4j/sail/inferencer/fc/MemInferencingTest.java
GitHub issue resolved: #4462
This PR migrates as much as possible without radical changes from JUnit 3 to JUnit 5.
----
> GH-4462: Migration of JUnit 3 tests to JUnit 5

- compliance/elasticsearch/pom.xml
> Revert "Bump snakeyaml from 1.26 to 2.0 in /compliance/elasticsearch"

- compliance/elasticsearch/pom.xml
- core/model-api/src/main/java/org/eclipse/rdf4j/model/base/AbstractLiteral.java
- core/queryresultio/text/src/test/java/org/eclipse/rdf4j/query/resultio/text/tsv/SPARQLTSVCustomTest.java
- core/rio/rdfxml/src/test/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParserTest.java
> Merge main develop conflicts

- site/content/download.md
- site/content/news/rdf4j-424.md
- site/content/release-notes/4.2.4.md
Javadocs, release-notes and news item for 4.2.4
> 4.2.4-release-notes

- docker/build.sh
- pom.xml
GitHub issue resolved: #4542 
----
> GH-4542 Remove automatic activation of use-sonatype-snapshots

- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/config/ShaclSailConfig.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/config/ShaclSailConfigTest.java
GitHub issue resolved: #4532 
----
> GH-4532 correctly set default shapes graphs

- pom.xml
> GH-3396 add exclusion as recommended by Erik

- scripts/milestone-release.sh
- scripts/release.sh
- site/content/download.md
- site/content/news/rdf4j-430.md
- site/content/release-notes/4.3.0.md
Javadocs, release-notes and news item for 4.3.0
> 4.3.0-release-notes

- pom.xml
GitHub issue resolved: #4588 
----
> GH-4588 update japicmp version to compare against for the next major release

- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/AbstractShaclTest.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/results/ShaclValidatorTest.java
> fix unstable test due to modifying a static field during testing

- scripts/release.sh
- site/content/download.md
- site/content/news/rdf4j-432.md
- site/content/release-notes/4.3.2.md
Javadocs, release-notes and news item for 4.3.2
> 4.3.2-release-notes

- site/content/documentation/tools/server-workbench.md
> server-workbench.md to state we need java 11

- .github/workflows/dash-license.yml
- .github/workflows/develop-status.yml
- .github/workflows/main-status.yml
- .github/workflows/pr-verify.yml
> GH-4627 update Github CI to jdk 11 & 20 (from 11 & 19)

- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/ParentReferenceChecker.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/AbstractQueryModelNode.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Projection.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/QueryRoot.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/StatementPattern.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Var.java
- core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLParserTest.java
- core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractSearchIndex.java
- core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/BindingSetCollection.java
GitHub issue resolved: #4625 
----
> GH-4625 Make all QueryModelNode serializable 

- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/BaseConcurrentBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/MemStatementListBenchmark.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/ParallelMixedReadWriteBenchmark.java
GitHub issue resolved: #4636 
----
> GH-4636 MemStatementList benchmark

- site/content/documentation/programming/shacl.md
GitHub issue resolved: #4643 
- updated SHACL documentation
----
> GH-4643 update SHACL documentation

- site/content/download.md
- site/content/news/rdf4j-433.md
- site/content/release-notes/4.3.3.md
Javadocs, release-notes and news item for 4.3.3
> 4.3.3-release-notes

- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/ParentReferenceChecker.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/DeadlockTest.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/MultithreadedTest.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/ShaclTestWithoutRdfsReasonerTest.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/TransactionalIsolationSlowIT.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/BenchmarkIT.java
GitHub issue resolved: #4661 
----
> GH-4661 fix slow tests

- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/ArrayBindingSet.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/HashJoinIteration.java
- core/sail/api/src/main/java/org/eclipse/rdf4j/sail/helpers/AbstractSailConnection.java
- core/sail/api/src/main/java/org/eclipse/rdf4j/sail/helpers/TupleExprWrapperIteration.java
GitHub issue resolved: none 
- Adds better error messages to ArrayBindingSet to help diagnose GH-4646
----
> GH-4646 add better error messages to the ArrayBindingSet

- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/lmdb.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/memory-customrule.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/memory-lucene.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/memory-rdfs-dt.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/memory-rdfs-legacy.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/memory-rdfs-lucene.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/memory-rdfs.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/memory-shacl.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/memory.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/native-customrule.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/native-lucene.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/native-rdfs-dt.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/native-rdfs-lucene.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/native-rdfs.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/native-shacl.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/native.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/remote.ttl
- core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/sparql.ttl
- tools/workbench/src/main/webapp/transformations/create.xsl
GitHub issue resolved: #4657 
----
> GH-4657 revert turtle config templates

- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/HashJoinIteration.java
- core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/CRC32.java
- core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTArray.java
- core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTArrayFactory.java
- core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTArrayLog64.java
- core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTBitmap.java
- core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTDictionary.java
- core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTDictionarySection.java
- core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTDictionarySectionFactory.java
- core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTDictionarySectionPFC.java
- core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTGlobal.java
- core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTHeader.java
- core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTParser.java
- core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTPart.java
- core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTTriples.java
- core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTTriplesSection.java
- core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTTriplesSectionBitmap.java
- core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTTriplesSectionFactory.java
- core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/VByte.java
- core/rio/hdt/src/test/java/org/eclipse/rdf4j/rio/hdt/VByteTest.java
GitHub issue resolved: #4665 
----
> GH-4665 Clean up HDT code

- core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/PathIterationTest.java
GitHub issue resolved: #4690
Fix copyright year.
> GH-4690 update copyright year

- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/ParentReferenceChecker.java
- core/sail/shacl/pom.xml
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/MultithreadedLmdbStoreIT.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/MultithreadedLmdbStoreRDFSIT.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/ComplexLargeBenchmark.java
GitHub issue resolved: #4134 
----
> GH-4134 Test LmdbStore with the ShaclSail

- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSail.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclValidator.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/Shape.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/wrapper/shape/BackwardChainingShapeSource.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/wrapper/shape/CombinedShapeSource.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/wrapper/shape/Rdf4jShaclShapeGraphShapeSource.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/AbstractShaclTest.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/results/ShaclValidatorNamedGraphTest.java
GitHub issue resolved: #4694 
----
> GH-4694 Fix support for named graphs in ShaclValidator 

- tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/ExclusiveStatement.java
> Merge main

- spring-components/spring-boot-sparql-web/src/main/java/org/eclipse/rdf4j/http/server/readonly/QueryResponder.java
GitHub issue resolved: #4574 
----
> GH-4574 minor fix

- core/collection-factory/mapdb3/pom.xml
> update to correct project version of new module

- site/content/download.md
- site/content/news/rdf4j-435.md
- site/content/release-notes/4.3.5.md
Javadocs, release-notes and news item for 4.3.5
> 4.3.5-release-notes

- scripts/milestone-release.sh
- scripts/release.sh
- scripts/templates/patch-release-notes.md
> Adjust release template and scripts

- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/DefaultEvaluationStrategy.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/evaluationsteps/ProjectionQueryEvaluationStep.java
- core/repository/sail/src/main/java/org/eclipse/rdf4j/repository/sail/SailTupleQuery.java
- tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXConnection.java
- tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/FederationEvalStrategy.java
- tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/TripleSourceBase.java
- tools/federation/src/test/java/org/eclipse/rdf4j/federated/FedXBaseTest.java
- tools/federation/src/test/java/org/eclipse/rdf4j/federated/MediumConcurrencyTest.java
- tools/federation/src/test/java/org/eclipse/rdf4j/federated/MediumConcurrencyTestIT.java
GitHub issue resolved: #4711 
----
> GH-4711 improve chances that iteration is closed on time

- pom.xml
GitHub issue resolved: #4734 
----
> GH-4734 update Maven plugins

- scripts/milestone-release.sh
- site/content/download.md
- site/content/news/rdf4j-500-M1.md
Javadocs, release-notes and news item for 5.0.0-M1
> 5.0.0-M1-release-notes

- .github/workflows/pr-verify.yml
- docker/build.sh
- pom.xml
- scripts/milestone-release.sh
- scripts/release.sh
- site/content/download.md
- site/content/news/rdf4j-500-M1.md
It looks as if our github action to automatically create a sync PR for main->develop is broken.
----
> sync main to develop (manual)

- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/ShaclProperties.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/ShaclShapeParsingException.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/Shape.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/QualifiedMaxCountConstraintComponent.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/QualifiedMinCountConstraintComponent.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/ast/ShaclPropertiesCastingTest.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/ast/ShaclPropertiesLiteralParsingTest.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/ast/ShaclPropertiesMultipleValueTest.java
GitHub issue resolved: #4754 
----
> GH-4754 improve error handling in ShaclProperties class

- core/model-vocabulary/src/main/java/org/eclipse/rdf4j/model/vocabulary/RSX.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSail.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSailConnection.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclValidator.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/ContextWithShape.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/ShaclParsingException.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/UnorderedSelect.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/ValidationTuple.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/ValuesBackedNode.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/targets/EffectiveTarget.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/wrapper/shape/BackwardChainingShapeSource.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/wrapper/shape/Rdf4jShaclShapeGraphShapeSource.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/wrapper/shape/RepositoryConnectionShapeSource.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/wrapper/shape/SailConnectionShapeSource.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/wrapper/shape/ShapeSource.java
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/AbstractShaclTest.java
- core/sail/shacl/src/test/resources/test-cases/minCount/unionDataset/invalid/case1/query1.rq
- core/sail/shacl/src/test/resources/test-cases/minCount/unionDataset/invalid/case1/report.ttl
- core/sail/shacl/src/test/resources/test-cases/minCount/unionDataset/invalid/case2/query1.rq
- core/sail/shacl/src/test/resources/test-cases/minCount/unionDataset/invalid/case2/query2.rq
- core/sail/shacl/src/test/resources/test-cases/minCount/unionDataset/invalid/case2/report.ttl
- core/sail/shacl/src/test/resources/test-cases/minCount/unionDataset/shacl.trig
- core/sail/shacl/src/test/resources/test-cases/minCount/unionDataset/valid/case1/query1.rq
- core/sail/shacl/src/test/resources/test-cases/minCount/unionDataset/valid/case1/report.ttl
- core/sail/shacl/src/test/resources/test-cases/minCount/unionDataset/valid/case2/query1.rq
- core/sail/shacl/src/test/resources/test-cases/minCount/unionDataset/valid/case2/query2.rq
- core/sail/shacl/src/test/resources/test-cases/minCount/unionDataset/valid/case2/report.ttl
- tools/federation/src/test/java/org/eclipse/rdf4j/federated/MediumConcurrencyTest.java
GitHub issue resolved: #4758 
----
> GH-4758 support for union of data graphs as well as union of shape graphs

- scripts/release-notes.sh
- site/content/download.md
- site/content/news/rdf4j-436.md
- site/content/release-notes/4.3.6.md
Javadocs, release-notes and news item for 4.3.6
> 4.3.6-release-notes

- .github/workflows/dash-license.yml
- .github/workflows/develop-status.yml
- .github/workflows/main-status.yml
- .github/workflows/pr-verify.yml
GitHub issue resolved: #4781 
----
> GH-4781 update github actions workflow to use java 21

- site/content/download.md
- site/content/news/rdf4j-437.md
- site/content/release-notes/4.3.7.md
Javadocs, release-notes and news item for 4.3.7
> 4.3.7-release-notes

- .gitignore
update git ignore in anticipation of the new end to end tests using Playwright
> update git ignore in anticipation of the new end to end tests using Playwright

- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/wrapper/shape/Rdf4jShaclShapeGraphShapeSource.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/wrapper/shape/ShapeSource.java
GitHub issue resolved: #4834 
----
> GH-4834 remove code used for debugging

- site/content/download.md
- site/content/news/rdf4j-438.md
- site/content/release-notes/4.3.8.md
Javadocs, release-notes and news item for 4.3.8
> 4.3.8-release-notes

- pom.xml
GitHub issue resolved: #4841 
----
> GH-4841 update dependencies and plugins

- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/ArrayBindingBasedQueryEvaluationContext.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/DefaultEvaluationStrategy.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/FilterIterator.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/SameTermFilterOptimizer.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/util/QueryEvaluationUtil.java
- testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/RepositorySPARQLComplianceTestSuite.java
- testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/tests/FilterScopeTest.java
GitHub issue resolved: #4769 
----
> GH-4769 Variable scoping issue with FILTER

- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSailConnection.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclValidator.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShapeValidationContainer.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/Shape.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/results/lazy/LazyValidationReport.java
GitHub issue resolved: #4867 
----
> GH-4867 log exceptions as warnings during parsing and validation of SHACL shapes

- site/content/download.md
- site/content/news/rdf4j-439.md
- site/content/release-notes/4.3.9.md
Javadocs, release-notes and news item for 4.3.9
> 4.3.9-release-notes

- testsuites/repository/pom.xml
- testsuites/repository/src/main/java/org/eclipse/rdf4j/testsuite/repository/TupleQueryResultTest.java
> Reduce logging when testing unclosed connections

- core/sail/elasticsearch-store/pom.xml
- pom.xml
GitHub issue resolved: #4884 
----
> GH-4884 bump maven plugin version

- compliance/sparql/src/test/java/org/eclipse/rdf4j/sail/lmdb/LmdbPARQL11UpdateComplianceTest.java
- compliance/sparql/src/test/java/org/eclipse/rdf4j/sail/lmdb/LmdbSPARQL11QueryComplianceTest.java
- core/sail/extensible-store/src/main/java/org/eclipse/rdf4j/sail/extensiblestore/ExtensibleSailSource.java
- testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/query/parser/sparql/manifest/SPARQL11UpdateComplianceTest.java
- testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/query/parser/sparql/manifest/SPARQLComplianceTest.java
- testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/tests/BuiltinFunctionTest.java
GitHub issue resolved: #4886 
----
> GH-4886 problem with use of @TestFactory and @TempDir

- core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/ValueStoreRevision.java
- core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/benchmark/QueryBenchmark.java
- core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/benchmark/QueryWriteBenchmark.java
- core/sail/lmdb/src/test/resources/benchmarkFiles/common-themes.qr
- core/sail/lmdb/src/test/resources/benchmarkFiles/different-datasets-with-similar-distributions.qr
- core/sail/lmdb/src/test/resources/benchmarkFiles/long-chain.qr
- core/sail/lmdb/src/test/resources/benchmarkFiles/lots-of-optional.qr
- core/sail/lmdb/src/test/resources/benchmarkFiles/minus.qr
- core/sail/lmdb/src/test/resources/benchmarkFiles/nested-optionals.qr
- core/sail/lmdb/src/test/resources/benchmarkFiles/particularly-large-join-surface.qr
- core/sail/lmdb/src/test/resources/benchmarkFiles/query-distinct-predicates.qr
- core/sail/lmdb/src/test/resources/benchmarkFiles/query6.qr
- core/sail/lmdb/src/test/resources/benchmarkFiles/query8-pathexpression2.qr
- core/sail/lmdb/src/test/resources/benchmarkFiles/query9.qr
- core/sail/lmdb/src/test/resources/benchmarkFiles/simple-filter-not.qr
- core/sail/lmdb/src/test/resources/benchmarkFiles/wild-card-chain-with-common-ends.qr
GitHub issue resolved: #4896 
Use same benchmarks as NativeStore and improve performance of value comparisons.
----
> GH-4896 LMDB: Update benchmarks and improve performance

- core/common/iterator/src/main/java/org/eclipse/rdf4j/common/iteration/ThreadSafeDelayedIteration.java
- core/model/src/main/java/org/eclipse/rdf4j/model/impl/GenericStatement.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/DefaultEvaluationStrategy.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/QueryJoinOptimizer.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/TupleExpr.java
- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/helpers/collectors/BGPCollector.java
GitHub issue resolved: #4894 
----
> GH-4894 revert code that is still in use by our users

- core/sail/elasticsearch-store/pom.xml
- pom.xml
GitHub issue resolved: #4910 
----
> GH-4910 update maven plugins

- core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/ValueStore.java
GitHub issue resolved: #4861 
----
> GH-4861 don't cause OOM exception when throwing IllegalArgumentException

- site/content/download.md
- site/content/news/rdf4j-4310.md
- site/content/release-notes/4.3.10.md
Javadocs, release-notes and news item for 4.3.10
> 4.3.10-release-notes

- site/content/download.md
- site/content/news/rdf4j-4311.md
- site/content/release-notes/4.3.11.md
Javadocs, release-notes and news item for 4.3.11
> 4.3.11-release-notes

- pom.xml
GitHub issue resolved: #4976 
----
> GH-4976 update eclipse dash license tool

- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/targets/RSXTargetShape.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/targets/TargetChainRetriever.java
- core/sail/shacl/src/test/resources/test-cases/class/complexTargetShape2/valid/case4/query1.rq
- core/sail/shacl/src/test/resources/test-cases/class/complexTargetShape2/valid/case4/query2.rq
- core/sail/shacl/src/test/resources/test-cases/class/complexTargetShape2/valid/case4/report.ttl
- core/sail/shacl/src/test/resources/test-cases/class/complexTargetShape2/valid/case5/query1.rq
- core/sail/shacl/src/test/resources/test-cases/class/complexTargetShape2/valid/case5/query2.rq
- core/sail/shacl/src/test/resources/test-cases/class/complexTargetShape2/valid/case5/report.ttl
GitHub issue resolved: #4993 
----
> GH-4993 check if null before using the removedStatementTarget

- core/sail/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/impl/LuceneDocument.java
- core/sail/lucene/src/test/java/org/eclipse/rdf4j/sail/lucene/impl/LuceneIndexTest.java
GitHub issue resolved: #4978 
I added the indexing of the points using the geo prefix and not only the point prefix.
----
> GH-4978 Index geosparql points using geo field

- pom.xml
upgrade dependencies with vulnerabilities
- jetty
- logback
> upgrade dependencies with vulnerabilities

- site/content/download.md
- site/content/news/rdf4j-500-M3.md
Javadocs, release-notes and news item for 5.0.0-M3
> 5.0.0-M3-release-notes

- core/collection-factory/mapdb3/pom.xml
- pom.xml
GitHub issue resolved: #5035 
----
> GH-5035 update version of mapdb and dependency manage kerby to 1.1.1 since this one has good enough license info for ClearlyDefined

- core/rio/jsonld/src/main/resources/META-INF/services/jakarta.json.spi.JsonProvider
- core/rio/jsonld/src/test/java/org/eclipse/rdf4j/rio/jsonld/JSONLDParserCustomTest.java
GitHub issue resolved: #5041 
----
> GH-5041 register glassfish implementation of Jakarta JSON with SPI

- scripts/milestone-release.sh
- scripts/release.sh
> javadocs for 5.0.0

- pom.xml
GitHub issue resolved: #5050 
Briefly describe the changes proposed in this PR: add dependency management for netty dependencies
----
> GH-5050: add netty dependency management to fix CVEs

- core/model-vocabulary/src/main/java/org/eclipse/rdf4j/model/vocabulary/DCAT.java
GitHub issue resolved: #5054  
- added DataSeries class + new properties 
----
> GH-5054: added DCAT v3 class and properties

- site/content/release-notes/5.0.1.md
GitHub issue resolved: #5073 
Briefly describe the changes proposed in this PR: added a paragraph on the CVEs fixed
> GH-5073: added note on CVEs

- scripts/release.sh
- site/content/download.md
- site/content/news/rdf4j-4313.md
- site/content/news/rdf4j-502.md
- site/content/release-notes/4.3.13.md
- site/content/release-notes/5.0.2.md
Javadocs, release-notes and news item for 5.0.2.
> 5.0.2-release-notes

- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShapeValidationContainer.java
GitHub issue resolved: #5178 
----
> GH-5178 backport of improved error message

- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/PatternConstraintComponent.java
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/PatternFilter.java
GitHub issue resolved: #5180 
----
> GH-5180 backport fix for handling of pattern in shacl

- site/content/news/rdf4j-510-M1.md
Javadocs, release-notes and news item for 5.1.0-M1
> 5.1.0-M1-release-notes

- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/UnknownShapesTest.java
> GH-5130 fix test

- .github/workflows/hugo.yml
> Setup github pages using hugo

- site/layouts/partials/head_suffix.html
> github pages with hugo

- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/LeftJoinIterator.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/ConjunctiveConstraintSplitterOptimizer.java
- testsuites/repository/src/main/java/org/eclipse/rdf4j/testsuite/repository/TupleQueryResultTest.java
GitHub issue resolved: #5247 
----
> GH-5247 LeftJoinIterator bugfix when using condition

- .github/workflows/develop-status.yml
- .github/workflows/main-status.yml
- .github/workflows/pr-verify.yml
- core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSailValidationException.java
fix ci and minor shacl caching fix
> fix ci and minor shacl caching fix

- core/rio/jsonld/pom.xml
- core/rio/jsonld/src/main/resources/META-INF/services/jakarta.json.spi.JsonProvider
GitHub issue resolved: #5233 
----
> GH-5233 use <classifier>module</classifier> to fix SPI issue

- site/content/download.md
- site/content/news/rdf4j-512.md
- site/content/release-notes/5.1.2.md
Javadocs, release-notes and news item for 5.1.2.
> 5.1.2 release notes

- core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/helpers/collectors/StatementPatternCollector.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/MemoryStoreConnectionTest.java
GitHub issue resolved: #5294 
----
> GH-5294 stack overflow sparql update

- site/content/download.md
- site/content/news/rdf4j-4316.md
- site/content/release-notes/4.3.16.md
> 4.3.16 release notes (main)

- .github/workflows/hugo.yml
> uncompress javadocs during deploy of rdf4j.org

- .github/workflows/hugo.yml
> uncompress javadocs

- core/collection-factory/mapdb3/src/main/java/org/eclipse/rdf4j/collection/factory/mapdb/MapDb3CollectionFactory.java
- core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/benchmark/QueryBenchmark.java
GitHub issue resolved: #5322 
----
> GH-5322 MapDB late init

- pom.xml
- site/content/download.md
GitHub issue resolved: #5359 
----
> GH-5359 switch from oss.sonatype.org to central.sonatype.org

- .github/workflows/merge_main_to_develop.yml
Fix GitHub ci merge main into develop
> Fix GitHub ci merge main into develop

- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/ConjunctiveConstraintSplitterOptimizer.java
- core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/FilterOptimizer.java
- core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/QueryPlanRetrievalTest.java
GitHub issue resolved: #4872 
----
> GH-4872 FilterOptimizer retains scoping of filters

- AGENTS.md
- core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/ShutdownDuringValidationIT.java
> Fix for flaky ShutdownDuringValidationIT

- .github/workflows/dash-license.yml
GitHub issue resolved: #5457  
----
> Remove Dash license workflow regression test

- core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/QueryBenchmarkTest.java
- core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/benchmark/QueryBenchmark.java
- core/sail/lmdb/src/test/resources/benchmarkFiles/multiple-sub-select.qr
- core/sail/lmdb/src/test/resources/benchmarkFiles/optional-lhs-filter.qr
- core/sail/lmdb/src/test/resources/benchmarkFiles/optional-rhs-filter.qr
- core/sail/lmdb/src/test/resources/benchmarkFiles/ordered-union-limit.qr
- core/sail/lmdb/src/test/resources/benchmarkFiles/sub-select.qr
> Add LMDB benchmarks for optional filters and complex sub-selects

- .github/workflows/copilot-setup-steps.yml
> Fix copilot-setup-steps

- core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/graphpattern/FilterExistsGraphPattern.java
- core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/core/query/ConstructQueryFilterNotExistsTest.java
GitHub issue resolved: #1503 
----
> GH-1503 Ensure filterNotExists wraps group patterns
