core/http/client/src/main/java/org/eclipse/rdf4j/http/client/RDF4JProtocolSession.java, core/http/protocol/src/main/java/org/eclipse/rdf4j/http/protocol/Protocol.java, core/repository/api/src/main/java/org/eclipse/rdf4j/repository/RepositoryConnection.java, core/repository/api/src/main/java/org/eclipse/rdf4j/repository/base/RepositoryConnectionWrapper.java, core/repository/http/src/main/java/org/eclipse/rdf4j/repository/http/HTTPRepository.java, core/repository/http/src/main/java/org/eclipse/rdf4j/repository/http/HTTPRepositoryConnection.java, core/repository/sail/src/main/java/org/eclipse/rdf4j/repository/sail/SailRepositoryConnection.java, core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/SPARQLConnection.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/PrepareCommitTest.java, testsuites/repository/src/main/java/org/eclipse/rdf4j/repository/optimistic/SerializableTest.java, tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/RepositoryConfigRepository.java, tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/Transaction.java, tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/TransactionController.java
GitHub issue resolved: #2675  
- added RepositoryConnection.prepare and implementations in core classes
- added handling over remote protocol
- added tests, including a SHACL-specific use case test
----
=> GH-2675 add new RepositoryConnection.prepare method

core/model-api/src/main/java/org/eclipse/rdf4j/model/Triple.java, core/model-api/src/main/java/org/eclipse/rdf4j/model/ValueFactory.java, core/model/src/main/java/org/eclipse/rdf4j/model/util/Literals.java, core/model/src/main/java/org/eclipse/rdf4j/model/util/Statements.java, core/model/src/main/java/org/eclipse/rdf4j/model/util/Values.java, core/model/src/test/java/org/eclipse/rdf4j/model/util/ValuesTest.java, examples/pom.xml, examples/src/main/java/org/eclipse/rdf4j/examples/model/Example01BuildModel.java, examples/src/main/java/org/eclipse/rdf4j/examples/model/Example02BuildModel.java, examples/src/main/java/org/eclipse/rdf4j/examples/model/Example03LiteralDatatypes.java, examples/src/main/java/org/eclipse/rdf4j/examples/model/Example04LanguageTags.java, examples/src/main/java/org/eclipse/rdf4j/examples/model/Example05BlankNode.java, examples/src/main/java/org/eclipse/rdf4j/examples/model/Example06WriteRdfXml.java, examples/src/main/java/org/eclipse/rdf4j/examples/model/Example07WriteTurtle.java, examples/src/main/java/org/eclipse/rdf4j/examples/model/Example08ReadTurtle.java, examples/src/main/java/org/eclipse/rdf4j/examples/model/Example09Filter.java, examples/src/main/java/org/eclipse/rdf4j/examples/model/Example10PropertyValues.java, examples/src/main/java/org/eclipse/rdf4j/examples/model/Example11SinglePropertyValue.java, examples/src/main/java/org/eclipse/rdf4j/examples/model/Example12BuildModelWithNamedGraphs.java, examples/src/main/java/org/eclipse/rdf4j/examples/model/vocabulary/EX.java, examples/src/main/java/org/eclipse/rdf4j/examples/repository/Example13AddRDFToDatabase.java, examples/src/main/java/org/eclipse/rdf4j/examples/repository/Example14AddRDFToDatabase.java, examples/src/main/java/org/eclipse/rdf4j/examples/repository/Example15SimpleSPARQLQuery.java, examples/src/main/java/org/eclipse/rdf4j/examples/repository/Example16SPARQLConstructQuery.java, pom.xml, site/content/documentation/programming/model.md, site/content/documentation/programming/repository.md, site/content/documentation/tutorials/getting-started.md
GitHub issue resolved: #1325  
- A new utility class `org.eclipse.rdf4j.model.util.Values` with static factory methods for quick creation of all value types. This allows easier code at the client end, e.g. instead of 
```java
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
IRI example =    SimpleValueFactory.getInstance().createIRI("http://www.example.org/");
```
We can now do 
```java
import org.eclipse.rdf4j.model.util.Values;
IRI example =    Values.iri("http://www.example.org/");
```
or even:
```java
import static org.eclipse.rdf4j.model.util.Values.iri;
IRI example =  iri("http://www.example.org/");
```
- The utility methods are deliberately quite strict about checking syntactic validity of input arguments (including checks …
=> GH-1325 added Values convenience functions for quick IRI, Literal, BNode, and Triple creation

tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXConnection.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/write/ReadOnlyWriteStrategy.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/write/RepositoryWriteStrategy.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/write/WriteStrategy.java, tools/federation/src/test/java/org/eclipse/rdf4j/federated/write/RepositoryWriteStrategyTest.java
GitHub issue resolved: #2678  
- implement SailConnection.setTransactionSettings in FedXConnection
- add handling to WriteStrategy
----
=> GH-2678 FedX to pass through TransactionSettings to WriteStrategy

core/http/client/src/main/java/org/eclipse/rdf4j/http/client/SPARQLProtocolSession.java
GitHub issue resolved: #2683  
- minimal fix in logging at client side, to avoid full shacl report being logged at warning level
Possible followup is to take a good hard look at how the validation report is sent in the first place, and see if we can reuse the exsitng ErrorInfo / ErrorType functionality for it somehow. 
----
=> GH-2683 avoid full SHACL report in log at warning level

core/http/client/src/main/java/org/eclipse/rdf4j/http/client/SharedHttpClientSessionManager.java, pom.xml
GitHub issue resolved: #2666 
- bump Jetty and HttpClient version
- added custom retry handler to (only) retry stale connections, which became an issue for Jetty 9.4.24+
(doesn't seem to occur that often, but is happening in federated tests)
There are different ways to solve this, but 
- retries were explicitly disabled in #647 (including omnipotent requests)
- Apache HttpClient offers the option to retry stale connections at `RequestConfig` level, but this method `setStaleConnectionCheckEnabled` has been deprecated
- another HttpClient option is a ConnectionPool with a separate monitoring thread, but this seems to add more complexity and may need additional (sizing) configuration
----
PR Author Checklist (see the [contributor …
=> GH 2666 jetty federated fix

compliance/sparql/src/test/java/org/eclipse/rdf4j/sail/federation/FederationSparqlTest.java, core/repository/api/src/main/java/org/eclipse/rdf4j/repository/RepositoryConnection.java, core/rio/api/src/main/java/org/eclipse/rdf4j/rio/RDFParser.java, core/rio/api/src/main/java/org/eclipse/rdf4j/rio/Rio.java, core/rio/api/src/test/java/org/eclipse/rdf4j/rio/BaseURIHandlingTest.java, core/rio/hdt/src/main/java/org/eclipse/rdf4j/rio/hdt/HDTParser.java, core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDParser.java, core/rio/nquads/src/main/java/org/eclipse/rdf4j/rio/nquads/NQuadsParser.java, core/rio/ntriples/src/main/java/org/eclipse/rdf4j/rio/ntriples/NTriplesParser.java, core/rio/rdfxml/src/main/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParser.java, core/rio/rdfxml/src/main/java/org/eclipse/rdf4j/rio/rdfxml/SAXFilter.java, core/rio/rdfxml/src/test/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLBaseURIHandlingTest.java, core/rio/rdfxml/src/test/resources/org/eclipse/rdf4j/rio/rdfxml/rdfxml-absolute-iris.rdf, core/rio/rdfxml/src/test/resources/org/eclipse/rdf4j/rio/rdfxml/rdfxml-relative-iris-internal-base.rdf, core/rio/rdfxml/src/test/resources/org/eclipse/rdf4j/rio/rdfxml/rdfxml-relative-iris-missing-base.rdf, core/rio/trix/src/main/java/org/eclipse/rdf4j/rio/trix/TriXParser.java, core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleParser.java, core/rio/turtle/src/test/java/org/eclipse/rdf4j/rio/turtle/TurtleBaseURIHandlingTest.java, core/rio/turtle/src/test/resources/org/eclipse/rdf4j/rio/turtle/turtle-absolute-iris.ttl, core/rio/turtle/src/test/resources/org/eclipse/rdf4j/rio/turtle/turtle-relative-iris-internal-base.ttl, core/rio/turtle/src/test/resources/org/eclipse/rdf4j/rio/turtle/turtle-relative-iris-missing-base.ttl, core/sail/sail-spin/src/test/java/org/eclipse/rdf4j/sail/spin/EvaluationModeTest.java
GitHub issue resolved: #2670  
- method overloads in Rio interfaces to allow omission of base URI when not relevant
- method overloads in RepositoryConnection interfaces to allow omission of base URI when not relevant
- clarified expectations of input arguments on Javadoc
----
=> GH-2670 baseuri optional

.github/workflows/develop-status.yml, .github/workflows/master-status.yml
- should only happen in verify/test phase
- this avoids problems with module reorg across versions
=> do not run api comparison checks in build phase

.github/workflows/develop-status.yml, .github/workflows/master-status.yml, .github/workflows/pr-verify.yml, core/model/pom.xml, core/util/pom.xml, pom.xml
GitHub issue resolved: #2711  
- fixes configuration problem / circular dependency issue in japicmp setup for rdf4j-util by making the two annotation classes exceptions
- fixes wrong version problem in japicmp setup for rdf4j-model
- reverts earlier change to github actions to skip japicmp check on build, should no longer be necessary. 
----
=> GH-2711 fix japicmp setup

core/model/src/main/java/org/eclipse/rdf4j/model/util/ModelBuilder.java, core/model/src/test/java/org/eclipse/rdf4j/model/util/ModelBuilderTest.java
GitHub issue resolved: #2260 
- replace call to deprecated method
- don't add XSD namespace when the literal is of type xsd:string
- add tests
----
=> GH-2260 don't add xsd namespace for xsd:string literals

core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/AbstractRDFParser.java, core/rio/api/src/test/java/org/eclipse/rdf4j/rio/helpers/AbstractRDFParserTest.java, core/rio/jsonld/src/test/java/org/eclipse/rdf4j/rio/jsonld/JSONLDParserCustomTest.java, core/rio/nquads/src/test/java/org/eclipse/rdf4j/rio/nquads/AbstractNQuadsParserUnitTest.java, core/rio/ntriples/src/test/java/org/eclipse/rdf4j/rio/ntriples/AbstractNTriplesParserUnitTest.java, core/rio/rdfjson/src/test/java/org/eclipse/rdf4j/rio/rdfjson/RDFJSONParserCustomTest.java, core/rio/rdfxml/src/test/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParserCustomTest.java, core/rio/trig/src/test/java/org/eclipse/rdf4j/rio/trig/TriGParserCustomTest.java, core/rio/turtle/src/test/java/org/eclipse/rdf4j/rio/turtle/CustomTurtleParserTest.java
GitHub issue resolved: #2732 
- added skolemize_origin to the list of supported settings + increase number of supported settings in various tests
- check if skolemize_origin setting has been changed
- if so, cache the parsediri (or null) in a local variable, instead of parsing the origin each and every time
- added test case
----
=> GH-2732 cache skolem IRI + added test

site/content/documentation/tools/server-workbench.md
GitHub issue resolved: #2730  
- fixed rest api link
----
=> GH-2730 fix link to REST API reference

core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/QueryBindingSetTest.java
Signed-off-by: Jerven bolleman <jerven.bolleman@sib.swiss>
GitHub issue resolved: #2715 
Add new tests for the QueryBindingSet to make sure new implementations do not break existing usage.
----
=> GH-2724 Add more tests to validate behaviour of QueryBindingSet.

core/model/src/main/java/org/eclipse/rdf4j/model/util/Namespaces.java, core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/BasicParserSettings.java, core/rio/api/src/test/java/org/eclipse/rdf4j/rio/helpers/BasicParserSettingsTest.java, tools/console/src/main/java/org/eclipse/rdf4j/console/setting/Prefixes.java
GitHub issue resolved: #2737 
- Correction for documentation: default list is actually RDFa 1.1 initial context + a few others
- Moved the list from rio.helpers.BasicParserSettings to model.util.Namespaces
- Made this initial context public, so it can be reused
- Reuse it in Console
----
=> GH-2737 move RDFa prefixes to Namespaces class + use them in Console

core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java, core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLParseBenchmark.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/QueryPlanRetrievalTest.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/QueryBenchmark.java, core/sail/memory/src/test/resources/benchmarkFiles/query7-pathexpression1.qr, core/sail/memory/src/test/resources/benchmarkFiles/query8-pathexpression2.qr, testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ComplexSPARQLQueryTest.java
GitHub issue resolved: #2727  
- refactor of property path processing to a cleaner tree-visitor approach instead of a massive if-else. 
- simplified path modifier processing code (old code was still written for {min,max} syntax which is no longer supported)
- added regression test for GH-2727
To explain the main ideas behind the refactor:
A SPARQL path expression is parsed into an AST tree structure. Each path expression is a PathAlternative, consisting of one more PathSequences. Each PathSequence, in turn, consists of one or more PathElements. PathElements have optional modifiers (?, + and *), and can be either negated or inverted (or both). Note that a PathElement itself can be a nested path expression again.
In the previous code, the …
=> GH-2727 simplified path expression processing and fixed nested inverse optional handling

core/model/src/main/java/org/eclipse/rdf4j/model/util/Literals.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/util/QueryEvaluationUtil.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/util/QueryEvaluationUtilTest.java
Added test reproducing GH-2760 - an NPE in QueryEvaluationUtil.compareLiterals()
GitHub issue resolved: #2760 
Literals.getXsdDatatype() used to return Optional.empty() which the argument was not an instance of `SimpleLiteral` that cause the `QueryEvaluationUtil.compareLiterals()` to hit NPE while at least one of its arguments was not an instance of `SimpleLiteral`
Added also a test case reproducing #2760
----
=> GH-2760: fixes Literals.getXsdDatatype() to work also with custom Literal implementations

core/model/src/main/java/org/eclipse/rdf4j/model/util/Values.java, core/model/src/test/java/org/eclipse/rdf4j/model/util/ValuesTest.java
GitHub issue resolved: #2789  
- added missing factory methods for creation of language-tagged literals
- added unit tests
----
=> GH-2789 added factory methods for language-tagged literals

core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/SPARQLConnection.java, core/repository/sparql/src/test/java/org/eclipse/rdf4j/repository/sparql/SPARQLConnectionTest.java
GitHub issue resolved: #2782  
- renamed `enableSilentMode` to `setSilentClear` to make role and scope more obvious
- added javadoc documentation and an additional test
----
=> GH-2782 javadoc and rename for SPARQLCOnnection#setSilentClear

scripts/milestone-release.sh, scripts/patch-release.sh, scripts/release-notes.sh, scripts/release.sh, scripts/templates/milestone-news-item.md, scripts/templates/patch-news-item.md, scripts/templates/patch-release-notes.md
GitHub issue resolved: #2784 
- moved release scripts into new directory
- made one script for patch release and another for milestone build
- created script for generating news item and release-notes from templates
----
=> GH-2784 scripts for release, release-notes and news item

core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/MultithreadedNativeStoreTest.java
Test is failing due to running out of memory. This is just disabling said test to we can continue working.
----
=> GH-2806 disable failing test 

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/package-info.java, core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/algebra/package-info.java, core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/config/package-info.java, core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/evaluation/package-info.java, core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/optimizers/package-info.java, core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/package-info.java, core/sail/lucene-spin/src/main/java/org/eclipse/rdf4j/lucene/spin/config/package-info.java, core/sail/lucene-spin/src/main/java/org/eclipse/rdf4j/lucene/spin/package-info.java, core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/package-info.java, core/sail/model/src/main/java/org/eclipse/rdf4j/sail/model/NonSerializables.java, core/sail/model/src/main/java/org/eclipse/rdf4j/sail/model/SailModel.java, core/sail/model/src/main/java/org/eclipse/rdf4j/sail/model/package-info.java, core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/btree/package-info.java, core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/datastore/package-info.java, core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/model/package-info.java
GitHub issue resolved: #2755  
Removed use of `@deprecated` javadoc tag in `package-info.java`, and removed `@Deprecated` annotation in several places. 
(mostly did this because Eclipse considers a `@deprecated` javadoc tag in package-info an error, and it annoyed me)
----
=> GH-2755 fix javadoc tags in package-info.java

pom.xml
Signed-off-by: Richard Eckart de Castilho <richard.eckart@gmail.com>
GitHub issue resolved: #2813
Added lifecycle mapping xml formatting maven plugin for Eclipse (disable plugin in Eclipse)
----
=> GH-2813 Maven lifecycle mapping errors when importing into Eclipse

README.md, site/content/documentation/programming/repository.md
GitHub issue resolved: #2822  
- replaced obsolete federation code example with redirect to FedX documentation
- fixed outdated links in main project readme
- added our logo to the readme because it looks nice
----
=> GH-2822 documentation updates and fixes to links in README

core/http/client/pom.xml, core/repository/manager/pom.xml, examples/pom.xml, pom.xml, tools/pom.xml, tools/server-spring/pom.xml
GitHub issue resolved: #2812  
- removed scope declaration for commons-codec from root pom dependencyManagement section, moved to specific dependency usages in module poms
- removed old version number for commons-codec 1.11 from tools module
----
=> GH-2812 set scope for dependencies in actual dependency, not management

compliance/rio/src/test/java/org/eclipse/rdf4j/rio/turtle/TurtleWriterInliningTest.java, core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleWriter.java
GitHub issue resolved: #2830 
- make sure we handle rdf:first predicate on a subject before others, to ensure RDF collection statements are processed in the right order
- added regression test (in compliance because we need queryalgebra classes for handling custom sorting)
----
=> GH-2830 handle rdf list statements in correct order

compliance/model/src/test/java/org/eclipse/rdf4j/model/util/IsomorphicTest.java, core/model/src/main/java/org/eclipse/rdf4j/model/util/GraphComparisons.java, core/model/src/test/java/org/eclipse/rdf4j/model/util/GraphComparisonsTest.java, core/sail/shacl/src/test/resources/test-cases/complex/targetShapeAndQualifiedShape/invalid/case1/report.ttl, core/sail/shacl/src/test/resources/test-cases/minExclusive/simple/invalid/case8/report.ttl, core/sail/shacl/src/test/resources/test-cases/qualifiedShape/complex/invalid/case1/report.ttl, core/sail/shacl/src/test/resources/test-cases/qualifiedShape/complex/invalid/case2/report.ttl, core/sail/shacl/src/test/resources/test-cases/qualifiedShape/complex/invalid/case3/report.ttl, core/sail/shacl/src/test/resources/test-cases/qualifiedShape/complex/shacl.ttl, core/sail/shacl/src/test/resources/test-cases/qualifiedShape/maxCountSimple/invalid/case1/report.ttl, core/sail/shacl/src/test/resources/test-cases/qualifiedShape/maxCountSimple/invalid/case2/report.ttl, core/sail/shacl/src/test/resources/test-cases/qualifiedShape/maxCountSimple/invalid/case3/report.ttl, core/sail/shacl/src/test/resources/test-cases/qualifiedShape/maxCountSimple/invalid/case4/report.ttl, core/sail/shacl/src/test/resources/test-cases/qualifiedShape/maxCountSimple/shacl.ttl, core/sail/shacl/src/test/resources/test-cases/qualifiedShape/minCountSimple/invalid/case1/report.ttl, core/sail/shacl/src/test/resources/test-cases/qualifiedShape/minCountSimple/invalid/case2/report.ttl, core/sail/shacl/src/test/resources/test-cases/qualifiedShape/minCountSimple/invalid/case3/report.ttl, core/sail/shacl/src/test/resources/test-cases/qualifiedShape/minCountSimple/invalid/case4/report.ttl, core/sail/shacl/src/test/resources/test-cases/qualifiedShape/minCountSimple/invalid/case5/report.ttl, core/sail/shacl/src/test/resources/test-cases/qualifiedShape/minCountSimple/shacl.ttl
GitHub issue resolved: #2843  
- hash code calculation for literals now includes language tag and datatype
----
=> GH-2843 hashcode for literals needs to include lang tag and datatype

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSail.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSailConnection.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/TransactionSettingsTest.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/ComplexLargeBenchmark.java
GitHub issue resolved: #2846  
- new transaction settings to control parallel validation and cache
- allow for settings to override Bulk validation and sail level settings
----
=> GH-2846 transaction settings to control parallel validation and cache

core/rio/api/src/main/java/org/eclipse/rdf4j/rio/RDFFormat.java, core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/BufferedGroupingRDFHandler.java, core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDParser.java, core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/ndjsonld/NDJSONLDParser.java, core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/ndjsonld/NDJSONLDParserFactory.java, core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/ndjsonld/NDJSONLDWriter.java, core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/ndjsonld/NDJSONLDWriterFactory.java, core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/ndjsonld/package-info.java, core/rio/jsonld/src/main/resources/META-INF/services/org.eclipse.rdf4j.rio.RDFParserFactory, core/rio/jsonld/src/main/resources/META-INF/services/org.eclipse.rdf4j.rio.RDFWriterFactory, core/rio/jsonld/src/test/java/org/eclipse/rdf4j/rio/ndjsonld/NDJSONLDParserHandlerTest.java, core/rio/jsonld/src/test/java/org/eclipse/rdf4j/rio/ndjsonld/NDJSONLDParserTest.java, core/rio/jsonld/src/test/java/org/eclipse/rdf4j/rio/ndjsonld/NDJSONLDWriterTest.java, core/rio/jsonld/src/test/resources/testcases/ndjsonld/mates.ndjsonld
GitHub issue resolved: #2840
Introduce NDJSONLDParser that extends the JSONLDParser. It collects each JSON-LD line from the input, puts all JSON objects in a list, flattening them if necessary and pass further to the JSON API as one single JSON object.
Introduce NDJSONLDWriter that groups triples by subject and context and writes an JSON-LD line for each group, by delegating to the JSONLDWriter.
=> GH-2840 Implement an RDFParser and RDFWriter for Newline delimited JSON-LD

site/layouts/partials/header.html
Added a little Octocat "fork me on github" corner for the main website, as a bit of fun.
----
=> Add Github :octocat: corner to top right

scripts/milestone-release.sh, scripts/release.sh, site/static/javadoc/uncompress.sh
GitHub issue resolved: #2879 
- release script adapted to create javadoc tgz files without `target/...` dir
- release script automatically updates `latest.tgz` as well
- uncompress script adapted to deal with extracting to version-specific subdir
- updated existing tgz files to conform to expected directory structure
----
=> GH-2879 javadoc tars created and extracted with correct dirs

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/MinCountConstraintComponent.java
GitHub issue resolved: #2855 
- validate against "added" before validating against the base sail
----
=> GH-2855 optimize sh:minCount when doing transactional validation

bom/pom.xml
GitHub issue resolved: #2895
- Add rdf4j-sail-extensible-store module to BOM
----
=> GH-2895 Add rdf4j-sail-extensible-store module to BOM

core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ComplexSPARQLQueryTest.java, testsuites/sparql/src/main/resources/testdata-query/dataset-construct-modifiers.ttl
Signed-off-by: Alexey Ivanov <amivanoff@gmail.com>
GitHub issue resolved: #2791
* LIMIT and OFFSET swapped before the CONSTRUCT query form
----
=> GH-2791 LIMIT and OFFSET should be applied to the solution sequence before the CONSTRUCT query form

site/content/documentation/programming/model.md, site/content/documentation/reference/rest-api.md, tools/server/src/main/webapp/swagger.yaml
Signed-off-by: Alexey Ivanov <amivanoff@gmail.com>
GitHub issue resolved: #2889
* Documentation typos in Model and REST API
* Collecting more typos
----
=> GH-2889 Documentation typos in Model and REST API

core/sail/inferencer/src/main/java/org/eclipse/rdf4j/sail/inferencer/fc/SchemaCachingRDFSInferencerConnection.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSail.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSailConnection.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/results/ValidationReport.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/DeadlockTest.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/MultithreadedMemoryStoreTest.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/MultithreadedNativeStoreRDFSTest.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/ReduceNumberOfPlansTest.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/TransactionalIsolationTest.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/ShaclLoadingBenchmark.java
GitHub issue resolved: #2756 
- Remove shapes cache in ShaclSail
- Clean up locking now that we don't have to keep a cache in sync
- Disable serializable validation (with SNAPSHOT isolation) when used with the RDFS reasoner (since this causes deadlocks)
The shapes cache was initially created back when parsing shapes was slow. Since then we have tremendously improved the performance of parsing shapes so removing the cache causes very marginal performance impacts, but it obviously depends on the number of shapes. 
----
=> GH-2756 ShaclSail + RDFS + NativeStore sometimes deadlocks

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/LeftOuterJoin.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/LoggingCloseableIteration.java
GitHub issue resolved: #2908 
- fix for LeftOuterJoin
- detect when iterators return false from hasNext() but true when called again
----
=> GH-2908 LeftOuterJoin will sometimes miss the last left element

compliance/repository/src/test/java/org/eclipse/rdf4j/repository/http/HTTPRepositoryTest.java, compliance/repository/src/test/resources/logback-test.xml, core/http/client/src/main/java/org/eclipse/rdf4j/http/client/RDF4JProtocolSession.java, core/http/client/src/main/java/org/eclipse/rdf4j/http/client/SharedHttpClientSessionManager.java, site/content/documentation/programming/repository.md
GitHub issue resolved: #2918 
- switch to CachedThreadPool executor since it has better behavior for spawning new threads as needed
- allow core threads to be terminated when keepAlive timeout has passed to conserve resources
- RDF4JProtocolSession uses a separate scheduled executor specifically for its transaction ping functionality
----
=> GH-2918 switch to CachedThreadPool to avoid deadlocks in interdependent queries

scripts/milestone-release.sh, scripts/release.sh
GitHub issue resolved: #2698  
Java 1.8 check now asks to continue instead of just exiting immediately.
----
=> GH-2698 make Java version check non-fatal

core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/NativeStore.java, core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/NativeStoreTmpDatadirTest.java, site/content/documentation/programming/repository.md
GitHub issue resolved: #2940 
- set temp data dir instead of throwing an exception (will be deleted on shutdown)
- added tests for tmp datadir, including one when re-initializing after shutdown
- corrected minor typo
- slightly improved the nativestore/memstore website documentation on amount triples + explaine use case
----
=> Gh 2940 nativestore tempdir

core/sail/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneIndex.java
GitHub issue resolved: #2958  
- allow both a Rectangle and 1-element Rectangle array (instead of checking if an instance is an array and then cast it to a non-array)
----
=> GH-2958 fix cast of rectangle shape

.github/CONTRIBUTING.md, README.md, site/content/documentation/developer/merge-strategy.md, site/content/documentation/developer/squashing.md
GitHub issue resolved: #2968  
- removed git sign-off requirement, and github link on profile in README, CONTRIBUTING, and squashing documentation. Neither are required any longer (though it's not a problem if people continue to do it either, of course).
----
=> GH-2968 remove git sign-off requirement, and github link on profile

.github/PULL_REQUEST_TEMPLATE.md
GitHub issue resolved: #2968 
Updated the PR template so that it no longer has the signoff in the checklist
----
=> GH-2968 updated PR template, removed signoff from checklist

core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/ShaclTest.java
Main SHACL test suite has been marked as integration tests even though they are the main unit tests for the ShaclSail that checks that constraints work.
----
=> main shacl tests are not integration tests

.gitignore
Signed-off-by: Jerven bolleman <jerven.bolleman@sib.swiss>
GitHub issue resolved: #2988
Add one line to the .gitignore to make it more difficult to accidentally check these files in.
----
=> GH-2988 Add eclipse annotation processor files to the .gitignore

core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/RDFJSONWriterSettings.java, core/rio/rdfjson/src/main/java/org/eclipse/rdf4j/rio/rdfjson/RDFJSONWriter.java, core/rio/rdfjson/src/test/java/org/eclipse/rdf4j/rio/rdfjson/RDFJSONStreamingWriterTest.java
GitHub issue resolved: #2957 
Reimplemented RDFJSONWriter to stream output rather than storing all statements consumed in a TreeModel before writing output.
=> GH-2957 Optimize RDFJSONWriter to stream output

core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryCostEstimatesTest.java, core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/PropertySetElem.java, core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java, core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/TestSparqlStarParser.java, core/spin/src/main/java/org/eclipse/rdf4j/spin/SpinParser.java, core/spin/src/test/java/org/eclipse/rdf4j/spin/SpinParserTest.java, core/spin/src/test/java/org/eclipse/rdf4j/spin/SpinRendererTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ComplexSPARQLQueryTest.java, tools/federation/src/test/resources/tests/optimizer/queryPlan_Join_2.txt
GitHub issue resolved: #2985  
- removed unnecessary creation of extension elements for variables that do not appear in WHERE clause
- added test case
- also did some deprecation cleanup
----
=> GH-2985 remove unnecessary addition of extension elems

core/sail/nativerdf/pom.xml, core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/SailSourceModel.java, core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/SailSourceModelTest.java, testsuites/model/src/main/java/org/eclipse/rdf4j/model/ModelTest.java
GitHub issue resolved: #2967  
- added unit test that reproduces the bug
- added additional unit tests on SailSourceModel to have better coverage/compliance
- fixed by making sure private `sink` field is not directly referenced, but only via the `sink()` method
----
=> GH-2967 fix nulllpointerexception in SailSourceModel.remove

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/EvaluationStatistics.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/ParentReferenceCleaner.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StandardQueryOptimizerPipeline.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/PathIteration.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/QueryOptimizerTest.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/BindingAssignerTest.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/CompareOptimizerTest.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/ConjunctiveConstraintSplitterTest.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/ConstantOptimizerTest.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/DisjunctiveConstraintOptimizerTest.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/EvaluationStatisticsTest.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/FilterOptimizerTest.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/IterativeEvaluationOptimizerTest.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/OrderLimitOptimizerTest.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/ParentReferenceCleanerTest.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryJoinOptimizerTest.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryModelNormalizerTest.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/RegexAsStringFunctionOptimizerTest.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/SameTermFilterOptimizerTest.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/AbstractQueryModelNode.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/GroupElem.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/helpers/QueryModelTreeToGenericPlanNode.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/QueryPlanRetrievalTest.java
GitHub issue resolved: #2187 
- ensure optimizers and other components that manipulate the algebra tree keep the parent node references consistent
- added "cleanup" at end of optimizer pipeline to catch any wrongdoers
- added regression tests for all optimizer implementations
---- 
=> GH-2187 keep parent reference in querymodelnode consistent

core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/MemoryOverflowModel.java, core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/benchmark/OverflowBenchmarkReal.java, core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/benchmark/OverflowBenchmarkSynthetic.java
GitHub issue resolved: #2799 
- initialize the LinkedHashModel with a fixed size equal to the threshold we use for overflow to disk - this should avoid unexpected resizing before overflow is triggered
- note that LinkedHashModel itself internally already uses `size * 2` for the statement set to compensate for the load factor, so using the exact block size should be fine for our purposes
----
=> GH-2799 avoid OOM through HashMap resizing by setting initial size

core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ComplexSPARQLQueryTest.java
GitHub issue resolved: #3011  
- handling of SameTerm constraints introduced for cyclic paths extended to deal with more complex expressions
- added  compliance testcase
----
=> GH-3011 fix handling of cyclic paths in construct queries

pom.xml
GitHub issue resolved: #3005  
- added snapshot repo def again by default for ease of use
- can be locally disabled if necessary by setting `-P-use-sonatype-snapshots`
----
=> GH-3005 reinstate snapshot repo def but as a profile

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/BindingSetAssignmentInliner.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StandardQueryOptimizerPipeline.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/BindingSetAssignmentInlinerTest.java
GitHub issue resolved: #3008 
- special-case fix for VALUES clause with a single value for a variable: inline where possible
----
=> GH-3008 inline VALUES clause values if possible

core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleParser.java, core/rio/turtle/src/test/java/org/eclipse/rdf4j/rio/turtlestar/TurtleStarParserTest.java
GitHub issue resolved: #2921 
- add support annotation-style Turtle-star 
- test coverage 
----
=> GH-2921 parse simple Turtle-star annotations

core/http/client/src/main/java/org/eclipse/rdf4j/http/client/SPARQLProtocolSession.java, core/http/client/src/test/java/org/eclipse/rdf4j/http/client/SPARQLProtocolSessionTest.java, core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/SPARQLRepository.java, core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/config/SPARQLRepositoryConfig.java, core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/config/SPARQLRepositoryFactory.java, core/repository/sparql/src/test/java/org/eclipse/rdf4j/repository/sparql/SPARQLRepositoryTest.java, core/repository/sparql/src/test/java/org/eclipse/rdf4j/repository/sparql/config/SPARQLRepositoryConfigTest.java, core/repository/sparql/src/test/java/org/eclipse/rdf4j/repository/sparql/config/SPARQLRepositoryFactoryTest.java
GitHub issue resolved: #2978 
- allow disabling passthrough in SPARQLProtocolSession
- add configuration option in SPARQLRepository(Config)
- added/updated unit tests
----
=> GH-2978 explicit disabling/enabling of pass-through for SPARQL endpoints

core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java, core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/TestPropPathMisbehaviour.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/MemoryStoreTest.java
- make sure the projection is not a sub-select using proper consturctor in `TupleExprBuilder`
- added test cases.
GitHub issue resolved: #3053
make use of `subselect` argument of constructor so the external bound vars are visible
----
=> Fixes GH-3053 Correct handling of zero-or-one case with sub-select.

core/http/protocol/src/main/java/org/eclipse/rdf4j/http/protocol/transaction/TransactionSAXParser.java, core/http/protocol/src/main/java/org/eclipse/rdf4j/http/protocol/transaction/TransactionWriter.java, core/http/protocol/src/main/java/org/eclipse/rdf4j/http/protocol/transaction/TransactionXMLConstants.java, core/http/protocol/src/test/java/org/eclipse/rdf4j/http/protocol/transaction/TransactionReaderTest.java
GitHub issue resolved: #3048
- persist Triple resources as base64 encoded IRI using new "triple" tag
- parse the newly introduced tag and decode the Triple from it's base64 encoded value
----
=> GH-3048 transaction writer with rdfstar

.github/workflows/pr-verify.yml, compliance/pom.xml, core/pom.xml, pom.xml
GitHub issue resolved: #3038 
- introduced new 'slowTestsOnly' profile, to be activated by the slow-tests CI job
- adjusted pr-verify CI job
- update to JUnit 5.7.2 (necessary to avoid NPE in modules that contain no slow tests)
----
=> GH-3038 run _only_ tests marked as slow in slow-tests CI job

.github/workflows/develop-status.yml, .github/workflows/main-status.yml, .github/workflows/pr-verify.yml, pom.xml
GitHub issue resolved: #2046  
- update maven compiler settings to use Java 11
- update all github action configs to use Java 11
----
=> GH-2046 use JDK 11 as the minimal java version

compliance/elasticsearch/pom.xml, compliance/geosparql/pom.xml, compliance/lucene/pom.xml, compliance/model/pom.xml, compliance/pom.xml, compliance/rio/pom.xml, compliance/serql/pom.xml, compliance/solr/pom.xml, core/http/protocol/pom.xml, core/pom.xml, core/sail/lucene-spin/pom.xml, core/sail/sail-spin/pom.xml, core/sail/solr/pom.xml, pom.xml, tools/pom.xml
GitHub issue resolved: #2739  
- use release flag on maven compiler plugin
- remove now-obsolete animal-sniffer plugin
- bumped compiler plugin version 
- api compatibility checks no longer fail the build (we'll re-enable this after 4.0 is out the door)
----
=> GH-2739 use release flag, remove obsolete animal-sniffer

.github/workflows/main-status.yml
GitHub issue resolved: #3083  
- added jdk 11 to the matrix build so that required job for merging into develop is run, unblocking PR #3082 
----
=> GH-3083 run jdk 11 build for main branch to enable sync with develop

core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/BinaryRDFWriterSettings.java, core/rio/binary/src/main/java/org/eclipse/rdf4j/rio/binary/BinaryRDFConstants.java, core/rio/binary/src/main/java/org/eclipse/rdf4j/rio/binary/BinaryRDFParser.java, core/rio/binary/src/main/java/org/eclipse/rdf4j/rio/binary/BinaryRDFWriter.java, core/rio/binary/src/test/java/org/eclipse/rdf4j/rio/binary/BinaryRDFWriterBackgroundTest.java, core/rio/binary/src/test/java/org/eclipse/rdf4j/rio/binary/BinaryRDFWriterTest.java, core/util/pom.xml, core/util/src/main/java/org/eclipse/rdf4j/common/io/IOUtil.java, core/util/src/test/java/org/eclipse/rdf4j/common/io/IOUtilTest.java, testsuites/benchmark/src/main/java/org/eclipse/rdf4j/benchmark/rio/RDFSizeBenchmarks.java, testsuites/benchmark/src/main/java/org/eclipse/rdf4j/benchmark/rio/RDFTestDataset.java
GitHub issue resolved: #3010
Added a parser and writer second version of the binary RDF format with backwards compatibility with version 1. Notable changes in this version are the default use of UTF-8, variable length integers for string lengths and value identifiers and a larger default statement queue.
----
----
=> GH-3010 improve binary rdf format

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/BindingSetAssignmentInliner.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/BindingSetAssignmentInlinerTest.java
GitHub issue resolved: #3091 
- avoid inlining values clause assignment inside an optional clause
----
=> GH-3091 do not inline values when part of right arg of leftjoin

site/content/support.md
GitHub issue resolved: #3056 
- add link to new Github Discussions forum on support page
- de-emphasize google group (a little)
=> GH-3056 add link to new Github Discussions support forum

tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/join/ControlledWorkerBoundJoin.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/join/ControlledWorkerJoin.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/join/ControlledWorkerLeftJoin.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/join/PhaserHandlingParallelExecutor.java, tools/federation/src/test/java/org/eclipse/rdf4j/federated/LargeJoinTest.java
GitHub issue resolved: #3106 
In the concurrency facilities of FedX we make use of the Java Phaser.
This is limited to 65535 registered parties.
In case of large joins (see the example test case) we were seeing errors
that the the phaser has reached limits.
This is now avoided by using tiering of phasers as suggested by the
Phaser javadocs. Note that we pass on a delegate executor control now to
call the arrive and deregister on the correct phaser instance.
----
=> GH-3106: fix large joins in FedX engine

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StrictEvaluationStrategy.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ComplexSPARQLQueryTest.java
GitHub issue resolved: #3071 
- fix corner case of binding set assignment result processing when binding is UNDEF.
- added regresssion test
- some variable renaming and code cleanup 
----
=> GH-3071 ensure bsa result iter returns result when assignment is UNDEF

core/query/src/main/java/org/eclipse/rdf4j/query/QueryResults.java, core/query/src/test/java/org/eclipse/rdf4j/query/QueryResultsTest.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StrictEvaluationStrategy.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ComplexSPARQLQueryTest.java
GitHub issue resolved: #3072  
- handle case of unbound variables in compatibility check: guard against NPE and continue processing
----
=> GH-3072 handle values clause after optional join correctly

tools/federation/src/main/java/org/eclipse/rdf4j/federated/util/QueryStringUtil.java, tools/federation/src/test/java/org/eclipse/rdf4j/federated/BasicTests.java, tools/federation/src/test/resources/tests/basic/data01endpoint3.ttl, tools/federation/src/test/resources/tests/basic/data01endpoint4.ttl, tools/federation/src/test/resources/tests/basic/query_lang.rq, tools/federation/src/test/resources/tests/basic/query_lang.srx, tools/federation/src/test/resources/tests/basic/query_quotes.rq, tools/federation/src/test/resources/tests/basic/query_quotes.srx, tools/federation/src/test/resources/tests/basic/query_quotes_datatype.rq, tools/federation/src/test/resources/tests/basic/query_quotes_datatype.srx
GitHub issue resolved: #3117 
Fix FedX ASK queries generated that fail with syntax errors. Use triple quotes to handle literals with new lines and get language tag properly.
=> GH-3117 Fix FedX syntax error on literal with new lines and language tags

core/queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/text/SPARQLResultsXSVMappingStrategy.java, core/queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/text/csv/SPARQLResultsCSVMappingStrategy.java, core/queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/text/tsv/SPARQLResultsTSVMappingStrategy.java, core/queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/text/tsv/SPARQLResultsTSVReader.java, pom.xml
GitHub issue resolved: #3127  
- remove deprecated methods
- bump version to opencsv 5.3
- use switch statement instead of nested ifs
----
=> GH-3127: bump version + remove deprecated methods

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/ClassConstraintComponent.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/targets/TargetClass.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/AbstractShaclTest.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/ShaclTestWithoutRdfsReasoner.java
GitHub issue resolved: #3154 
- add tests
- check if null before using reasoner
----
=> GH-3154 fix null pointer exception when disabling the ShaclSail RDFS reasoner 

core/util/src/main/java/org/eclipse/rdf4j/common/iteration/UnionIteration.java
GitHub issue resolved: #3150 
- Use while loop instead of recursion in UnionIteration
----
=> GH-3150 use while loop instead of recursion

bom/pom.xml
GitHub issue resolved: #1706 
- removed some left over references that cause build to fail if you don't have the lucene spin snapshot build
----
=> GH-1706 remove left overs from lucene spin sail

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSailConnection.java
GitHub issue resolved: #3166 
----
=> GH-3166 GlobalValidationExecutionLogging should log before iterator is created

site/content/documentation/programming/lucene.md
GitHub issue resolved: #3170 
- 'three' instead of 'five'
- 'Apachce Lucence' to 'Apache Lucene' 
- correct casing of ElasticsearchIndex
----
=> GH-3170: fix typos

tools/federation/src/test/java/org/eclipse/rdf4j/federated/ServiceTests.java
GitHub issue resolved: #3160  
- temporarily disable flaky test to avoid intermittent build failures
- we should not close the underlying issue until we have time to look a bit deeper at the underlying cause
----
=> GH-3160 disable flaky FedX test until we have time to hunt the cause

tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/RepositoryController.java, tools/server-spring/src/test/java/org/eclipse/rdf4j/http/server/repository/RepositoryControllerTest.java
GitHub issue resolved: #3153  
- check for missing config data in RepositoryController and return an explicit /  helpful error (400 Bad Request)
- also catch other config validation errors  and also return a 400 error with useful message in body
----
=> GH-3153 better error handling/reporting on PUT repo config operations

README.md, site/content/support.md
GitHub issue resolved: #3178  
- adapted website support page to make Github Discussions the preferred comms channel, and make it clear that rdf4j-users is no longer used.
----
=> GH-3178 rdf4j-users archived, made Github Discussion more prominent

.github/workflows/new-issue.yml
- timeout to avoid long queue of "stuck" actions (like we saw after migrating several issue to discussion board)
- version bump because it might fix some relevant things
=> setting timeout on task and bumping version

.github/workflows/new-issue.yml
rolling back version bump on project automation github action: it can't seem to pull the docker image.
=> revert version change for project automation github action 

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/workflows/new-issue.yml
GitHub issue resolved: #3199  
- adds issue templates with forms for bug reports and feature requests
- adds an obvious direct link to the discussion forum for questions, comments, etc.
- still possible to create a "blank" new issue if none of the templates fit (e.g. for our own internal tasks).
- bumped version of the new-issue github action (hopefully fixes the problems I ran into earlier, but this is as yet untested)
----
=> GH-3199 issue templates for bug reports and feature requests

.github/ISSUE_TEMPLATE/config.yml
apparently Github already automatically adds that anyway.
----
=> GH-3199 remove security vulnerability bit

bom/pom.xml, compliance/geosparql/pom.xml, core/client/pom.xml, core/repository/api/pom.xml, core/repository/sail/pom.xml, core/sail/elasticsearch-store/pom.xml, core/sail/extensible-store/pom.xml, core/sail/inferencer/pom.xml, core/sail/lucene-api/pom.xml, core/sail/lucene-api/src/test/java/org/eclipse/rdf4j/sail/lucene/QuerySpecBuilderTest.java, core/sail/lucene/pom.xml, core/sail/memory/pom.xml, core/sail/nativerdf/pom.xml, core/sail/shacl/pom.xml, core/storage/pom.xml, testsuites/lucene/pom.xml, testsuites/rio/pom.xml, testsuites/sail/pom.xml
GitHub issue resolved: GH-2992  
- remove leftover dependencies on serql parser
- rewrote test case that was overlooked earlier
- also removed a dangling reference to the lucene-spin sail (see GH-1706)
----
=> GH-2992 remove orphan references to removed serql parser

core/sail/api/src/main/java/org/eclipse/rdf4j/sail/helpers/SailConnectionWrapper.java, core/sail/base/src/main/java/org/eclipse/rdf4j/sail/inferencer/InferencerConnectionWrapper.java
GitHub issue resolved: #3212 
- delegate hasStatement to wrapped connection
----
=> GH-3212 SailConnectionWrapper should implement hasStatement(...)

pom.xml, src/main/javadoc/overview.html
GitHub issue resolved: #3116  
- fewer groups to make horizontal "tab" layout work better
- added general overview text with pointers to more comprehensive documentation
Screenshot of new Javadoc overview page (Firefox on desktop):
----
=> GH-3116 fix aggregated javadoc layout for HTML5 features

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/VerySimpleRdfsBackwardsChainingConnection.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/ClassConstraintComponent.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/QualifiedValueShapeBenchmarkEmpty.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/RdfsReasonerBenchmarkEmpty.java, core/sail/shacl/src/test/resources/shaclQualifiedShapeBenchmark.ttl, core/sail/shacl/src/test/resources/shaclRdfsBenchmark.ttl
GitHub issue resolved: #3216 
- some simplification to return earlier
- check size of inferred set and if it is above 10 then we use getStatements to get the actual rdf:type(s) and check them against the inferred set
----
=> GH-3216 VerySimpleRdfsBackwardsChainingConnection handles larger inferred sets

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/NodeShape.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/PropertyShape.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/AndConstraintComponent.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/ClassConstraintComponent.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/DashHasValueInConstraintComponent.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/HasValueConstraintComponent.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/MaxCountConstraintComponent.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/MinCountConstraintComponent.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/NotConstraintComponent.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/OrConstraintComponent.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/QualifiedMaxCountConstraintComponent.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/QualifiedMinCountConstraintComponent.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/SimpleAbstractConstraintComponent.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/UniqueLangConstraintComponent.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/PlanNodeHelper.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/UnionNode.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/Unique.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/targets/DashAllObjects.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/targets/DashAllSubjects.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/targets/EffectiveTarget.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/targets/RSXTargetShape.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/targets/TargetClass.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/targets/TargetObjectsOf.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/targets/TargetSubjectsOf.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/UniqueTest.java
GitHub issue resolved: #GH-3217 
- use getInstance methods instead of constructors
- check input so that for 
- Unique we can return the provided node if the is already unique
- UnionNode we can return the provided node if the effective node count is 1
- also (because it was hard to untangle from this code) GH-3218 optimize QualifiedMinCount to better handle bulk validation
----
=> GH-3217 Union and Unique plan nodes can return the provided node if they are redundant

core/util/src/main/java/org/eclipse/rdf4j/common/io/FileUtil.java
GitHub issue resolved: #3261  
- no code changes, just adding Deprecated annotation to methods
----
=> GH-3261: deprecated fileutils

core/util/src/main/java/org/eclipse/rdf4j/common/text/StringUtil.java
GitHub issue resolved: #3264  
- no code changes, added deprecated annotations to methods that could be removed in 4.0
----
=> GH-3264: deprecated stringutil methods

site/content/documentation/programming/repository.md
GitHub issue resolved: #3270 
- remove whitespaces after/before curly braces to fix rendering of link
----
=> GH-3270: remove whitespaces in placeholder / template code

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/targets/EffectiveTarget.java
GitHub issue resolved: #3226 
AllTargetsPlanNode is used to signal bulk validation. The .extend(...) method is aimed at supporting sh:or and sh:not in particular. When using the target override feature (designed to support sh:or and sh:not) we don't need to extend the overriding targets if they are actually "all" targets. So the presence of the AllTargetsPlanNode means that we can just return a new one based on the current effective target chain.
----
=> GH-3226 return a new AllTargetsPlanNode instead of extending

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/ValidationTuple.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/ValuesBackedNode.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/targets/TargetChainRetriever.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/ValidationTupleBenchmark.java
GitHub issue resolved: #3228  
- The chain is the most used structure in the ValidationTuple. It's similar to a binding set. Using an array instead of a list reduces the amount of memory we use.
- Fixed some empty set and empty list usage elsewhere in the ValidationTuple code too
- Also added benchmark
----
=> GH-3228 ValidationTuple uses array instead of list

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSailConnection.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/NativeStoreBenchmark.java
GitHub issue resolved: #3232 
- skip fillAddedAndRemovedStatementRepositories when using bulk validation
- fix a validation plan that caused a null pointer exception when addedStatements repo was null for bulk validation
----
=> GH-3232 skip fillAddedAndRemovedStatementRepositories on bulk validation

core/http/protocol/src/main/java/org/eclipse/rdf4j/http/protocol/Protocol.java, core/query/src/main/java/org/eclipse/rdf4j/query/Operation.java, core/query/src/main/java/org/eclipse/rdf4j/query/Query.java, core/query/src/main/java/org/eclipse/rdf4j/query/QueryResultHandler.java, core/queryrender/src/main/java/org/eclipse/rdf4j/queryrender/BaseTupleExprRenderer.java, core/queryrender/src/main/java/org/eclipse/rdf4j/queryrender/RenderUtils.java, core/queryrender/src/main/java/org/eclipse/rdf4j/queryrender/package-info.java, core/queryrender/src/main/java/org/eclipse/rdf4j/queryrender/sparql/SPARQLQueryRenderer.java, core/queryrender/src/main/java/org/eclipse/rdf4j/queryrender/sparql/SparqlTupleExprRenderer.java, core/queryrender/src/main/java/org/eclipse/rdf4j/queryrender/sparql/SparqlValueExprRenderer.java, core/sail/inferencer/src/main/java/org/eclipse/rdf4j/sail/inferencer/fc/CustomGraphQueryInferencer.java, core/sail/inferencer/src/main/java/org/eclipse/rdf4j/sail/inferencer/fc/config/CustomGraphQueryInferencerConfig.java, core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSail.java, core/sail/lucene/src/test/java/org/eclipse/rdf4j/sail/lucene/AbstractGenericLuceneTest.java, site/content/documentation/reference/rest-api.md, site/content/documentation/tools/server-workbench.md, testsuites/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractLuceneSailTest.java, tools/console/src/main/java/org/eclipse/rdf4j/console/command/QueryEvaluator.java, tools/console/src/main/java/org/eclipse/rdf4j/console/command/TupleAndGraphQueryEvaluator.java, tools/workbench/src/main/java/org/eclipse/rdf4j/workbench/util/PagedQuery.java, tools/workbench/src/main/java/org/eclipse/rdf4j/workbench/util/QueryStorage.java, tools/workbench/src/main/webapp/transformations/query.xsl
GitHub issue resolved: #3251 
- removed code comments and obsolete methods referencing SeRQL
- tested/modified workbench to verify removal of SeRQL introduces no errors in query page or saved query functionality.
----
=> GH-3251 remove lingering references to SeRQL

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryJoinOptimizer.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryJoinOptimizerEmptyStatisticsTest.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryJoinOptimizerTest.java
GitHub issue resolved: #3102 
----
=> GH-3102 favour BindingSetAssignment if it binds variables in the query

core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/NativeStore.java
GitHub issue resolved: #2956 
- use standard JDK Files instead of commons FileUtils
- explicitly define character set being used (UTF8, should not make a difference for version, but just in case)
- log when upgrading native store data dir
----
=> GH-2956: use standard JDK instead of commons fileutils

core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/ndjsonld/NDJSONLDParser.java
GitHub issue resolved: # GH-3252
- Added UTF-8 encoding at getJSONObject method so to not use the default platform encoding
----
=> GH-3252-NDJSONLDParser-uses-platform-encoding-to-convert-chars-to-bytes

core/sail/lucene/pom.xml, site/content/release-notes/4.0.0.md
GitHub issue resolved: #2392  
- always add lucene-backward-codecs jar as runtime dependency
- added documentation on upgrading lucene index
- mention upgrade from Solr and ElasticSearch
----
=> GH-2392: added lucene-backward-codecs + documentation

core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSailConnection.java
GitHub issue resolved: #3314 
- removed the unused private static field and associated imports 
----
=> GH-3314: remove unused field and imports

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StandardQueryOptimizerPipeline.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/UnionScopeChangeOptimizer.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/UnionScopeChangeOptimizerTest.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/QueryPlanRetrievalTest.java
GitHub issue resolved: #3322  
- add new optimizer that switches scope change off for unions when possible: only should not be allowed when BIND or VALUES clauses are inside one of the union arguments
- this optimization allows us to use interleaved joining when combining VALUES clauses with unions in the majority of practical cases, which is much more efficient.
----
=> GH-3322 optimize union clauses to inject vars when we can

core/http/client/src/main/java/org/eclipse/rdf4j/http/client/RDF4JProtocolSession.java, core/repository/http/src/main/java/org/eclipse/rdf4j/repository/http/HTTPRepositoryConnection.java
GitHub issue resolved: #3329  
- RDF4JProtocolSession.close now forces a shutdown on its internal ping thread scheduler
----
=> GH-3329 ensure ping threads are closed when RDF4JProtocolSession exits

core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/XMLReaderBasedParser.java, core/rio/trix/src/test/java/org/eclipse/rdf4j/rio/trix/TriXParserTest.java, core/rio/trix/src/test/resources/org/eclipse/rdf4j/rio/trix/trix-xxe-external-dtd.trix
GitHub issue resolved: #3347 
- make LOAD_EXTERNAL_DTD a compulsory XML feature setting so that its default value (`false`) is explicitly configured on the SAX reader
----
=> GH-3347 make LOAD_EXTERNAL_DTD compulsory so default is set to false

pom.xml
GitHub issue resolved: #3372  
- tweaked javadoc plugin config to conform to changes that were made in its supported options since 3.0
----
=> GH-3372 maven-javadoc-plugin 3.x uses different config flags

tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/ExclusiveGroup.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/optimizer/FilterOptimizer.java, tools/federation/src/test/java/org/eclipse/rdf4j/federated/FilterTests.java, tools/federation/src/test/resources/tests/filter/query07.qp, tools/federation/src/test/resources/tests/filter/query07.rq, tools/federation/src/test/resources/tests/filter/query07.srx
GitHub issue resolved: #3377 
- do not push filter expressions into exclusive statements, as they have
to be handled on the exclusive group
- fix parent assignment for exclusive statements when adding them to the
group
- fix computation of scope binding names in exclusive groups by
collecting the bindings produced by the individual statements
Covered with a unit test that checks evaluation and the produced query
plan
Signed-off-by: Andreas Schwarte <aschwarte10@gmail.com>
----
=> GH-3377: fix FedX filter optimizations for ExclusiveGroups

compliance/pom.xml, core/pom.xml
GitHub issue resolved: #3400  
This ensures benchmarks fat jars do not get built unless needed, and
avoids accidental deployment
----
=> GH-3400 only build benchmark jars when -Pbenchmarks flag is used

.gitignore, pom.xml
GitHub issue resolved: #3389 
- update .gitignore to ignore the temporary directory in the docker dir.
----
=> GH-3389 update gitignore

tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/statements/StatementsController.java
GH-3404-Error parsing JSON-LD data with the default base URI from StatementsController
GitHub issue resolved: 3404
Remove the default 'foo:bar' base URI in order to prevent error when data is parsed with JSONLDParser 
----
=> GH-3404-Error parsing JSON-LD data with the default base URI from StatementsController

compliance/rio/pom.xml, core/http/protocol/pom.xml, core/rio/api/pom.xml, core/sail/solr/pom.xml, pom.xml, testsuites/sparql/pom.xml
GitHub issue resolved: #3453 
- use the Eclipse Jakarta version of (Oracle) Javax JAXB
- bump patch version to 2.3.3
----
=> GH-3453: use Eclipse Jakarta JAXB

core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleParser.java, core/rio/turtle/src/test/java/org/eclipse/rdf4j/rio/turtle/TurtleParserTest.java
GitHub issue resolved: #3412
The line number counter is incremented on each new line character inside multi-line string literals in Turtle.
----
PR Author Checklist:
=> increase the line number on newlines inside long string literals

core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/rdf/RdfLiteral.java, core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/util/SparqlBuilderUtils.java, core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/rdf/RdfLiteralTest.java
GitHub issue resolved: #1815 
Handles escape sequences, such as `\n`, in string literals as prescribed by the spec
https://www.w3.org/TR/2013/REC-sparql11-query-20130321/#grammarEscapes
Note: codepoint escape sequences are not treated in any special way. Users who want unusual characters in their literals must find a way to get them into the Java String, e.g. by encoding them in Java source code as, e.g. `\u2021`, in which case they will be properly represented in the literal's String representation.
(see https://www.w3.org/TR/2013/REC-sparql11-query-20130321/#codepointEscape )
Fixes #1815 
----
=> GH-1815: Escape String literals in SparqlBuilder

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/FilterOptimizer.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/FilterOptimizerTest.java
GitHub issue resolved: #GH-3439
Merge adjacent filters into one via "and"ing the valueexpresions of them and removing one from the algebra.
Must run after the existing placing filter which is slightly changed to place filter next to statementpatterns now that produce the variables,
----
=> GH-3439 Filters next to each other in the algebra can be merged.

core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/FilterOptimizerTest.java
GitHub issue resolved: #3439 
#GH-3406 added a QueryRoot to everything parsed. This was not reflected in the test of #3440 
----
=> GH-3406 affected GH-3439 by adding a queryroot to the parsed TupleExpr

core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryCostEstimatesTest.java
GitHub issue resolved: #3473 
Building `develop` fails on windows. One of the tests is platform-dependent. Fixed by using `System.lineSeparator()` for line endings.
----
=> GH-3473: Fix platform-dependent test failing on Windows

core/sail/extensible-store/src/main/java/org/eclipse/rdf4j/sail/extensiblestore/evaluationstatistics/ExtensibleDynamicEvaluationStatistics.java, core/sail/extensible-store/src/test/java/org/eclipse/rdf4j/sail/extensiblestore/NaiveHashSetDataStructure.java
GitHub issue resolved: #3484 
- fix synchronization issues in `ExtensibleDynamicEvaluationStatistics`
- use correct way to instantiate a set from a map
----
=> GH-3484 extensible store failing test

assembly-descriptors/pom.xml, bom/pom.xml, compliance/elasticsearch/pom.xml, compliance/geosparql/pom.xml, compliance/lucene/pom.xml, compliance/model/pom.xml, compliance/pom.xml, compliance/repository/pom.xml, compliance/rio/pom.xml, compliance/shacl/pom.xml, compliance/solr/pom.xml, compliance/sparql/pom.xml, core/pom.xml, core/sail/elasticsearch-store/pom.xml, core/sail/elasticsearch/pom.xml, core/sail/extensible-store/pom.xml, core/sail/lucene-api/pom.xml, core/sail/lucene/pom.xml, core/sail/solr/pom.xml, examples/pom.xml, testsuites/geosparql/pom.xml, testsuites/lucene/pom.xml, testsuites/pom.xml, testsuites/rio/pom.xml, testsuites/shacl/pom.xml, testsuites/sparql/pom.xml, tools/pom.xml, tools/workbench/pom.xml
Renames all module names such that they start with
'RDF4J: '
GitHub issue resolved: #3476
maven modules are renamed so they all start with the same prefix
----
=> GH-3476: Pedantically rename maven modules according to guidelines

tools/console/src/test/java/org/eclipse/rdf4j/console/command/ExportTest.java, tools/console/src/test/java/org/eclipse/rdf4j/console/command/SparqlTest.java
Rio.parse(Reader, String, RDFFormat) does not close the reader after reading (at least not for TTL), causing tests to fail on Windows. Closing the reader fixes that problem.
GitHub issue resolved: #3479
The reader passed to `Rio.parse()` is closed after the call.
----
=> GH-3479: Fix Rio.parse() calls in console tests

core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/MemorySailStore.java, core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemStatement.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/InferredMemStatementTest.java
GitHub issue resolved: #3486 
- MemorySailStore can optimize read operations against the inferred source when there are no statements. This is done by having a flag that gets set to `true` once inferred statements have been added.
- The explicit flag in MemStatement is now final and no longer volatile. There were no uses for modifying this flag in our code base, so I've deprecated the setter and modified it to use reflection (so it will still work, but not very well).
----
=> GH-3486 memorystore explicit inferred performance

core/query/src/main/java/org/eclipse/rdf4j/query/explanation/ExplanationImpl.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/QueryPlanRetrievalTest.java
Also adapts ExplanationImpl to use the platform-specific line separator.
GitHub issue resolved: #3477 
A test uses `\n` line endings but the classes being tested use the platform-specific line separator. 
----
=> GH-3477: Fix platform-dependent test

core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/NativeStoreConsistencyIT.java
GitHub issue resolved: #3496 
Speed up test NativeStoreConsistencyIT by using other methods for computing the difference.
----
=> GH-3496 Replace RepositoryUtil.difference by methods of LinkedHashModel.

core/rio/ntriples/src/main/java/org/eclipse/rdf4j/rio/ntriples/NTriplesParser.java, core/rio/ntriples/src/test/java/org/eclipse/rdf4j/rio/ntriples/AbstractNTriplesParserUnitTest.java
GitHub issue resolved: #3498 
- pass line/column number to helper method when checking datatype / language tag
- added test
----
=> GH-3498: use method which reports line/column numbers

compliance/elasticsearch/pom.xml, core/sail/solr/pom.xml
GitHub issue resolved: #3504 
- use log4j 2.16.0 for additional hardening 
----
=> GH-3504: use 2.16.0 for ES compliance

core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/ShaclSailSupportedPredicatesDocumentationIT.java
GitHub issue resolved: #3519
Use a concurrent safe set implementation for a field that may be accessed by multiple threads during junit testing.
----
=> Concurent safe set used for share static in after class

core/common/iterator/src/main/java/org/eclipse/rdf4j/common/iteration/DelayedIteration.java, core/common/iterator/src/main/java/org/eclipse/rdf4j/common/iteration/FilterIteration.java, core/common/iterator/src/main/java/org/eclipse/rdf4j/common/iteration/IntersectIteration.java, core/common/iterator/src/main/java/org/eclipse/rdf4j/common/iteration/LimitIteration.java, core/common/iterator/src/main/java/org/eclipse/rdf4j/common/iteration/MinusIteration.java, core/common/iterator/src/main/java/org/eclipse/rdf4j/common/iteration/SingletonIteration.java, core/common/iterator/src/main/java/org/eclipse/rdf4j/common/iteration/UnionIteration.java, core/common/iterator/src/main/java/org/eclipse/rdf4j/common/iterator/LookAheadIterator.java, core/common/iterator/src/main/java/org/eclipse/rdf4j/common/iterator/UnionIterator.java, core/query/src/main/java/org/eclipse/rdf4j/query/impl/MutableTupleQueryResult.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/federation/TupleFunctionFederatedService.java
GitHub issue resolved: #3042 
Remove volatile and synchronized in iterators that are inherently not threadsafe.
----
=> GH-3042 no volatile atomic in iterators that are not threadsafe

core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Like.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/QueryModelVisitor.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/helpers/AbstractQueryModelVisitor.java, core/queryrender/src/main/java/org/eclipse/rdf4j/queryrender/sparql/SparqlValueExprRenderer.java, core/queryrender/src/main/java/org/eclipse/rdf4j/queryrender/sparql/experimental/ParsedQueryPreprocessor.java, core/queryrender/src/main/java/org/eclipse/rdf4j/queryrender/sparql/experimental/PreprocessedQuerySerializer.java
GitHub issue resolved: #3543 
Marks the Like code as deprecated for removal.
Alternatively we can just remove the class 
----
=> GH-3543 deprecate like from serql

core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/MemoryOverflowModel.java, core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/NativeStore.java, core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/MemoryOverflowToDiskTest.java
GitHub issue resolved: #3541
Similar to #3540 but now for native store, doesn't use a shutdown hook so might be better/cleaner.
@kenwenzel I now see where the code came from. Still would like your opinion though :)
This can not be backported to the 3 series as requires java11
----
=> nativerdf use cleaner to close overflowmemory backing store when not used.

core/rio/api/src/main/java/org/eclipse/rdf4j/rio/ParserConfig.java, core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/AbstractRDFParser.java, core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/NTriplesParserSettings.java, core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/TriXParserSettings.java, core/rio/api/src/test/java/org/eclipse/rdf4j/rio/ParserConfigTest.java, core/rio/nquads/src/test/java/org/eclipse/rdf4j/rio/nquads/AbstractNQuadsParserUnitTest.java, core/rio/ntriples/src/test/java/org/eclipse/rdf4j/rio/ntriples/AbstractNTriplesParserUnitTest.java, site/content/release-notes/4.0.0.md
GitHub issue resolved: #1841 
- removed deprecated settings 
- added info on release notes
----
=> GH-1841: remove deprecated NTriples / Trix parser settings

.github/workflows/pr-verify.yml
GitHub issue resolved: #3533 
bump checkout action to v2
=> GH-3535 pr-verify uses checkout v2

core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbRecordIterator.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbSailStore.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbStatementIterator.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/Pool.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/RecordIterator.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/TripleStore.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/TxnRef.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/ValueStore.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/ValueStoreRevision.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/Varint.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/model/LmdbBNode.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/model/LmdbIRI.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/model/LmdbLiteral.java, core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/TripleStoreTest.java
Store value types in 2 bits of ID and load real data on demand.
GitHub issue resolved: #3416 
Currently, intermediate results are fully materialized when a SPARQL query is evaluated.
This change introduces lazy values for the LMDB store.
----
=> GH-3416 Cleanup and further optimization of LMDB store.

.github/workflows/develop-status.yml, .github/workflows/main-status.yml, .github/workflows/merge_main_to_develop.yml, .github/workflows/pr-verify.yml
GitHub issue resolved: #3533  
- use action/checkout@v2 in all github action workflows
----
=> GH-3533 set checkout action version to v2 in all workflows

.github/workflows/merge_main_to_develop.yml
GitHub issue resolved: #3533  
- merge-main-develop workflow started failing after updating to checkout v2
- a recent fix in the repo-sync/pull-request action should address this, so bumping to latest
----
=> GH-3533 bump pull-request action to be compatible with checkout v2

core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbRecordIterator.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbSailStore.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbStatementIterator.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/Pool.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/RecordIterator.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/TripleStore.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/TxnRef.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/ValueStore.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/ValueStoreRevision.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/Varint.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/model/LmdbBNode.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/model/LmdbIRI.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/model/LmdbLiteral.java, core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/TripleStoreTest.java
GitHub issue resolved: #3534 
Improves query speed for LMDB based store by using different DBs for explicit and inferred statements.
This is the best solution until SailSourceConnection is rewritten to use a combined source for explicit and inferred statements while querying. 
----
=> GH-3534 Optimize reading from LMDB SailSource by using different DBs for explicit and inferred statements.

core/model-api/src/main/java/org/eclipse/rdf4j/model/IRI.java, core/model-api/src/main/java/org/eclipse/rdf4j/model/base/AbstractIRI.java, core/model-api/src/test/java/org/eclipse/rdf4j/model/IRITest.java, core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemIRI.java, core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/ValueStore.java, core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/ValueStoreRevision.java, site/content/release-notes/4.0.0.md
GitHub issue resolved: #2565  
- adjusted javadoc on `IRI` interface
- fixed code in all core implementations of `IRI`
- adjusted relevant unit test case
- small unrelated change in native store that I stumbled across
- added entry to release notes
----
=> GH-2565 IRI equals/hashCode now based on stringValue instead of toString

core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemIRI.java
GitHub issue resolved: #3589 
- cache the results of toString() using a soft reference to reduce the number of times we need to recompute it
- typically the .toString() method is called when retrieving the MemIRI from MemValueFactory with an AbstractIRI because the .equals() method there uses the full string representation instead of the namespace and local name like MemIRI does.
----
=> GH-3589 cache toString() in MemIRI 

core/model-api/src/main/java/org/eclipse/rdf4j/model/base/AbstractLiteral.java, core/model/src/main/java/org/eclipse/rdf4j/model/datatypes/XMLDatatypeUtil.java
GitHub issue resolved: #3598 
XMLGregorianCalendar.getXMLSchemaType() is defined to only return the constants from DatatypeConstants. This means we can use == instead of .equals(...). See https://docs.oracle.com/javase/8/docs/api/javax/xml/datatype/XMLGregorianCalendar.html#getXMLSchemaType--
----
=> GH-3598 use == everywhere we compare the xml schema datatype with the DatatypeConstants from the XMLGregorianCalendar

tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/statements/ExportStatementsView.java, tools/server-spring/src/test/java/org/eclipse/rdf4j/http/server/repository/statements/TestExportStatementsView.java, tools/server-spring/src/test/java/org/eclipse/rdf4j/http/server/repository/statements/TestStatementsCommon.java, tools/server-spring/src/test/java/org/eclipse/rdf4j/http/server/repository/statements/TestStatementsController.java
GitHub issue resolved: #3597
Passed new ByteArrayOutputStream to RDFWriter, which is written in response output stream if no exception is thrown.
----
- [X ] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
- [ X] I've added tests for the changes I made
- [ X] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
- [ X] every commit message starts with the issue number (GH-xxxx) …
=> Gh 3597 wrong status code in export statements view on exception

site/content/release-notes/4.0.0.md, tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedX.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXConfig.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXConnection.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXFactory.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/FederationContext.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/FederationManager.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/QueryManager.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/ExclusiveGroup.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/FederationEvalStrategy.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/FederationEvaluationStrategyFactory.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/SailTripleSource.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/TripleSourceBase.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/concurrent/ParallelExecutorBase.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/join/JoinExecutorBase.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/union/ControlledWorkerUnion.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/union/SynchronousWorkerUnion.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/union/UnionExecutorBase.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/union/WorkerUnionBase.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/structures/QueryInfo.java, tools/federation/src/test/java/org/eclipse/rdf4j/federated/write/WriteTest.java
GitHub issue resolved: #3483 
(NOTE: it is recommended to do any review commit wise, as this is much easier to follow)
Commit 1: GH-3483: refactor federation execution to use a per-query strategy
This change refactors the execution of federated queries to use a
per-query instance of the FederationEvaluationStrategy.
The instance is passed via the QueryInfo object, which is already
specific to a given query execution.
Note that as a next step a proper factory mechanism needs to be put in
place in FederationManager and FederationContext (i.e. this change is
only the preparation, and it in fact still uses the same instance of the
strategy).
Commit 2: GH-3483: instantiate federation strategy through a factory
Adjust the federation …
=> GH-3483: refactor federation execution to use a per-query strategy

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/DescribeIteration.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/FederatedDescribeOperator.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/FederationEvalStrategy.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/iterator/FederatedDescribeIteration.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/optimizer/GenericInfoOptimizer.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/repository/FedXRepositoryConnection.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/structures/QueryType.java, tools/federation/src/test/java/org/eclipse/rdf4j/federated/BasicTests.java, tools/federation/src/test/resources/tests/basic/query_describe1.rq, tools/federation/src/test/resources/tests/basic/query_describe1.ttl, tools/federation/src/test/resources/tests/basic/query_describe2.rq, tools/federation/src/test/resources/tests/basic/query_describe2.ttl
GitHub issue resolved: #2759 
This change adds support for DESCRIBE queries to the federation and
makes sure that these are evaluated properly against the federation
members.
Notes:
* the existing DescribeIteration is extended for use in the federation.
In order to avoid code duplication some methods have been declared
protected
* the FedX internal query type "DESCRIBE" has been introduced
* tests for single and multiple resource descriptions are provided
----
=> GH-2759: add support for DESCRIBE in FedX federation

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/EvaluationStatistics.java, core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java, core/queryrender/src/main/java/org/eclipse/rdf4j/queryrender/BaseTupleExprRenderer.java, core/queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/text/csv/SPARQLResultsCSVWriter.java, core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/AbstractRDFParser.java
GitHub issue resolved: #3609 
- use String.replace instead of replaceAll when not using a regular expression
----
=> GH-3609: use replace instead of replaceAll

core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbSailStore.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/ValueStore.java, core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/benchmark/BenchmarkBaseFoaf.java, core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/benchmark/QueryBenchmark.java, core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/benchmark/QueryBenchmarkFoaf.java, core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/benchmark/TransactionsPerSecondBenchmarkFoaf.java, core/sail/lmdb/src/test/resources/benchmarkFiles/query-persons-count-friends-sorted.qr, core/sail/lmdb/src/test/resources/benchmarkFiles/query-persons-count-friends.qr, core/sail/lmdb/src/test/resources/benchmarkFiles/query-persons-friends.qr, core/sail/lmdb/src/test/resources/benchmarkFiles/query7-pathexpression1.qr
GitHub issue resolved: #3570 
Rewrite LmdbSailStore and introduce the possibility to insert triples on a second thread.
----
=> GH-3570 LMDB store multi-threading

core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/ValueStore.java
GitHub issue resolved: #3634 
Also cache IDs of own values after lookup from persistent storage.
----
=> GH-3634 Fix caching of LMDB value store

site/content/release-notes/4.0.0.md, tools/federation/src/main/java/org/eclipse/rdf4j/federated/FederationManager.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/repository/FedXRepositoryConfig.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/repository/FedXRepositoryWrapper.java
GitHub issue resolved: #3483 
- remove deprecate FedXConfig#setFedXConfig (to specify a location)
- fix use of supplied strategy factory in FederationManager (we need to
use the factory that is available in the federation instead of creating
a new one)
- refine FedXRepositoryWrapper for slightly better extensibility
(use-case: support fine-tuning the FedXFactory without requiring to
overwrite the entire file. Note that this is now required because the
evaluationstrategy can no longer be influenced through the FedXConfig)
----
=> GH-3483: wrap up the use of FederationEvalStrategy per query

core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/config/LmdbStoreConfig.java, core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/LmdbStoreConcurrencyTest.java, core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/QueryBenchmarkTest.java, core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/benchmark/BenchmarkBaseFoaf.java, core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/benchmark/ConfigUtil.java, core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/benchmark/OverflowBenchmarkReal.java, core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/benchmark/OverflowBenchmarkSynthetic.java, core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/benchmark/QueryBenchmark.java, core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/benchmark/TransactionsPerSecondBenchmark.java, core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/benchmark/TransactionsPerSecondForceSyncBenchmark.java
GitHub issue resolved: #3648   
Reduce default maximum DB size to 10 MiB for value and triple store.
----
=> GH-3648 Reduce default maximum DB size of LMDB store

core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/SailSourceBranch.java, core/sail/base/src/test/java/org/eclipse/rdf4j/sail/base/SnapshotSailStoreTest.java
GitHub issue resolved: #3646 
Correctly clear changes if an exception occurs while flushing to sink.
----
=> GH-3646 Clear changes if SailException occurs.

compliance/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLServiceEvaluationTest.java, core/rio/api/src/main/java/org/eclipse/rdf4j/rio/ParserConfig.java, core/rio/api/src/main/java/org/eclipse/rdf4j/rio/RDFParser.java, core/rio/api/src/main/java/org/eclipse/rdf4j/rio/Rio.java, core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/AbstractRDFParser.java, core/rio/api/src/test/java/org/eclipse/rdf4j/rio/ParserConfigTest.java, core/rio/api/src/test/java/org/eclipse/rdf4j/rio/RioTest.java, core/rio/ntriples/src/test/java/org/eclipse/rdf4j/rio/ntriples/AbstractNTriplesParserUnitTest.java, site/content/release-notes/4.0.0.md, testsuites/rio/src/main/java/org/eclipse/rdf4j/testsuite/rio/PositiveParserTest.java, testsuites/rio/src/main/java/org/eclipse/rdf4j/testsuite/rio/n3/N3ParserTestCase.java, testsuites/rio/src/main/java/org/eclipse/rdf4j/testsuite/rio/rdfjson/RDFJSONParserTestCase.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/query/parser/sparql/manifest/SPARQL10ManifestTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/query/parser/sparql/manifest/SPARQL11ManifestTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/query/parser/sparql/manifest/SPARQLComplianceTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/query/parser/sparql/manifest/SPARQLQueryComplianceTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/query/parser/sparql/manifest/SPARQLQueryTest.java
GitHub issue resolved: #3557  
- add overloaded parse methods for supplying (only) custom parser config
- added some testing around the Rio util methods
- cleaned up some deprecated code
----
=> GH-3557 add parse overloads for supplying custom ParserConfig

core/model-api/src/main/java/org/eclipse/rdf4j/model/ValueFactory.java, core/model/src/main/java/org/eclipse/rdf4j/model/util/Values.java, core/model/src/test/java/org/eclipse/rdf4j/model/util/ValuesTest.java
GitHub issue resolved: #3677 
- minor javadoc improvements
- let Values.literal accept  BigInteger, BigDecimal, TemporalAmount
- added tests for these types
----
=> GH-3677: added tests and convenience methods for literals

core/sail/elasticsearch-store/src/main/java/org/eclipse/rdf4j/sail/elasticsearchstore/ElasticsearchHelper.java
GitHub issue resolved: #3682 
- use string instead of TimeValue so that our code becomes compatible with future minor versions of Elasticsearch
----
=> GH-3682 stop using Elasticsearch TimeValue

tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/TransactionStartController.java, tools/server-spring/src/test/java/org/eclipse/rdf4j/http/server/repository/transaction/TransactionStartControllerTest.java, tools/server/src/main/resources/org/eclipse/rdf4j/http/server/application.properties, tools/server/src/main/webapp/WEB-INF/rdf4j-http-server-servlet.xml
GitHub issue resolved: #3687
I have added an optional property to configure the external base URL of the server. 
----
=> GH-3687 add external url configuration property

tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/Transaction.java, tools/server-spring/src/test/java/org/eclipse/rdf4j/http/server/repository/transaction/TestBnodesUniquenessInTransactions.java
Remove setting of PRESERVE_BNODE_IDS parameter to true when a remote transaction is created. So when data is added to transaction the parser will use the default value of the parameter which is false and will create new identifiers to ensure uniqueness of blank nodes across multiple files.
If preserveNodeId parameter of HttpServletRequest is set to true, PRESERVE_BNODE_IDS will be reconfigured and bnode ids will be preserved.
GitHub issue resolved: #3623  
----
=> GH-3623 Use unique bnode ids in remote transactions

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryJoinOptimizer.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryJoinOptimizerTest.java
GitHub issue resolved: #3667
Optimize the graph when a subquery/optional/bind clause is present in the SPARQL.
=> GH-3667: Optimize subqueries and bind statements 

core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java, core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilderTest.java
GitHub issue resolved: #2990  
When a projection alias involves a simple variable-to-variable mapping, an Extension node is redundant.
----
=> GH-2990 remove redundant Extension when alias mapping is var->var

core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDWriter.java, core/rio/jsonld/src/test/java/org/eclipse/rdf4j/rio/jsonld/JSONLDWriterTest.java
Resolves issue: #3708 
Not only use the JSON-LD writer options for expand/flatten/compact but also for generating the JSON-LD output by passing them to `JsonLdProcessor.fromRDF()`. This will make sure that options like “use native types” will be honored.
----
=> GH-3708 Pass JSON-LD writer options to JSON-LD processor

core/http/client/src/main/java/org/eclipse/rdf4j/http/client/SharedHttpClientSessionManager.java, core/http/client/src/test/java/org/eclipse/rdf4j/http/client/SPARQLProtocolSessionTest.java
GitHub issue resolved: #3711
When a request fails because the underlying connection was shut down on
the server due to inactivity only once a retry is attempted.
If the connection is not empty, the next connection from the pool will
be used for the retry. However, this connection can be older than the
idle threshold on the server too. In that case we need to clean up this
pooled connection as well and retry with another connection.
In the worst case the pool is full of connections that are already idled
out on the server. We then need to clean the pool and retry with a fresh
connection.
This is a follow up fix to #3699
----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING. …
=> GH-3711 Retry pooled, shut down connections

core/model/src/main/java/org/eclipse/rdf4j/model/util/Literals.java, core/model/src/test/java/org/eclipse/rdf4j/model/util/LiteralsTest.java, core/rio/api/src/main/java/org/eclipse/rdf4j/rio/LanguageHandler.java, core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/BasicParserSettings.java
GitHub issue resolved: #3695  
- full normalization according to rules in RFC 5646 (section 2.1.1) implemented
- extended test coverage
- clarified javadoc in language handlers and parser settings
----
=> GH-3695 improved BCP47 language tag normalization

core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractSearchIndex.java, core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSail.java, core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSailBuffer.java, core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSailConnection.java, core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/SearchIndex.java, core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/TypeBacktraceMode.java, core/sail/lucene-api/src/test/java/org/eclipse/rdf4j/sail/lucene/LangSpecTest.java, core/sail/lucene-api/src/test/java/org/eclipse/rdf4j/sail/lucene/SearchQueryEvaluatorTest.java, core/sail/lucene/src/test/java/org/eclipse/rdf4j/sail/lucene/TypeSpecTest.java, site/content/documentation/programming/lucene.md
GitHub issue resolved: #3720 
It add parameters in the LuceneSail to filter the indexed element by languages and types.
- ``INDEXEDLANG``: Check when we are indexing a Literal that the language of the literal is one of the elements in the parameters. 
Example: ``INDEXEDLANG=fr en`` to filter only French and English literals.
- ``INDEXEDTYPES``: Check for the triple (?s my:pred my:type) in the store or update query before adding an element to the store, my:pred and my:type can be configured. 
Example:``INDEXEDTYPES="http\\://example.org/oftype=http\\://example.org/type1"``, will filter all the subjects ?s without the triple (?s http://example.org/oftype, http://example.org/type1) in the store or the query.
Another parameter …
=> GH-3720 add Lucene language and type filtering

core/sail/api/src/main/java/org/eclipse/rdf4j/sail/features/ThreadSafetyAware.java, core/sail/api/src/main/java/org/eclipse/rdf4j/sail/helpers/SailConnectionWrapper.java, core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/MemoryStoreConnection.java, core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/NativeStoreConnection.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSailConnection.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/TransactionValidationLimitTest.java
GitHub issue resolved: #2874 
- an interface with a single method to signal support
- implemented in the MemoryStore and NativeStore, wrapper connections and the ShaclSail
- no tests planned for this at the moment
----
=> GH-2874 interface to signal a SailConnection that supports concurrent reads

core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSail.java, core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSailSchema.java, core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/QuerySpec.java, core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/QuerySpecBuilder.java, core/sail/lucene/src/test/java/org/eclipse/rdf4j/sail/lucene/LuceneIndexIdFilteringTest.java
GitHub issue resolved: #3729 
In this pull request, I've added a new property to the LuceneSail ``search:indexid`` to select a LuceneSail by ID.
To set an ID, a new parameter was added: ``LuceneSail.INDEX_ID`` and configured with an IRI:
```java
luceneSail.setParameter(LuceneSail.INDEX_ID, "http://example.org/myluceneindex");
```
Now we can select the Lucene index in a SPARQL query by using ``search:indexid``:
```sparql
SELECT ?result {
?result search:matches ?match .
?match search:indexid ex:myluceneindex .
?match search:query 'text' .
}
```
This feature can be used with multiple LuceneSail, we create 3 sails, *ls1*, *ls2* and *ls3* and we chain them like this:
```java
// tripleSource is the next sail
// ...
ls3.setBaseSail(tripleSource); …
```
=> GH-3729 allow setting a Lucene index id and select it

pom.xml
GitHub issue resolved: #3737  
Replace the use of of the `source` and `target` compiler arguments with the (new since Java 9) `release` argument. This will ensure that when we do 3.7.x releases, the produced artifacts will be compatible with Java 8 (even if the artifacts are compiled using a newer JVM).
A potential downside: this flag will cause an error if you are _actually_ using Java 8 to compile the code, as the `release` argument was only introduced in Java 9. However, given that we are all running more modern Javas on our machines, and that our Jenkins deployment jobs also have been configured to use Java 11, I think  this may be the simplest way to fix the issue.
See https://stackoverflow.com/questions/43102787/what-is-the-release-fl …
=> GH-3737 use release flag to compile for Java 8

tools/workbench/src/main/webapp/transformations/url-encode.xsl
GitHub issue resolved: #3676
Use a divide and conquer approach to iterate through the xslt string in order to prevent a stackoverflow for large strings.  see: https://stackoverflow.com/a/9081077/5237756
----
=> A patch for url-encode.xsl potential to stackoverflow

pom.xml
GitHub issue resolved: #3763  
Bump version of Spring framework to 5.3.18 to address possible security vulnerability.
----
=> GH-3763 update spring to 5.3.18

core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/FileIO.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/MemoryRDFStarSupportTest.java, testsuites/repository/src/main/java/org/eclipse/rdf4j/repository/RDFStarSupportTest.java
GitHub issue resolved: #3765  
- added support for reading/writing RDF-star triples in memory store custom persistence format
- extended rdf-star tests to explicitly run with a persistence-enabled memory store
----
=> GH-3765 add support for rdf-star triple persistence in memorystore

core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbUtil.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/TripleStore.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/TxnRecordCache.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/ValueStore.java
GitHub issue resolved: #3793 
Choose a larger new size and also correctly block read transactions in value store while resizing.
----
=> Improve autogrow logic of LMDB store 

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/function/Function.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/function/numeric/Rand.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/function/rdfterm/STRUUID.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/function/rdfterm/UUID.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StrictEvaluationStrategy.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/function/numeric/RandTest.java, core/spin/src/main/java/org/eclipse/rdf4j/spin/function/spif/GenerateUUID.java, core/spin/src/main/java/org/eclipse/rdf4j/spin/function/spif/Random.java
GitHub issue resolved: #3809 
If we prepare/precompile a functioncall then functions may be turned into constant values. This is never valid for a number of functions such as UUID or RAND(). A new method is added to the Function interface that is used to mark such cases, and avoids constant folding.
----
=> GH-3809 introduce a method to state that each invocation of a query

site/content/documentation/programming/rdfstar.md
GitHub issue resolved: #3817 
- fix type in FileOutputStream
- use correct casing in RDFFormat
----
=> GH-3817: fix all-uppercase and typo in FileOutputStream

core/model/src/main/java/org/eclipse/rdf4j/model/impl/NumericLiteral.java
Signed-off-by: Jerven Bolleman <jerven.bolleman@sib.swiss>
GitHub issue resolved: #3594 
For a NumericLiteral store only the Number value and datatype.
----
=> GH-3594 Only do toString on the Number value when getLabel is called

pom.xml
GitHub issue resolved: #3830 
- re-enable japicmp plugin for compatibility checks against 4.0.0
- bumped version of plugin which fixes several issues we had to put exceptions in for earlier
- removed exceptions and simplified config
----
=> GH-3830 re-enable japicmp checks, new version no longer needs exceptions

pom.xml
GitHub issue resolved: #3847 
----
=> GH-3847 skip japicmp and formatters when using the quick profile in maven

core/sail/api/src/main/java/org/eclipse/rdf4j/common/concurrent/locks/AbstractReadWriteLockManager.java, core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/WeakObjectRegistry.java
GitHub issue resolved: #3835 
----
=> GH-3835 use full fence to ensure memory ordering for new LongAdder based locks

core/sail/api/src/main/java/org/eclipse/rdf4j/sail/helpers/AbstractNotifyingSailConnection.java, core/sail/api/src/main/java/org/eclipse/rdf4j/sail/helpers/AbstractSailConnection.java, core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/SailSourceConnection.java
GitHub issue resolved: #3867 
- improve change tracking to reduce unneeded flushing
- reduce use of synchronization
----
=> GH-3867 improve generic flushing performance

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/QueryValueEvaluationStep.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryEvaluationContext.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StrictEvaluationStrategy.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/function/datetime/NowTest.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/MinimalContextNowTest.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StrictEvaluationStrategyTest.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/HashJoinIterationTest.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/JoinIteratorTest.java
GitHub issue resolved: #3811 
Ensure the now value is instantiated to the same value but lazily at a low cost.
----
=> GH-3811 ensure thread safety of the shared now value.

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/QueryEvaluationStep.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StrictEvaluationStrategy.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/FilterIterator.java
GitHub issue resolved: #3601
In the FilterIterator a new QueryBindingSet was made to hide few potential bindings. Which might have been a problem in subquery cases. Now we just hide access to the fields by introducing a new FilteredQueryContext. 
This patch series also prepares the `Exist` to show the benefit in the two benchmarks.
From the memory sail benchmarks.
| Benchmark | before | after |
|----------------|---------|-------|
| QueryBenchmark.lots_of_optional | 349.636 | 303.136 |
| QueryBenchmark.simple_filter_not | 18.268  | 14.130 |
----
=> Gh 3601 filter no new bindingset per iteraration next

core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/MemEvaluationStatistics.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/BenchmarkIT.java
GitHub issue resolved: #3902 
Original code first looked up all four S,P,O,C in the memory value factory before finding out what the smallest statement list size was. I rewrote it to look up one value at a time instead of all four at once, that way we could return earlier if the statement list size was 0. 
I forgot to take account of that the memory value factory returns null when the value is unknown, which entails that there can't be any statements with the value. Fixed that now.
----
=> GH-3902 fix MemEvaluationStatistics regression

core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemValueFactory.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/model/MemValueFactoryTest.java
GitHub issue resolved: #3917 
- Change MemValueFactory to use a SimpleValueFactory internally, instead of a (validating) `Values` utility method
----
=> GH-3917 MemValueFactory should not validate on IRI creation

core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbSailStore.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/TripleStore.java
GitHub issue resolved: #3911 
Use the active write transaction for reading the statements that should be removed.
----
=> GH-3911 LMDB store: do not use additional read transaction for removals

core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/BaseConcurrentBenchmark.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/ConcurrentQueryBenchmark.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/LoadingBenchmark.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/MemValueFactoryConcurrentBenchmark.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/NotifyingSailBenchmark.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/ParallelMixedReadWriteBenchmark.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/QueryBenchmark.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/QueryWriteBenchmark.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/SortBenchmark.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/SparqlOverheadBenchmark.java, core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/Expressions.java, spring-components/rdf4j-spring/src/main/java/org/eclipse/rdf4j/spring/dao/support/RelationMapBuilder.java, spring-components/rdf4j-spring/src/main/java/org/eclipse/rdf4j/spring/tx/TransactionObject.java, spring-components/rdf4j-spring/src/test/java/org/eclipse/rdf4j/spring/dao/support/ServiceLayerTests.java
GitHub issue resolved: #3935 
Removing the `SmartTransactionObject` dependencie from `TransactionObject` and extend `Expressions`
----
=> GH-3935 Remove SmartTransactionObject from TransactionObject

core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/MemorySailStore.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/ParallelMixedReadWriteBenchmark.java
GitHub issue resolved: #3860 
- further improve when to prioritise snapshot cleanup
- improve benchmark
----
=> GH-3860 prioritse cleanup when low on memory

core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java, core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLParserTest.java
GitHub issue resolved: #3954 
- use recursion to check if a projected variable is effectively a constant, an aggregation or declared in the group by expression
----
=> GH-3954 fix for query regression with group by

core/model-api/src/main/java/org/eclipse/rdf4j/model/base/CoreDatatype.java, core/model-api/src/test/java/org/eclipse/rdf4j/model/LiteralTest.java, core/model/src/main/java/org/eclipse/rdf4j/model/impl/SimpleLiteral.java
GitHub issue resolved: #3948 
- SimpleLiteral could not be serialized when the CoreDatatype was NONE, fix is to make CoreDatatype.NONE an enum
----
=> GH-3948 Serializable CoreDatatype.NONE

compliance/repository/src/test/java/org/eclipse/rdf4j/repository/http/HTTPTupleQueryResultTest.java, core/sail/api/src/main/java/org/eclipse/rdf4j/sail/helpers/AbstractSailConnection.java, core/sail/api/src/main/java/org/eclipse/rdf4j/sail/helpers/CleanerIteration.java, core/sail/api/src/test/java/org/eclipse/rdf4j/common/concurrent/locks/TestHelper.java, core/sail/elasticsearch-store/src/test/java/org/eclipse/rdf4j/sail/elasticsearchstore/compliance/ElasticsearchStoreTupleQueryResultIT.java, core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/LmdbTupleQueryResultTest.java, core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/NativeTupleQueryResultTest.java, testsuites/repository/src/main/java/org/eclipse/rdf4j/testsuite/repository/TupleQueryResultTest.java
GitHub issue resolved: #3590 
Instead of tracking all iterations in a map we instead tell the JVM to automatically close them if the users has forgotten. We register the iterations with the [Java Cleaner](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/ref/Cleaner.html) (introduced in Java 9 as a better alternative to finalize) together with a Runnable that closes the iteration. The Cleaner executes the runnable when the iteration has become phantom reachable (e.g. eligible for GC). We use our existing ConcurrentCleaner which wraps an array of Cleaner instances to spread the load when objects are registered from multiple threads.
I've retained the tracking functionality for debugging purposes and it can be enabled …
=> GH-3590 Use Cleaner instead of Map for closing unreachable iterations

core/model-api/src/main/java/org/eclipse/rdf4j/model/base/CoreDatatype.java, core/model-api/src/main/java/org/eclipse/rdf4j/model/base/CoreDatatypeHelper.java, core/model-api/src/main/java/org/eclipse/rdf4j/model/base/InternedIRI.java, core/model-vocabulary/src/main/java/org/eclipse/rdf4j/model/vocabulary/Vocabularies.java, testsuites/benchmark/src/main/java/org/eclipse/rdf4j/benchmark/ReasoningBenchmark.java
GitHub issue resolved: #3987 
- New (internalOnly) class InternedIRI which interns the stringValue and pre-calculates the hashCode
- Use InternedIRI in Vocabularies and in CoreDatatype
----
=> GH-3987 introduce InternedIRI for use in Vocabularies to improve performance

core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSail.java, core/sail/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/impl/LuceneIndex.java, core/sail/lucene/src/test/java/org/eclipse/rdf4j/sail/lucene/LuceneFuzzinessPrefixTest.java
GitHub issue resolved: #3940
Add an option to configure the fuzzy prefix length of the lucene sail
----
=> GH-3940 add fuzzy prefix option to lucene sail

spring-components/spring-boot-sparql-web/src/main/java/org/eclipse/rdf4j/http/server/readonly/EvaluateResultHttpResponse.java, spring-components/spring-boot-sparql-web/src/main/java/org/eclipse/rdf4j/http/server/readonly/QueryResponder.java, spring-components/spring-boot-sparql-web/src/main/java/org/eclipse/rdf4j/http/server/readonly/sparql/EvaluateResult.java, spring-components/spring-boot-sparql-web/src/main/java/org/eclipse/rdf4j/http/server/readonly/sparql/QueryTypes.java, spring-components/spring-boot-sparql-web/src/main/java/org/eclipse/rdf4j/http/server/readonly/sparql/SparqlQueryEvaluator.java, spring-components/spring-boot-sparql-web/src/main/java/org/eclipse/rdf4j/http/server/readonly/sparql/SparqlQueryEvaluatorDefault.java
GitHub issue resolved: #4004
Providing a SparqlQueryEvaluator that can be used independently of the servlet api and can therefore also be used in other contexts such as apache-camel, etc. Seperation of Concerns.
----
=> GH-4004 Make QueryTypes independend of HTTP and provide it in a reusable

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/EvaluationStatistics.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/ZeroLengthPathIteration.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/QueryJoinOptimizer.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/EvaluationStatisticsTest.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/EvaluationStrategyWithRDFStarTest.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/AbstractQueryModelNode.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/ArbitraryLengthPath.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/BindingSetAssignment.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/StatementPattern.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/TripleRef.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Var.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/QueryBenchmark.java
GitHub issue resolved: #3984 
- add support for caching cardinality for StatementPattern, TripleRef and BindingSetAssignment
- reduce the use of HashMap for caching cardinality in QueryJoinOptimizer
----
=> GH-3984 improve caching of cardinality

core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/PrefixDeclProcessor.java, core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLParser.java, core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLParserFactory.java, core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLParserTest.java
GitHub issue resolved: #3992
This PR add a constructor to the SPARQLParser class and a new method in the SPARQLParserFactory to add custom default prefixes to the parser.
```java
// SPARQLParser
SPARQLParser(Set<Namespace> customDefaultPrefixes)
// SPARQLParserFactory
QueryParser getParser(Set<Namespace> customDefaultPrefixes);
```
Example
```java
// create a set with the ex namespace 
Set<Namespace> customDefaultPrefixes = new HashSet<>();
customDefaultPrefixes.add(Values.namespace("ex", "http://example.org/"));
// create a parser with the default prefixes
SPARQLParser parser = new SPARQLParser(customDefaultPrefixes);
// we can use the default prefix without having to specify it
parser.parseQuery("SELECT ?s {?s ex:aaa ex:ooo}", null);
// …
```
=> GH-3992 add sparql parser default prefixes

core/common/iterator/src/main/java/org/eclipse/rdf4j/common/iteration/AbstractCloseableIteration.java, core/common/iterator/src/main/java/org/eclipse/rdf4j/common/iteration/CloseableIteratorIteration.java, core/common/iterator/src/main/java/org/eclipse/rdf4j/common/iteration/DualUnionIteration.java, core/common/iterator/src/main/java/org/eclipse/rdf4j/common/iteration/EmptyIteration.java, core/common/iterator/src/main/java/org/eclipse/rdf4j/common/iteration/Iterations.java, core/common/iterator/src/main/java/org/eclipse/rdf4j/common/iteration/LookAheadIteration.java, core/common/iterator/src/main/java/org/eclipse/rdf4j/common/iteration/QueueIteration.java, core/common/iterator/src/main/java/org/eclipse/rdf4j/common/iteration/SingletonIteration.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Var.java, core/sail/base/src/main/java/org/eclipse/rdf4j/sail/TripleSourceIterationWrapper.java, core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/SailDatasetTripleSource.java, core/sail/base/src/main/java/org/eclipse/rdf4j/sail/evaluation/SailTripleSource.java, core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/MemorySailStore.java, core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemStatement.java, core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemStatementIterator.java, core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemStatementIteratorCache.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/UnionNode.java
GitHub issue resolved: #4047 
----
=> GH-4047 simplify iteratios to reduce JVM generated itable stubs

core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSail.java
GitHub issue resolved: #4010 
Instead of having Exception in the LuceneSail's reindex, I've used the SailException, I used the SailException and not the IOException like the Javadoc suggested to keep the consistency with the other sail methods.
----
=> GH-4010 replace Exception to SailException in LuceneSail reindex method

core/query/src/main/java/org/eclipse/rdf4j/query/QueryResult.java, core/query/src/main/java/org/eclipse/rdf4j/query/QueryResults.java
GitHub issue resolved: #4065  
- redefine method previously inherited from now deprecated classes to avoid deprecation warnings in places we don't want them. 
----
=> GH-4065 public api deprecation fixes

tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/TransactionController.java, tools/server-spring/src/test/java/org/eclipse/rdf4j/http/server/repository/transaction/TestTransactionControllerErrorHandling.java
GitHub issue resolved: #4073 
Send MalformedQuery error info with error message to the client when a query with syntax error is processed through TransactionController.
----
=> GH-4073 Propagate the correct query syntax error to the client

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/StandardQueryOptimizerPipeline.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/QueryPlanRetrievalTest.java
GitHub issue resolved: #4084 
----
=> GH-4084 revert optimizer pipeline order

site/content/documentation/programming/model.md
GitHub issue resolved: #4086 
- use correct variable name and correct number of parameters
----
=> GH-4086: fix code example

core/model/src/main/java/org/eclipse/rdf4j/model/util/Statements.java
GitHub issue resolved: #4089 
- no code changes, just removed incorrect whitespaces
----
=> GH-4089: remove whitespace in javadoc link

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/function/Function.java, examples/src/main/java/org/eclipse/rdf4j/examples/function/ExistingPalindromeFunction.java, examples/src/main/java/org/eclipse/rdf4j/examples/function/PalindromeFunction.java, site/content/documentation/tutorials/custom-sparql-functions.md
GitHub issue resolved: #3826  
- ~added default implementation of deprecated `evaluate` method (to allow implementations to avoid overriding it if they already implement the new variant with a `TripleSource` argument)~
- slightly updated the tutorial and example code
----
=> GH-3826 update tutorial, add default impl for deprecated method

docker/Dockerfile
GitHub issue resolved: #4110 
- use multi-stage build: move copy/unzip part from build to a temp docker image
- don't use apt update in final image (was only needed to add unzip tool, which is only needed in temp image)
----
=> GH-4110: use multi-stage build to reduce image size

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/PathIteration.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/ZeroLengthPathIteration.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/CompareOptimizer.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/ConstantOptimizer.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/ParentReferenceChecker.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/RegexAsStringFunctionOptimizer.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/StandardQueryOptimizerPipeline.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/FilterOptimizerTest.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/ValueExprTripleRef.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Var.java, core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/GraphPattern.java, core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java, testsuites/repository/src/main/java/org/eclipse/rdf4j/testsuite/repository/RDFStarSupportTest.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/EmptyStatementPattern.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/ExclusiveArbitraryLengthPath.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/FedXStatementPattern.java
GitHub issue resolved: #4112 
- add test
- add missing replaceChild method (which was the main issue)
- remove the parent reference cleaner from the standard query optimizers
- add a parent reference checker to the standard query optimizers if assertions are enabled (so that our tests fail)
- prevent sharing or reuse of a Var object by checking (assert) that the parent ref was null before setting it
----
=> GH-4112 fix query regression for CONSTRUCT query with RDF*

pom.xml
RDF4J currently uses an old version of the apache felix plugin, this is just a dependency update for this.
By the way maybe you want enable https://github.com/dependabot for this repository to get such notifications automatically?
=> Update Apache Felix Version

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/ArrayBindingBasedQueryEvaluationContext.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/ConstantOptimizer.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/OrderLimitOptimizer.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/SameTermFilterOptimizer.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/ProjectionIterator.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/ConstantOptimizer.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/OrderLimitOptimizer.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/SameTermFilterOptimizer.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/MultiProjection.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Projection.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/ProjectionElem.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/ProjectionElemList.java, core/queryalgebra/model/src/test/java/org/eclipse/rdf4j/query/algebra/ProjectionElemListTest.java, core/queryalgebra/model/src/test/java/org/eclipse/rdf4j/query/algebra/ProjectionElemTest.java, core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java, core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLParserTest.java, core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/TestSparqlStarParser.java, core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilderTest.java, core/queryrender/src/main/java/org/eclipse/rdf4j/queryrender/BaseTupleExprRenderer.java, core/queryrender/src/main/java/org/eclipse/rdf4j/queryrender/sparql/SPARQLQueryRenderer.java, core/queryrender/src/main/java/org/eclipse/rdf4j/queryrender/sparql/experimental/PreprocessedQuerySerializer.java, core/queryrender/src/main/java/org/eclipse/rdf4j/queryrender/sparql/experimental/SerializableParsedConstructQuery.java, core/queryrender/src/main/java/org/eclipse/rdf4j/queryrender/sparql/experimental/SerializableParsedTupleQuery.java, core/spin/src/main/java/org/eclipse/rdf4j/spin/SpinParser.java, core/spin/src/main/java/org/eclipse/rdf4j/spin/SpinRenderer.java
GitHub issue resolved: #4066  
- re-introduce use of Extension for all non-var SELECT expressions
- refactor of ProjectionElem and ProjectionElemList to clarify use of name vs targetName
----
=> GH-4066 re-introduce use of Extension for all select expressions

core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config/lmdb.ttl, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/config/LmdbStoreFactory.java, tools/workbench/src/main/webapp/transformations/create-lmdb.xsl, tools/workbench/src/main/webapp/transformations/create.xsl
GitHub issue resolved: #4119 
----
=> GH-4119 LMDB store in Workbench

core/model-vocabulary/src/main/java/org/eclipse/rdf4j/model/vocabulary/RSX.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/XmlDatatypeUtilFunction.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/DatatypeConstraintComponent.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/DatatypeFilter.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/ExternalFilterByPredicate.java, core/sail/shacl/src/main/resources/META-INF/services/org.eclipse.rdf4j.query.algebra.evaluation.function.Function, core/sail/shacl/src/test/resources/test-cases/datatype/simple/invalid/case6/query1.rq, core/sail/shacl/src/test/resources/test-cases/datatype/simple/invalid/case6/report.ttl, core/sail/shacl/src/test/resources/test-cases/datatype/simple/invalid/case7/query1.rq, core/sail/shacl/src/test/resources/test-cases/datatype/simple/invalid/case7/report.ttl, core/sail/shacl/src/test/resources/test-cases/datatype/simple/invalid/case8/query1.rq, core/sail/shacl/src/test/resources/test-cases/datatype/simple/invalid/case8/report.ttl, core/sail/shacl/src/test/resources/test-cases/datatype/simple/shacl.trig
GitHub issue resolved: #4149 
SHACL spec says that we should check for ill-typed literals if they are the datatype is one of the supported XSD datatypes. Easiest way to do this is to use the `XMLDatatypeUtil.isValidValue(...)` method. To allow this to be used in the SPARQL query we also introduce a custom function in the RSX namespace that calls this method.
----
=> GH-4149 Check for ill-typed literals during SHACL datatype validation

tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/TransactionStartController.java, tools/server-spring/src/test/java/org/eclipse/rdf4j/http/server/repository/transaction/TransactionStartControllerTest.java
patch for: https://github.com/eclipse/rdf4j/issues/4146
resubmitting with correct credentials to satisfy eca
=> GH-4146 Fixes for REST Isolation-level settings

core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java, testsuites/repository/src/main/java/org/eclipse/rdf4j/testsuite/repository/RDFStarSupportTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/tests/PropertyPathTest.java
GitHub issue resolved: #4187 and resolved #4184 and resolved #4189 
- fix a general problem with potential Var object reuse by cloning at the origin of the issue
- add tests
- cleanup and fix existing tests
----
=> GH-4187 and GH-4184 clone Var object at origin to prevent reuse

compliance/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/function/CustomAggregateFunctionEvaluationTest.java, core/queryalgebra/evaluation/pom.xml, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/function/aggregate/StatisticCollector.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/function/aggregate/StatisticalAggregateFunction.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/function/aggregate/stdev/PopulationStandardDeviationAggregateFactory.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/function/aggregate/stdev/StandardDeviationAggregateFactory.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/function/aggregate/stdev/StandardDeviationCollector.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/function/aggregate/variance/PopulationVarianceAggregateFactory.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/function/aggregate/variance/VarianceAggregateFactory.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/function/aggregate/variance/VarianceCollector.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/util/MathUtil.java, core/queryalgebra/evaluation/src/main/resources/META-INF/services/org.eclipse.rdf4j.query.parser.sparql.aggregate.AggregateFunctionFactory
GitHub issue resolved: #4131
Introduce support for custom Variance & Standard Deviation aggregate functions through magic predicates.
In total 4 magic predicates have been added with support for standard deviation & variance calculation based on sample & population formulas.
The added magic predicates and subsequent functions include:
- <http://rdf4j.org/aggregate#variance_sample> - used to calculate variance based on sample assumption (e.g. N-1 variation)
- <http://rdf4j.org/aggregate#variance> - used to calculate variance based on population assumption 
-  <http://rdf4j.org/aggregate#stdev> - used to calculate standard deviation based on population assumption 
-  <http://rdf4j.org/aggregate#stdev_sample> - used to calculate standard …
=> GH-4131 Introduce Variance & Standard Deviation aggregate functions

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/evaluationsteps/StatementPatternQueryEvaluationStep.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/PathIteration.java
GitHub issue resolved: #4197 
- use null instead of EmptyIteration to signal when PathIteration is finished
----
=> GH-4197 use null instead of EmptyIteration to signal when PathIteration is finished

core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/Pool.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/Statistics.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/TripleStore.java, core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/CardinalityTest.java
GitHub issue resolved: #3982 
The computation now uses several buckets to collect samples at multiple locations within the possible key range.
The cardinality estimate is based on the average distance of the sampled keys.
----
=> GH-3982 Rework cardinality computation for LMDB triple store.

tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/namespaces/NamespaceController.java, tools/server-spring/src/test/java/org/eclipse/rdf4j/http/server/repository/namespaces/NamespaceControllerTest.java
GitHub issue resolved: #3781
The NamespaceController is now validating the prefix and namespace before updating it.
----
=> GH-3781 add namespace validation

core/sail/elasticsearch/src/main/java/org/eclipse/rdf4j/sail/elasticsearch/ElasticsearchIndex.java, core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractSearchIndex.java, core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSailSchema.java, core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/QuerySpec.java, core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/QuerySpecBuilder.java, core/sail/lucene-api/src/test/java/org/eclipse/rdf4j/sail/lucene/LangSpecTest.java, core/sail/lucene-api/src/test/java/org/eclipse/rdf4j/sail/lucene/QuerySpecBuilderTest.java, core/sail/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/impl/LuceneIndex.java, core/sail/lucene/src/test/java/org/eclipse/rdf4j/sail/lucene/MultiParamTest.java, core/sail/solr/src/main/java/org/eclipse/rdf4j/sail/solr/SolrIndex.java, site/content/documentation/programming/lucene.md
GitHub issue resolved: #4182
I've added a new format for the Lucene query, instead of putting one query in a Lucene request, we can add more complex per-field queries.
It's the same format as the one presented in #4182.
```SPARQL
PREFIX search: <http://www.openrdf.org/contrib/lucenesail#>
SELECT * {
?subj search:matches [
search:query [
search:property my:property1
search:query "search terms for my:property1..."
search:boost 0.8;
search:snippet ?snippetp1
] , [
search:property my:property2
search:query "search terms for my:property2..."
search:boost 0.2;
search:snippet ?snippetp2
] ;
search:score ?score
] .
}
```
It adds a new predicate `search:boost` to boost a field compared to another one, it can be useful if the query is the same on 2 …
=> GH-4182 Add complex Lucene queries

SECURITY.md
Update the list of supported versions for security patch releases.
1. is this the correct list (in particular do we actually want to support doing security patch release for RDF4J 3.7.x?)
2. is this generic replacement easy enough to understand (intent is to make it easier for us to maintain without losing clarity for our users)?
----
=> Update security policy wrt supported patch releases

tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/TripleSourceBase.java, tools/federation/src/test/java/org/eclipse/rdf4j/federated/BasicTests.java, tools/federation/src/test/resources/tests/basic/query_describe1_singleSource.ttl
GitHub issue resolved: #4214
Previously DESCRIBE queries (when targeting a single source, i.e. a single federation member) could run into a QueryEvaluationException.
This change now completes the code path for evaluating single source DESCRIBE queries in the the TripleSource by treating them in the same way as CONSTRUCT queries.
Scenario covered with a simulated unit test.
----
=> GH-4214: fix DESCRIBE queries in FedX when targeting a single source

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/function/xsd/DateCast.java, core/queryalgebra/evaluation/src/main/resources/META-INF/services/org.eclipse.rdf4j.query.algebra.evaluation.function.Function, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/function/xsd/TestDateCast.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/util/QueryEvaluationUtilityTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/tests/BuiltinFunctionTest.java
GitHub issue resolved: #4158
Added cast function for xsd:date.
----
=> GH-4158 add xsd:date cast function

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/PropertyShape.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/AbstractShaclTest.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/ShaclTest.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/UnknownShapesTest.java, core/sail/shacl/src/test/resources/complexPath.trig
GitHub issue resolved: #4240 
- add tests
- add checks to skip property shapes with unsupported path expressions
----
=> GH-4240 skip property shape if sh:path is not implemented/supported

docker/README_DEV.md, site/content/documentation/developer/releases.md
GitHub issue resolved: #4243 
- align info on RDF4J website and Readme in docker directory
- added section on building/pushing multi-platform docker images
----
=> GH-4243: update and align the docker documentation

tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/TransactionStartController.java, tools/server-spring/src/test/java/org/eclipse/rdf4j/http/server/repository/transaction/TransactionStartControllerTest.java
GH-4230: Refactor isolation-level settings in TransactionStartController in order to check the correct request parameter
GitHub issue resolved: #4230 
----
=> GH-4230 Make isolation-level setting to be compatible with different versions of client and server side

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/QueryEvaluationStep.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/function/aggregate/StatisticalAggregateFunction.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/evaluationsteps/LeftJoinQueryEvaluationStep.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/evaluationsteps/StatementPatternQueryEvaluationStep.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/HashJoinIteration.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/PathIteration.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/util/MathUtil.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/util/OrderComparator.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StrictEvaluationStrategyTest.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/BinaryTupleOperator.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/UnaryTupleOperator.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/UnaryValueOperator.java, core/queryparser/api/src/main/java/org/eclipse/rdf4j/query/impl/AbstractParserQuery.java, core/queryparser/api/src/main/java/org/eclipse/rdf4j/query/impl/AbstractParserUpdate.java, core/queryparser/api/src/main/java/org/eclipse/rdf4j/query/parser/ParsedQuery.java, core/queryparser/api/src/main/java/org/eclipse/rdf4j/query/parser/ParsedUpdate.java, core/repository/dataset/src/main/java/org/eclipse/rdf4j/repository/dataset/DatasetQuery.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/query/parser/sparql/manifest/SPARQL11UpdateComplianceTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/query/parser/sparql/manifest/SPARQLQueryComplianceTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/query/parser/sparql/manifest/SPARQLSyntaxComplianceTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/AbstractComplianceTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/tests/AggregateTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/tests/OrderByTest.java
GitHub issue resolved: #4245 
- add hashCode() checks into the main query parsing/evaluating tests
- implement hashCode() and equals() in various classes so that the tests work
- fix the NullPointerException by first checking if the arg is null
----
=> GH-4245 fix SPARQL COUNT hashCode() NullPointerException

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSail.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSailValidationException.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/Shape.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/results/ValidationReport.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/results/ValidationResult.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/AbstractShaclTest.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/ShaclTestWithoutRdfsReasonerTest.java, core/sail/shacl/src/test/resources/test-cases/hasValue/targetNode2/invalid/case1/report.ttl, core/sail/shacl/src/test/resources/test-cases/hasValue/targetNode2/shacl.trig, core/sail/shacl/src/test/resources/test-cases/minCount/simple/invalid/case1/report.ttl, core/sail/shacl/src/test/resources/test-cases/minCount/simple/invalid/case2/report.ttl, core/sail/shacl/src/test/resources/test-cases/minCount/simple/invalid/case3/report.ttl, core/sail/shacl/src/test/resources/test-cases/minCount/simple/invalid/case4/report.ttl, core/sail/shacl/src/test/resources/test-cases/minCount/simple/shacl.trig, site/content/documentation/programming/shacl.md
GitHub issue resolved: #2642 
- sh:message is already read during parsing, but wasn't written out when the shape was converted to a model
- sh:resultMessage is now added if there are any values for sh:message in the source shape
----
=> GH-2642 improve support for sh:message and add support sh:resultMessage

testsuites/repository/src/main/java/org/eclipse/rdf4j/testsuite/repository/TupleQueryResultTest.java
GitHub issue resolved: #4242 
- track unclosed iterations so that we can wait a bit for the GC to kick in before we fail
----
=> GH-4242 fix flaky test

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StrictEvaluationStrategy.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/FilterIterator.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/CompareAll.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/CompareAny.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/CompareSubQueryValueOperator.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/Filter.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/SubQueryValueOperator.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/RepositorySPARQLComplianceTestSuite.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/tests/AggregateTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/tests/ExistsTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/tests/MinusTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/tests/OrderByTest.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/SailTripleSource.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/SparqlTripleSource.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/TripleSourceBase.java
GitHub issue resolved: #4256 
From the spec: 
> Variables in the pattern that are bound in the current [solution mapping](http://www.w3.org/TR/rdf-sparql-query/#defn_sparqlSolutionMapping) take the value that they have from the solution mapping. Variables in the pattern pattern that are not bound in the current solution mapping take part in pattern matching.
https://www.w3.org/TR/sparql11-query/#func-filter-exists
I've removed the check for `isPartOfSubQuery` because it seems to be related to some legacy code that is no longer in use. 
----
=> GH-4256 sparql exists filter scope

compliance/repository/pom.xml, compliance/sparql/pom.xml, pom.xml, tools/federation/pom.xml, tools/server/pom.xml
GitHub issue resolved: #4267 
- use jetty BOM in root pom to override older versions imported by e.g. elasticsearch dependencies
- don't use jetty.version variable anymore in other pom.xml files
----
=> GH-4267: use latest jetty dependencies

site/content/documentation/programming/spring.md, spring-components/rdf4j-spring/pom.xml, spring-components/rdf4j-spring/src/main/java/org/eclipse/rdf4j/spring/repository/remote/RemoteRepositoryConfig.java, spring-components/rdf4j-spring/src/main/java/org/eclipse/rdf4j/spring/repository/remote/RemoteRepositoryProperties.java, spring-components/rdf4j-spring/src/test/java/org/eclipse/rdf4j/spring/repository/remote/RemoteRepositoryConfigTest.java, spring-components/rdf4j-spring/src/test/resources/__files/repositories.srj
GitHub issue resolved: #4227 
Added spring config options for username & password of remote repositories
----
=> GH-4227 add config for spring repository manager username & password

core/sail/elasticsearch/src/main/java/org/eclipse/rdf4j/sail/elasticsearch/ElasticsearchIndex.java, core/sail/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSail.java, core/sail/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/impl/LuceneIndex.java, core/sail/lucene/src/test/java/org/eclipse/rdf4j/sail/lucene/impl/LuceneIndexTest.java
GitHub issue resolved: #4235
The indexing analyzer is configurable, however, this is only half the
problem because if we query with a different analyzer than what's
indexed, we will end up missing a number of results (particularly as it
pertains to stopwords and stemming). For the cases where you want
to configure the indexing analyzer, we should also be allowed to
configure the query analyzer.
----
=> Add support for custom query analyzers in Lucene and ES

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/FilterOptimizer.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/FilterOptimizerTest.java
GitHub issue resolved: #4279 
----
=> GH-4279 FilterOptimizer should not modify the query tree above the node it is currently on

core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/SailSourceConnection.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbSailStore.java, core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/NativeSailStore.java, testsuites/repository/src/main/java/org/eclipse/rdf4j/testsuite/repository/RDFStarSupportTest.java, testsuites/sail/src/main/java/org/eclipse/rdf4j/testsuite/sail/RDFStoreTest.java
GitHub issue resolved: #4248  
- added explicit check in SailSourceConnection to avoid adding Triple as a context value 
- added test coverage
----
=> GH-4248 check for invalid triple context value

CONTRIBUTING.md, site/content/documentation/developer/releases.md, site/content/documentation/developer/workflow.md
GitHub issue resolved: #4237 
- removed steps for branch/PR creation from one place, added a link to the contributor guide instead
- updated our release management doco a little
----
=> GH-4237 reorg and update of developer docs

docker/Dockerfile, docker/build.sh
- use apt-get instead of apt in Dockerfile
- ensure the target of the COPY command ends on a / to indicate it's a directory
- remove parallel build setting from maven to ensure stable build
=> small tweaks to Dockerfile and build script

tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/namespaces/NamespaceController.java, tools/server-spring/src/test/java/org/eclipse/rdf4j/http/server/repository/namespaces/NamespaceControllerTest.java
GitHub issue resolved: #3781
Validate prefixes according SPARL grammar spec
----
=> GH-3781 Accept only valid SPARQL prefixes

compliance/repository/src/test/java/org/eclipse/rdf4j/repository/sparql/SPARQLStoreConnectionTest.java, core/repository/api/src/main/java/org/eclipse/rdf4j/repository/RepositoryConnection.java, core/repository/api/src/main/java/org/eclipse/rdf4j/repository/base/AbstractRepositoryConnection.java, core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/SPARQLConnection.java, testsuites/repository/src/main/java/org/eclipse/rdf4j/testsuite/repository/RepositoryConnectionTest.java
Signed-off-by: Dzerom Dzenkins <dzeri96@proton.me>
GitHub issue resolved: #2749
As suggested by @jeenbroekstra, I've added a call to `setNamespace` for all new namespaces coming from the imported `Statement`s, and I've removed the appropriate overrides in the SPARQL repository, as it seems like the code was almost identical. Please correct me if I'm wrong.
Since this is a WIP, there are some things to clear up:
1. Where do I put the unit tests for this? I couldn't find an appropriate place with similar tests.
2. What should we do with the deprecated `Iteration` overload of the `add` method? I suspect this might get removed with the next release so I haven't added any changes there.
3. What about the `remove` method? Should we prune unused …
=> GH-2749 Include Namespaces in Statement imports from NamespaceAware collections

core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/tests/AggregateTest.java
GitHub issue resolved: #4290  
- the logic to reorder extensions for SELECT expressions and the order clause now takes into account that a new implicit group node may have been introduced
- rewrote all tests in AggregateTest to use AssertJ.
----
=> GH-4290 fix for count and order by with an implicit group clause

.github/workflows/new-issue.yml
GitHub issue resolved: #4337  
- replace and reconfigure github action to assign new issues to project board
- 
----
=> GH-4337 assign new issues to new board automatically

spring-components/spring-boot-sparql-web/src/test/java/org/eclipse/rdf4j/http/server/readonly/MemoryBackedOnlySparqlApplicationTest.java, tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/ServerInterceptor.java
GitHub issue resolved: #4376 
Before attempting to upgrade to new major versions of spring/spring-boot we should fix all use of deprecated APIs. This will ease the migration as deprecated APIs have a tendency of being removed in new major versions.
----
=> GH-4376 fix usage of deprecated spring/spring-boot APIs

.gitmodules, site/layouts/partials/head_variables.html, site/static/js/hugo-solstice-headvars.js
Website security hardening: removing use of inline javascript.
----
=> GH-4388 solstice theme upstream -> gitlab, removed inline js (CSP)

core/model/src/main/java/org/eclipse/rdf4j/model/impl/DynamicModel.java, core/model/src/test/java/org/eclipse/rdf4j/model/impl/DynamicModelTest.java
GitHub issue resolved: #4391
Preserves namespace of the `DynamicModel` after an upgrade happened.
=> GH-4391 dynamic model namespaces

core/queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqljson/AbstractSPARQLJSONParser.java, core/queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqljson/AbstractSPARQLJSONWriter.java, core/queryresultio/sparqljson/src/test/java/org/eclipse/rdf4j/query/resultio/sparqljson/SPARQLJSONParserCustomTest.java, core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDParser.java, core/rio/jsonld/src/test/java/org/eclipse/rdf4j/rio/jsonld/JSONLDParserCustomTest.java, core/rio/rdfjson/src/main/java/org/eclipse/rdf4j/rio/rdfjson/RDFJSONParser.java, core/rio/rdfjson/src/main/java/org/eclipse/rdf4j/rio/rdfjson/RDFJSONWriter.java, core/rio/rdfjson/src/test/java/org/eclipse/rdf4j/rio/rdfjson/RDFJSONParserCustomTest.java
GitHub issue resolved: #4382
This PR fixes all use of currently deprecated Jackson APIs.
----
=> GH-4382 Fix usage of deprecated Jackson APIs

core/repository/api/pom.xml, core/repository/api/src/test/java/org/eclipse/rdf4j/repository/util/RDFLoaderTest.java, core/repository/manager/pom.xml, core/repository/manager/src/test/java/org/eclipse/rdf4j/repository/manager/LocalRepositoryManagerTest.java, core/repository/manager/src/test/java/org/eclipse/rdf4j/repository/manager/RemoteRepositoryManagerTest.java, core/repository/manager/src/test/java/org/eclipse/rdf4j/repository/manager/RepositoryManagerTest.java, pom.xml
GitHub issue resolved: #4403 
This migrates WireMock tests to JUnit 5 using the documented approach: https://wiremock.org/docs/junit-jupiter/.
Also upgrading WireMock to latest stable version to make the JUnit 5 integration available.
----
=> GH-4403: Migrate WireMock tests to JUnit 5

core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/function/datetime/NowTest.java, core/rio/trig/src/test/java/org/eclipse/rdf4j/rio/trigstar/TriGStarParserTest.java, core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/benchmark/QueryBenchmark.java, core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/benchmark/QueryBenchmark.java, core/sail/nativerdf/src/test/java/org/eclipse/rdf4j/sail/nativerdf/benchmark/QueryWriteBenchmark.java, core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/constraint/ExpressionsTest.java, testsuites/benchmark/src/main/java/org/eclipse/rdf4j/benchmark/QueryOrderBenchmark.java, tools/config/src/main/java/org/eclipse/rdf4j/common/logging/file/logback/MultipleFileLogReader.java, tools/server/src/test/java/org/eclipse/rdf4j/http/server/ShaclValidationReportIT.java
GitHub issue resolved: #4414 
- swap out use of junit rules with explicit creation and deletion of temporary folders in benchmark files where junit isn't in use anyways
----
=> GH-4414 fix junit in benchmarks

docker/README_DEV.md, docker/build.sh, docker/run.sh
GitHub issue resolved: #4399  
- docker compose is a docker plugin now instead of a separate command: all usages of `docker-compose` replaced with `docker compose`.
- docker compose v2 uses a differerent naming convention for the produced image: `docker-rdf4j` instead of `docker_rdf4j`
- tested with Docker version 23.0.0, Docker Compose version v2.15.1
----
=> GH-4399 adjust docker setup to work with docker compose 2

core/http/protocol/pom.xml, core/http/protocol/src/main/java/org/eclipse/rdf4j/http/protocol/transaction/TransactionSAXParser.java, core/http/protocol/src/main/java/org/eclipse/rdf4j/http/protocol/transaction/TransactionWriter.java, core/http/protocol/src/test/java/org/eclipse/rdf4j/http/protocol/transaction/TransactionWriterTest.java, core/rio/api/pom.xml, core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/AbstractRDFParser.java, core/rio/api/src/test/java/org/eclipse/rdf4j/rio/helpers/AbstractRDFParserTest.java
GitHub issue resolved: #4421
This PR eliminates dependencies to` javax.xml.bind` from core libraries. Main motivation being to ease the javax->jakarta migration, ref. #3559.
- Base64 encoding now uses the standard Java library support added in Java 8
- To perform Hex encoding, I am proposing to use commons-codec for now,. But it should be fairly simple to write our own utility method if that is an unwanted dependency. And migrate to the standard Java library support added in Java 17 - once Java 17 becomes the minimum supported version.
----
Kudos to @aschwarte10 for the test additions.
=> GH-4421: Eliminate dependencies to javax.xml.bind from core libraries

core/http/client/pom.xml, core/http/client/src/test/java/org/eclipse/rdf4j/http/client/RDF4JProtocolSessionTest.java, core/http/client/src/test/java/org/eclipse/rdf4j/http/client/SPARQLProtocolSessionTest.java, core/pom.xml, core/repository/api/pom.xml, core/repository/api/src/test/java/org/eclipse/rdf4j/repository/util/RDFLoaderTest.java, core/repository/manager/pom.xml, core/repository/manager/src/test/java/org/eclipse/rdf4j/repository/manager/RemoteRepositoryManagerTest.java, pom.xml, spring-components/rdf4j-spring/pom.xml, spring-components/rdf4j-spring/src/test/java/org/eclipse/rdf4j/spring/repository/remote/RemoteRepositoryConfigTest.java
GitHub issue resolved: #4431 
This PR migrates all use of WireMock in the codebase to MockServer. MockServer is built on Netty, and provides no-dependency shaded jars, which will ease upgrading Jetty (https://github.com/eclipse/rdf4j/issues/4252), upgrade Java/Jakarta EE and migrate from Java EE to Jakarta EE (https://github.com/eclipse/rdf4j/issues/3559).
The MockServer code is a bit more verbose, but fairly equivalent to WireMock. MockServer lacks the ability to load mocked response bodies from file, so in order to not change "everything" in this PR, I added small utility methods to adapt this missing feature. This can be changed/improved in a follow-up PR.
----
PR Author Checklist (see the [contributor …
=> GH-4431: Replace WireMock with MockServer

core/common/iterator/src/test/java/org/eclipse/rdf4j/common/iteration/SilentIterationTest.java, core/pom.xml, tools/console/src/test/java/org/eclipse/rdf4j/console/command/DropTest.java, tools/console/src/test/java/org/eclipse/rdf4j/console/command/LoadTest.java, tools/console/src/test/java/org/eclipse/rdf4j/console/command/VerifyTest.java, tools/console/src/test/java/org/eclipse/rdf4j/console/setting/AbstractSettingTest.java, tools/federation/src/test/java/org/eclipse/rdf4j/federated/write/RepositoryWriteStrategyTest.java
GitHub issue resolved: #4427 
The initial motivation was to remove usage of deprecated Mockito API. But during my investigation, I found some obvious migrations to the Mockito JUnit 5 integration - that's fixing warnings suppressions.
----
=> GH-4427: Don't use deprecated Mockito API

.github/workflows/dash-license.yml, pom.xml
GitHub issue resolved: #4452
This adds an initial workflow that runs Dash license-check. If have haven't done anything wrong, I had to add an exclude to make CI pass. The artifact `org.openjdk.jmh:jmh-generator-annprocess` is reported as restricted.
I suggest a separate workflow since we eventually will migrate to the [Dash License reusable workflow](https://github.com/eclipse/dash-licenses#reusable-github-workflow-for-automatic-license-check-and-ip-team-review-requests).
----
=> GH-4452: Add Dash license-check CI

pom.xml, tools/pom.xml, tools/server-spring/pom.xml, tools/server/pom.xml, tools/workbench/pom.xml
GitHub issue resolved: #4446
This PR replaces the maven plugin that can be used to run server/workbench in a local development environment. I am now able to run server in standalone mode by executing `mvn jetty:run` from the server module, and workbench+server if running from the workbench module.
Also cleaning up some dependency issues detected by duplicate class detection on Jetty startup. There is still a problem with duplicate commons-logging classes, but that requires more delicate work to fix. Please let me know if you want the dep-changes in a dedicated PR. I have made an attempt in https://github.com/eclipse/rdf4j/pull/4443, but IMO it makes more sense to do it here - when actually running the applications.
----
PR Author Checklist …
=> GH-4446: Replace tomcat7-maven-plugin with jetty-maven-plugin

compliance/elasticsearch/pom.xml, core/repository/api/pom.xml, core/repository/api/src/test/java/org/eclipse/rdf4j/repository/util/RDFLoaderTest.java, core/sparqlbuilder/pom.xml, core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/core/SparqlBuilderTest.java, core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/examples/BaseExamples.java, core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/examples/sparql11spec/Section11Test.java, core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/examples/sparql11spec/Section12Test.java, core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/examples/sparql11spec/Section13Test.java, core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/examples/sparql11spec/Section15Test.java, core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/examples/sparql11spec/Section16Test.java, core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/examples/sparql11spec/Section17Test.java, core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/examples/sparql11spec/Section2Test.java, core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/examples/sparql11spec/Section3Test.java, core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/examples/sparql11spec/Section4Test.java, core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/examples/sparql11spec/Section5Test.java, core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/examples/sparql11spec/Section6Test.java, core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/examples/sparql11spec/Section7Test.java, core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/examples/sparql11spec/Section8Test.java, core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/examples/sparql11spec/Section9Test.java, core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/examples/updatespec/Section3Test.java, tools/console/pom.xml, tools/workbench/pom.xml
GitHub issue resolved: #4459
This removes almost all usage of Hamcrest from our codebase. There is a single custom Hamcrest matcher left, which is now encapsulated by an AssertJ Condition. I did an attempt to fix this also, but I could not make a custom AssertJ condition behave exactly like the current Hamcrest matcher - especially in the error description area.
----
=> GH-4459: Replace usage of Hamcrest with AssertJ

core/model-api/src/main/java/org/eclipse/rdf4j/model/base/AbstractLiteral.java, core/queryresultio/text/src/test/java/org/eclipse/rdf4j/query/resultio/text/tsv/SPARQLTSVCustomTest.java, core/rio/rdfxml/src/test/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParserTest.java
GitHub issue resolved: #4482
I replace the IRI by CoreDatatype, I hope it is fine without any test knowing how trivial it is.
----
=> GH-4482 Replace Datatype IRI to CoreDatatype in AbstractLiteral

compliance/elasticsearch/pom.xml
GitHub issue resolved: #4484  
- remove test dependency on obsolete snakeyaml library in elasticsearch compliance tests
----
=> GH-4484 remove unused snakeyaml dependency

core/queryresultio/binary/src/main/java/org/eclipse/rdf4j/query/resultio/binary/BinaryQueryResultParser.java
GitHub issue resolved: #4430  
Provide more user-friendly error message when trying to parse invalid content with BinaryQueryResultParser.
When BinaryQueryResultParser gets unknown symbol, the remaining bytes from the result are parsed as string in order to provide more user-friendly error message. Also, introduced limit of the returned string, if its length > INVALID_CONTENT_LIMIT, it is trimmed and "..." is appended in order to prevent displaying too long result.
----
=> GH-4430: Provide more user-friendly error message in BinaryQueryResultParser

core/repository/http/pom.xml, core/repository/http/src/main/java/org/eclipse/rdf4j/repository/http/HTTPRepositoryConnection.java, core/repository/http/src/test/java/org/eclipse/rdf4j/repository/http/HTTPRepositoryConnectionTest.java
GitHub issue resolved: #4451  
- added regression test and fix
- fixed on develop branch instead of main because we recently switched to mockserver (from wiremock) on develop and I didn't want to refactor.
----
=> GH-4451 dataformat now correctly determined

compliance/repository/pom.xml, compliance/repository/src/test/java/org/eclipse/rdf4j/repository/http/HTTPMemServer.java, compliance/sparql/pom.xml, compliance/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/SPARQLEmbeddedServer.java, tools/federation/src/test/java/org/eclipse/rdf4j/federated/server/EmbeddedServer.java, tools/server/pom.xml, tools/server/src/test/java/org/eclipse/rdf4j/http/server/TestServer.java, tools/workbench/pom.xml
GitHub issue resolved: #4474
By publishing "classes" artifacts from war modules we avoid the duplicated dependency management in modules using the war to run tests with a test server. In this PR I fix the two compliance modules running tests using a test server. The federation module desperately need some care, but I'll leave this for a follow-up PR. I suspect we need to establish a dedicated module for the federation tests to fix this - as the compliance modules are for their corresponding functional module.
----
=> GH-4474: Publish classes attachment from war modules

core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/GraphPattern.java, core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java, core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilderTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/tests/BindTest.java
GitHub issue resolved: #4499  
- previous handling of BIND involved it completely replacing/encapsulating the _group_ graph pattern (instead of only the basic graph pattern)
- fix simplifies code and clarifies the distinction between a group graph pattern (the full contents of the GraphPattern class) and a basic graph pattern (only the required TEs)
----
=> GH-4499 fix BIND + FILTER EXISTS by simplifying code

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/limited/LimitedSizeEvaluationStrategy.java, core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/LimitedSizeNativeStore.java, core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/LimitedSizeNativeStoreConnection.java
GitHub issue resolved: #3983  
- deprecate LimitedSizeEvaluationStrategy, and Native Store extensions that make use of it
----
=> GH-3983 deprecate limitsize strategy + native store impl

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryJoinOptimizer.java
GitHub issue resolved: #4532 
Fixes a merge conflict that resulted in the old QueryJoinOptimizer to throw a NullPointerException.
We don't have any tests for the old QueryJoinOptimizer, so that's why it wasn't caught earlier. I don't think it's worth it to make a test now though since the class will be removed in 5.0.0.
----
=> GH-4532 fix breaking changes caused by merge conflict

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/DefaultEvaluationStrategy.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/util/MathUtil.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/util/XMLDatatypeMathUtil.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/util/MathUtilTest.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/util/benchmark/MathUtilBenchmark.java
GitHub issue resolved: #4537 
Used the CoreDatatype.XSD to make math operations a bit faster. 
Added a test for division which has some unexpected behaviour.
----
=> Gh 4537 math util test and constant folding

compliance/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/function/CustomAggregateFunctionEvaluationTest.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/QueryValueEvaluationStep.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/DefaultEvaluationStrategy.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/evaluationsteps/RegexValueEvaluationStepSupplier.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/evaluationsteps/values/AndValueEvaluationStep.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/evaluationsteps/values/CompareAllQueryValueEvaluationStep.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/evaluationsteps/values/CompareAnyValueEvaluationStep.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/evaluationsteps/values/ExistsQueryValueEvaluationStep.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/evaluationsteps/values/IfValueEvaluationStep.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/evaluationsteps/values/InValueEvaluationStep.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/evaluationsteps/values/ListMemberValueOperationStep.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/evaluationsteps/values/OrValueEvaluationStep.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/evaluationsteps/values/QueryValueEvaluationStepSupplier.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/evaluationsteps/values/ValueExprTripleRefEvaluationStep.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StrictEvaluationStrategyTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/tests/BuiltinFunctionTest.java
GitHub issue resolved: #3798 
Start precompiling the binary operators. Taking into account constant propagation.
----
=> GH-3798 Prepare the FunctionCall and And operators.

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/DefaultEvaluationStrategy.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/ConstantOptimizer.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StrictEvaluationStrategyTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/tests/BuiltinFunctionTest.java
Test identity not just equality
GitHub issue resolved: #4540 
ConstantOptimizer uses a QueryEvaluationContext to avoid this breakage.
----
=> GH-4540 NOW() should always evaluate to a single value per query. 

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/util/QueryEvaluationUtil.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/util/QueryEvaluationUtilTest.java
GitHub issue resolved: #3947  
Instead of a type error, we now return `false` when comparing two literals with incompatible (but known) datatypes. 
----
=> GH-3947 in STANDARD mode, "foo" = "1"^^xsd:integer will return false

pom.xml
GitHub issue resolved: #4549 
The aggregate goal uses forking, and there are some issues with how dependent modules are built. Switching to the aggregate-no-fork goal fixes this.
----
=> GH-4549 javadocs aggregate goal is brittle

tools/federation/src/main/java/org/eclipse/rdf4j/federated/util/QueryStringUtil.java, tools/federation/src/test/java/org/eclipse/rdf4j/federated/BasicTests.java
GitHub issue resolved: #4556 
When creating federation sub-queries from intermediate bindings sets, we need to make sure to properly escape single quotes in literal string.
Example literal: "'A quoted literal'"
When not escaping such single quotes, query parsing fails.
Issue is covered by an integration unit test.
----
=> GH-4556: properly escape single quotes in generated federation queries

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSailConnection.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclValidator.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/results/ValidationResult.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/results/lazy/ValidationResultIterator.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/AbstractShaclTest.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/results/ShaclValidatorTest.java
GitHub issue resolved: #3950 
This is more of a bug fix for the code to support ShaclValidator and severity, so tacking it onto the same issue since it hasn't been released yet.
----
=> GH-3950 Validation report should never conform if it has results

core/sail/elasticsearch-store/pom.xml
GitHub issue resolved: #3396 
Fix after merging branch for GH-3396.
----
=> GH-3396 the elasticsearch-maven-plugin should not run while tests are skipped or while integration tests are skipped

core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/MemorySailStore.java, core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemBNode.java, core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemIRI.java, core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemLiteral.java, core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemResource.java, core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemStatementList.java, core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemTriple.java, core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemValue.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/model/MemStatementListTestIT.java
GitHub issue resolved: #4511 #4468 
We can assume that there is only one thread that can remove statements from the statement list, because there is only 1 cleanup thread in the MemorySailStore. That means we can remove the StampedLock and instead change to being 100% lock free!
I also ended up doing a bit of a rewrite of parts of the code and also fixing a bug I hadn't noticed before.
A lot of time was spent on trying to create a decent test. That test made me discover the bug when the code checks if the write was lost due to the array growing.
----
=> GH-4511 MemStatementList concurrency during cleanup

spring-components/rdf4j-spring-demo/pom.xml
=> maven modules should not declare their own groupId or version

tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/join/ControlledWorkerBoundJoin.java
GitHub issue resolved: #4610 
Instead of registering to the root phaser, we need to register to the current phaser. Otherwise we may reach the limit of 65535 for large joins.
Note that in ControlledWorkerJoin and ControlledWorkerLeftJoin this was done correctly.
----
=> GH-4610: fix FedX issue with large join (Phaser > 65535)

tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/GraphQueryResultView.java, tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/TupleQueryResultView.java, tools/server-spring/src/test/java/org/eclipse/rdf4j/http/server/repository/TupleQueryResultViewTest.java
GitHub issue resolved: #4512  
- change try-with-resource to regular try-catch-finally to ensure closing the outputstream (and committing the response) happens _after_ potentially setting an error code (in the catch clause)
----
=> GH-4512 error code must be set on uncommitted response - do not autoclose the outputstream

docker/Dockerfile, tools/server/pom.xml
GitHub issue resolved: #4638 
----
=> GH-4638 revert dependency so that the server doesn't throw an exception on startup due to a missing class

core/model/src/main/java/org/eclipse/rdf4j/model/util/Configurations.java
GitHub issue resolved: GH-4651  
- fix log warning by checking if the new vocabulary is in use or not before we compare with the old (legacy) vocabulary
----
=> GH-4651 fix log warning by checking if the new vocabulary is in use or not before we compare with the old (legacy) vocabulary

core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbUtil.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/TripleStore.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/TxnManager.java, core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/TripleStoreAutoGrowTest.java
GitHub issue resolved: #4547 
Improve the autogrow feature of LmdbStore.
- directly renew stale transactions instead of using a list
- abort triple store transaction if commit fails
- add debug log for resize operations
- add simple test for triple store autogrow
----
=> GH-4547 Improve autogrow of LmdbStore.

core/query/src/main/java/org/eclipse/rdf4j/query/explanation/GenericPlanNode.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/evaluationsteps/StatementPatternQueryEvaluationStep.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/QueryPlanRetrievalTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/query/parser/sparql/manifest/SPARQLQueryComplianceTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/tests/BasicTest.java
GitHub issue resolved: #4659 
- add test
- reorder code so that the getters are always created in the StatementPatternQueryEvaluationStep, even if they are duplicates
- also slightly improve the human readable format of the query plans explanation
----
=> GH-4659 Fix for shared var name between context and subject in StatementPatternQueryEvaluationStep

core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/PathIterationTest.java
GitHub issue resolved: #4690
Add some unit tests, to give more confidence in future improvements.
----
=> GH-4690 Add unit test for path iteration

spring-components/spring-boot-sparql-web/src/main/java/org/eclipse/rdf4j/http/server/readonly/QueryResponder.java, spring-components/spring-boot-sparql-web/src/main/java/org/eclipse/rdf4j/http/server/readonly/sparql/SparqlQueryEvaluator.java, spring-components/spring-boot-sparql-web/src/main/java/org/eclipse/rdf4j/http/server/readonly/sparql/SparqlQueryEvaluatorDefault.java, spring-components/spring-boot-sparql-web/src/test/java/org/eclipse/rdf4j/http/server/readonly/sparql/EvaluateResultDefault.java, spring-components/spring-boot-sparql-web/src/test/java/org/eclipse/rdf4j/http/server/readonly/sparql/SparqlQueryEvaluatorDefaultTest.java
GitHub issue resolved: #4574
The Parameter `defaultGraphUri` in `SparqlQueryEvaluator.evaluate` is now a array. So it's possible to pass more than one  defaultGraphUri.
----
=> GH4574 - Extending SparqlQueryEvaluator defaultGraphUri -> Array

core/common/iterator/src/main/java/org/eclipse/rdf4j/common/iteration/Iterations.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/concurrent/ParallelServiceExecutor.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/concurrent/ParallelTaskBase.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/iterator/CloseDependentConnectionIteration.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/iterator/ConsumingIteration.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/join/ParallelServiceJoinTask.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/optimizer/SourceSelection.java
GitHub issue resolved: #4711 
----
=> GH-4711 Improve chances that iterations are closed on time in FedX

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/results/ValidationResult.java
GitHub issue resolved: #4714 
----
=> GH-4714 be more defensive in case a bug results in value being null

.github/workflows/pr-verify.yml
GitHub issue resolved: #4744  
----
=> GH-4744 add install step before package to unblock osgi package failures

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/PathIteration.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/PathIterationTest.java
GitHub issue resolved: #4646 
The PathIteration adds variables to the binding set that are not known ahead of time and not needed after the pathiteration logic is done. These should be stripped out and not propegated.
----
=> GH-4646 remove intermediate join variables

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/DefaultEvaluationStrategy.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/DescribeIteration.java, core/repository/sail/src/main/java/org/eclipse/rdf4j/repository/sail/SailRepositoryConnection.java, core/sail/api/src/main/java/org/eclipse/rdf4j/sail/helpers/AbstractSail.java, core/sail/api/src/main/java/org/eclipse/rdf4j/sail/helpers/AbstractSailConnection.java, core/sail/api/src/main/java/org/eclipse/rdf4j/sail/helpers/SailWrapper.java, core/sail/inferencer/src/test/java/org/eclipse/rdf4j/sail/inferencer/fc/DirectTypeHierarchyInferencerTest.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbSailStore.java, core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/MemorySailStore.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSail.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSailConnection.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/ContextWithShape.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/ShaclParsingException.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/AbstractConstraintComponent.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/DashHasValueInConstraintComponent.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/DatatypeConstraintComponent.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/DisjointConstraintComponent.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/LanguageInConstraintComponent.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/paths/AlternativePath.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/UnorderedSelect.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/wrapper/shape/BackwardChainingShapeSource.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/wrapper/shape/Rdf4jShaclShapeGraphShapeSource.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/ast/ShaclPropertiesCastingTest.java, testsuites/sail/src/main/java/org/eclipse/rdf4j/testsuite/sail/SailConcurrencyTest.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/FederationEvalStrategy.java
GitHub issue resolved: #4784 #4790 
This is mainly an issue with the MemoryStore, but has been detected when using the ShaclSail since it uses memory stores for tracking the changes in a transaction.
When one connection holds the MemorySailStore `txnLockManager` then another thread can get stuck waiting for the same lock if both threads are forcefully closed. Two issues are causing this, the first is that the `txnLockManager` can't be forcefully unlocked by another thread, the second is that the `txnLockManager` is being locked without support for interruptions.
The fix is to track the owner thread of the connection and interrupt that thread. Since connections shouldn't be shared between threads we can assume that the thread that created …
=> GH-4784 interrupt threads using connections when forcefully closing

core/http/client/src/main/java/org/eclipse/rdf4j/http/client/shacl/RemoteValidation.java, tools/server-spring/pom.xml, tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/ProtocolExceptionResolver.java, tools/server/src/test/java/org/eclipse/rdf4j/http/server/ShaclValidationReportIT.java, tools/server/src/test/java/org/eclipse/rdf4j/http/server/TransactionSettingsIT.java
GitHub issue resolved: #4622 
This is a simple solution that fixes the issue in a backwards compatible manner.
----
=> GH-4622 SHACL preserve bnode (simple solution)

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/ShaclSparqlConstraintFailureException.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/Shape.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/SparqlConstraintSelect.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/SparqlConstraintTest.java
GitHub issue resolved: #4686 
----
=> GH-4686 support ?failure var in SparqlConstraint select queries

site/content/download.md, site/content/news/rdf4j-500-M2.md
Javadocs, release-notes and news item for 5.0.0-M2
=> 5.0.0-M2-release-notes

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/ArrayBindingBasedQueryEvaluationContext.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/tests/ValuesTest.java
GitHub issue resolved: #4815 
----
=> GH-4815 retrieve the variable names from BindingSetAssignment nodes when making the list of names to include in the ArrayBindingSet

core/repository/contextaware/src/main/java/org/eclipse/rdf4j/repository/contextaware/ContextAwareConnection.java
GitHub issue resolved: #4826 
Cast `ConvertingIteration` to `Iteration` so calling `super.add(...)` does not end in a StackOverflowError.
----
=> GH-4826: Fix StackOverflow in ContextAwareConnection

core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/GraphPattern.java, core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java, core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilderTest.java
GitHub issue resolved: #4811 
Process also optional TEs when handling BIND, Added a test case.
----
=> GH-4811 process also optional TEs when handling BIND

core/sail/elasticsearch-store/pom.xml
GitHub issue resolved: #4831 
Just limit the heap size of the java process for the elastic search tests to 1gb.
----
=> GH-4831 Elasticsearch store created by unit test uses max 1gb heap

core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbRecordIterator.java
Ensures that a lock is used if close() is called asynchronously from another thread than next().
GitHub issue resolved: #4817 
Ensures that close method does not interfere next if called asynchronously from another thread. 
----
=> GH-4817 LMDB: Make close method of LmdbRecordIterator thread-safe.

core/sail/elasticsearch-store/pom.xml
=> GH-4831 Limit the elasticsearch node for unit tests to 1gb of Java heap

core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDHierarchicalProcessor.java, core/rio/jsonld/src/test/java/org/eclipse/rdf4j/rio/jsonld/JSONLDHierarchicalWriterTest.java, core/rio/jsonld/src/test/resources/serialized/testMultipleLoops.json
The current implementation of the algorithm for the hierachical JSON-LD output changes references of the triples stored in `List`s and keeps adding these references to the output. This can leed to infinite loops when traversing the result. Making copies of the contained lists avoids this.
GitHub issue resolved: #4833 
----
=> GH-4833: Copy triple structures to avoid infinite loops

core/sail/inferencer/src/main/resources/META-INF/services/org.eclipse.rdf4j.sail.config.SailFactory
GitHub issue resolved: #4854 
----
=> GH-4854 remove SPI reference to deprecated & removed ForwardChainingRDFSInferencerFactory

site/content/download.md
Maven doesn't support http anymore so we should use https in our documentation
=> Maven doesn't support http anymore so we should use https in our documentation

testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/query/parser/sparql/manifest/SPARQL10QueryComplianceTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/query/parser/sparql/manifest/SPARQL11QueryComplianceTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/query/parser/sparql/manifest/SPARQL11SyntaxComplianceTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/query/parser/sparql/manifest/SPARQL11UpdateComplianceTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/query/parser/sparql/manifest/SPARQL12QueryComplianceTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/query/parser/sparql/manifest/SPARQLComplianceTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/query/parser/sparql/manifest/SPARQLQueryComplianceTest.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/query/parser/sparql/manifest/SPARQLSyntaxComplianceTest.java
GitHub issue resolved: #4592 
- allow users to see variables used in compliance tests
----
=> GH-4592 allow users to see variables used in compliance tests

core/repository/sail/src/main/java/org/eclipse/rdf4j/repository/sail/SailQuery.java, core/repository/sail/src/test/java/org/eclipse/rdf4j/repository/sail/SailRepositoryConnectionTest.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/QueryPlanRetrievalTest.java
GitHub issue resolved: #4859
This change adds instead of removes `QueryRoot` in `SailQuery#explain` to support explanations of queries of which the root `TupleExpr` is replaced.
----
=> GH-4859 Add instead of remove QueryRoot for explaining optimized Sail queries

core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/RDFStarUtil.java, core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/FileIO.java, core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/MemoryStore.java, core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemValueFactory.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/StoreSerializationTest.java
GitHub issue resolved: #4866 
----
=> GH-4866 add tests and fix for loading a persisted MemoryStore with RDF star triples

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/ArrayBindingSet.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/ArrayBindingBasedQueryEvaluationContext.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/DefaultEvaluationStrategy.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/FilterIterator.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/SameTermFilterOptimizer.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/util/QueryEvaluationUtil.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/ArrayBindingSetTest.java, core/repository/sail/src/main/java/org/eclipse/rdf4j/repository/sail/SailQuery.java, core/repository/sail/src/test/java/org/eclipse/rdf4j/repository/sail/SailRepositoryConnectionTest.java, core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/RDFStarUtil.java, core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDHierarchicalProcessor.java, core/rio/jsonld/src/test/java/org/eclipse/rdf4j/rio/jsonld/JSONLDHierarchicalWriterTest.java, core/rio/jsonld/src/test/resources/serialized/testMultipleLoops.json, core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/FileIO.java, core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/MemoryStore.java, core/sail/memory/src/main/java/org/eclipse/rdf4j/sail/memory/model/MemValueFactory.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/QueryPlanRetrievalTest.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/StoreSerializationTest.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclValidator.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShapeValidationContainer.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/Shape.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/results/lazy/LazyValidationReport.java, pom.xml, site/content/download.md, site/content/news/rdf4j-438.md, site/content/news/rdf4j-439.md, site/content/release-notes/4.3.8.md, site/content/release-notes/4.3.9.md, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/RepositorySPARQLComplianceTestSuite.java, testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/sparql/tests/FilterScopeTest.java
=> Merge main into develop

core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/RDFaParserSettings.java, core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/RDFaVersion.java
GitHub issue resolved: #4779 
This flag is not ready for deprecation as it is used by 3rd party plugins. It would be good to set up an alternative mechanism for providing this support before this is deprecated. See #4779 for details.
----
=> GH-4779 Maintain RDFa support

core/query/src/main/java/org/eclipse/rdf4j/query/explanation/GenericPlanNode.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/QueryJoinOptimizer.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryCostEstimatesTest.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/AbstractQueryModelNode.java, core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/helpers/QueryModelTreePrinter.java, core/queryalgebra/model/src/test/java/org/eclipse/rdf4j/query/algebra/AbstractQueryModelNodeTest.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/QueryPlanRetrievalTest.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/benchmark/QueryBenchmark.java, core/sail/memory/src/test/resources/benchmarkFiles/multiple-sub-select.qr, core/sail/memory/src/test/resources/benchmarkFiles/sub-select.qr
GitHub issue resolved: #4878 
----
=> GH-4878 optimise sub-select

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclValidator.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShapeValidationContainer.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/Shape.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/results/lazy/LazyValidationReport.java
GitHub issue resolved: #4867 
- GH-4867 change from Exception to Throwable so that we can also log StackOverflowError and which shape caused it
----
=> GH-4867 change from Exception to Throwable so that we can also log StackOverflowError and which shape caused it

.github/workflows/develop-status.yml, .github/workflows/main-status.yml
GitHub issue resolved: #4913 
GH-4913 downgrade to java 17 for main/develop status checks to allow some older elasticsearch tests to pass
----
=> GH-4913 downgrade to java 17 for main/develop status checks to allow some older elasticsearch tests to pass

site/content/about.md
The link to _Strabon_ on https://rdf4j.org/about/ is broken.
It should be https://strabon.di.uoa.gr (not http://www.strabon.di.uoa.gr).
=> docs: Fix broken link to Strabon on About

core/queryalgebra/model/src/main/java/org/eclipse/rdf4j/query/algebra/ValueExprTripleRef.java
GitHub issue resolved: #4915 
`ValueExprTripleRef#replaceChildNode` now sets itself as parent on the replacement.
----
=> GH-4915 Fixed setting parent in ValueExprTripleRef#replaceChildNode

core/model/src/main/java/org/eclipse/rdf4j/model/impl/ValidatingValueFactory.java
=> fix: Include the invalid IRI in the IllegalArgumentException when validating IRIs in the ValidatingValueFactory

core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/propertypath/InversePath.java, core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/propertypath/InversePredicatePath.java, core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/propertypath/NegatedPropertySet.java, core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/propertypath/OneOrMorePath.java, core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/propertypath/ZeroOrMorePath.java, core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/propertypath/ZeroOrOnePath.java, core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/constraint/propertypath/builder/PropertyPathTest.java
GitHub issue resolved: #4923
- Removed spaces after prefix operators and before postfix operators
----
=> GH-4923 Spaces inserted by PropertyPathBuilder cause problems with AllegroGraph

core/repository/api/src/main/java/org/eclipse/rdf4j/repository/config/AbstractRepositoryImplConfig.java, core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDSettings.java, core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDWriter.java, core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/ndjsonld/NDJSONLDWriter.java, core/rio/jsonld/src/test/java/org/eclipse/rdf4j/rio/jsonld/JSONLDWriterBackgroundTest.java, core/rio/jsonld/src/test/java/org/eclipse/rdf4j/rio/jsonld/JSONLDWriterTest.java, core/rio/jsonld/src/test/java/org/eclipse/rdf4j/rio/ndjsonld/NDJSONLDWriterTest.java
GitHub issue resolved: #3654 
----
=> GH-3654 reverted removal of generalized rdf

core/model/src/main/java/org/eclipse/rdf4j/model/impl/SimpleIRI.java, core/model/src/main/java/org/eclipse/rdf4j/model/impl/SimpleValueFactory.java, core/rio/rdfxml/src/main/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLWriter.java, core/rio/rdfxml/src/main/java/org/eclipse/rdf4j/rio/rdfxml/util/RDFXMLPrettyWriter.java, core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleUtil.java, core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleWriter.java, core/rio/turtle/src/test/java/org/eclipse/rdf4j/rio/turtle/TurtleWriterTest.java
GitHub issue resolved: #4921
- SimpleValueFactory.createIRI(String, String) how actually properly respects the specified namespace and localname
- TurtleWriter tries to use the namespace encoded in the IRI unless the localname contains characters which are not valid in prefixed notation
- Added test
----
=> GH-4921 Turtle writer does not respect namespaces in IRIs

core/repository/manager/src/main/java/org/eclipse/rdf4j/repository/manager/LocalRepositoryManager.java
GitHub issue resolved: #4401 
----
=> GH-4401 bug fix for configuration handling with new vocab

core/collection-factory/mapdb3/src/main/java/org/eclipse/rdf4j/collection/factory/mapdb/MapDb3CollectionFactory.java, core/collection-factory/mapdb3/src/test/java/org/eclipse/rdf4j/collection/factory/mapdb/MapDb3CollectionFactoryTest.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/StrictEvaluationStrategyFactory.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/PathIteration.java
GitHub issue resolved: #4899 
Introduce a new MapDb3 backed queue implementation to the MapDb3CollectionFactory. This spills to disk onze the queue reaches size 128. The queue is backed by a map and a small class which keeps a pointer to the tail and head. 
----
=> GH-4899 Introduce MapDB3 backed queue to the MapDb3CollectionFactory

tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXConfig.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/FederationContext.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/cache/SourceSelectionCache.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/cache/SourceSelectionCacheFactory.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/cache/SourceSelectionMemoryCache.java, tools/federation/src/test/java/org/eclipse/rdf4j/federated/cache/SourceSelectionMemoryCacheTest.java
GitHub issue resolved: #4962
* provide a means for externally invalidating the FedX source selection cache (e.g. upon writes)
* provide a means for configuring a custom source selection cache implementation
----
=> GH-4962: invalidation support for FedX source selection cache + factory

core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbSailStore.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbUtil.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/TripleStore.java, core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/TripleStoreTest.java
Ensures that GC is also working if triple store needs to grow and that the correct count is returned for statement removals.
GitHub issue resolved: #4954
Tests removed values after the triple store's transaction is committed and correctly calls handler in removeStatement methods.
----
=> GH-4954 LMDB: Fix GC and record counting for deletions

tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/handler/AbstractQueryRequestHandler.java
GitHub issue resolved: #4968
- Introduce explicit result closing (in addition to existing repo close) when an exception occurs between the evaluation & rendering stages.
- :information_source: I have **not** added any tests yet since I'd like to get feedback on whether this is the right approach (and there weren't any other pre-existing tests for the `AbstractQueryRequestHandler` class.
----
=> GH-4968: server-spring - Close query result on pre-render exception

site/content/documentation/programming/federation.md, tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXConfig.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/join/ControlledWorkerBoundJoin.java, tools/federation/src/test/java/org/eclipse/rdf4j/federated/BoundJoinTests.java, tools/federation/src/test/java/org/eclipse/rdf4j/federated/ServiceTests.java, tools/federation/src/test/java/org/eclipse/rdf4j/federated/repository/FedXRepositoryConfigTest.java
GitHub issue resolved: #4983
This change applies fine-tuning to the bind join implementation on
certain parameters.
Note that the original implementations and benchmarks were done when
there was no SPARQL 1.1 around, and FedX was using UNION constructs for
the bind join implementation. Since a few year back it is using VALUES
clauses.
Changes:
- default bind join size is set to 25 (also reflected in documentation,
some unit tests require adjustments)
- no longer send small hard-coded sub-queries of size 3 for the first
requests and instead rely on configured bind join size
- no longer send the first request in a non-bound way by default (Note:
kept as internal configuration parameter in the implementation to allow
modifications in extensions)
- support to influence the bind join size in …
=> GH-4983: fine-tune bind join implementation in FedX engine

core/model-vocabulary/src/main/java/org/eclipse/rdf4j/model/vocabulary/GEO.java
GitHub issue resolved: #4505 
The following item is addressed:
- add GeoSPARQL vocabulary constants
Also addressed: 
- update javadoc GeoSPARQL version to 1.1
- update copyright year to current year
----
=> GH-4505: Add GeoSPARQL vocabulary constants

tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/FedXArbitraryLengthPath.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/FedXZeroLengthPath.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/algebra/HolderNode.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/FedXZeroLengthPathEvaluationStep.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/FederationEvalStrategy.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/iterator/FedXPathIteration.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/iterator/FedXZeroLengthPathIteration.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/optimizer/ExclusiveTupleExprOptimizer.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/optimizer/GenericInfoOptimizer.java, tools/federation/src/test/java/org/eclipse/rdf4j/federated/PropertyPathTests.java
GitHub issue resolved: #4990 
This change adds support for zero-length path expressions in the FedX
engine and also fixes source selection for other path expressions.
Note that the implementation reuses the implementation from
PathIteration and ZeroLengthPathIteration. Unfortunately the existing
implementations cannot be reused without larger refactoring right now.
Functionality is covered with unit tests
----
=> GH-4990: support for zero-length path expression in FedX

core/common/iterator/src/main/java/org/eclipse/rdf4j/common/iteration/DistinctIteration.java, core/common/iterator/src/main/java/org/eclipse/rdf4j/common/iteration/IntersectIteration.java, core/query/src/main/java/org/eclipse/rdf4j/query/QueryResults.java, core/query/src/test/java/org/eclipse/rdf4j/common/iteration/DistinctIterationTest.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/EvaluationStrategy.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/DefaultEvaluationStrategy.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/evaluationsteps/IntersectionQueryEvaluationStep.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/PathIteration.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/ZeroLengthPathIteration.java, core/repository/api/src/main/java/org/eclipse/rdf4j/repository/RepositoryResult.java, core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/SailDatasetImpl.java, core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/SailDatasetTripleSource.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXConfig.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXConnection.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXFactory.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/FederationEvalStrategy.java, tools/federation/src/test/java/org/eclipse/rdf4j/federated/FedXRule.java
Remove LimitedSize evaluation strategy code, as well as a few methods in the EvaluationStrategy API that was replaced by the collection factory API.
Closes #4581
=> Gh 4581 remove jerven design mistakes

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/AbstractPairwisePlanNode.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/DatatypeFilter.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/ExternalFilterByQuery.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/GroupByCountFilter.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/LanguageInFilter.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/NodeKindFilter.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/PatternFilter.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/Unique.java
GitHub issue resolved: #5027 #5028 
----
=> GH-5027 ShaclSail logging

core/query/src/main/java/org/eclipse/rdf4j/query/impl/FallbackDataset.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/FederationEvalStrategy.java, tools/federation/src/test/java/org/eclipse/rdf4j/federated/BasicTests.java
GitHub issue resolved: #5030 
FedX supports interpret the Dataset being defined on the query: if it is of type FedXDataset, the federation is reduced to the members defined by FedXDataset#getEndpoints().
This is a nice means to evaluate a query on a subset of the federation and is generally working fine.
When the query contains a FROM clause, however, the externally passed Dataset is wrapped into a FallbackDataset (which internally keeps the FedXDataset as primary one.
This change now inspects the FallbackDataset and unwraps it to reduce the members. Note that for execution still the "FallbackDataset" is used.
----
=> GH-5030: fix FedXDataset support for queries with FROM clauses

spring-components/rdf4j-spring/src/main/java/org/eclipse/rdf4j/spring/dao/support/RelationMapBuilder.java, spring-components/rdf4j-spring/src/test/java/org/eclipse/rdf4j/spring/dao/support/RelationMapBuilderTests.java
GitHub issue resolved: #5009 
Generating the query was simplified such that any constraints specified are put first, then the relation triple is added, which may be optional, depending on builder configuration
----
=> GH-5009: Fix position of OPTIONAL in RelationMapBuilder

spring-components/rdf4j-spring/src/main/java/org/eclipse/rdf4j/spring/dao/support/operation/TupleQueryResultConverter.java
GitHub issue resolved: #5000
Briefly describe the changes proposed in this PR: 
Reduces loglevel for two very frequent, not-so-serious situations
----
- [~] I've added tests for the changes I made
=> GH-5000: Tone down WARN log output for frequent, non-critical events

tools/federation/src/main/java/org/eclipse/rdf4j/federated/optimizer/LimitOptimizer.java, tools/federation/src/test/java/org/eclipse/rdf4j/federated/LimitTests.java
GitHub issue resolved: #5033 
This change makes sure to push limits for simple ASK queries with a single statement patterns into the query.
The optimization is the same as applied for simple SELECT queries with a LIMIT.
Rational: if the limit is not pushed, the federation engine will first fetch all data for the statement pattern and only then locally check if there is at least one, i.e it will cause performance issues and memory pressure when there are many triples matching the statement pattern (for instance millions of persons).
Query plan of a simple ASK query after this fix (note the upper limit):
```
QueryRoot
Slice (limit=1)
StatementSourcePattern
Var (name=person)
Var (name=_const_f5e5585a_uri, value=http://www.w3.org/1999/02/22-rdf-syntax-ns#type, anonymous)
Var …
```
=> GH-5033: fix pushing of limits for simple ASK queries in FedX

core/repository/api/src/main/java/org/eclipse/rdf4j/repository/config/RepositoryConfig.java
GitHub issue resolved: #5040 
----
=> GH-5040 add the old rdf:type when using legacy vocabulary

site/content/download.md, site/content/news/rdf4j-500.md, site/content/release-notes/5.0.0.md
Please add info about the improvements and enhancements that you've contributed to the RDF4J 5.0.0 release.
=> 5.0.0 Release Notes

tools/federation/pom.xml, tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedX.java
GitHub issue resolved: #5055 
Also use MapDB3 for FedX
Hand tested that this resolves the reported problem
=> GH-5055 make mapdb3 default for the FedX engine as well

core/sail/solr/pom.xml
GitHub issue resolved: # 5060
- use a newer version of zookeeper for fix CVE
----
=> GH-5060: use more recent version of zookeeper to fix CVE

core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/RDFaParserSettings.java
GitHub issue resolved: https://github.com/eclipse-rdf4j/rdf4j/issues/4779
PR #4858 reinstated some settings needed for RDFa support but I missed one that is used internally by the Semargl library. This PR removes the deprecation of `VOCAB_EXPANSION_ENABLED` so that 3rd party libraries which depend on it can work with RDF4J v5.
----
=> GH-4779: Un-deprecate RDFa parser setting

core/sail/solr/pom.xml
GitHub issue resolved: #5052 
- upgrade to newer version of snappy to fix CVEs
----
=> GH-5052: use more recent version of snappy to fix CVEs

pom.xml
GitHub issue resolved: #5048  
Just a bump in (patch release) version number for Spring Framework
----
=> GH-5048: updated spring dependency to fix CVEs

core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbContextIdIterator.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbRecordIterator.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbSailStore.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbUtil.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/PersistentSet.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/TripleStore.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/TxnRecordCache.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/ValueStore.java
GitHub issue resolved: #5059 
----
=> GH-5059 remove calls to E(...) when the return value is already being checked

spring-components/rdf4j-spring/src/main/java/org/eclipse/rdf4j/spring/support/RDF4JTemplate.java, spring-components/rdf4j-spring/src/test/java/org/eclipse/rdf4j/spring/domain/model/EX.java, spring-components/rdf4j-spring/src/test/java/org/eclipse/rdf4j/spring/support/RDF4JTemplateTests.java
GitHub issue resolved: #5024 
`RDF4JTemplate.delete(IRI, List<PropertyPath>)` is meant to
1. delete the 'star' around `IRI`
2. find all nodes from `IRI` by the specified property paths and delete the 'star' around them.
The problem was that the  `source - propertypath - target` pattern was optional, and so the star pattern around the target could match all triples. Now that pattern is not optional, which limits deletes to any matches of that pattern.
----
=> GH-5024 Fix 'nuclear' delete bug in RDF4JTemplate.delete(IRI, List)

core/rio/api/src/test/java/org/eclipse/rdf4j/rio/AbstractParserHandlingTest.java, core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDParser.java
GitHub issue resolved: #5095 
----
=> GH-5095 Correctly call startRDF() and endRDF*() when parsing JSON-LD

scripts/release.sh
Improve release script to delay calling jenkins until we know that the build went through correctly, also improve the automation by reducing the number of times you need to press any key to continue.
=> Improve release script

core/model/src/main/java/org/eclipse/rdf4j/model/util/Configurations.java, core/model/src/test/java/org/eclipse/rdf4j/model/util/ConfigurationsTest.java
GitHub issue resolved: #5053
When there is only a value for the legacy setting (i.e. the new config setting is not used) we now log on level debug. Otherwise on warn.
The rational is: when users still have persisted legacy repository configurations, the log is easily spammed with warnings.
----
=> GH-5053: avoid log spam for configurations class with legacy settings

tools/federation/src/main/java/org/eclipse/rdf4j/federated/monitoring/MonitoringImpl.java
GitHub issue resolved: #5105 
The monitoring service in FedX is a useful tool for evaluations / benchmarks to inspect the number of requests sent to the endpoints.
This change makes the implementation thread safe.
----
=> GH-5105: make MonitoringImpl in FedX thread safe

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/MaxCountConstraintComponent.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/MaxLengthConstraintComponent.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/MinCountConstraintComponent.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/MinLengthConstraintComponent.java
GitHub issue resolved: #5108 
----
=> GH-5108 add a java system property to modify the limit for when we can still use SPARQL validation approach with sh:maxCount

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/util/QueryEvaluationUtil.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/MaxCountConstraintComponent.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/BenchmarkConfigs.java, core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/benchmark/MaxCountSparqlBenchmarkEmpty.java, core/sail/shacl/src/test/resources/shaclMaxCountBenchmark1.trig, core/sail/shacl/src/test/resources/shaclMaxCountBenchmark2.trig, core/sail/shacl/src/test/resources/shaclMaxCountBenchmark3.trig, core/sail/shacl/src/test/resources/shaclMaxCountBenchmark4.trig
GitHub issue resolved: #5153 
- benchmarked sh:maxCount for both SPARQL and transactional validation
- adjusted the default cutoff value
- also made some small optimisations in the QueryEvaluationUtil using object identiy
----
=> GH-5153 max count cut off for sparql based validation

core/http/client/src/main/java/org/eclipse/rdf4j/http/client/SharedHttpClientSessionManager.java, core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/federation/SPARQLServiceResolver.java, core/sail/memory/src/test/java/org/eclipse/rdf4j/sail/memory/QueryPlanRetrievalTest.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/endpoint/provider/RemoteRepositoryProvider.java
GitHub issue resolved: #5124 
- introduced timeout for the underlying Apache HttpClient
- made them configurable
- made different timeouts for when using with a SPARQL SERVICE call
----
=> GH-5124 configurable http timeouts

core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/ValueStore.java, core/sail/nativerdf/src/main/java/org/eclipse/rdf4j/sail/nativerdf/model/CorruptValue.java
GitHub issue resolved: #5148
- Improved use of a corrupted ValueStore by handling error situations in `ValueStore.data2value()` with SailException (previously it was possible to get an `ArrayIndexOutOfBoundsException` and `IllegalArgumentException`).
- Introduction of a new system property `org.eclipse.rdf4j.sail.nativerdf.softFailOnCorruptData` to enable "soft failure mode" and to avoid exceptions as described above. Instead, an instance of the newly introduced CorruptValue will be returned.
- This solves the problem of not being able to iterate (and in consequence, backup) over the NativeStore in order to save uncorrupted statements. Without "soft failure mode" the `RepositoryConnection` would be forcefully closed when hitting the first …
=> GH-5148 Introduce "soft fail" for corrupt ValueStore

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/GroupIterator.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/GroupIteratorTest.java
GitHub issue resolved: #5159
I've added the child argument's iterator as (volatile) field in the GroupIterator so that it can be closed while building entires.
----
=> GH-5159 close child of GroupIterator

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/constraintcomponents/PatternConstraintComponent.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/PatternFilter.java
GitHub issue resolved: #5182 
----
=> GH-5182 improve performance of SHACL sh:pattern

site/content/download.md, site/content/news/rdf4j-4315.md, site/content/release-notes/4.3.15.md
=> 4.3.15 release notes 2

core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/ValidationQuery.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/AllTargetsPlanNode.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/FilterByPredicate.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/FilterByPredicateObject.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/LeftOuterJoin.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ast/planNodes/NonUniqueTargetLang.java, core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/wrapper/data/ConnectionsGroup.java
GitHub issue resolved: #5189 
----
=> GH-5189 cache Value objects retrieved from parent sail

core/rio/api/src/main/java/org/eclipse/rdf4j/rio/RioConfig.java, core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/CachingDocumentLoader.java, core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDMode.java, core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDParser.java, core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDSettings.java, core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDWriter.java, core/rio/jsonld/src/test/java/org/eclipse/rdf4j/rio/jsonld/JSONLDParserCustomOldTest.java, core/rio/jsonld/src/test/java/org/eclipse/rdf4j/rio/jsonld/JSONLDWriterBackgroundTest.java, core/rio/jsonld/src/test/java/org/eclipse/rdf4j/rio/jsonld/JSONLDWriterOldTest.java, core/rio/jsonld/src/test/java/org/eclipse/rdf4j/rio/ndjsonld/NDJSONLDWriterTest.java
GitHub issue resolved: #5080 
----
=> GH-5080 Support for using a user provided document loader with HASMAC JSON-LD

tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/FederationEvalStrategy.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/SparqlFederationEvalStrategy.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/join/ControlledWorkerBindJoin.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/join/ParallelCheckJoinTask.java, tools/federation/src/test/java/org/eclipse/rdf4j/federated/BoundJoinTests.java, tools/federation/src/test/resources/tests/boundjoin/query02_checkJoin.rq, tools/federation/src/test/resources/tests/boundjoin/query02_checkJoin.srx, tools/federation/src/test/resources/tests/data/data1.ttl, tools/federation/src/test/resources/tests/data/data2.ttl
GitHub issue resolved: #GH-5151
For evaluation of bind joins the implementation for quite some time
makes use of a VALUES clause query.
Except for one code-path: for bind joins - where in the join all
arguments are bound - it was still using the old UNION query approach.
This approach is error prone and no longer required, i.e. the check join
can be executed with the same logic as the regular VALUES clause.
Note: an additional unit test for covering bind joins with no free vars
is added.
This change also marks a number of methods and classes used for the old
UNION based approach as deprecated. The implementations are internal to
the FedX engine and can be removed in the next major release.
----
PR Author Checklist (see the [contributor …
=> GH-5151: use VALUES clause for FedX bind join with no free vars

core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/SPARQLConnection.java, core/repository/sparql/src/test/java/org/eclipse/rdf4j/repository/sparql/SPARQLConnectionTest.java
GitHub issue resolved #4920
SPARQLConnection.size() method should not fetch every statement in the repository. Just send a count query instead.
----
=> GH-4920 SPARQLConnection.size() now uses count query

site/content/download.md, site/content/news/rdf4j-503.md, site/content/release-notes/5.0.3.md
Javadocs, release-notes and news item for 5.0.3.
=> 5.0.3 release notes

tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/join/ControlledWorkerBindLeftJoin.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/join/ParallelEmptyBindLeftJoinTask.java, tools/federation/src/test/java/org/eclipse/rdf4j/federated/BindLeftJoinTests.java
GitHub issue resolved: #5121 
Previously we introduced support for left bind joins in FedX. The case
of empty left bind joins (i.e. where the clause inside the OPTIONAL does
not provide any statements) was not handled and resulted in an exception
This change now adds support for empty optional joins and passes the
results from the left-handside through.
----
Note: this is a follow up issue and fix for #5121, which we found by using RDF4J 5.1-M1. The fix should be added to 5.1.0
----
=>  GH-5121: support empty left bind join (OPTIONAL) in FedX

tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedX.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/FederationManager.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/concurrent/ControlledWorkerScheduler.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/concurrent/DefaultSchedulerFactory.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/concurrent/SchedulerFactory.java
GitHub issue resolved: #5197 
This change adds preparational infrastructure for having different
implementations of schedulers. Configuration is here prepared by means
of defining a "SchedulerFactory" interface with a default implementation
aside (which essentially mimics the current behavior).
Note that for ease of development some aspects of
ControlledWorkerScheduler are made accessible to sub-classes. The idea
is that in the end version there is an abstract scheduler class
providing shared functionality and different implementation (e.g. the
current FIFO one and a fair implementation)
-----
Note: I would like to see this preparation merged in RDF4J 5.1 such that we can prepare (and test) an implementation of a fair scheduler asynchronously already. The final target version for the …
=> GH-5197: preparation for supporting fair sub-query execution in FedX

spring-components/rdf4j-spring/src/main/java/org/eclipse/rdf4j/spring/dao/support/UpdateWithModelBuilder.java, spring-components/rdf4j-spring/src/test/java/org/eclipse/rdf4j/spring/dao/support/ServiceLayerTests.java, spring-components/rdf4j-spring/src/test/java/org/eclipse/rdf4j/spring/domain/dao/PaintingDao.java, spring-components/rdf4j-spring/src/test/java/org/eclipse/rdf4j/spring/domain/service/ArtService.java
GitHub issue resolved: #4999 
The `UpdateWithModelBuilder` used to be just an `Operation` with an internal `ModelBuilder` that is exposed to clients. thus, one can only add statements with it, but not delete any. In practice, it turns out that sometimes, the data for one bigger update is often collected iteratively, which can lead to the need for removing some of the statements already added.
With this update, the `UpdateWithModel` builder allows for removal of statements, and applies additions and removals correctly when its `execute()` method is called.
----
=> GH-4999: improve UpdateWithModelBuilder to support statement removal

core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/Values.java, core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/core/query/Query.java, core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/graphpattern/GraphPattern.java, core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/examples/BaseExamples.java, core/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/examples/sparql11spec/Section10Test.java
GitHub issue resolved: #4997 
Adds a builder for VALUES clauses and integrates them with GraphPattern and Select
----
=> GH-4997: Enable SparqlBuilder to create VALUES clauses

site/content/about.md
GitHub issue resolved: N/A
Added a link to the Jelly serialization format implementation for RDF4J: https://w3id.org/jelly/jelly-jvm
Jelly is a binary RDF format with a strong performance focus. The implementation for RDF4J can be either used as a Maven dependency, or as a JAR plugin that you drop into your classpath.
Jelly was also implemented for Apache Jena. An implementation for rdflib is planned.
----
=> Add link to Jelly to about.md

tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/ServerInterceptor.java
GitHub issue resolved: #5208 
This PR adds a unique request identifier to MDC in order to allow for more intelligent log parsing and aggregation as well as aid in server debugging.
----
=> GH-5208 Enable request tracing through logs using new associated request id

core/sail/api/src/main/java/org/eclipse/rdf4j/sail/helpers/AbstractSailConnection.java
GitHub issue resolved: #5210 
This PR adds an overridable internal method `bulkAddStatementsInternal` which implementing SAILs can use to leverage the existing multithreading-safe, buffering implemented in `AbstractSailConnection`. This change should be fully backwards compatible as it defaults to the exiting implementation.
----
=> GH-5210 Enable implementing sails to benefit from parent sail buffering

site/content/download.md, site/content/news/rdf4j-510.md, site/content/release-notes/5.1.0.md
Javadocs, release-notes and news item for 5.1.0.
=> 5.1.0 release notes (auto-generated)

core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/evaluationsteps/RegexValueEvaluationStepSupplier.java, core/repository/sail/src/main/java/org/eclipse/rdf4j/repository/sail/helpers/SailUpdateExecutor.java, core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/Changeset.java, core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/SailSourceConnection.java, core/sail/extensible-store/src/main/java/org/eclipse/rdf4j/sail/extensiblestore/ReadCommittedWrapper.java, core/sail/extensible-store/src/main/java/org/eclipse/rdf4j/sail/extensiblestore/valuefactory/ExtensibleStatementImpl.java, testsuites/sail/src/main/java/org/eclipse/rdf4j/testsuite/sail/RDFNotifyingStoreTest.java
GitHub issue resolved: #5221 
----
=> GH-5221 fix NotifyingSail bug

tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/FederationEvalStrategy.java, tools/federation/src/test/java/org/eclipse/rdf4j/federated/BindLeftJoinTests.java
GitHub issue resolved: #5229 
This change fixes a situation that can incorrectly cause empty results. It happens when the input of the left argument is a single binding set and for special source selection situations (e.g. the right argument is marked as ExclusiveStatement while the endpoint does not provide data)
To avoid the issue we also use the regular left join logic also for a single binding set input, which can handle the situation properly.
Issue is covered with a unit test.
----
=> GH-5229: fix left bind join in FedX for single binding input

tools/federation/src/main/java/org/eclipse/rdf4j/federated/cache/SourceSelectionMemoryCache.java
GitHub issue resolved: #5234 
Add an additional constructor accepting a supplier for an initialized cache.
----
=> GH-5234: fix limited programmatic configuration support of FedX source selection cache

tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/FederationEvalStrategy.java, tools/federation/src/test/java/org/eclipse/rdf4j/federated/evaluation/FederationEvalStrategyTest.java
GitHub issue resolved: #5227 
The federation optimizer was missing to execute the binding assigner (which injects external bindings into the statement pattern). The consequence was potentially incorrect results (due to source source selection with partial knowledge) as well as sub-optimal source selection
Issue is covered with a unit test, which is failing in two places prior to this change.
----
=> GH-5227: fix binding assigner optimizer in FedX

tools/federation/src/main/java/org/eclipse/rdf4j/federated/FedXConnection.java, tools/federation/src/main/java/org/eclipse/rdf4j/federated/evaluation/FederationEvalStrategy.java, tools/federation/src/test/java/org/eclipse/rdf4j/federated/BasicTests.java
GitHub issue resolved: #5231 
The previous implementation of the FedXConnection was delegating "hasStatements()" to the implementation of "getStatements()", where the latter was actually fetching data from the federation members.
For checks hasStatements() checks like {null, rdf:type, null} or even {null, null, null} the implementation is problematic as it would fetch all data matching the pattern from the federation members, only to answer if it actually exists.
We now make use of "existence" check on the federation members, and can actually rely on the source selection cache for this.
Unit test coverage has been added.
----
=> GH-5231: fix poor query performance for hasStatements() in FedX

bom/pom.xml, core/sail/lmdb/pom.xml, pom.xml
GH-5214 lmdb supports linux ppc, updated to latest version and also some cleanup in the bom pom
GitHub issue resolved: #5214 
----
=> GH-5214 LMDB supports linux ppc

testsuites/benchmark/pom.xml
fix issue with testsuites benchmark sometimes causing japicmp to trigger by mistake
=> fix issue with testsuites benchmark sometimes causing japicmp to trigger by mistake

core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/ValueStore.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/config/LmdbStoreConfig.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/config/LmdbStoreSchema.java, core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/ValueStoreTest.java, core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/config/LmdbStoreConfigTest.java
#5260 
The pull request adds a configurable valueEvictionInterval to the LMDB Store, allowing for control over garbage collection (GC). If valueEvictionInterval is less than or equal to 0, GC is disabled. Tests were added to verify this new behavior.
----
=> GH-5260 LMDB Store: Add valueEvictionInterval config

core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/TripleStore.java, core/sail/lmdb/src/test/java/org/eclipse/rdf4j/sail/lmdb/TripleStoreManyIndexesTest.java
GitHub issue resolved: #5279 
- The added test can be used to reproduce the issue with the current main-branch version of RDF4J.
- I changed the maxdbs parameter to 13, which allows the test to pass.
----
=> GH-5279: support up to 6 triple indexes in LmdbStore

site/content/download.md, site/content/news/rdf4j-511.md, site/content/release-notes/5.1.1.md
Javadocs, release-notes and news item for 5.1.1.
=> 5.1.1 release notes

core/repository/api/src/main/java/org/eclipse/rdf4j/repository/RepositoryConnection.java
Fix _"content"_ to _"context"_ typo in RepositoryConnection JavaDoc.
This PR only changes JavaDoc, no code.
----
=> docs: Fix content => context typo in RepositoryConnection JavaDoc

core/http/client/src/main/java/org/eclipse/rdf4j/http/client/SPARQLProtocolSession.java, core/http/client/src/test/java/org/eclipse/rdf4j/http/client/ProxyTest.java
GitHub issue resolved: #5292
The `SPARQLProtocolSession` uses a `SystemDefaultCredentialsProvider` to store the credentials for a repository.
----
=> GH-5292 Proxy credentials lost when setting repository credentials

site/content/download.md, site/content/news/rdf4j-513.md, site/content/release-notes/5.1.3.md
Javadocs, release-notes and news item for 5.1.3.
=> 5.1.3 release notes

core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/ValueStore.java
GitHub issue resolved: #5259 
Removing the debug-level requirement on lmdb valuestore initialize so gc collection can be enabled. Also, removed the call to logValues to dump entire lmdb file
----
- [ x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
- [ x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
- [ x] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my …
=> remove logValues and enable lmdb gc on init

tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/RepositoryInterceptor.java, tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/namespaces/NamespaceController.java, tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/namespaces/NamespacesController.java
#5330 
Adds a null check for the repository in `getRepositoryConnection` to ensure that an appropriate `ClientHTTPException` is thrown when the requested repository is not found, preventing potential `NullPointerExceptions`.
Otherwise, it returns a `InternalSeverError`
----
=> GH-5330 throw an exception for unknown repo in getRepositoryCon

core/http/protocol/src/main/java/org/eclipse/rdf4j/http/protocol/Protocol.java, site/static/documentation/reference/rest-api/rdf4j-openapi.yaml, tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/ExplainQueryResultView.java, tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/QueryResultView.java, tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/handler/AbstractQueryRequestHandler.java, tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/handler/DefaultQueryRequestHandler.java
#2979 
Add an additional parameter to the query endpoint. If parm `explain` is present, don't execute the query and return the query explaination instead.
Currently only supports Text and Json response format.
Requst to return Json
```bash
curl -G 'http://localhost:8080/rdf4j-server/repositories/testrepo' \
--data-urlencode 'explain=Timed' \
--data-urlencode 'query=SELECT * WHERE { ?s ?p ?o }' \
-H 'Accept:application/json'
```
```json
{
"type" : "StatementPattern",
"resultSizeEstimate" : 0.0,
"resultSizeActual" : 0,
"totalTimeActual" : 0.005417,
"plans" : [ {
"type" : "Var (name=s)"
}, {
"type" : "Var (name=p)"
}, {
"type" : "Var (name=o)"
} ],
"selfTimeActual" : 0.005417
}
```
Request to return plain text …
=> GH-2979 Allow query explanation via REST API

tools/console/src/main/java/org/eclipse/rdf4j/console/command/Verify.java, tools/console/src/test/java/org/eclipse/rdf4j/console/command/VerifyTest.java
GitHub issue resolved: #5397 
Change SHACL format inference to be based on the SHACL itself (`shaclPath`), instead of the report file (`reportFile`).
----
=> GH-5397 Fix incorrect SHACL format inference

compliance/repository/src/test/java/org/eclipse/rdf4j/repository/sparql/federation/RepositoryFederatedServiceIntegrationTest.java, compliance/repository/src/test/java/org/eclipse/rdf4j/repository/sparql/federation/SparqlFederatedServiceIntegrationTest.java, core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/optimizer/BindingSetAssignmentInlinerOptimizer.java, core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/BindingSetAssignmentInlinerTest.java
GitHub issue resolved: #5358
The BindingSetAssingmentInlinerOptimizer attempts to inject a single value from VALUES clauses into matching variables.
For SERVICE causes this is problematic (when they later get evaluated through the SparqlFederatedService):
the SPARQLFederatedService computes the set of bound variables and applies logic. Here it is important, that binding set assignments are not inlined. Otherwise, a query evaluation exception is thrown due to a malformed query.
The actual query at evaluation time (in case such inlining happened) would contain something like
VALUES <http://www.example.com/MyResource> {
<http://www.example.com/MyResource>
}
i.e. the variable name of the VALUES clause incorrectly replaced.
This change fixes it by not applying inlining insider SERVICE nodes. …
=> GH-5358: fix query evaluation errors when using VALUES clause in SERVICE

core/queryresultio/api/src/main/java/org/eclipse/rdf4j/query/resultio/TupleQueryResultFormat.java, core/queryresultio/ods/pom.xml, core/queryresultio/ods/src/main/java/org/eclipse/rdf4j/query/resultio/sparqlods/SPARQLResultsODSWriter.java, core/queryresultio/ods/src/main/java/org/eclipse/rdf4j/query/resultio/sparqlods/SPARQLResultsODSWriterFactory.java, core/queryresultio/ods/src/main/java/org/eclipse/rdf4j/query/resultio/sparqlods/package.html, core/queryresultio/ods/src/test/java/org/eclipse/rdf4j/query/resultio/sparqlxml/SPARQLODSTupleTest.java, core/queryresultio/pom.xml, core/queryresultio/xlsx/pom.xml, core/queryresultio/xlsx/src/main/java/org/eclipse/rdf4j/query/resultio/sparqlxslx/SPARQLResultsXLSXWriter.java, core/queryresultio/xlsx/src/main/java/org/eclipse/rdf4j/query/resultio/sparqlxslx/SPARQLResultsXLSXWriterFactory.java, core/queryresultio/xlsx/src/main/java/org/eclipse/rdf4j/query/resultio/sparqlxslx/package.html, core/queryresultio/xlsx/src/main/resources/META-INF/services/org.eclipse.rdf4j.query.resultio.TupleQueryResultWriterFactory, core/queryresultio/xlsx/src/test/java/org/eclipse/rdf4j/query/resultio/sparqlxml/SPARQLXLSXTupleTest.java, pom.xml
GitHub issue resolved: #5290 
Introduce two new SPARQL result set writers, one for XLSX and another for ODS.
The XLSX one uses Apache POI, while the ODS one is more raw zip file + xml.
----
=> Gh 5290 xlsx query result format

AGENTS.md, core/sail/extensible-store/src/main/java/org/eclipse/rdf4j/sail/extensiblestore/evaluationstatistics/ExtensibleDynamicEvaluationStatistics.java, core/sail/extensible-store/src/test/java/org/eclipse/rdf4j/sail/extensiblestore/evaluationstatistics/ExtensibleDynamicEvaluationStatisticsNullContextTest.java
GitHub issue resolved: #5133
Fixes #5133
- Fix NullPointerException in `ExtensibleDynamicEvaluationStatistics#getContextCardinality(Var)` when the context `Var` is null (e.g., during `ZeroLengthPath` evaluation). The method now guards `var == null || var.getValue() == null`.
- Add focused unit test `ExtensibleDynamicEvaluationStatisticsNullContextTest` to reproduce the previous NPE and assert stable behavior (returns 0.0 with empty stats).
- Update `AGENTS.md` with “Always Install Before Tests” guidance and a concise “Branch & PR Workflow (Agent)” that includes using the default PR template and explicitly filling in its fields.
----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/CONTRIBUTING …
=> GH-5133 Fix NPE when evaluating ZeroLengthPath with null context var in ExtensibleDynamicEvaluationStatistics

AGENTS.md, core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleParser.java, core/rio/turtle/src/test/java/org/eclipse/rdf4j/rio/turtle/TurtleParserTest.java
GitHub issue resolved: #5407
What changed:
- Fix Turtle number parsing: when a '.' follows digits at end-of-file, treat it as the statement terminator, not as a decimal.
- Adds a focused test to cover the case (:alice :age 30. at EOF).
Why:
- Per Turtle grammar, DECIMAL requires a digit after '.', so "30." must tokenize as INTEGER(30) followed by '.'.
Verification:
- New focused test fails pre-fix with EOF, passes post-fix.
- Module tests for rio-turtle pass.
Fixes #5407
=> GH-5407 Fix Turtle integer-literal + dot at EOF

core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbContextIdIterator.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbRecordIterator.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/LmdbStoreConnection.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/Pool.java, core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/TripleStore.java
GitHub issue resolved: #5438 
Use thread-local pool in LmdbStore to minimize synchronization
----
=> GH-5438 Use thread-local pool in LmdbStore to minimize synchronization

core/sail/api/src/main/java/org/eclipse/rdf4j/sail/SailConnectionListener.java, core/sail/api/src/main/java/org/eclipse/rdf4j/sail/helpers/AbstractNotifyingSailConnection.java, core/sail/base/src/main/java/org/eclipse/rdf4j/sail/base/SailSourceConnection.java
GitHub issue resolved: #5118 
Extend methods of SailConnectionListener with inferred argument to distinguish between explicit and inferred statements.
----
=> Extend methods of SailConnectionListener with inferred argument

core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java, core/queryparser/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilderTest.java
GitHub issue resolved: #4992
This pull request improves the handling of aggregate operators in SPARQL query parsing, ensuring that each aggregate operator instance is properly cloned and parented in the query model tree. This prevents shared references and ensures correct parent-child relationships, which is critical for query correctness and further processing. The changes also add comprehensive tests to verify these relationships across various query constructs.
* Updated `TupleExprBuilder.java` to clone aggregate operator instances before adding them to `ExtensionElem`, preventing shared references between group and extension nodes and ensuring correct parent assignment. [[1]](diffhunk://#diff-bbccb2ab14ceed75efc33659f7ed7a65b205d950d03fc04f1e0ed406ab7aa93cL452-R452) …
=> GH-4992  fix for parent

core/model-api/src/main/java/org/eclipse/rdf4j/model/base/AbstractLiteral.java, core/model/src/test/java/org/eclipse/rdf4j/model/util/LiteralsTest.java
GitHub issue resolved: #4104 
----
=> Handle Instant literals in TemporalAccessorLiteral
